//! Every `qr` row of `fixtures/behaviour_mfa.json`: `qr.Encode(text, qr.H).PNG()` from the Go
//! library itself, compared byte for byte.

use base64::Engine as _;

#[test]
fn every_png_is_the_go_librarys() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("../../../fixtures/behaviour_mfa.json"))
            .expect("behaviour_mfa.json is generated by reference/dump");
    let b64 = base64::engine::general_purpose::STANDARD;
    let rows = fixture["qr"].as_array().expect("rows");
    assert!(rows.len() >= 40, "the corpus is all there");
    let mut errors = 0;
    for row in rows {
        let text = String::from_utf8(b64.decode(row["text_b64"].as_str().unwrap()).unwrap())
            .unwrap_or_else(|e| String::from_utf8_lossy(e.as_bytes()).into_owned());
        let got = goqr::encode(&text, goqr::Level::H);
        match row["error"].as_str() {
            Some(message) => {
                assert_eq!(
                    got.map(|c| c.size).unwrap_err().to_string(),
                    message,
                    "{text:?}"
                );
                errors += 1;
            }
            None => {
                let code = got.unwrap_or_else(|e| panic!("{text:?}: {e}"));
                assert_eq!(code.size as u64, row["size"].as_u64().unwrap(), "{text:?}");
                let want = b64.decode(row["png_b64"].as_str().unwrap()).unwrap();
                assert!(code.png() == want, "{text:?}: PNG bytes differ");
            }
        }
    }
    assert!(errors >= 2, "the too-long branch is exercised");
}
