//! Port of `platform/shared/web.WriteFileResponse` (web/files.go:42) and the `http.ServeContent`
//! it ends in.
//!
//! This is the entire wire format of every route that returns file bytes — `GET /files/{id}`,
//! `/thumbnail`, `/preview`, `/public`, and (through [`serve_content`] alone) `downloadExport`.
//! Nine response headers, five conditional-request answers and the whole `Range` family, none of
//! which is Mattermost code: it is Go's standard library, so reading the handler tells you almost
//! none of it.
//!
//! Pinned end to end by `fixtures/behaviour_filestore.json` (`write_file_response`), which was
//! generated by driving the *real* `WriteFileResponse` through `httptest` and recording status,
//! every header, and the body.
//!
//! # Four things the source does not say and the corpus does
//!
//! 1. **`contentSize` does not set `Content-Length`.** `WriteFileResponse` sets it, and then
//!    `ServeContent` overwrites it from the seek size. The parameter's only surviving effect is
//!    in `gzip` mode, where it becomes `X-Uncompressed-Content-Length` instead — which is why
//!    `getFileThumbnail` passing `0` changes nothing about the response.
//! 2. **A 416 loses `Cache-Control`, `Last-Modified` and `Accept-Ranges`.** `serveError`
//!    (fs.go) deletes the first two, and `Accept-Ranges` is set *after* the range handling,
//!    so an unsatisfiable range never reaches the line that sets it.
//! 3. **The Unix epoch is "no modification time"** — `isZeroTime` treats `time.Unix(0,0)` like the
//!    zero `time.Time` — so a `FileInfo` with `update_at: 0` gets no `Last-Modified`. But
//!    `checkIfRange` and `checkIfUnmodifiedSince` test `IsZero()` *only*, so the epoch is a real
//!    date to those two. One value, two meanings, four call sites.
//! 4. **`Content-Disposition` carries the filename twice**, both `url.PathEscape`d — so the
//!    quoted form is percent-escaped as well, and a name with a space is `my%20report.pdf`
//!    inside the quotes.

use axum::body::Body;
use axum::http::{HeaderMap, HeaderName, HeaderValue, Method, StatusCode};
use axum::response::Response;
use tokio::io::{AsyncReadExt, AsyncSeekExt};

/// Port of `web.UnsafeContentTypes` (web/files.go:17).
///
/// Matched by **prefix**, so `text/html; charset=utf-8` is unsafe too.
const UNSAFE_CONTENT_TYPES: [&str; 6] = [
    "application/javascript",
    "application/ecmascript",
    "text/javascript",
    "text/ecmascript",
    "application/x-javascript",
    "text/html",
];

/// Port of `web.MediaContentTypes` (web/files.go:26) — the types served `inline` rather than as an
/// attachment. Prefix-matched, like the unsafe list.
const MEDIA_CONTENT_TYPES: [&str; 11] = [
    "image/jpeg",
    "image/png",
    "image/bmp",
    "image/gif",
    "image/tiff",
    "image/webp",
    "video/avi",
    "video/mpeg",
    "video/mp4",
    "audio/mpeg",
    "audio/wav",
];

/// Port of `http.TimeFormat` — RFC 1123 with a hard-coded `GMT`.
const HTTP_TIME_FORMAT: &str = "%a, %d %b %Y %H:%M:%S GMT";

/// What [`write_file_response`] decided to do.
pub enum FileResponse {
    /// The complete response, ready to return.
    Response(Response),
    /// Go would answer with something this port does not reproduce. The caller forwards the
    /// request so Go answers it. The string says which case, for the log line.
    Forward(&'static str),
}

/// The arguments `WriteFileResponse` takes, named rather than positional — Go's call sites pass
/// nine values in a row and two of them are booleans.
pub struct FileResponseSpec<'a> {
    /// `FileInfo.Name`, or the export name. Percent-escaped into `Content-Disposition`.
    pub filename: &'a str,
    /// `FileInfo.MimeType` for the original, and the fixed thumbnail/preview types for those.
    pub content_type: &'a str,
    /// `FileInfo.Size` for the original and **`0`** for the thumbnail and preview. See the module
    /// docs: outside `gzip` mode this changes nothing.
    pub content_size: i64,
    /// `time.Unix(0, UpdateAt*1e6)` as epoch milliseconds, or `None` for Go's zero `time.Time`
    /// (which is what `downloadExport` passes).
    pub modtime_millis: Option<i64>,
    /// `ServiceSettings.WebserverMode`.
    pub webserver_mode: &'a str,
    /// The `?download=` query parameter, parsed with `strconv.ParseBool`.
    pub force_download: bool,
}

/// Port of `web.WriteFileResponse` (web/files.go:42).
pub async fn write_file_response(
    spec: &FileResponseSpec<'_>,
    method: &Method,
    request_headers: &HeaderMap,
    file: tokio::fs::File,
    size: u64,
) -> FileResponse {
    let mut headers = set_headers(spec.content_type, spec.force_download, spec.filename);

    if spec.content_size > 0 {
        let value = spec.content_size.to_string();
        let name = if spec.webserver_mode == "gzip" {
            "x-uncompressed-content-length"
        } else {
            "content-length"
        };
        set_header(&mut headers, name, &value);
    }

    serve_content(
        headers,
        spec.filename,
        spec.modtime_millis,
        method,
        request_headers,
        file,
        size,
    )
    .await
}

/// Port of `web.setHeaders` (web/files.go:127).
///
/// Returns the headers rather than mutating a writer, because the outcome has to survive being
/// turned into a 304 or a 416 that deletes some of them.
fn set_headers(content_type: &str, force_download: bool, filename: &str) -> HeaderMap {
    let mut headers = HeaderMap::new();

    // Go's guard is `if w.Header().Get("Cache-Control") == ""`. No file route sets one before
    // this, so it is always taken — but the guard is reproduced because `getFileInfo`'s sibling
    // route *does* set one, and a future caller might.
    set_header(&mut headers, "cache-control", "private, max-age=86400");
    set_header(&mut headers, "x-content-type-options", "nosniff");

    let content_type = if content_type.is_empty() {
        "application/octet-stream"
    } else if UNSAFE_CONTENT_TYPES
        .iter()
        .any(|unsafe_type| content_type.starts_with(unsafe_type))
    {
        "text/plain"
    } else {
        content_type
    };
    set_header(&mut headers, "content-type", content_type);

    // An unsafe type has already become `text/plain`, which is not in the media list, so an HTML
    // attachment is downloaded rather than rendered — that rewrite is the whole point of the
    // list, and it happens *before* this test.
    let is_media = MEDIA_CONTENT_TYPES
        .iter()
        .any(|media| content_type.starts_with(media));
    let to_download = force_download || !is_media;

    let escaped = path_escape(filename);
    let disposition = if to_download { "attachment" } else { "inline" };
    set_header(
        &mut headers,
        "content-disposition",
        &format!("{disposition};filename=\"{escaped}\"; filename*=UTF-8''{escaped}"),
    );

    set_header(&mut headers, "x-frame-options", "DENY");
    set_header(
        &mut headers,
        "content-security-policy",
        "Frame-ancestors 'none'",
    );

    headers
}

/// Port of `net/url.PathEscape` — `escape(s, encodePathSegment)`.
///
/// Unreserved (`A-Za-z0-9-_.~`) and the sub-delims Go leaves alone in a *segment*
/// (`$ & + : = @`) pass through; `/ ; , ?` and every other byte are percent-escaped, uppercase
/// hex. Byte-oriented, so a multi-byte character becomes one escape per UTF-8 byte — which is
/// what makes `réunion` into `r%C3%A9union`.
fn path_escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for byte in value.as_bytes() {
        if should_escape_in_path_segment(*byte) {
            out.push('%');
            out.push(char::from(HEX[usize::from(byte >> 4)]));
            out.push(char::from(HEX[usize::from(byte & 0x0f)]));
        } else {
            out.push(char::from(*byte));
        }
    }
    out
}

const HEX: &[u8; 16] = b"0123456789ABCDEF";

/// Port of `url.shouldEscape(c, encodePathSegment)` (net/url/url.go:100).
fn should_escape_in_path_segment(byte: u8) -> bool {
    if byte.is_ascii_alphanumeric() {
        return false;
    }
    match byte {
        // §2.3 unreserved marks.
        b'-' | b'_' | b'.' | b'~' => false,
        // §2.2 reserved. In a path *segment* Go escapes only these four of the ten.
        b'/' | b';' | b',' | b'?' => true,
        b'$' | b'&' | b'+' | b':' | b'=' | b'@' => false,
        _ => true,
    }
}

/// Port of `http.serveContent` (net/http/fs.go), for a seekable file of known size.
#[allow(clippy::too_many_arguments)]
async fn serve_content(
    mut headers: HeaderMap,
    _name: &str,
    modtime_millis: Option<i64>,
    method: &Method,
    request_headers: &HeaderMap,
    mut file: tokio::fs::File,
    size: u64,
) -> FileResponse {
    set_last_modified(&mut headers, modtime_millis);

    if let Some(response) =
        check_preconditions(&mut headers, method, request_headers, modtime_millis)
    {
        return FileResponse::Response(response);
    }
    let range_header = effective_range_header(method, request_headers, modtime_millis);

    // Go's content-type sniffing block is unreachable here: `setHeaders` has already set
    // `Content-Type` unconditionally, so `haveType` is always true and the `mime.TypeByExtension`
    // / `DetectContentType` path — the only use of the `name` argument — never runs.

    let size = i64::try_from(size).unwrap_or(i64::MAX);
    let mut send_size = size;
    let mut start = 0i64;
    let mut code = StatusCode::OK;

    let ranges = match parse_range(range_header.as_deref(), size) {
        Ok(ranges) => ranges,
        Err(RangeError::NoOverlap) if size == 0 => {
            // "Some clients add a Range header to all requests to limit the size of the
            // response." An empty file answers 200 rather than 416.
            Vec::new()
        }
        Err(RangeError::NoOverlap) => {
            set_header(&mut headers, "content-range", &format!("bytes */{size}"));
            return FileResponse::Response(serve_error(
                headers,
                "invalid range: failed to overlap",
                StatusCode::RANGE_NOT_SATISFIABLE,
            ));
        }
        Err(RangeError::Invalid) => {
            return FileResponse::Response(serve_error(
                headers,
                "invalid range",
                StatusCode::RANGE_NOT_SATISFIABLE,
            ));
        }
    };

    // "The total number of bytes in all the ranges is larger than the size of the file by itself,
    // so this is probably an attack, or a dumb client. Ignore the range request."
    let ranges = if ranges.iter().map(|r| r.length).sum::<i64>() > size {
        Vec::new()
    } else {
        ranges
    };

    match ranges.len() {
        0 => {}
        1 => {
            let range = ranges[0];
            start = range.start;
            send_size = range.length;
            code = StatusCode::PARTIAL_CONTENT;
            set_header(
                &mut headers,
                "content-range",
                &format!(
                    "bytes {}-{}/{size}",
                    range.start,
                    range.start + range.length - 1
                ),
            );
        }
        _ => {
            // `multipart/byteranges` with a **random** boundary — thirty bytes from
            // `crypto/rand`, so the response is not byte-comparable against Go's even when the
            // parts are identical. No Mattermost client asks for more than one range; forwarding
            // costs one request and keeps the answer Go's own. See [D-205].
            return FileResponse::Forward("multipart/byteranges has a random boundary");
        }
    }

    set_header(&mut headers, "accept-ranges", "bytes");
    // Go's `Content-Encoding` guard is dead here — nothing in this path sets one — so the length
    // is always written.
    set_header(&mut headers, "content-length", &send_size.to_string());

    let body = if method == Method::HEAD {
        Body::empty()
    } else {
        if start > 0
            && file
                .seek(std::io::SeekFrom::Start(start as u64))
                .await
                .is_err()
        {
            // `content.Seek` failing is Go's other 416, and it carries the seek error's own text
            // rather than one of the two range messages. Unreachable for a regular file that has
            // just been stat'd, so rather than invent Go's wording, forward.
            return FileResponse::Forward("seeking into the file failed");
        }
        Body::from_stream(tokio_util::io::ReaderStream::new(
            file.take(send_size.max(0) as u64),
        ))
    };

    FileResponse::Response(build_response(code, headers, body))
}

/// Port of `http.serveError` (net/http/fs.go) followed by `http.Error`.
///
/// Four headers are deleted and two are reset. `Content-Encoding` and `Etag` are in the deleted
/// set and are never present here; `Cache-Control` and `Last-Modified` are, which is why a 416
/// response has neither.
fn serve_error(mut headers: HeaderMap, text: &str, code: StatusCode) -> Response {
    headers.remove("cache-control");
    headers.remove("content-encoding");
    headers.remove("etag");
    headers.remove("last-modified");

    // `http.Error`.
    headers.remove("content-length");
    set_header(&mut headers, "content-type", "text/plain; charset=utf-8");
    set_header(&mut headers, "x-content-type-options", "nosniff");

    // `fmt.Fprintln` — the trailing newline is on the wire.
    build_response(code, headers, Body::from(format!("{text}\n")))
}

/// Port of `http.setLastModified` (net/http/fs.go).
fn set_last_modified(headers: &mut HeaderMap, modtime_millis: Option<i64>) {
    if is_zero_time(modtime_millis) {
        return;
    }
    let Some(formatted) = format_http_date(modtime_millis) else {
        return;
    };
    set_header(headers, "last-modified", &formatted);
}

/// Port of `http.isZeroTime` — the zero `time.Time` **and** the Unix epoch.
fn is_zero_time(modtime_millis: Option<i64>) -> bool {
    matches!(modtime_millis, None | Some(0))
}

fn format_http_date(modtime_millis: Option<i64>) -> Option<String> {
    let millis = modtime_millis?;
    let instant = chrono::DateTime::from_timestamp_millis(millis)?;
    Some(instant.format(HTTP_TIME_FORMAT).to_string())
}

/// Port of `http.ParseTime` — the three formats an HTTP date may take, tried in order.
///
/// Returns whole seconds since the epoch, which is all any caller compares.
fn parse_http_time(value: &str) -> Option<i64> {
    use chrono::{NaiveDateTime, TimeZone, Utc};

    // `http.TimeFormat` — RFC 1123 with a literal GMT.
    if let Ok(parsed) = NaiveDateTime::parse_from_str(value, "%a, %d %b %Y %H:%M:%S GMT") {
        return Some(Utc.from_utc_datetime(&parsed).timestamp());
    }
    // `time.RFC850` — "Monday, 02-Jan-06 15:04:05 MST".
    if let Ok(parsed) = NaiveDateTime::parse_from_str(value, "%A, %d-%b-%y %H:%M:%S GMT") {
        return Some(Utc.from_utc_datetime(&parsed).timestamp());
    }
    // `time.ANSIC` — "Mon Jan _2 15:04:05 2006", with the day space-padded.
    if let Ok(parsed) = NaiveDateTime::parse_from_str(value.trim(), "%a %b %e %H:%M:%S %Y") {
        return Some(Utc.from_utc_datetime(&parsed).timestamp());
    }
    None
}

/// Go's `condResult`.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
enum Cond {
    None,
    True,
    False,
}

/// Port of `http.checkPreconditions` (net/http/fs.go).
///
/// Returns the finished response when a precondition ends the request, and `None` when the
/// handler should carry on. **No route here ever sets an `Etag`**, so every etag comparison is
/// against the empty string: `If-Match: "x"` cannot match and is a 412, while `If-None-Match: "x"`
/// cannot match either and therefore falls through to `If-Modified-Since`. Only the `*` forms
/// short-circuit.
fn check_preconditions(
    headers: &mut HeaderMap,
    method: &Method,
    request_headers: &HeaderMap,
    modtime_millis: Option<i64>,
) -> Option<Response> {
    let mut ch = check_if_match(request_headers);
    if ch == Cond::None {
        ch = check_if_unmodified_since(request_headers, modtime_millis);
    }
    if ch == Cond::False {
        return Some(build_response(
            StatusCode::PRECONDITION_FAILED,
            headers.clone(),
            Body::empty(),
        ));
    }

    match check_if_none_match(request_headers) {
        Cond::False => {
            return Some(if method == Method::GET || method == Method::HEAD {
                write_not_modified(headers.clone())
            } else {
                build_response(
                    StatusCode::PRECONDITION_FAILED,
                    headers.clone(),
                    Body::empty(),
                )
            });
        }
        Cond::None => {
            if check_if_modified_since(method, request_headers, modtime_millis) == Cond::False {
                return Some(write_not_modified(headers.clone()));
            }
        }
        Cond::True => {}
    }

    None
}

/// The `Range` header, emptied when `If-Range` says the client's copy is stale — the tail of
/// `checkPreconditions`, split out because it runs after the early returns.
fn effective_range_header(
    method: &Method,
    request_headers: &HeaderMap,
    modtime_millis: Option<i64>,
) -> Option<String> {
    let range = header_str(request_headers, "range")?;
    if range.is_empty() {
        return None;
    }
    if check_if_range(method, request_headers, modtime_millis) == Cond::False {
        return None;
    }
    Some(range)
}

/// Port of `http.writeNotModified`.
fn write_not_modified(mut headers: HeaderMap) -> Response {
    headers.remove("content-type");
    headers.remove("content-length");
    headers.remove("content-encoding");
    // The `Etag` guard that would delete `Last-Modified` cannot fire: no route here sets one.
    build_response(StatusCode::NOT_MODIFIED, headers, Body::empty())
}

fn check_if_match(request_headers: &HeaderMap) -> Cond {
    let Some(value) = header_str(request_headers, "if-match") else {
        return Cond::None;
    };
    if value.is_empty() {
        return Cond::None;
    }
    // With no `Etag` set, only `*` can be true. A malformed value breaks the loop and falls
    // through to `condFalse`, which is the same answer as a well-formed non-matching one.
    let mut rest = value.as_str();
    loop {
        rest = rest.trim_matches([' ', '\t']);
        if rest.is_empty() {
            break;
        }
        if let Some(stripped) = rest.strip_prefix(',') {
            rest = stripped;
            continue;
        }
        if rest.starts_with('*') {
            return Cond::True;
        }
        let Some((_etag, remain)) = scan_etag(rest) else {
            break;
        };
        // `etagStrongMatch(etag, "")` is false for every etag.
        rest = remain;
    }
    Cond::False
}

fn check_if_none_match(request_headers: &HeaderMap) -> Cond {
    let Some(value) = header_str(request_headers, "if-none-match") else {
        return Cond::None;
    };
    if value.is_empty() {
        return Cond::None;
    }
    let mut rest = value.as_str();
    loop {
        rest = rest.trim_matches([' ', '\t']);
        if rest.is_empty() {
            break;
        }
        if let Some(stripped) = rest.strip_prefix(',') {
            rest = stripped;
            continue;
        }
        if rest.starts_with('*') {
            return Cond::False;
        }
        let Some((etag, remain)) = scan_etag(rest) else {
            break;
        };
        // `etagWeakMatch(etag, "")` compares both with `W/` stripped — so an `Etag` of `""`
        // matches a request etag of `W/` exactly. Reproduced rather than simplified away.
        if etag.trim_start_matches("W/").is_empty() {
            return Cond::False;
        }
        rest = remain;
    }
    Cond::True
}

fn check_if_unmodified_since(request_headers: &HeaderMap, modtime_millis: Option<i64>) -> Cond {
    let Some(value) = header_str(request_headers, "if-unmodified-since") else {
        return Cond::None;
    };
    if value.is_empty() || is_zero_time(modtime_millis) {
        return Cond::None;
    }
    let Some(theirs) = parse_http_time(&value) else {
        return Cond::None;
    };
    // "The Last-Modified header truncates sub-second precision so the modtime needs to be
    // truncated too." Go truncates *toward zero* with `Truncate`, which for a positive instant is
    // a floor; epoch milliseconds divided by 1000 in Rust truncates the same way.
    if truncate_to_seconds(modtime_millis) <= theirs {
        Cond::True
    } else {
        Cond::False
    }
}

fn check_if_modified_since(
    method: &Method,
    request_headers: &HeaderMap,
    modtime_millis: Option<i64>,
) -> Cond {
    if method != Method::GET && method != Method::HEAD {
        return Cond::None;
    }
    let Some(value) = header_str(request_headers, "if-modified-since") else {
        return Cond::None;
    };
    if value.is_empty() || is_zero_time(modtime_millis) {
        return Cond::None;
    }
    let Some(theirs) = parse_http_time(&value) else {
        return Cond::None;
    };
    if truncate_to_seconds(modtime_millis) <= theirs {
        Cond::False
    } else {
        Cond::True
    }
}

fn check_if_range(
    method: &Method,
    request_headers: &HeaderMap,
    modtime_millis: Option<i64>,
) -> Cond {
    if method != Method::GET && method != Method::HEAD {
        return Cond::None;
    }
    let Some(value) = header_str(request_headers, "if-range") else {
        return Cond::None;
    };
    if value.is_empty() {
        return Cond::None;
    }
    if scan_etag(&value).is_some() {
        // An etag was supplied and ours is empty, so `etagStrongMatch` is false.
        return Cond::False;
    }
    // **`IsZero()`, not `isZeroTime`** — the Unix epoch is a real date to this function even
    // though it suppressed `Last-Modified`.
    if modtime_millis.is_none() {
        return Cond::False;
    }
    let Some(theirs) = parse_http_time(&value) else {
        return Cond::False;
    };
    if theirs == truncate_to_seconds(modtime_millis) {
        Cond::True
    } else {
        Cond::False
    }
}

/// Epoch milliseconds to epoch seconds, flooring — Go's `Time.Unix()` after `Truncate(Second)`.
fn truncate_to_seconds(modtime_millis: Option<i64>) -> i64 {
    modtime_millis.unwrap_or(0).div_euclid(1000)
}

/// Port of `http.scanETag` — returns the etag *with its quotes* and the remainder.
fn scan_etag(value: &str) -> Option<(&str, &str)> {
    let value = value.trim_matches([' ', '\t']);
    let start = if value.starts_with("W/") { 2 } else { 0 };
    let bytes = value.as_bytes();
    if bytes.len() - start < 2 || bytes[start] != b'"' {
        return None;
    }
    for i in start + 1..bytes.len() {
        let c = bytes[i];
        if c == b'"' {
            return Some((&value[..i + 1], &value[i + 1..]));
        }
        let allowed = c == 0x21 || (0x23..=0x7e).contains(&c) || c >= 0x80;
        if !allowed {
            return None;
        }
    }
    None
}

#[derive(Debug, Clone, Copy)]
struct HttpRange {
    start: i64,
    length: i64,
}

enum RangeError {
    /// `errNoOverlap` — every range began past the end of the content.
    NoOverlap,
    /// Everything else `parseRange` rejects, all under one message.
    Invalid,
}

/// Port of `http.parseRange` (net/http/fs.go).
///
/// The two error kinds are not interchangeable: only `NoOverlap` gets a `Content-Range` header on
/// the 416, and only it is downgraded to a 200 when the content is empty.
fn parse_range(header: Option<&str>, size: i64) -> Result<Vec<HttpRange>, RangeError> {
    let Some(header) = header else {
        return Ok(Vec::new());
    };
    if header.is_empty() {
        return Ok(Vec::new());
    }
    let Some(spec) = header.strip_prefix("bytes=") else {
        return Err(RangeError::Invalid);
    };

    let mut ranges = Vec::new();
    let mut no_overlap = false;
    for part in spec.split(',') {
        let part = part.trim_matches([' ', '\t']);
        if part.is_empty() {
            continue;
        }
        let Some((start, end)) = part.split_once('-') else {
            return Err(RangeError::Invalid);
        };
        let start = start.trim_matches([' ', '\t']);
        let end = end.trim_matches([' ', '\t']);

        if start.is_empty() {
            // `bytes=-N` — a suffix length, which must be a non-negative integer.
            if end.is_empty() || end.starts_with('-') {
                return Err(RangeError::Invalid);
            }
            let Ok(suffix) = end.parse::<i64>() else {
                return Err(RangeError::Invalid);
            };
            if suffix < 0 {
                return Err(RangeError::Invalid);
            }
            let suffix = suffix.min(size);
            ranges.push(HttpRange {
                start: size - suffix,
                length: suffix,
            });
        } else {
            let Ok(begin) = start.parse::<i64>() else {
                return Err(RangeError::Invalid);
            };
            if begin < 0 {
                return Err(RangeError::Invalid);
            }
            if begin >= size {
                // Past the end: not an error on its own, only if *every* range is.
                no_overlap = true;
                continue;
            }
            let length = if end.is_empty() {
                size - begin
            } else {
                let Ok(last) = end.parse::<i64>() else {
                    return Err(RangeError::Invalid);
                };
                if begin > last {
                    return Err(RangeError::Invalid);
                }
                let last = last.min(size - 1);
                last - begin + 1
            };
            ranges.push(HttpRange {
                start: begin,
                length,
            });
        }
    }

    if no_overlap && ranges.is_empty() {
        return Err(RangeError::NoOverlap);
    }
    Ok(ranges)
}

fn header_str(headers: &HeaderMap, name: &str) -> Option<String> {
    headers
        .get(name)?
        .to_str()
        .ok()
        .map(std::borrow::ToOwned::to_owned)
}

/// Set a header, replacing any existing value — `http.Header.Set`.
///
/// A name or value axum rejects is dropped with a log line rather than panicking: every value
/// here is either a constant or a percent-escaped filename, so this cannot fire for a name, and
/// for a value only if a filename contained a control character that `path_escape` somehow let
/// through.
fn set_header(headers: &mut HeaderMap, name: &str, value: &str) {
    match (
        HeaderName::from_bytes(name.as_bytes()),
        HeaderValue::from_str(value),
    ) {
        (Ok(name), Ok(value)) => {
            headers.insert(name, value);
        }
        _ => tracing::error!(name, value, "refusing to set a malformed response header"),
    }
}

fn build_response(code: StatusCode, headers: HeaderMap, body: Body) -> Response {
    let mut response = Response::new(body);
    *response.status_mut() = code;
    *response.headers_mut() = headers;
    // The marker every migrated route carries, so the parity suite can tell who answered.
    set_header(response.headers_mut(), "x-mmrs-served-by", "rust");
    response
}

#[cfg(test)]
mod go_parity {
    use super::*;

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!("../../../fixtures/behaviour_filestore.json"))
            .expect("behaviour_filestore.json is generated by reference/dump")
    }

    /// Write the corpus body to a temporary file and hand back an open handle plus its size —
    /// what a real route gets from the file backend.
    async fn corpus_file(body: &[u8]) -> (tokio::fs::File, u64, std::path::PathBuf) {
        use std::sync::atomic::{AtomicU64, Ordering};
        static NEXT: AtomicU64 = AtomicU64::new(0);

        let path = std::env::temp_dir().join(format!(
            "mmrs-servecontent-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        tokio::fs::write(&path, body).await.unwrap();
        let file = tokio::fs::File::open(&path).await.unwrap();
        let size = file.metadata().await.unwrap().len();
        (file, size, path)
    }

    async fn collect_body(response: Response) -> Vec<u8> {
        use axum::body::to_bytes;
        to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap()
            .to_vec()
    }

    /// The whole of `WriteFileResponse`, case by case, against the responses Go's own
    /// `httptest` recorder produced: status, **every** header, and the body.
    ///
    /// The header comparison is exact in both directions — a header we set that Go did not is a
    /// failure, and so is one Go set that we did not — with `x-mmrs-served-by` excluded because
    /// it is this port's own marker and has no Go counterpart. That strictness is the point:
    /// most of what this file reproduces is a *deletion* (a 304 without `Content-Type`, a 416
    /// without `Cache-Control`), and a one-sided comparison cannot see a deletion that did not
    /// happen.
    #[tokio::test]
    async fn write_file_response_matches_go() {
        use base64::Engine;

        let oracle = oracle();
        let cases = oracle["write_file_response"].as_array().unwrap();
        assert!(
            cases.len() >= 30,
            "corpus should cover setHeaders and the Range family"
        );

        for case in cases {
            let name = case["name"].as_str().unwrap();

            let mut request_headers = HeaderMap::new();
            for pair in case["req_headers"].as_array().unwrap() {
                set_header(
                    &mut request_headers,
                    pair["name"].as_str().unwrap(),
                    pair["value"].as_str().unwrap(),
                );
            }
            let method = Method::from_bytes(case["method"].as_str().unwrap().as_bytes()).unwrap();

            let want_body = base64::engine::general_purpose::STANDARD
                .decode(case["body_base64"].as_str().unwrap())
                .unwrap();
            // Every case serves the same 26 bytes; the recorded body is what came *out*.
            let (file, size, path) = corpus_file(b"abcdefghijklmnopqrstuvwxyz").await;

            let spec = FileResponseSpec {
                filename: case["filename"].as_str().unwrap(),
                content_type: case["content_type_in"].as_str().unwrap(),
                content_size: case["content_size"].as_i64().unwrap(),
                modtime_millis: case["modtime_unix_ms"].as_i64(),
                webserver_mode: case["webserver_mode"].as_str().unwrap(),
                force_download: case["force_download"].as_bool().unwrap(),
            };

            let response =
                match write_file_response(&spec, &method, &request_headers, file, size).await {
                    FileResponse::Response(response) => response,
                    FileResponse::Forward(reason) => {
                        // The one deliberate gap: multiple ranges. Assert that it is the only
                        // case that forwards, so a new forward cannot appear unnoticed.
                        assert_eq!(name, "range_multiple", "{name} forwarded: {reason}");
                        let _ = tokio::fs::remove_file(&path).await;
                        continue;
                    }
                };
            let _ = tokio::fs::remove_file(&path).await;

            assert_eq!(
                response.status().as_u16(),
                u16::try_from(case["status"].as_i64().unwrap()).unwrap(),
                "{name}: status"
            );

            let want_headers = case["headers"].as_object().unwrap();
            let mut got_headers = std::collections::BTreeMap::new();
            for (key, value) in response.headers() {
                if key.as_str() == "x-mmrs-served-by" {
                    continue;
                }
                got_headers.insert(key.as_str().to_owned(), value.to_str().unwrap().to_owned());
            }

            let want_headers: std::collections::BTreeMap<String, String> = want_headers
                .iter()
                .map(|(key, value)| (key.to_ascii_lowercase(), value.as_str().unwrap().to_owned()))
                .collect();
            assert_eq!(got_headers, want_headers, "{name}: headers");

            assert_eq!(collect_body(response).await, want_body, "{name}: body");
        }
    }

    /// `url.PathEscape` in isolation, over the characters the `Content-Disposition` cases do not
    /// separate: the six sub-delims a *segment* leaves alone and the four it does not.
    ///
    /// Asserted against Go's answers as recorded in the corpus's `Content-Disposition` values for
    /// the filename cases, plus these transcribed from `url.shouldEscape` — which is a
    /// transcription and is marked as one.
    #[test]
    fn path_escape_leaves_the_six_segment_sub_delims_alone() {
        assert_eq!(path_escape("$&+:=@"), "$&+:=@");
        assert_eq!(path_escape("/;,?"), "%2F%3B%2C%3F");
        assert_eq!(path_escape("aA0-_.~"), "aA0-_.~");
        assert_eq!(path_escape(" \"'"), "%20%22%27");
        assert_eq!(path_escape("é"), "%C3%A9", "one escape per UTF-8 byte");
        assert_eq!(path_escape(""), "");
    }

    /// The escaping the corpus *does* pin, read back out of it so the two cannot drift.
    #[test]
    fn the_corpus_content_dispositions_are_reproduced_exactly() {
        let oracle = oracle();
        let mut checked = 0;
        for case in oracle["write_file_response"].as_array().unwrap() {
            let Some(want) = case["headers"]["Content-Disposition"].as_str() else {
                continue;
            };
            let escaped = path_escape(case["filename"].as_str().unwrap());
            assert!(
                want.contains(&format!("filename=\"{escaped}\""))
                    && want.ends_with(&format!("filename*=UTF-8''{escaped}")),
                "{}: {want}",
                case["name"].as_str().unwrap()
            );
            checked += 1;
        }
        assert!(checked >= 30, "every case carries a Content-Disposition");
    }

    /// `parseRange`'s two error kinds are different answers, not two spellings of one: only
    /// `NoOverlap` produces a `Content-Range` on the 416, and only it becomes a 200 for empty
    /// content.
    #[test]
    fn the_two_range_errors_are_distinguishable() {
        assert!(matches!(
            parse_range(Some("bytes=100-200"), 26),
            Err(RangeError::NoOverlap)
        ));
        assert!(matches!(
            parse_range(Some("chunks=1-2"), 26),
            Err(RangeError::Invalid)
        ));
        assert!(matches!(
            parse_range(Some("bytes=5-1"), 26),
            Err(RangeError::Invalid),
        ));
        assert!(matches!(
            parse_range(Some("bytes=-"), 26),
            Err(RangeError::Invalid)
        ));
        // A satisfiable range beside an unsatisfiable one is *not* an error: `noOverlap` only
        // fires when it collected nothing at all.
        let ranges = parse_range(Some("bytes=0-4,100-200"), 26).unwrap_or_default();
        assert_eq!(ranges.len(), 1);
        assert_eq!(ranges[0].start, 0);
        assert_eq!(ranges[0].length, 5);
    }

    /// The Unix epoch is "no modification time" to `setLastModified` and a real date to
    /// `checkIfRange`. One value, two meanings — pinned because collapsing them is the obvious
    /// simplification and it changes a 206 into a 200.
    #[test]
    fn the_unix_epoch_is_zero_to_some_checks_and_not_to_others() {
        assert!(
            is_zero_time(Some(0)),
            "setLastModified sees the epoch as zero"
        );
        assert!(is_zero_time(None));
        assert!(!is_zero_time(Some(1)));

        let mut headers = HeaderMap::new();
        set_header(&mut headers, "if-range", "Thu, 01 Jan 1970 00:00:00 GMT");
        assert_eq!(
            check_if_range(&Method::GET, &headers, Some(0)),
            Cond::True,
            "IsZero() is false for the epoch, so the date is compared and it matches"
        );
        assert_eq!(
            check_if_range(&Method::GET, &headers, None),
            Cond::False,
            "the zero time.Time short-circuits to condFalse"
        );
    }

    /// With no `Etag` ever set, `If-Match` can only succeed through `*` and `If-None-Match` can
    /// only fail through it — every real etag falls through to the date check.
    #[test]
    fn etag_preconditions_without_an_etag() {
        let with = |name: &str, value: &str| {
            let mut headers = HeaderMap::new();
            set_header(&mut headers, name, value);
            headers
        };

        assert_eq!(check_if_match(&with("if-match", "*")), Cond::True);
        assert_eq!(check_if_match(&with("if-match", "\"abc\"")), Cond::False);
        assert_eq!(check_if_match(&HeaderMap::new()), Cond::None);

        assert_eq!(
            check_if_none_match(&with("if-none-match", "*")),
            Cond::False
        );
        assert_eq!(
            check_if_none_match(&with("if-none-match", "\"abc\"")),
            Cond::True
        );
        assert_eq!(check_if_none_match(&HeaderMap::new()), Cond::None);
    }

    /// `http.ParseTime` accepts three formats. Only the first is what any client sends, but a
    /// port that accepted only it would answer 200 where Go answers 304.
    #[test]
    fn http_dates_parse_in_all_three_formats() {
        // 2021-03-04T05:06:07Z — the corpus's fixed instant.
        assert_eq!(
            parse_http_time("Thu, 04 Mar 2021 05:06:07 GMT"),
            Some(1_614_834_367)
        );
        assert_eq!(
            parse_http_time("Thursday, 04-Mar-21 05:06:07 GMT"),
            Some(1_614_834_367)
        );
        assert_eq!(
            parse_http_time("Thu Mar  4 05:06:07 2021"),
            Some(1_614_834_367)
        );
        assert_eq!(parse_http_time("not a date"), None);
    }
}
