// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `encoding/asn1`.

#![allow(clippy::doc_markdown)]

/// Go `encoding/asn1.ObjectIdentifier` (slice).
pub type ObjectIdentifier = ::std::vec::Vec<i64>;
