// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `math/big`.

#![allow(clippy::doc_markdown)]

/// Go `math/big.Int` (gob).
pub type Int = ::gobwire::GobBytes;
