// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `net/http`.

#![allow(clippy::doc_markdown)]

/// Go `net/http.Header` (map).
pub type Header =
    ::std::collections::HashMap<::std::string::String, ::std::vec::Vec<::std::string::String>>;

/// Go `net/http.Request`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Request")]
pub struct Request {
    #[gob(name = "Method")]
    pub method: ::std::string::String,
    #[gob(name = "URL")]
    pub url: ::std::option::Option<super::url::URL>,
    #[gob(name = "Proto")]
    pub proto: ::std::string::String,
    #[gob(name = "ProtoMajor")]
    pub proto_major: i64,
    #[gob(name = "ProtoMinor")]
    pub proto_minor: i64,
    #[gob(name = "Header")]
    pub header: Header,
    #[gob(name = "Body")]
    pub body: ::std::option::Option<::gobwire::Interface>,
    #[gob(name = "ContentLength")]
    pub content_length: i64,
    #[gob(name = "TransferEncoding")]
    pub transfer_encoding: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "Close")]
    pub close: bool,
    #[gob(name = "Host")]
    pub host: ::std::string::String,
    #[gob(name = "Form")]
    pub form: super::url::Values,
    #[gob(name = "PostForm")]
    pub post_form: super::url::Values,
    #[gob(name = "MultipartForm")]
    pub multipart_form: ::std::option::Option<::std::boxed::Box<super::multipart::Form>>,
    #[gob(name = "Trailer")]
    pub trailer: Header,
    #[gob(name = "RemoteAddr")]
    pub remote_addr: ::std::string::String,
    #[gob(name = "RequestURI")]
    pub request_uri: ::std::string::String,
    #[gob(name = "TLS")]
    pub tls: ::std::option::Option<::std::boxed::Box<super::tls::ConnectionState>>,
    #[gob(name = "Response")]
    pub response: ::std::option::Option<::std::boxed::Box<Response>>,
    #[gob(name = "Pattern")]
    pub pattern: ::std::string::String,
}

/// Go `net/http.Response`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Response")]
pub struct Response {
    #[gob(name = "Status")]
    pub status: ::std::string::String,
    #[gob(name = "StatusCode")]
    pub status_code: i64,
    #[gob(name = "Proto")]
    pub proto: ::std::string::String,
    #[gob(name = "ProtoMajor")]
    pub proto_major: i64,
    #[gob(name = "ProtoMinor")]
    pub proto_minor: i64,
    #[gob(name = "Header")]
    pub header: Header,
    #[gob(name = "Body")]
    pub body: ::std::option::Option<::gobwire::Interface>,
    #[gob(name = "ContentLength")]
    pub content_length: i64,
    #[gob(name = "TransferEncoding")]
    pub transfer_encoding: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "Close")]
    pub close: bool,
    #[gob(name = "Uncompressed")]
    pub uncompressed: bool,
    #[gob(name = "Trailer")]
    pub trailer: Header,
    #[gob(name = "Request")]
    pub request: ::std::option::Option<::std::boxed::Box<Request>>,
    #[gob(name = "TLS")]
    pub tls: ::std::option::Option<::std::boxed::Box<super::tls::ConnectionState>>,
}
