// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `encoding/json`.

#![allow(clippy::doc_markdown)]

/// Go `encoding/json.RawMessage` (slice).
pub type RawMessage = ::std::vec::Vec<u8>;
