// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `github.com/mattermost/logr/v2`.

#![allow(clippy::doc_markdown)]

/// Go `github.com/mattermost/logr/v2.Color` (uint8).
pub type Color = u8;

/// Go `github.com/mattermost/logr/v2.Level`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Level")]
pub struct Level {
    #[gob(name = "ID")]
    pub id: LevelID,
    #[gob(name = "Name")]
    pub name: ::std::string::String,
    #[gob(name = "Stacktrace")]
    pub stacktrace: bool,
    #[gob(name = "Color")]
    pub color: Color,
}

/// Go `github.com/mattermost/logr/v2.LevelID` (uint).
pub type LevelID = u64;
