// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `mime/multipart`.

#![allow(clippy::doc_markdown)]

/// Go `mime/multipart.FileHeader`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "FileHeader")]
pub struct FileHeader {
    #[gob(name = "Filename")]
    pub filename: ::std::string::String,
    #[gob(name = "Header")]
    pub header: super::textproto::MIMEHeader,
    #[gob(name = "Size")]
    pub size: i64,
}

/// Go `mime/multipart.Form`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Form")]
pub struct Form {
    #[gob(name = "Value")]
    pub value:
        ::std::collections::HashMap<::std::string::String, ::std::vec::Vec<::std::string::String>>,
    #[gob(name = "File")]
    pub file: ::std::collections::HashMap<::std::string::String, ::std::vec::Vec<FileHeader>>,
}
