// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `net`.

#![allow(clippy::doc_markdown)]

/// Go `net.IP` (slice).
pub type IP = ::std::vec::Vec<u8>;

/// Go `net.IPMask` (slice).
pub type IPMask = ::std::vec::Vec<u8>;

/// Go `net.IPNet`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "IPNet")]
pub struct IPNet {
    #[gob(name = "IP")]
    pub ip: IP,
    #[gob(name = "Mask")]
    pub mask: IPMask,
}
