// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `crypto/x509/pkix`.

#![allow(clippy::doc_markdown)]

/// Go `crypto/x509/pkix.AttributeTypeAndValue`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AttributeTypeAndValue")]
pub struct AttributeTypeAndValue {
    #[gob(name = "Type")]
    pub r#type: super::asn1::ObjectIdentifier,
    #[gob(name = "Value")]
    pub value: ::std::option::Option<::gobwire::Interface>,
}

/// Go `crypto/x509/pkix.Extension`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Extension")]
pub struct Extension {
    #[gob(name = "Id")]
    pub id: super::asn1::ObjectIdentifier,
    #[gob(name = "Critical")]
    pub critical: bool,
    #[gob(name = "Value")]
    pub value: ::std::vec::Vec<u8>,
}

/// Go `crypto/x509/pkix.Name`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Name")]
pub struct Name {
    #[gob(name = "Country")]
    pub country: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "Organization")]
    pub organization: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "OrganizationalUnit")]
    pub organizational_unit: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "Locality")]
    pub locality: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "Province")]
    pub province: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "StreetAddress")]
    pub street_address: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "PostalCode")]
    pub postal_code: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "SerialNumber")]
    pub serial_number: ::std::string::String,
    #[gob(name = "CommonName")]
    pub common_name: ::std::string::String,
    #[gob(name = "Names")]
    pub names: ::std::vec::Vec<AttributeTypeAndValue>,
    #[gob(name = "ExtraNames")]
    pub extra_names: ::std::vec::Vec<AttributeTypeAndValue>,
}
