// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `github.com/lib/pq`.

#![allow(clippy::doc_markdown)]

/// Go `github.com/lib/pq.Error`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Error")]
pub struct Error {
    #[gob(name = "Severity")]
    pub severity: ::std::string::String,
    #[gob(name = "Code")]
    pub code: super::pqerror::Code,
    #[gob(name = "Message")]
    pub message: ::std::string::String,
    #[gob(name = "Detail")]
    pub detail: ::std::string::String,
    #[gob(name = "Hint")]
    pub hint: ::std::string::String,
    #[gob(name = "Position")]
    pub position: ::std::string::String,
    #[gob(name = "InternalPosition")]
    pub internal_position: ::std::string::String,
    #[gob(name = "InternalQuery")]
    pub internal_query: ::std::string::String,
    #[gob(name = "Where")]
    pub r#where: ::std::string::String,
    #[gob(name = "Schema")]
    pub schema: ::std::string::String,
    #[gob(name = "Table")]
    pub table: ::std::string::String,
    #[gob(name = "Column")]
    pub column: ::std::string::String,
    #[gob(name = "DataTypeName")]
    pub data_type_name: ::std::string::String,
    #[gob(name = "Constraint")]
    pub constraint: ::std::string::String,
    #[gob(name = "File")]
    pub file: ::std::string::String,
    #[gob(name = "Line")]
    pub line: ::std::string::String,
    #[gob(name = "Routine")]
    pub routine: ::std::string::String,
}
