// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `github.com/lib/pq/pqerror`.

#![allow(clippy::doc_markdown)]

/// Go `github.com/lib/pq/pqerror.Code` (string).
pub type Code = ::std::string::String;
