// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `github.com/mattermost/gosaml2`.

#![allow(clippy::doc_markdown)]

/// Go `github.com/mattermost/gosaml2.AssertionInfo`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AssertionInfo")]
pub struct AssertionInfo {
    #[gob(name = "NameID")]
    pub name_id: ::std::string::String,
    #[gob(name = "Values")]
    pub values: Values,
    #[gob(name = "WarningInfo")]
    pub warning_info: ::std::option::Option<::std::boxed::Box<WarningInfo>>,
    #[gob(name = "SessionIndex")]
    pub session_index: ::std::string::String,
    #[gob(name = "AuthnInstant")]
    pub authn_instant: ::std::option::Option<::gobwire::GoTime>,
    #[gob(name = "SessionNotOnOrAfter")]
    pub session_not_on_or_after: ::std::option::Option<::gobwire::GoTime>,
    #[gob(name = "Assertions")]
    pub assertions: ::std::vec::Vec<super::saml2_types::Assertion>,
    #[gob(name = "ResponseSignatureValidated")]
    pub response_signature_validated: bool,
}

/// Go `github.com/mattermost/gosaml2.ProxyRestriction`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "ProxyRestriction")]
pub struct ProxyRestriction {
    #[gob(name = "Count")]
    pub count: i64,
    #[gob(name = "Audience")]
    pub audience: ::std::vec::Vec<::std::string::String>,
}

/// Go `github.com/mattermost/gosaml2.Values` (map).
pub type Values = ::std::collections::HashMap<::std::string::String, super::saml2_types::Attribute>;

/// Go `github.com/mattermost/gosaml2.WarningInfo`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "WarningInfo")]
pub struct WarningInfo {
    #[gob(name = "OneTimeUse")]
    pub one_time_use: bool,
    #[gob(name = "ProxyRestriction")]
    pub proxy_restriction: ::std::option::Option<::std::boxed::Box<ProxyRestriction>>,
    #[gob(name = "NotInAudience")]
    pub not_in_audience: bool,
    #[gob(name = "InvalidTime")]
    pub invalid_time: bool,
}
