// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `github.com/mattermost/gosaml2/types`.

#![allow(clippy::doc_markdown)]

/// Go `github.com/mattermost/gosaml2/types.Assertion`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Assertion")]
pub struct Assertion {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Version")]
    pub version: ::std::string::String,
    #[gob(name = "ID")]
    pub id: ::std::string::String,
    #[gob(name = "IssueInstant")]
    pub issue_instant: ::gobwire::GoTime,
    #[gob(name = "Issuer")]
    pub issuer: ::std::option::Option<::std::boxed::Box<Issuer>>,
    #[gob(name = "Signature")]
    pub signature: ::std::option::Option<::std::boxed::Box<Signature>>,
    #[gob(name = "Subject")]
    pub subject: ::std::option::Option<::std::boxed::Box<Subject>>,
    #[gob(name = "Conditions")]
    pub conditions: ::std::option::Option<::std::boxed::Box<Conditions>>,
    #[gob(name = "AttributeStatement")]
    pub attribute_statement: ::std::option::Option<::std::boxed::Box<AttributeStatement>>,
    #[gob(name = "AuthnStatement")]
    pub authn_statement: ::std::option::Option<::std::boxed::Box<AuthnStatement>>,
    #[gob(name = "SignatureValidated")]
    pub signature_validated: bool,
}

/// Go `github.com/mattermost/gosaml2/types.Attribute`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Attribute")]
pub struct Attribute {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "FriendlyName")]
    pub friendly_name: ::std::string::String,
    #[gob(name = "Name")]
    pub name: ::std::string::String,
    #[gob(name = "NameFormat")]
    pub name_format: ::std::string::String,
    #[gob(name = "Values")]
    pub values: ::std::vec::Vec<AttributeValue>,
}

/// Go `github.com/mattermost/gosaml2/types.AttributeStatement`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AttributeStatement")]
pub struct AttributeStatement {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Attributes")]
    pub attributes: ::std::vec::Vec<Attribute>,
}

/// Go `github.com/mattermost/gosaml2/types.AttributeValue`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AttributeValue")]
pub struct AttributeValue {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Type")]
    pub r#type: ::std::string::String,
    #[gob(name = "Value")]
    pub value: ::std::string::String,
}

/// Go `github.com/mattermost/gosaml2/types.Audience`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Audience")]
pub struct Audience {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Value")]
    pub value: ::std::string::String,
}

/// Go `github.com/mattermost/gosaml2/types.AudienceRestriction`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AudienceRestriction")]
pub struct AudienceRestriction {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Audiences")]
    pub audiences: ::std::vec::Vec<Audience>,
}

/// Go `github.com/mattermost/gosaml2/types.AuthnContext`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AuthnContext")]
pub struct AuthnContext {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "AuthnContextClassRef")]
    pub authn_context_class_ref: ::std::option::Option<::std::boxed::Box<AuthnContextClassRef>>,
}

/// Go `github.com/mattermost/gosaml2/types.AuthnContextClassRef`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AuthnContextClassRef")]
pub struct AuthnContextClassRef {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Value")]
    pub value: ::std::string::String,
}

/// Go `github.com/mattermost/gosaml2/types.AuthnStatement`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "AuthnStatement")]
pub struct AuthnStatement {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "SessionIndex")]
    pub session_index: ::std::string::String,
    #[gob(name = "AuthnInstant")]
    pub authn_instant: ::std::option::Option<::gobwire::GoTime>,
    #[gob(name = "SessionNotOnOrAfter")]
    pub session_not_on_or_after: ::std::option::Option<::gobwire::GoTime>,
    #[gob(name = "AuthnContext")]
    pub authn_context: ::std::option::Option<::std::boxed::Box<AuthnContext>>,
}

/// Go `github.com/mattermost/gosaml2/types.Conditions`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Conditions")]
pub struct Conditions {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "NotBefore")]
    pub not_before: ::std::string::String,
    #[gob(name = "NotOnOrAfter")]
    pub not_on_or_after: ::std::string::String,
    #[gob(name = "AudienceRestrictions")]
    pub audience_restrictions: ::std::vec::Vec<AudienceRestriction>,
    #[gob(name = "OneTimeUse")]
    pub one_time_use: ::std::option::Option<::std::boxed::Box<OneTimeUse>>,
    #[gob(name = "ProxyRestriction")]
    pub proxy_restriction: ::std::option::Option<::std::boxed::Box<ProxyRestriction>>,
}

/// Go `github.com/mattermost/gosaml2/types.Issuer`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Issuer")]
pub struct Issuer {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Value")]
    pub value: ::std::string::String,
}

/// Go `github.com/mattermost/gosaml2/types.NameID`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "NameID")]
pub struct NameID {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Value")]
    pub value: ::std::string::String,
}

/// Go `github.com/mattermost/gosaml2/types.OneTimeUse`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "OneTimeUse")]
pub struct OneTimeUse {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
}

/// Go `github.com/mattermost/gosaml2/types.ProxyRestriction`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "ProxyRestriction")]
pub struct ProxyRestriction {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Count")]
    pub count: i64,
    #[gob(name = "Audience")]
    pub audience: ::std::vec::Vec<Audience>,
}

/// Go `github.com/mattermost/gosaml2/types.Signature`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Signature")]
pub struct Signature {
    #[gob(name = "SignatureDocument")]
    pub signature_document: ::std::vec::Vec<u8>,
}

/// Go `github.com/mattermost/gosaml2/types.Subject`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Subject")]
pub struct Subject {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "NameID")]
    pub name_id: ::std::option::Option<::std::boxed::Box<NameID>>,
    #[gob(name = "SubjectConfirmation")]
    pub subject_confirmation: ::std::option::Option<::std::boxed::Box<SubjectConfirmation>>,
}

/// Go `github.com/mattermost/gosaml2/types.SubjectConfirmation`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "SubjectConfirmation")]
pub struct SubjectConfirmation {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "Method")]
    pub method: ::std::string::String,
    #[gob(name = "SubjectConfirmationData")]
    pub subject_confirmation_data:
        ::std::option::Option<::std::boxed::Box<SubjectConfirmationData>>,
}

/// Go `github.com/mattermost/gosaml2/types.SubjectConfirmationData`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "SubjectConfirmationData")]
pub struct SubjectConfirmationData {
    #[gob(name = "XMLName")]
    pub xml_name: super::xml::Name,
    #[gob(name = "NotOnOrAfter")]
    pub not_on_or_after: ::std::string::String,
    #[gob(name = "Recipient")]
    pub recipient: ::std::string::String,
    #[gob(name = "InResponseTo")]
    pub in_response_to: ::std::string::String,
}
