// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `database/sql/driver`.

#![allow(clippy::doc_markdown)]

/// Go `database/sql/driver.IsolationLevel` (int).
pub type IsolationLevel = i64;

/// Go `database/sql/driver.NamedValue`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "NamedValue")]
pub struct NamedValue {
    #[gob(name = "Name")]
    pub name: ::std::string::String,
    #[gob(name = "Ordinal")]
    pub ordinal: i64,
    #[gob(name = "Value")]
    pub value: ::std::option::Option<::gobwire::Interface>,
}

/// Go `database/sql/driver.TxOptions`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "TxOptions")]
pub struct TxOptions {
    #[gob(name = "Isolation")]
    pub isolation: IsolationLevel,
    #[gob(name = "ReadOnly")]
    pub read_only: bool,
}
