// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `net/textproto`.

#![allow(clippy::doc_markdown)]

/// Go `net/textproto.MIMEHeader` (map).
pub type MIMEHeader =
    ::std::collections::HashMap<::std::string::String, ::std::vec::Vec<::std::string::String>>;
