// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `crypto/tls`.

#![allow(clippy::doc_markdown)]

/// Go `crypto/tls.ConnectionState`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "ConnectionState")]
pub struct ConnectionState {
    #[gob(name = "Version")]
    pub version: u16,
    #[gob(name = "HandshakeComplete")]
    pub handshake_complete: bool,
    #[gob(name = "DidResume")]
    pub did_resume: bool,
    #[gob(name = "CipherSuite")]
    pub cipher_suite: u16,
    #[gob(name = "CurveID")]
    pub curve_id: CurveID,
    #[gob(name = "NegotiatedProtocol")]
    pub negotiated_protocol: ::std::string::String,
    #[gob(name = "NegotiatedProtocolIsMutual")]
    pub negotiated_protocol_is_mutual: bool,
    #[gob(name = "ServerName")]
    pub server_name: ::std::string::String,
    #[gob(name = "PeerCertificates")]
    pub peer_certificates: ::std::vec::Vec<super::x509::Certificate>,
    #[gob(name = "VerifiedChains")]
    pub verified_chains: ::std::vec::Vec<::std::vec::Vec<super::x509::Certificate>>,
    #[gob(name = "SignedCertificateTimestamps")]
    pub signed_certificate_timestamps: ::std::vec::Vec<::std::vec::Vec<u8>>,
    #[gob(name = "OCSPResponse")]
    pub ocsp_response: ::std::vec::Vec<u8>,
    #[gob(name = "TLSUnique")]
    pub tls_unique: ::std::vec::Vec<u8>,
    #[gob(name = "ECHAccepted")]
    pub ech_accepted: bool,
    #[gob(name = "HelloRetryRequest")]
    pub hello_retry_request: bool,
}

/// Go `crypto/tls.CurveID` (uint16).
pub type CurveID = u16;
