// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `crypto/x509`.

#![allow(clippy::doc_markdown)]

/// Go `crypto/x509.Certificate`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Certificate")]
pub struct Certificate {
    #[gob(name = "Raw")]
    pub raw: ::std::vec::Vec<u8>,
    #[gob(name = "RawTBSCertificate")]
    pub raw_tbs_certificate: ::std::vec::Vec<u8>,
    #[gob(name = "RawSubjectPublicKeyInfo")]
    pub raw_subject_public_key_info: ::std::vec::Vec<u8>,
    #[gob(name = "RawSubject")]
    pub raw_subject: ::std::vec::Vec<u8>,
    #[gob(name = "RawIssuer")]
    pub raw_issuer: ::std::vec::Vec<u8>,
    #[gob(name = "Signature")]
    pub signature: ::std::vec::Vec<u8>,
    #[gob(name = "SignatureAlgorithm")]
    pub signature_algorithm: SignatureAlgorithm,
    #[gob(name = "PublicKeyAlgorithm")]
    pub public_key_algorithm: PublicKeyAlgorithm,
    #[gob(name = "PublicKey")]
    pub public_key: ::std::option::Option<::gobwire::Interface>,
    #[gob(name = "Version")]
    pub version: i64,
    #[gob(name = "SerialNumber")]
    pub serial_number: ::std::option::Option<super::big::Int>,
    #[gob(name = "Issuer")]
    pub issuer: super::pkix::Name,
    #[gob(name = "Subject")]
    pub subject: super::pkix::Name,
    #[gob(name = "NotBefore")]
    pub not_before: ::gobwire::GoTime,
    #[gob(name = "NotAfter")]
    pub not_after: ::gobwire::GoTime,
    #[gob(name = "KeyUsage")]
    pub key_usage: KeyUsage,
    #[gob(name = "Extensions")]
    pub extensions: ::std::vec::Vec<super::pkix::Extension>,
    #[gob(name = "ExtraExtensions")]
    pub extra_extensions: ::std::vec::Vec<super::pkix::Extension>,
    #[gob(name = "UnhandledCriticalExtensions")]
    pub unhandled_critical_extensions: ::std::vec::Vec<super::asn1::ObjectIdentifier>,
    #[gob(name = "ExtKeyUsage")]
    pub ext_key_usage: ::std::vec::Vec<ExtKeyUsage>,
    #[gob(name = "UnknownExtKeyUsage")]
    pub unknown_ext_key_usage: ::std::vec::Vec<super::asn1::ObjectIdentifier>,
    #[gob(name = "BasicConstraintsValid")]
    pub basic_constraints_valid: bool,
    #[gob(name = "IsCA")]
    pub is_ca: bool,
    #[gob(name = "MaxPathLen")]
    pub max_path_len: i64,
    #[gob(name = "MaxPathLenZero")]
    pub max_path_len_zero: bool,
    #[gob(name = "SubjectKeyId")]
    pub subject_key_id: ::std::vec::Vec<u8>,
    #[gob(name = "AuthorityKeyId")]
    pub authority_key_id: ::std::vec::Vec<u8>,
    #[gob(name = "OCSPServer")]
    pub ocsp_server: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "IssuingCertificateURL")]
    pub issuing_certificate_url: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "DNSNames")]
    pub dns_names: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "EmailAddresses")]
    pub email_addresses: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "IPAddresses")]
    pub ip_addresses: ::std::vec::Vec<super::net::IP>,
    #[gob(name = "URIs")]
    pub ur_is: ::std::vec::Vec<super::url::URL>,
    #[gob(name = "PermittedDNSDomainsCritical")]
    pub permitted_dns_domains_critical: bool,
    #[gob(name = "PermittedDNSDomains")]
    pub permitted_dns_domains: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "ExcludedDNSDomains")]
    pub excluded_dns_domains: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "PermittedIPRanges")]
    pub permitted_ip_ranges: ::std::vec::Vec<super::net::IPNet>,
    #[gob(name = "ExcludedIPRanges")]
    pub excluded_ip_ranges: ::std::vec::Vec<super::net::IPNet>,
    #[gob(name = "PermittedEmailAddresses")]
    pub permitted_email_addresses: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "ExcludedEmailAddresses")]
    pub excluded_email_addresses: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "PermittedURIDomains")]
    pub permitted_uri_domains: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "ExcludedURIDomains")]
    pub excluded_uri_domains: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "CRLDistributionPoints")]
    pub crl_distribution_points: ::std::vec::Vec<::std::string::String>,
    #[gob(name = "PolicyIdentifiers")]
    pub policy_identifiers: ::std::vec::Vec<super::asn1::ObjectIdentifier>,
    #[gob(name = "Policies")]
    pub policies: ::std::vec::Vec<OID>,
    #[gob(name = "InhibitAnyPolicy")]
    pub inhibit_any_policy: i64,
    #[gob(name = "InhibitAnyPolicyZero")]
    pub inhibit_any_policy_zero: bool,
    #[gob(name = "InhibitPolicyMapping")]
    pub inhibit_policy_mapping: i64,
    #[gob(name = "InhibitPolicyMappingZero")]
    pub inhibit_policy_mapping_zero: bool,
    #[gob(name = "RequireExplicitPolicy")]
    pub require_explicit_policy: i64,
    #[gob(name = "RequireExplicitPolicyZero")]
    pub require_explicit_policy_zero: bool,
    #[gob(name = "PolicyMappings")]
    pub policy_mappings: ::std::vec::Vec<PolicyMapping>,
}

/// Go `crypto/x509.ExtKeyUsage` (int).
pub type ExtKeyUsage = i64;

/// Go `crypto/x509.KeyUsage` (int).
pub type KeyUsage = i64;

/// Go `crypto/x509.OID` (binary).
pub type OID = ::gobwire::BinaryBytes;

/// Go `crypto/x509.PolicyMapping`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "PolicyMapping")]
pub struct PolicyMapping {
    #[gob(name = "IssuerDomainPolicy")]
    pub issuer_domain_policy: OID,
    #[gob(name = "SubjectDomainPolicy")]
    pub subject_domain_policy: OID,
}

/// Go `crypto/x509.PublicKeyAlgorithm` (int).
pub type PublicKeyAlgorithm = i64;

/// Go `crypto/x509.SignatureAlgorithm` (int).
pub type SignatureAlgorithm = i64;
