// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! Gob wire types of Go package `encoding/xml`.

#![allow(clippy::doc_markdown)]

/// Go `encoding/xml.Name`, as gob sends it.
#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]
#[gob(name = "Name")]
pub struct Name {
    #[gob(name = "Space")]
    pub space: ::std::string::String,
    #[gob(name = "Local")]
    pub local: ::std::string::String,
}
