//! Cross-server parity for the plugin Marketplace: `GET` and `POST /api/v4/plugins/marketplace`
//! (api4/plugin.go:284, :130) and `POST /api/v4/plugins/install_from_url` (:100), with this
//! server hosting plugins.
//!
//! ```sh
//! scripts/parity.sh --test parity marketplace
//! ```
//!
//! The Marketplace is an outbound service, so this suite **is** the Marketplace: a mock served
//! from the test process on Go's port + 37, which `scripts/go-plugins.sh` points the plugins
//! oracle at (`MarketplaceURL`, with `AllowInsecureDownloadURL` so bundles come over plain http,
//! and `SignaturePublicKeyFiles` naming the test key this suite plants in `ConfigurationFiles`).
//! The Rust host is a second `mm-api` given the same three settings. The bundles, their
//! signatures and the key are `fixtures/behaviour_plugin_signature.json`, generated by
//! `reference/dump`. Each case goes to both servers and the answers are compared, and so are the
//! requests each server made of the Marketplace.
//!
//! The settings a Go oracle cannot be given per case — the remote Marketplace off, the
//! Marketplace off, plugins off, a signature requirement — are covered against further Rust
//! hosts, with Go's answers transcribed from plugin.go; each such assertion says so.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use base64::Engine;

use crate::common;

use common::{
    GO, SecondServer, assert_error_bodies_match_except_known_gaps, client, create_plain_user,
    delete_plain_user, go_minted_token, stack_enabled,
};

/// The Rust host compared with the plugins oracle; see `second_server_ports`. 8067-8094 are
/// nearly all taken, so two of these sit above the stack's oracles (+30..+37), below the next
/// stack's Go (+100).
const HOST_PORT: u16 = 8067;
/// Remote Marketplace off, uploads on, insecure downloads off.
const REMOTE_OFF_PORT: u16 = 8068;
/// Marketplace off, uploads on, a signature requirement.
const MARKETPLACE_OFF_PORT: u16 = 8094;
/// Plugins off.
const PLUGINS_OFF_PORT: u16 = 8103;
/// Every setting at its default: uploads off.
const DEFAULTS_PORT: u16 = 8104;

/// The configuration file `go-plugins.sh` names in `SignaturePublicKeyFiles`.
const KEY_FILE: &str = "mmrs-marketplace-test.plugin.asc";

fn go_port() -> u16 {
    GO.rsplit(':')
        .next()
        .and_then(|p| p.parse().ok())
        .expect("GO has a port")
}

fn oracle() -> String {
    super::plugin_upload::oracle()
}

// ---------------------------------------------------------------------------------------------
// The fixture
// ---------------------------------------------------------------------------------------------

fn fixture() -> serde_json::Value {
    serde_json::from_str(include_str!(
        "../../../../fixtures/behaviour_plugin_signature.json"
    ))
    .expect("generated by reference/dump")
}

/// The fixture's base64 for one entry, which is also the Marketplace's `signature` form.
fn b64(fixture: &serde_json::Value, section: &str, name: &str) -> String {
    fixture[section][name]
        .as_str()
        .expect("a base64 string")
        .to_owned()
}

fn raw(fixture: &serde_json::Value, section: &str, name: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(b64(fixture, section, name))
        .expect("base64")
}

// ---------------------------------------------------------------------------------------------
// The mock Marketplace
// ---------------------------------------------------------------------------------------------

#[derive(Default)]
struct Mock {
    /// Every request, as `path?query`, in arrival order.
    requests: Vec<String>,
    /// What `/api/v1/plugins` answers without a `plugin_id`.
    list: (u16, String),
    /// What it answers for a `plugin_id`; `[]` when absent.
    by_id: HashMap<String, (u16, String)>,
    bundles: HashMap<String, Vec<u8>>,
    /// Requests seen per `/flaky/{key}` key: the first two fail.
    flaky: HashMap<String, u32>,
}

type Shared = Arc<Mutex<Mock>>;

async fn plugins(
    axum::extract::State(mock): axum::extract::State<Shared>,
    axum::extract::RawQuery(query): axum::extract::RawQuery,
) -> (axum::http::StatusCode, String) {
    let mut mock = mock.lock().unwrap();
    let query = query.unwrap_or_default();
    mock.requests.push(format!("/api/v1/plugins?{query}"));
    let plugin_id = form_urlencoded::parse(query.as_bytes())
        .find(|(k, _)| k == "plugin_id")
        .map(|(_, v)| v.into_owned())
        .unwrap_or_default();
    let (status, body) = if plugin_id.is_empty() {
        mock.list.clone()
    } else {
        mock.by_id
            .get(&plugin_id)
            .cloned()
            .unwrap_or((200, "[]".to_owned()))
    };
    (axum::http::StatusCode::from_u16(status).unwrap(), body)
}

async fn bundle(
    axum::extract::State(mock): axum::extract::State<Shared>,
    axum::extract::Path(name): axum::extract::Path<String>,
) -> (axum::http::StatusCode, Vec<u8>) {
    let mut mock = mock.lock().unwrap();
    mock.requests.push(format!("/bundles/{name}"));
    match mock.bundles.get(&name) {
        Some(bytes) => (axum::http::StatusCode::OK, bytes.clone()),
        None => (axum::http::StatusCode::NOT_FOUND, Vec::new()),
    }
}

async fn flaky(
    axum::extract::State(mock): axum::extract::State<Shared>,
    axum::extract::Path((key, name)): axum::extract::Path<(String, String)>,
) -> (axum::http::StatusCode, Vec<u8>) {
    let mut mock = mock.lock().unwrap();
    mock.requests.push(format!("/flaky/{key}/{name}"));
    let seen = mock.flaky.entry(key).or_insert(0);
    *seen += 1;
    if *seen <= 2 {
        return (axum::http::StatusCode::SERVICE_UNAVAILABLE, Vec::new());
    }
    match mock.bundles.get(&name) {
        Some(bytes) => (axum::http::StatusCode::OK, bytes.clone()),
        None => (axum::http::StatusCode::NOT_FOUND, Vec::new()),
    }
}

/// Serve the mock on `127.0.0.1:port` (`0` for any), returning its state and base URL.
async fn start_mock(port: u16) -> (Shared, String) {
    let mock: Shared = Arc::default();
    let app = axum::Router::new()
        .route("/api/v1/plugins", axum::routing::get(plugins))
        .route("/bundles/{name}", axum::routing::get(bundle))
        .route("/flaky/{key}/{name}", axum::routing::get(flaky))
        .with_state(Arc::clone(&mock));
    let listener = tokio::net::TcpListener::bind(("127.0.0.1", port))
        .await
        .unwrap_or_else(|e| panic!("the mock Marketplace cannot bind :{port}: {e}"));
    let base = format!("http://127.0.0.1:{}", listener.local_addr().unwrap().port());
    tokio::spawn(async move {
        let _ = axum::serve(listener, app).await;
    });
    (mock, base)
}

fn take_requests(mock: &Shared) -> Vec<String> {
    std::mem::take(&mut mock.lock().unwrap().requests)
}

/// A Marketplace entry. Every field carries a value, and the manifest has an unknown key, which
/// both servers must drop.
fn entry(
    id: &str,
    name: &str,
    version: &str,
    download_url: &str,
    signature: &str,
) -> serde_json::Value {
    serde_json::json!({
        "homepage_url": format!("https://example.invalid/{id}"),
        "icon_data": "data:image/svg+xml;base64,PHN2Zz48L3N2Zz4=",
        "download_url": download_url,
        "release_notes_url": format!("https://example.invalid/{id}/notes"),
        "labels": [],
        "hosting": "on-prem",
        "author_type": "mattermost",
        "release_stage": "production",
        "enterprise": true,
        "signature": signature,
        "manifest": {
            "id": id,
            "name": name,
            "description": format!("{name} <from the mock>"),
            "version": version,
            "min_server_version": "5.0.0",
            "webapp": {"bundle_path": "dist/main.js"},
            "props": {"k": "v"},
            "unknown_to_go": true,
        },
    })
}

// ---------------------------------------------------------------------------------------------
// Sending a case to both servers
// ---------------------------------------------------------------------------------------------

struct Answer {
    status: u16,
    content_type: String,
    body: Vec<u8>,
    rust: bool,
}

async fn send(
    client: &reqwest::Client,
    method: reqwest::Method,
    base: &str,
    token: &str,
    path: &str,
    body: Option<&[u8]>,
) -> Answer {
    let mut request = client
        .request(method, format!("{base}{path}"))
        .header("Authorization", format!("Bearer {token}"))
        .header("X-Requested-With", "XMLHttpRequest");
    if let Some(body) = body {
        request = request.body(body.to_vec());
    }
    let response = request
        .send()
        .await
        .unwrap_or_else(|e| panic!("{base}{path} is unreachable: {e}"));
    let header = |name: &str| {
        response
            .headers()
            .get(name)
            .and_then(|v| v.to_str().ok())
            .unwrap_or_default()
            .to_owned()
    };
    Answer {
        status: response.status().as_u16(),
        content_type: header("content-type"),
        rust: header("x-mmrs-served-by") == "rust",
        body: response.bytes().await.unwrap().to_vec(),
    }
}

fn assert_same(go: &Answer, rs: &Answer, case: &str) {
    assert!(rs.rust, "{case}: not served by this server");
    assert_eq!(
        go.status,
        rs.status,
        "{case}: Go {} / Rust {}",
        String::from_utf8_lossy(&go.body),
        String::from_utf8_lossy(&rs.body)
    );
    assert_eq!(go.content_type, rs.content_type, "{case}: Content-Type");
    let is_error = serde_json::from_slice::<serde_json::Value>(&go.body)
        .is_ok_and(|v| v.get("status_code").is_some());
    if is_error {
        assert_error_bodies_match_except_known_gaps(&go.body, &rs.body, case);
    } else {
        assert_eq!(
            String::from_utf8_lossy(&go.body),
            String::from_utf8_lossy(&rs.body),
            "{case}"
        );
    }
}

/// One case to the oracle, then to the Rust host, comparing the answers and the Marketplace
/// requests each made. Returns Go's answer.
#[allow(clippy::too_many_arguments)]
async fn both(
    client: &reqwest::Client,
    mock: &Shared,
    rust: &str,
    method: reqwest::Method,
    token: &str,
    path: &str,
    body: Option<&[u8]>,
    case: &str,
) -> Answer {
    take_requests(mock);
    let go = send(client, method.clone(), &oracle(), token, path, body).await;
    let go_requests = take_requests(mock);
    let rs = send(client, method, rust, token, path, body).await;
    let rust_requests = take_requests(mock);
    assert_same(&go, &rs, case);
    assert_eq!(
        go_requests, rust_requests,
        "{case}: the Marketplace requests"
    );
    go
}

/// `install_from_url` to both, each with its own URL — the flaky endpoint counts per key.
async fn both_from_url(
    client: &reqwest::Client,
    rust: &str,
    token: &str,
    go_url: &str,
    rust_url: &str,
    force: &str,
    case: &str,
) -> Answer {
    let path = |url: &str| {
        format!(
            "/api/v4/plugins/install_from_url?force={force}&plugin_download_url={}",
            form_urlencoded::byte_serialize(url.as_bytes()).collect::<String>()
        )
    };
    let go = send(
        client,
        reqwest::Method::POST,
        &oracle(),
        token,
        &path(go_url),
        None,
    )
    .await;
    let rs = send(
        client,
        reqwest::Method::POST,
        rust,
        token,
        &path(rust_url),
        None,
    )
    .await;
    assert_same(&go, &rs, case);
    go
}

/// Put the test key where `SignaturePublicKeyFiles` points both servers.
async fn plant_key(fixture: &serde_json::Value) {
    let pool = common::fixture_pool().await.expect("the stack database");
    let key = String::from_utf8(raw(fixture, "keys", "armored")).expect("armored is text");
    sqlx::query(
        "INSERT INTO configurationfiles (name, data, createat, updateat) VALUES ($1, $2, 1, 1) \
         ON CONFLICT (name) DO UPDATE SET data = EXCLUDED.data",
    )
    .bind(KEY_FILE)
    .bind(key)
    .execute(&pool)
    .await
    .expect("the key file is planted");
}

fn scratch(name: &str) -> (PathBuf, [String; 3]) {
    let root = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(name);
    let _ = std::fs::remove_dir_all(&root);
    for dir in ["plugins", "client", "data"] {
        std::fs::create_dir_all(root.join(dir)).unwrap();
    }
    let s = |dir: &str| root.join(dir).to_string_lossy().into_owned();
    let dirs = [s("plugins"), s("client"), format!("{}/", s("data"))];
    (root, dirs)
}

const MARKETPLACE: &str = "/api/v4/plugins/marketplace";
const ALPHA: &str = "mmrs.market.alpha";

#[tokio::test]
async fn the_marketplace_answers_as_it_does_on_go() {
    if !stack_enabled() {
        return;
    }
    let _unlicensed = common::ACTIVE_LICENCE_ROW.read().await;
    let _states = common::PLUGIN_STATES.lock().await;
    let client = client();
    let ping = client
        .get(format!("{}/api/v4/system/ping", oracle()))
        .send()
        .await;
    assert!(
        ping.is_ok_and(|r| r.status().is_success()),
        "marketplace: no plugins oracle at {}. Run `scripts/go-plugins.sh start`.",
        oracle()
    );
    let fixture = fixture();
    plant_key(&fixture).await;
    let admin = go_minted_token(&client).await;

    let (mock, market) = start_mock(go_port() + 37).await;
    {
        let mut m = mock.lock().unwrap();
        m.bundles
            .insert("alpha".into(), raw(&fixture, "bundles", "alpha"));
        m.bundles
            .insert("beta".into(), raw(&fixture, "bundles", "beta"));
        m.list = (200, "[]".to_owned());
    }

    let (_root, [plugins, client_dir, data]) = scratch("marketplace-host");
    let Some(host) = SecondServer::start(
        HOST_PORT,
        &[
            ("MMRS_PLUGIN_HOST", "rust"),
            ("MM_PLUGINSETTINGS_ENABLEUPLOADS", "true"),
            ("MM_PLUGINSETTINGS_MARKETPLACEURL", market.as_str()),
            ("MM_PLUGINSETTINGS_ALLOWINSECUREDOWNLOADURL", "true"),
            ("MM_PLUGINSETTINGS_SIGNATUREPUBLICKEYFILES", KEY_FILE),
            ("MM_PLUGINSETTINGS_DIRECTORY", plugins.as_str()),
            ("MM_PLUGINSETTINGS_CLIENTDIRECTORY", client_dir.as_str()),
            ("MM_FILESETTINGS_DIRECTORY", data.as_str()),
        ],
    )
    .await
    else {
        return;
    };
    let rust = host.base.as_str();
    let alpha_url = format!("{market}/bundles/alpha");
    let set_alpha = |response: (u16, String)| {
        mock.lock()
            .unwrap()
            .by_id
            .insert(ALPHA.to_owned(), response);
    };
    let alpha_entry = |version: &str, url: &str, signature: &str| {
        serde_json::json!([entry(ALPHA, "MMRS Market Alpha", version, url, signature)]).to_string()
    };
    use reqwest::Method;

    // --- POST /plugins/marketplace, the refusals in Go's order ---
    let team = common::create_team(&client, &admin, "mkt").await;
    let user = create_plain_user(&client, &admin, &team, "mkt").await;
    let body = format!(r#"{{"id":"{ALPHA}"}}"#);
    both(
        &client,
        &mock,
        rust,
        Method::POST,
        &user.token,
        MARKETPLACE,
        Some(body.as_bytes()),
        "install: a plain user",
    )
    .await;
    for (bad, case) in [
        (&b""[..], "install: an empty body"),
        (br#"{"id":5}"#, "install: a mistyped id"),
        (b"[]", "install: an array"),
    ] {
        both(
            &client,
            &mock,
            rust,
            Method::POST,
            &admin,
            MARKETPLACE,
            Some(bad),
            case,
        )
        .await;
    }
    // Case-insensitive keys, an id the Marketplace does not have, and the version discarded.
    both(
        &client,
        &mock,
        rust,
        Method::POST,
        &admin,
        MARKETPLACE,
        Some(br#"{"ID":"mmrs.market.none","version":"9.9.9"}"#),
        "install: an unknown id",
    )
    .await;
    let signature = b64(&fixture, "signatures", "alpha_binary");
    let two = entry(ALPHA, "MMRS Market Alpha", "1.2.0", &alpha_url, &signature);
    for (response, case) in [
        (
            (
                200,
                alpha_entry(
                    "1.2.0",
                    &alpha_url,
                    &b64(&fixture, "signatures", "alpha_stranger"),
                ),
            ),
            "install: a stranger's signature",
        ),
        (
            (200, alpha_entry("1.2.0", &alpha_url, "")),
            "install: no signature",
        ),
        (
            (200, alpha_entry("1.2.0", &alpha_url, "!!not base64")),
            "install: an undecodable signature",
        ),
        (
            (
                200,
                alpha_entry(
                    "1.2.0",
                    &alpha_url,
                    &b64(&fixture, "signatures", "beta_binary"),
                ),
            ),
            "install: the other bundle's signature",
        ),
        (
            (200, alpha_entry("v1.2.0", &alpha_url, &signature)),
            "install: an invalid version",
        ),
        (
            (
                200,
                alpha_entry("1.2.0", &format!("{market}/bundles/missing"), &signature),
            ),
            "install: a download that fails",
        ),
        (
            (
                200,
                alpha_entry("1.2.0", "ftp://example.invalid/x", &signature),
            ),
            "install: a download URL that is not http",
        ),
        ((500, "oops".to_owned()), "install: the Marketplace fails"),
        (
            (200, "{}".to_owned()),
            "install: the Marketplace answers an object",
        ),
        (
            (
                200,
                serde_json::json!([two.clone(), two.clone()]).to_string(),
            ),
            "install: two entries",
        ),
    ] {
        set_alpha(response);
        both(
            &client,
            &mock,
            rust,
            Method::POST,
            &admin,
            MARKETPLACE,
            Some(body.as_bytes()),
            case,
        )
        .await;
    }

    // --- the installs ---
    set_alpha((
        200,
        alpha_entry(
            "1.2.0",
            &alpha_url,
            &b64(&fixture, "signatures", "alpha_armored"),
        ),
    ));
    let installed = both(
        &client,
        &mock,
        rust,
        Method::POST,
        &admin,
        MARKETPLACE,
        Some(body.as_bytes()),
        "install: alpha",
    )
    .await;
    assert_eq!(
        installed.status,
        201,
        "{}",
        String::from_utf8_lossy(&installed.body)
    );
    assert!(
        std::path::Path::new(&data)
            .join("plugins/mmrs.market.alpha.tar.gz.sig")
            .exists(),
        "the signature was kept in the file store"
    );

    // --- POST /plugins/install_from_url ---
    let beta_url = format!("{market}/bundles/beta");
    both_from_url(
        &client,
        rust,
        &user.token,
        &beta_url,
        &beta_url,
        "true",
        "from url: a plain user",
    )
    .await;
    delete_plain_user(&client, &admin, &user.id).await;
    both_from_url(
        &client,
        rust,
        &admin,
        "not a url",
        "not a url",
        "true",
        "from url: not a URL",
    )
    .await;
    both_from_url(&client, rust, &admin, "", "", "true", "from url: no URL").await;
    let missing = format!("{market}/bundles/missing");
    both_from_url(
        &client,
        rust,
        &admin,
        &missing,
        &missing,
        "true",
        "from url: a 404",
    )
    .await;
    let beta = both_from_url(
        &client,
        rust,
        &admin,
        &beta_url,
        &beta_url,
        "true",
        "from url: beta",
    )
    .await;
    assert_eq!(beta.status, 201, "{}", String::from_utf8_lossy(&beta.body));
    both_from_url(
        &client,
        rust,
        &admin,
        &beta_url,
        &beta_url,
        "nope",
        "from url: again, force unparseable",
    )
    .await;
    both_from_url(
        &client,
        rust,
        &admin,
        &format!("{market}/flaky/go/beta"),
        &format!("{market}/flaky/rust/beta"),
        "1",
        "from url: two failures, then the bundle",
    )
    .await;

    // --- GET /plugins/marketplace ---
    let list = serde_json::json!([
        entry(ALPHA, "MMRS Market Alpha", "1.2.0", &alpha_url, &signature),
        entry("mmrs.market.zeta", "MMRS Market Zeta", "2.0.0", "", ""),
        entry("mmrs.market.eta", "mmrs market eta", "0.0.1", "", ""),
        {
            "manifest": {"id": "mmrs.market.gamma", "name": "Gamma", "description": "a needle", "version": "3.0.0"},
            "labels": [{"name": "Beta", "description": "d", "url": "https://example.invalid", "color": "#fff"}],
        },
        {"homepage_url": "https://example.invalid/no-manifest"},
    ]);
    mock.lock().unwrap().list = (200, list.to_string());
    let user = create_plain_user(&client, &admin, &team, "mktlist").await;
    for (token, query, case) in [
        (&user.token, "", "list: a plain user"),
        (
            &user.token,
            "?remote_only=true",
            "list: remote only, a plain user",
        ),
        (
            &user.token,
            "?page=x",
            "list: a bad page, before the permission",
        ),
        (&admin, "?per_page=1.5", "list: a bad per_page"),
        (
            &admin,
            "?local_only=1&remote_only=t",
            "list: local and remote only",
        ),
        (&admin, "?filter=mmrs%20market", "list: ours"),
        (
            &admin,
            "?filter=%20MMRS%20MARKET%20&page=3&per_page=1&server_version=1.0.0",
            "list: ours, paging ignored",
        ),
        (&admin, "?filter=needle", "list: a description match"),
        (&admin, "?filter=mmrs.market.ZETA", "list: an exact id"),
        (
            &admin,
            "?filter=mmrs.market",
            "list: an id prefix is not a match",
        ),
        (&admin, "?filter=zzz-nothing", "list: nothing"),
        (
            &admin,
            "?local_only=true&filter=mmrs%20market",
            "list: local only",
        ),
    ] {
        both(
            &client,
            &mock,
            rust,
            Method::GET,
            token,
            &format!("{MARKETPLACE}{query}"),
            None,
            case,
        )
        .await;
    }
    delete_plain_user(&client, &admin, &user.id).await;
    for (response, case) in [
        ((500, "oops".to_owned()), "list: the Marketplace fails"),
        (
            (200, "{}".to_owned()),
            "list: the Marketplace answers an object",
        ),
        (
            (200, String::new()),
            "list: the Marketplace answers nothing",
        ),
        (
            (200, "null".to_owned()),
            "list: the Marketplace answers null",
        ),
    ] {
        mock.lock().unwrap().list = response;
        both(
            &client,
            &mock,
            rust,
            Method::GET,
            &admin,
            &format!("{MARKETPLACE}?filter=mmrs%20market"),
            None,
            case,
        )
        .await;
    }
}

/// The settings a Go oracle cannot be switched between: each is a Rust host of its own, and
/// Go's answer is transcribed from plugin.go and app/plugin.go — except where the main Go server
/// already has the setting, which is compared.
#[tokio::test]
async fn the_gates_follow_go_on_hosts_configured_otherwise() {
    if !stack_enabled() {
        return;
    }
    let client = client();
    let fixture = fixture();
    let admin = go_minted_token(&client).await;
    let (mock, market) = start_mock(0).await;
    mock.lock()
        .unwrap()
        .bundles
        .insert("beta".into(), raw(&fixture, "bundles", "beta"));
    mock.lock().unwrap().list = (200, "[]".to_owned());
    let error_id = |a: &Answer| -> (u16, String) {
        let v: serde_json::Value = serde_json::from_slice(&a.body).unwrap_or_default();
        (a.status, v["id"].as_str().unwrap_or_default().to_owned())
    };
    let beta_url = format!("{market}/bundles/beta");
    let from_url = format!(
        "/api/v4/plugins/install_from_url?plugin_download_url={}",
        form_urlencoded::byte_serialize(beta_url.as_bytes()).collect::<String>()
    );
    let install = format!(r#"{{"id":"{ALPHA}"}}"#);
    use reqwest::Method;

    // The remote Marketplace off: never asked; a local plugin carries no label. The host starts
    // with beta in its file store, which the start-up sync installs.
    let (_root, [plugins, client_dir, data]) = scratch("marketplace-remote-off");
    std::fs::create_dir_all(format!("{data}plugins")).unwrap();
    std::fs::write(
        format!("{data}plugins/mmrs.market.beta.tar.gz"),
        raw(&fixture, "bundles", "beta"),
    )
    .unwrap();
    if let Some(host) = SecondServer::start(
        REMOTE_OFF_PORT,
        &[
            ("MMRS_PLUGIN_HOST", "rust"),
            ("MM_PLUGINSETTINGS_ENABLEREMOTEMARKETPLACE", "false"),
            ("MM_PLUGINSETTINGS_ENABLEUPLOADS", "true"),
            ("MM_PLUGINSETTINGS_MARKETPLACEURL", market.as_str()),
            ("MM_PLUGINSETTINGS_DIRECTORY", plugins.as_str()),
            ("MM_PLUGINSETTINGS_CLIENTDIRECTORY", client_dir.as_str()),
            ("MM_FILESETTINGS_DIRECTORY", data.as_str()),
        ],
    )
    .await
    {
        take_requests(&mock);
        let listed = send(&client, Method::GET, &host.base, &admin, MARKETPLACE, None).await;
        assert_eq!(listed.status, 200);
        let body: serde_json::Value = serde_json::from_slice(&listed.body).unwrap();
        let beta = body
            .as_array()
            .and_then(|a| a.iter().find(|p| p["manifest"]["id"] == "mmrs.market.beta"))
            .expect("the installed plugin is listed");
        assert!(beta.get("labels").is_none(), "no Local label: {beta}");
        assert_eq!(beta["installed_version"], "0.4.0");
        let remote_only = send(
            &client,
            Method::GET,
            &host.base,
            &admin,
            &format!("{MARKETPLACE}?remote_only=true"),
            None,
        )
        .await;
        assert_eq!(
            String::from_utf8_lossy(&remote_only.body),
            "null",
            "nothing remote, nothing local"
        );
        let installed = send(
            &client,
            Method::POST,
            &host.base,
            &admin,
            MARKETPLACE,
            Some(install.as_bytes()),
        )
        .await;
        assert_eq!(
            error_id(&installed),
            (
                500,
                "app.plugin.marketplace_plugins.not_found.app_error".to_owned()
            )
        );
        assert!(
            take_requests(&mock).is_empty(),
            "the Marketplace was not asked"
        );
        // `AllowInsecureDownloadURL` is off here: an http URL is refused before any request.
        let refused = send(&client, Method::POST, &host.base, &admin, &from_url, None).await;
        assert_eq!(
            error_id(&refused),
            (
                400,
                "api.plugin.install.download_failed.app_error".to_owned()
            )
        );
        assert!(
            take_requests(&mock).is_empty(),
            "the insecure URL was not fetched"
        );
    }

    // The Marketplace off: both marketplace routes 501, after plugins-on. A signature requirement
    // refuses `install_from_url` with the plugins-off 501 although uploads are on.
    let (_root, [plugins, client_dir, data]) = scratch("marketplace-off");
    if let Some(host) = SecondServer::start(
        MARKETPLACE_OFF_PORT,
        &[
            ("MMRS_PLUGIN_HOST", "rust"),
            ("MM_PLUGINSETTINGS_ENABLEMARKETPLACE", "false"),
            ("MM_PLUGINSETTINGS_ENABLEUPLOADS", "true"),
            ("MM_PLUGINSETTINGS_REQUIREPLUGINSIGNATURE", "true"),
            ("MM_PLUGINSETTINGS_DIRECTORY", plugins.as_str()),
            ("MM_PLUGINSETTINGS_CLIENTDIRECTORY", client_dir.as_str()),
            ("MM_FILESETTINGS_DIRECTORY", data.as_str()),
        ],
    )
    .await
    {
        for method in [Method::GET, Method::POST] {
            let answer = send(
                &client,
                method,
                &host.base,
                &admin,
                MARKETPLACE,
                Some(install.as_bytes()),
            )
            .await;
            assert_eq!(
                error_id(&answer),
                (501, "app.plugin.marketplace_disabled.app_error".to_owned())
            );
        }
        let refused = send(&client, Method::POST, &host.base, &admin, &from_url, None).await;
        assert_eq!(
            error_id(&refused),
            (501, "app.plugin.disabled.app_error".to_owned())
        );
    }

    // Plugins off: every route here is the 501, ahead of the Marketplace switch.
    let (_root, [plugins, client_dir, data]) = scratch("marketplace-plugins-off");
    if let Some(host) = SecondServer::start(
        PLUGINS_OFF_PORT,
        &[
            ("MMRS_PLUGIN_HOST", "rust"),
            ("MM_PLUGINSETTINGS_ENABLE", "false"),
            ("MM_PLUGINSETTINGS_ENABLEMARKETPLACE", "false"),
            ("MM_PLUGINSETTINGS_ENABLEUPLOADS", "true"),
            ("MM_PLUGINSETTINGS_DIRECTORY", plugins.as_str()),
            ("MM_PLUGINSETTINGS_CLIENTDIRECTORY", client_dir.as_str()),
            ("MM_FILESETTINGS_DIRECTORY", data.as_str()),
        ],
    )
    .await
    {
        for (method, path) in [
            (Method::GET, MARKETPLACE),
            (Method::POST, MARKETPLACE),
            (Method::POST, from_url.as_str()),
        ] {
            let answer = send(
                &client,
                method,
                &host.base,
                &admin,
                path,
                Some(install.as_bytes()),
            )
            .await;
            assert_eq!(
                error_id(&answer),
                (501, "app.plugin.disabled.app_error".to_owned()),
                "{path}"
            );
        }
    }

    // Uploads off, as on the main Go server, which answers `install_from_url` itself: compared.
    let (_root, [plugins, client_dir, data]) = scratch("marketplace-defaults");
    if let Some(host) = SecondServer::start(
        DEFAULTS_PORT,
        &[
            ("MMRS_PLUGIN_HOST", "rust"),
            ("MM_PLUGINSETTINGS_DIRECTORY", plugins.as_str()),
            ("MM_PLUGINSETTINGS_CLIENTDIRECTORY", client_dir.as_str()),
            ("MM_FILESETTINGS_DIRECTORY", data.as_str()),
        ],
    )
    .await
    {
        let go = send(&client, Method::POST, GO, &admin, &from_url, None).await;
        let rs = send(&client, Method::POST, &host.base, &admin, &from_url, None).await;
        assert_same(&go, &rs, "from url: uploads off");
        assert_eq!(
            error_id(&rs),
            (501, "app.plugin.disabled.app_error".to_owned())
        );
    }
}
