//! Cross-server parity for plugin **start-up** with this server hosting plugins
//! (`MMRS_PLUGIN_HOST=rust`): `initPlugins`' file-store sync with `RequirePluginSignature` on, the
//! prepackaged plugins, and the transitionally prepackaged ones persisted to the file store
//! (channels/app/plugin.go:172-259, 903-1242). Then what they feed: `GET /plugins/marketplace`
//! and a Marketplace install served from a prepackaged bundle.
//!
//! ```sh
//! scripts/parity.sh --test parity plugin_startup
//! ```
//!
//! Start-up happens once per process, so neither the stack's Go server nor the plugins oracle can
//! be the comparison: each would have to be restarted over a prepared file store. This suite starts
//! **its own Go server** (the stack's binary, on Go's port + 73, in a run directory of its own) and
//! a Rust host beside it, both over identical copies of `fixtures/behaviour_plugin_startup.json`:
//! bundles in the file store's `plugins/` and in a `prepackaged_plugins` directory next to each
//! server. Both read the shared configuration, into which the suite plants `PluginStates` for two
//! transitionally prepackaged ids (`jitsi`, `jenkins`) and from which it takes them out again.
//! The ids SetDefaults enables (`playbooks`, `com.mattermost.calls`, `mattermost-ai`) are used for
//! the install branches, so the document gains nothing else.
//!
//! Compared: the statuses, `GET /plugins`, `GET /plugins/webapp`, the Marketplace list, the files
//! in each file store, and the manifests in each plugin directory — before and after installing a
//! prepackaged plugin through `POST /plugins/marketplace`. Every bundle is webapp-only, so the
//! two hosts launch nothing (docs/PLUGIN_PLAN.md, D6).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::Duration;

use base64::Engine;

use crate::common;

use common::{GO, SecondServer, client, go_minted_token, request_raw, stack_enabled};

/// The Rust host; see `second_server_ports`.
const HOST_PORT: u16 = 8118;
/// This suite's Go server sits at Go's port plus this.
const GO_OFFSET: u16 = 73;
/// The two transitionally prepackaged ids the suite enables.
const PLANTED: [&str; 2] = ["jitsi", "jenkins"];

fn fixture() -> serde_json::Value {
    serde_json::from_str(include_str!(
        "../../../../fixtures/behaviour_plugin_startup.json"
    ))
    .expect("generated by reference/dump")
}

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// A run directory: `data/plugins` holds the file store's bundles, `prepackaged_plugins` the
/// prepackaged ones, and `plugins` and `client` the two plugin directories.
fn lay_out(run: &Path) {
    let _ = std::fs::remove_dir_all(run);
    for dir in ["data/plugins", "plugins", "client", "prepackaged_plugins"] {
        std::fs::create_dir_all(run.join(dir)).unwrap();
    }
    // Both servers refuse to start without their translations, and both find them relative to
    // this directory — `start_go` links them for Go; this links them for whoever runs here.
    for dir in ["i18n", "templates", "fonts"] {
        let _ = std::os::unix::fs::symlink(
            repo().join("reference/mattermost/server").join(dir),
            run.join(dir),
        );
    }
    let b64 = base64::engine::general_purpose::STANDARD;
    for bundle in fixture()["bundles"].as_array().expect("bundles") {
        let place = bundle["place"].as_str().unwrap();
        let dir = match place {
            "store" => run.join("data/plugins"),
            other => run.join(other.replacen("prepackaged", "prepackaged_plugins", 1)),
        };
        std::fs::create_dir_all(&dir).unwrap();
        let file = bundle["file"].as_str().unwrap();
        std::fs::write(
            dir.join(file),
            b64.decode(bundle["bundle"].as_str().unwrap()).unwrap(),
        )
        .unwrap();
        if let Some(signature) = bundle["signature"].as_str() {
            std::fs::write(
                dir.join(format!("{file}.sig")),
                b64.decode(signature).unwrap(),
            )
            .unwrap();
        }
    }
}

/// The Go server this suite starts: killed on drop.
struct GoServer {
    child: std::process::Child,
    base: String,
}

impl Drop for GoServer {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

fn go_port() -> u16 {
    GO.rsplit(':')
        .next()
        .and_then(|p| p.parse().ok())
        .expect("GO has a port")
}

/// Start the stack's Go binary in `run`, as `scripts/go-plugins.sh` starts its oracle: the shared
/// database and configuration, its own file store and plugin directories, and `env` on top.
async fn start_go(run: &Path, env: &[(&str, &str)]) -> GoServer {
    let binary = repo().join("reference/.build/mattermost");
    assert!(
        binary.exists(),
        "no Go binary at {} — run scripts/go-server.sh",
        binary.display()
    );
    let src = repo().join("reference/mattermost/server");
    std::fs::create_dir_all(run.join("logs")).unwrap();
    for dir in ["i18n", "templates", "fonts"] {
        let _ = std::os::unix::fs::symlink(src.join(dir), run.join(dir));
    }
    let port = go_port() + GO_OFFSET;
    let _ = std::process::Command::new("sh")
        .arg("-c")
        .arg(format!(
            "ss -ltnp 2>/dev/null | awk '$4 ~ /:{port}$/' \
             | grep -oE 'pid=[0-9]+' | cut -d= -f2 | sort -u | xargs -r kill -9"
        ))
        .status();
    let dsn = format!(
        "{}?sslmode=disable&connect_timeout=10",
        std::env::var("DATABASE_URL").expect("parity.sh sets DATABASE_URL")
    );
    let s = |p: &str| run.join(p).to_string_lossy().into_owned();
    let log = std::fs::File::create(run.join("go.log")).unwrap();
    let mut command = std::process::Command::new(&binary);
    command
        .arg("server")
        .current_dir(run)
        .env("PWD", run)
        .env("MM_CONFIG", &dsn)
        .env("MM_SQLSETTINGS_DRIVERNAME", "postgres")
        .env("MM_SQLSETTINGS_DATASOURCE", &dsn)
        .env(
            "MM_SERVICESETTINGS_SITEURL",
            format!("http://localhost:{port}"),
        )
        .env("MM_SERVICESETTINGS_LISTENADDRESS", format!(":{port}"))
        .env("MM_SERVICESETTINGS_ENABLELOCALMODE", "false")
        // **Two connections, not fifty.** Postgres allows 100 and the stack's servers already hold
        // ~80 idle, so a server with Go's default `MaxIdleConns` (50) takes the database down for
        // every suite running beside this one: measured 2026-09-20 as 55 parity failures, among
        // them pools that could not be created at all ("the stack database") and a Go server that
        // could not save its configuration.
        .env("MM_SQLSETTINGS_MAXIDLECONNS", "2")
        .env("MM_SQLSETTINGS_MAXOPENCONNS", "5")
        // Nothing here needs a job runner, and one more scheduler on the shared database is one
        // more thing that can write while another suite is measuring.
        .env("MM_JOBSETTINGS_RUNJOBS", "false")
        .env("MM_JOBSETTINGS_RUNSCHEDULER", "false")
        .env("MM_FILESETTINGS_DIRECTORY", format!("{}/", s("data")))
        .env("MM_PLUGINSETTINGS_DIRECTORY", s("plugins"))
        .env("MM_PLUGINSETTINGS_CLIENTDIRECTORY", s("client"))
        .stdout(log.try_clone().unwrap())
        .stderr(log);
    for (key, value) in env {
        command.env(key, value);
    }
    let child = command.spawn().expect("the Go server starts");
    let mut server = GoServer {
        child,
        base: format!("http://127.0.0.1:{port}"),
    };
    let client = client();
    for _ in 0..450 {
        assert!(
            server.child.try_wait().ok().flatten().is_none(),
            "the Go server exited — see {}",
            run.join("go.log").display()
        );
        if client
            .get(format!("{}/api/v4/system/ping", server.base))
            .send()
            .await
            .is_ok_and(|r| r.status().is_success())
        {
            return server;
        }
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
    panic!(
        "the Go server never answered — see {}",
        run.join("go.log").display()
    );
}

/// Set (or, with `None`, remove) the planted states in the shared `PluginStates`, through main
/// Go: a patch replaces the map, so it is sent whole.
async fn plant_states(client: &reqwest::Client, admin: &str, enable: Option<bool>) {
    let config: serde_json::Value = client
        .get(format!("{GO}/api/v4/config"))
        .bearer_auth(admin)
        .send()
        .await
        .expect("Go answers")
        .json()
        .await
        .expect("the configuration");
    let mut states = config["PluginSettings"]["PluginStates"].clone();
    if let Some(map) = states.as_object_mut() {
        for id in PLANTED {
            match enable {
                Some(on) => {
                    map.insert(id.to_owned(), serde_json::json!({ "Enable": on }));
                }
                None => {
                    map.remove(id);
                }
            }
        }
    }
    let status = client
        .put(format!("{GO}/api/v4/config/patch"))
        .bearer_auth(admin)
        .json(&serde_json::json!({ "PluginSettings": { "PluginStates": states } }))
        .send()
        .await
        .expect("Go answers")
        .status();
    assert!(status.is_success(), "patching PluginStates: {status}");
}

/// Statuses with each `plugin_path` cut to its last component, the part two plugin directories
/// share.
fn comparable_statuses(body: &[u8]) -> serde_json::Value {
    let mut value: serde_json::Value = serde_json::from_slice(body).expect("statuses decode");
    for status in value.as_array_mut().expect("an array").iter_mut() {
        let path = status["plugin_path"]
            .as_str()
            .unwrap_or_default()
            .to_owned();
        status["plugin_path"] = serde_json::json!(path.rsplit('/').next().unwrap_or_default());
    }
    value
}

/// A server's statuses once start-up is over: the last plugins it activates are running.
async fn settled(client: &reqwest::Client, admin: &str, base: &str) -> serde_json::Value {
    let mut last = serde_json::Value::Null;
    for _ in 0..150 {
        let (status, body, _) = request_raw(
            client,
            base,
            reqwest::Method::GET,
            Some(admin),
            "/api/v4/plugins/statuses",
            None,
        )
        .await;
        if status == 200 {
            let value = comparable_statuses(&body);
            let running = |id: &str| {
                value
                    .as_array()
                    .is_some_and(|all| all.iter().any(|s| s["plugin_id"] == id && s["state"] == 2))
            };
            if running("playbooks") && running("jitsi") {
                return value;
            }
            last = value;
        }
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
    panic!("{base}: start-up never settled: {last}");
}

/// Every file under `dir`, relative, with a digest of its bytes.
fn files(dir: &Path) -> BTreeMap<String, String> {
    use sha2::Digest as _;
    let mut out = BTreeMap::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in std::fs::read_dir(&d).into_iter().flatten().flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else {
                let digest = sha2::Sha256::digest(std::fs::read(&path).unwrap_or_default());
                let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
                out.insert(
                    path.strip_prefix(dir)
                        .unwrap()
                        .to_string_lossy()
                        .into_owned(),
                    hex,
                );
            }
        }
    }
    out
}

/// The installed plugins: each plugin directory's manifest.
fn installed(plugins: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for entry in std::fs::read_dir(plugins).into_iter().flatten().flatten() {
        let manifest =
            std::fs::read_to_string(entry.path().join("plugin.json")).unwrap_or_default();
        out.insert(entry.file_name().to_string_lossy().into_owned(), manifest);
    }
    out
}

/// One read from both servers: equal statuses and equal bodies. `sort` sorts a JSON array body
/// by `id` first, for Go's `sync.Map`-ordered webapp list.
async fn same_read(
    client: &reqwest::Client,
    admin: &str,
    go: &str,
    rust: &str,
    path: &str,
    sort: bool,
    when: &str,
) {
    let (go_status, go_body, _) =
        request_raw(client, go, reqwest::Method::GET, Some(admin), path, None).await;
    let (rs_status, rs_body, served_by) =
        request_raw(client, rust, reqwest::Method::GET, Some(admin), path, None).await;
    assert_eq!(served_by.as_deref(), Some("rust"), "{path} {when}");
    assert_eq!(
        (go_status, rs_status),
        (200, 200),
        "{path} {when}: Go {} / Rust {}",
        String::from_utf8_lossy(&go_body),
        String::from_utf8_lossy(&rs_body)
    );
    if sort {
        let ordered = |body: &[u8]| {
            let mut v: Vec<serde_json::Value> = serde_json::from_slice(body).expect("an array");
            v.sort_by(|a, b| a["id"].as_str().cmp(&b["id"].as_str()));
            v
        };
        assert_eq!(ordered(&go_body), ordered(&rs_body), "{path} {when}");
    } else {
        assert_eq!(
            String::from_utf8_lossy(&go_body),
            String::from_utf8_lossy(&rs_body),
            "{path} {when}"
        );
    }
}

async fn compare(
    client: &reqwest::Client,
    admin: &str,
    go: &GoServer,
    rust: &SecondServer,
    go_run: &Path,
    rs_run: &Path,
    when: &str,
) {
    let go_statuses = settled(client, admin, &go.base).await;
    let rs_statuses = settled(client, admin, &rust.base).await;
    assert_eq!(go_statuses, rs_statuses, "statuses {when}");
    for (path, sort) in [
        ("/api/v4/plugins", false),
        ("/api/v4/plugins/webapp", true),
        ("/api/v4/plugins/marketplace", false),
    ] {
        same_read(client, admin, &go.base, &rust.base, path, sort, when).await;
    }
    assert_eq!(
        files(&go_run.join("data/plugins")),
        files(&rs_run.join("data/plugins")),
        "the file store {when}"
    );
    assert_eq!(
        installed(&go_run.join("plugins")),
        installed(&rs_run.join("plugins")),
        "the plugin directory {when}"
    );
}

#[tokio::test]
async fn start_up_matches_go() {
    if !stack_enabled() {
        return;
    }
    let _states = common::PLUGIN_STATES.lock().await;
    let client = client();
    let admin = go_minted_token(&client).await;
    super::marketplace::plant_key(&super::marketplace::fixture()).await;
    plant_states(&client, &admin, Some(true)).await;

    let scratch = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("plugin-startup");
    let (go_run, rs_run) = (scratch.join("go"), scratch.join("rust"));
    lay_out(&go_run);
    lay_out(&rs_run);
    let settings = [
        ("MM_PLUGINSETTINGS_REQUIREPLUGINSIGNATURE", "true"),
        (
            "MM_PLUGINSETTINGS_SIGNATUREPUBLICKEYFILES",
            "mmrs-marketplace-test.plugin.asc",
        ),
        // The Marketplace list and install without a Marketplace server: prepackaged and local.
        ("MM_PLUGINSETTINGS_ENABLEREMOTEMARKETPLACE", "false"),
    ];
    let go = start_go(&go_run, &settings).await;

    let s = |p: &str| rs_run.join(p).to_string_lossy().into_owned();
    let (dir, client_dir, data) = (s("plugins"), s("client"), format!("{}/", s("data")));
    let mut env = vec![
        ("MMRS_PLUGIN_HOST", "rust"),
        ("MM_PLUGINSETTINGS_DIRECTORY", dir.as_str()),
        ("MM_PLUGINSETTINGS_CLIENTDIRECTORY", client_dir.as_str()),
        ("MM_FILESETTINGS_DIRECTORY", data.as_str()),
    ];
    env.extend(settings);
    let rust = SecondServer::start_in(HOST_PORT, &rs_run, &env)
        .await
        .expect("the Rust host starts");

    compare(
        &client,
        &admin,
        &go,
        &rust,
        &go_run,
        &rs_run,
        "after start-up",
    )
    .await;

    // What start-up should have done, stated once so a reader need not derive it from the
    // fixture, and so both servers agreeing on nothing cannot pass.
    let store = files(&rs_run.join("data/plugins"));
    assert!(
        store.contains_key("jitsi.tar.gz") && store.contains_key("jitsi.tar.gz.sig"),
        "jitsi persisted: {store:?}"
    );
    let plugins = installed(&rs_run.join("plugins"));
    let ids: Vec<&str> = plugins.keys().map(String::as_str).collect();
    assert_eq!(
        ids,
        [
            "com.mattermost.calls",
            "jenkins",
            "jitsi",
            "mattermost-ai",
            "mmrs.startup.armored",
            "mmrs.startup.signed",
            "playbooks"
        ],
        "signed store bundles and enabled prepackaged ones"
    );
    assert!(
        plugins["com.mattermost.calls"].contains("2.0.0"),
        "upgraded from prepackaged"
    );
    assert!(plugins["mattermost-ai"].contains("2.0.0"), "not downgraded");

    // The Marketplace list offers the prepackaged plugins that verified, icon included, and none
    // of the transitional ones (an installed one is listed as local, like any installed plugin).
    let (_, listed, _) = request_raw(
        &client,
        &rust.base,
        reqwest::Method::GET,
        Some(&admin),
        "/api/v4/plugins/marketplace",
        None,
    )
    .await;
    let listed: Vec<serde_json::Value> = serde_json::from_slice(&listed).expect("a list");
    let entry = |id: &str| listed.iter().find(|p| p["manifest"]["id"] == id);
    assert!(
        entry("mmrs.startup.offered").is_some_and(|p| p["icon_data"]
            .as_str()
            .is_some_and(|i| i.starts_with("data:image/svg+xml;base64,"))),
        "{listed:?}"
    );
    assert!(
        entry("mmrs.startup.nested").is_some(),
        "found in a subdirectory"
    );
    for absent in [
        "mmrs.startup.preunsigned",
        "mmrs.startup.prestranger",
        "mattermost-autolink",
    ] {
        assert!(entry(absent).is_none(), "{absent} is not offered");
    }

    // A Marketplace install of a prepackaged plugin: from its bundle, signature and all.
    let body = br#"{"id":"mmrs.startup.offered","version":"0.5.0"}"#;
    let (go_status, go_body, _) = request_raw(
        &client,
        &go.base,
        reqwest::Method::POST,
        Some(&admin),
        "/api/v4/plugins/marketplace",
        Some(body),
    )
    .await;
    let (rs_status, rs_body, served_by) = request_raw(
        &client,
        &rust.base,
        reqwest::Method::POST,
        Some(&admin),
        "/api/v4/plugins/marketplace",
        Some(body),
    )
    .await;
    assert_eq!(served_by.as_deref(), Some("rust"));
    assert_eq!(
        (go_status, rs_status),
        (201, 201),
        "Go {} / Rust {}",
        String::from_utf8_lossy(&go_body),
        String::from_utf8_lossy(&rs_body)
    );
    assert_eq!(
        String::from_utf8_lossy(&go_body),
        String::from_utf8_lossy(&rs_body),
        "the installed manifest"
    );
    // One the environment does not offer: refused alike.
    for id in ["mmrs.startup.preunsigned", "jitsi"] {
        let body = format!(r#"{{"id":"{id}"}}"#);
        let (go_status, go_err, _) = request_raw(
            &client,
            &go.base,
            reqwest::Method::POST,
            Some(&admin),
            "/api/v4/plugins/marketplace",
            Some(body.as_bytes()),
        )
        .await;
        let (rs_status, rs_err, _) = request_raw(
            &client,
            &rust.base,
            reqwest::Method::POST,
            Some(&admin),
            "/api/v4/plugins/marketplace",
            Some(body.as_bytes()),
        )
        .await;
        assert_eq!((go_status, rs_status), (500, 500), "installing {id}");
        common::assert_error_bodies_match_except_known_gaps(&go_err, &rs_err, id);
    }
    compare(
        &client,
        &admin,
        &go,
        &rust,
        &go_run,
        &rs_run,
        "after the install",
    )
    .await;
    assert!(
        files(&rs_run.join("data/plugins")).contains_key("mmrs.startup.offered.tar.gz.sig"),
        "the install kept the prepackaged signature"
    );

    drop(rust);
    drop(go);
    plant_states(&client, &admin, None).await;
}
