//! The format-detection half of Go's `image.DecodeConfig`.
//!
//! `GetEmojiImage` (app/emoji.go:286) calls `image.DecodeConfig` for one thing: the **format
//! name**, which becomes `Content-Type: image/<name>` on `GET /emoji/{emoji_id}/image`. Nothing
//! reads the width or the height.
//!
//! # What `image.DecodeConfig` actually does, and where this port stops
//!
//! It walks the decoders registered by `image.RegisterFormat`, matching each one's magic prefix
//! (where `?` is a wildcard byte), and then asks the first match to parse the header. So it can
//! fail in two distinguishable ways, and the corpus in `fixtures/behaviour_filestore.json`
//! (`image_decode_config`) records which is which:
//!
//! - **No magic matched** — `image.ErrFormat`. Reproduced exactly by [`detect_format`].
//! - **A magic matched and the decoder then rejected the bytes** — a format-specific error.
//!   *Not* reproduced: this port stops at the prefix. A stored emoji whose first eight bytes are
//!   a PNG signature and whose body is corrupt gets `image/png` from us and a 500 from Go.
//!
//! That gap is narrow by construction — `CreateEmoji` decodes every image it accepts
//! (app/emoji.go:110), so a row reaching here has already been parsed once by Go — and closing it
//! would mean carrying PNG, JPEG, GIF, BMP, TIFF and WebP header parsers to compute a string we
//! throw away. Recorded as [D-203] rather than hidden.
//!
//! # The registry is the whole binary's, not emoji.go's
//!
//! `RegisterFormat` writes into a package-level list, so the formats available to `GetEmojiImage`
//! are every one any package in the server imports: png, jpeg and gif from the standard library,
//! plus bmp, tiff and webp registered by `channels/app/imaging/decode.go`. Reading only
//! emoji.go's own imports would miss three of the six.

/// One registered decoder: the name `image.DecodeConfig` returns, and its magic prefix.
///
/// `?` in the pattern is a **wildcard byte**, exactly as in `image.RegisterFormat` — it matches
/// any single byte, not a literal question mark.
struct Format {
    name: &'static str,
    magic: &'static [u8],
}

/// The six decoders a Mattermost server has registered, with the magic strings copied from their
/// `RegisterFormat` calls.
///
/// Order does not matter — no two patterns can match the same bytes — but it is Go's registration
/// order (standard library first, then `golang.org/x/image`) so a reader can check them off
/// against the source.
const FORMATS: &[Format] = &[
    // image/png/reader.go:1053 — `pngHeader`.
    Format {
        name: "png",
        magic: b"\x89PNG\r\n\x1a\n",
    },
    // image/jpeg/reader.go:811.
    Format {
        name: "jpeg",
        magic: b"\xff\xd8",
    },
    // image/gif/reader.go:640 — the wildcard is the version digit, so `GIF87a` and `GIF89a` are
    // one pattern rather than two.
    Format {
        name: "gif",
        magic: b"GIF8?a",
    },
    // golang.org/x/image/bmp/reader.go:278. The four zero bytes at offset 6 are the reserved
    // fields of the BMP file header, and they are why a bare `BM` is not enough: the oracle case
    // `bmp_magic_only` is six bytes long and Go answers `ErrFormat` for it.
    Format {
        name: "bmp",
        magic: b"BM????\x00\x00\x00\x00",
    },
    // golang.org/x/image/tiff/reader.go:908 — `leHeader`.
    Format {
        name: "tiff",
        magic: b"II\x2a\x00",
    },
    // golang.org/x/image/tiff/reader.go:909 — `beHeader`.
    Format {
        name: "tiff",
        magic: b"MM\x00\x2a",
    },
    // golang.org/x/image/webp/decode.go:319. Fifteen bytes, not sixteen: the pattern stops before
    // the codec byte, so `VP8 `, `VP8L` and `VP8X` all match.
    Format {
        name: "webp",
        magic: b"RIFF????WEBPVP8",
    },
];

/// Port of `image.match` (image/format.go:36) — a magic prefix where `?` matches any byte.
fn matches(magic: &[u8], data: &[u8]) -> bool {
    if data.len() < magic.len() {
        return false;
    }
    magic
        .iter()
        .zip(data)
        .all(|(pattern, byte)| *pattern == b'?' || pattern == byte)
}

/// The format name `image.DecodeConfig` would report, or `None` where it would return
/// `image.ErrFormat`.
///
/// See the module docs for the case this cannot reproduce: a matching magic over a corrupt body.
pub fn detect_format(data: &[u8]) -> Option<&'static str> {
    FORMATS
        .iter()
        .find(|format| matches(format.magic, data))
        .map(|format| format.name)
}

#[cfg(test)]
mod go_parity {
    use super::detect_format;

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!("../../../fixtures/behaviour_filestore.json"))
            .expect("behaviour_filestore.json is generated by reference/dump")
    }

    /// Asserted against `image.DecodeConfig` itself, over real 1×1 encodings and over magic
    /// prefixes with nothing behind them.
    ///
    /// The three-way comparison is what makes this meaningful:
    ///
    /// - Go decoded it → we must name the same format.
    /// - Go failed with `ErrFormat` (no magic matched) → we must answer `None`.
    /// - Go failed *without* `ErrFormat` (a magic matched, the body did not parse) → we must
    ///   answer `Some`, because the prefix did match. This is the documented gap, and asserting
    ///   it this way turns it from an unstated divergence into a pinned one: if the port ever
    ///   stopped recognising a prefix Go recognises, this fails.
    #[test]
    fn format_detection_matches_go() {
        use base64::Engine;

        let oracle = oracle();
        let cases = oracle["image_decode_config"].as_array().unwrap();
        assert!(cases.len() >= 15, "corpus should cover all six decoders");

        for case in cases {
            let name = case["name"].as_str().unwrap();
            let bytes = base64::engine::general_purpose::STANDARD
                .decode(case["bytes_base64"].as_str().unwrap())
                .unwrap();
            let got = detect_format(&bytes);

            if case["ok"].as_bool().unwrap() {
                assert_eq!(got, Some(case["format"].as_str().unwrap()), "{name}");
            } else if case["err_is_format"].as_bool().unwrap() {
                assert_eq!(got, None, "{name}: Go found no registered magic");
            } else {
                assert!(
                    got.is_some(),
                    "{name}: Go matched a magic and then failed to decode, so the prefix is real"
                );
            }
        }
    }

    /// `?` is a wildcard, not a literal — a GIF whose version digit is `?` is not special, and a
    /// pattern shorter than the data still matches on its prefix.
    #[test]
    fn the_wildcard_byte_matches_anything() {
        assert_eq!(detect_format(b"GIF87a\x01\x00"), Some("gif"));
        assert_eq!(detect_format(b"GIF89a\x01\x00"), Some("gif"));
        assert_eq!(detect_format(b"GIF8Xa"), Some("gif"));
        assert_eq!(detect_format(b"GIF8a"), None, "one byte short");
    }

    /// The three WebP codec variants share one pattern because it stops before the codec byte.
    #[test]
    fn every_webp_codec_matches_the_one_pattern() {
        for codec in [b"VP8 ", b"VP8L", b"VP8X"] {
            let mut data = b"RIFF\x00\x00\x00\x00WEBP".to_vec();
            data.extend_from_slice(codec);
            assert_eq!(detect_format(&data), Some("webp"));
        }
    }
}
