//! The format-detection half of Go's `image.DecodeConfig`.
//!
//! `GetEmojiImage` (app/emoji.go:286) calls `image.DecodeConfig` for one thing: the **format
//! name**, which becomes `Content-Type: image/<name>` on `GET /emoji/{emoji_id}/image`. Nothing
//! reads the width or the height.
//!
//! # What `image.DecodeConfig` actually does, and where this port stops
//!
//! It walks the decoders registered by `image.RegisterFormat`, matching each one's magic prefix
//! (where `?` is a wildcard byte), and then asks the first match to parse the header. So it can
//! fail in two distinguishable ways, and the corpus in `fixtures/behaviour_filestore.json`
//! (`image_decode_config`) records which is which:
//!
//! - **No magic matched** — `image.ErrFormat`. Reproduced exactly by [`detect_format`].
//! - **A magic matched and the decoder then rejected the bytes** — a format-specific error.
//!   *Not* reproduced: this port stops at the prefix. A stored emoji whose first eight bytes are
//!   a PNG signature and whose body is corrupt gets `image/png` from us and a 500 from Go.
//!
//! That gap is narrow by construction — `CreateEmoji` decodes every image it accepts
//! (app/emoji.go:110), so a row reaching here has already been parsed once by Go — and closing it
//! would mean carrying PNG, JPEG, GIF, BMP, TIFF and WebP header parsers to compute a string we
//! throw away. Recorded as [D-203] rather than hidden.
//!
//! # The registry is the whole binary's, not emoji.go's
//!
//! `RegisterFormat` writes into a package-level list, so the formats available to `GetEmojiImage`
//! are every one any package in the server imports: png, jpeg and gif from the standard library,
//! plus bmp, tiff and webp registered by `channels/app/imaging/decode.go`. Reading only
//! emoji.go's own imports would miss three of the six.

/// One registered decoder: the name `image.DecodeConfig` returns, and its magic prefix.
///
/// `?` in the pattern is a **wildcard byte**, exactly as in `image.RegisterFormat` — it matches
/// any single byte, not a literal question mark.
struct Format {
    name: &'static str,
    magic: &'static [u8],
}

/// The six decoders a Mattermost server has registered, with the magic strings copied from their
/// `RegisterFormat` calls.
///
/// Order does not matter — no two patterns can match the same bytes — but it is Go's registration
/// order (standard library first, then `golang.org/x/image`) so a reader can check them off
/// against the source.
const FORMATS: &[Format] = &[
    // image/png/reader.go:1053 — `pngHeader`.
    Format {
        name: "png",
        magic: b"\x89PNG\r\n\x1a\n",
    },
    // image/jpeg/reader.go:811.
    Format {
        name: "jpeg",
        magic: b"\xff\xd8",
    },
    // image/gif/reader.go:640 — the wildcard is the version digit, so `GIF87a` and `GIF89a` are
    // one pattern rather than two.
    Format {
        name: "gif",
        magic: b"GIF8?a",
    },
    // golang.org/x/image/bmp/reader.go:278. The four zero bytes at offset 6 are the reserved
    // fields of the BMP file header, and they are why a bare `BM` is not enough: the oracle case
    // `bmp_magic_only` is six bytes long and Go answers `ErrFormat` for it.
    Format {
        name: "bmp",
        magic: b"BM????\x00\x00\x00\x00",
    },
    // golang.org/x/image/tiff/reader.go:908 — `leHeader`.
    Format {
        name: "tiff",
        magic: b"II\x2a\x00",
    },
    // golang.org/x/image/tiff/reader.go:909 — `beHeader`.
    Format {
        name: "tiff",
        magic: b"MM\x00\x2a",
    },
    // golang.org/x/image/webp/decode.go:319. Fifteen bytes, not sixteen: the pattern stops before
    // the codec byte, so `VP8 `, `VP8L` and `VP8X` all match.
    Format {
        name: "webp",
        magic: b"RIFF????WEBPVP8",
    },
];

/// Port of `image.match` (image/format.go:36) — a magic prefix where `?` matches any byte.
fn matches(magic: &[u8], data: &[u8]) -> bool {
    if data.len() < magic.len() {
        return false;
    }
    magic
        .iter()
        .zip(data)
        .all(|(pattern, byte)| *pattern == b'?' || pattern == byte)
}

/// The format name `image.DecodeConfig` would report, or `None` where it would return
/// `image.ErrFormat`.
///
/// See the module docs for the case this cannot reproduce: a matching magic over a corrupt body.
pub fn detect_format(data: &[u8]) -> Option<&'static str> {
    FORMATS
        .iter()
        .find(|format| matches(format.magic, data))
        .map(|format| format.name)
}

#[cfg(test)]
mod go_parity {
    use super::detect_format;

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!("../../../fixtures/behaviour_filestore.json"))
            .expect("behaviour_filestore.json is generated by reference/dump")
    }

    /// Asserted against `image.DecodeConfig` itself, over real 1×1 encodings and over magic
    /// prefixes with nothing behind them.
    ///
    /// The three-way comparison is what makes this meaningful:
    ///
    /// - Go decoded it → we must name the same format.
    /// - Go failed with `ErrFormat` (no magic matched) → we must answer `None`.
    /// - Go failed *without* `ErrFormat` (a magic matched, the body did not parse) → we must
    ///   answer `Some`, because the prefix did match. This is the documented gap, and asserting
    ///   it this way turns it from an unstated divergence into a pinned one: if the port ever
    ///   stopped recognising a prefix Go recognises, this fails.
    #[test]
    fn format_detection_matches_go() {
        use base64::Engine;

        let oracle = oracle();
        let cases = oracle["image_decode_config"].as_array().unwrap();
        assert!(cases.len() >= 15, "corpus should cover all six decoders");

        for case in cases {
            let name = case["name"].as_str().unwrap();
            let bytes = base64::engine::general_purpose::STANDARD
                .decode(case["bytes_base64"].as_str().unwrap())
                .unwrap();
            let got = detect_format(&bytes);

            if case["ok"].as_bool().unwrap() {
                assert_eq!(got, Some(case["format"].as_str().unwrap()), "{name}");
            } else if case["err_is_format"].as_bool().unwrap() {
                assert_eq!(got, None, "{name}: Go found no registered magic");
            } else {
                assert!(
                    got.is_some(),
                    "{name}: Go matched a magic and then failed to decode, so the prefix is real"
                );
            }
        }
    }

    /// `?` is a wildcard, not a literal — a GIF whose version digit is `?` is not special, and a
    /// pattern shorter than the data still matches on its prefix.
    #[test]
    fn the_wildcard_byte_matches_anything() {
        assert_eq!(detect_format(b"GIF87a\x01\x00"), Some("gif"));
        assert_eq!(detect_format(b"GIF89a\x01\x00"), Some("gif"));
        assert_eq!(detect_format(b"GIF8Xa"), Some("gif"));
        assert_eq!(detect_format(b"GIF8a"), None, "one byte short");
    }

    /// The three WebP codec variants share one pattern because it stops before the codec byte.
    #[test]
    fn every_webp_codec_matches_the_one_pattern() {
        for codec in [b"VP8 ", b"VP8L", b"VP8X"] {
            let mut data = b"RIFF\x00\x00\x00\x00WEBP".to_vec();
            data.extend_from_slice(codec);
            assert_eq!(detect_format(&data), Some("webp"));
        }
    }
}

/// What [`decode_config`] could establish about a byte string, in the terms `CreateEmoji` needs.
///
/// `uploadEmojiImage` (app/emoji.go:107) asks `image.DecodeConfig` for three things: whether the
/// bytes are an image at all, how wide and how tall. Only the first is answerable for every
/// format from a magic prefix, so this type keeps "not an image" and "an image this port does not
/// measure" apart — the first is an answer, the second is a reason to hand the request to Go.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageConfig {
    /// No registered magic matched. Go returns `image.ErrFormat`, and `uploadEmojiImage` answers
    /// **400 `api.emoji.upload.image.app_error`** — which this port can give on its own.
    NoFormat,
    /// A decoder this port reproduces accepted the header. The dimensions are Go's.
    Known {
        format: &'static str,
        width: i64,
        height: i64,
    },
    /// A registered magic matched, but this port does not reproduce that decoder's header parse
    /// closely enough to claim its answer. The caller forwards; the string says why, for the log.
    ///
    /// Everything but a straightforward non-paletted PNG lands here today, on purpose: a
    /// dimension this port guessed wrong is a wrong *refusal* (or a wrong acceptance) on a route
    /// that writes to the file backend. See [D-380].
    Undecidable(&'static str),
}

/// Port of `checkImageResolutionLimit` (app/image.go:13): `width * height` as an `int64`
/// against `FileSettings.MaxImageResolution`, refused when **strictly** greater.
pub fn check_image_resolution_limit(
    width: i64,
    height: i64,
    max_res: i64,
) -> Result<(), ImageResolutionError> {
    let resolution = width.saturating_mul(height);
    if resolution > max_res {
        return Err(ImageResolutionError {
            resolution,
            max: max_res,
        });
    }
    Ok(())
}

/// The error `checkImageResolutionLimit` returns, with Go's text — it is `Wrap`ped into
/// `api.file.upload_file.large_image_detailed.app_error`, so the text is the wire detail when
/// `EnableDeveloper` is on.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("image resolution is too high: {resolution}, max allowed is {max}")]
pub struct ImageResolutionError {
    pub resolution: i64,
    pub max: i64,
}

/// Port of `getFileExtFromMimeType` (app/file.go:1849): `png` for `image/png`, `jpg` for
/// everything else — so a GIF's or a WebP's preview is named `_preview.jpg`.
pub fn file_ext_from_mime_type(mime_type: &str) -> &'static str {
    if mime_type == "image/png" {
        "png"
    } else {
        "jpg"
    }
}

/// The header half of `image.DecodeConfig`, for the formats this port measures exactly.
///
/// # Only PNG, and only the unambiguous part of PNG
///
/// [`detect_format`] already reproduces Go's whole registry, so `NoFormat` is exact for all six
/// decoders. The *dimensions* are another matter: each decoder has its own header grammar and its
/// own refusals, and a port that got one subtly wrong would not fail loudly — it would accept an
/// emoji Go rejects, or resize one Go writes through. So this measures PNG, where the layout is
/// fixed at bytes 16..24 and every one of `parseIHDR`'s conditions is checkable, and hands
/// everything else back as [`ImageConfig::Undecidable`].
///
/// Within PNG, a **paletted** image (colour type 3) is undecidable too — but for a reason that
/// comes *after* the header is accepted, not instead of accepting it: `DecodeConfig` does not stop
/// at IHDR for those (`cbPaletted(d.cb)` keeps the loop going until `dsSeentRNS`), so it can fail
/// on a PLTE chunk long after the dimensions were read.
///
/// Pinned by `fixtures/behaviour_emoji_upload.json`, whose corpus is run through Go's own
/// `image.DecodeConfig`.
pub fn decode_config(data: &[u8]) -> ImageConfig {
    let Some(format) = detect_format(data) else {
        return ImageConfig::NoFormat;
    };
    if format != "png" {
        return ImageConfig::Undecidable("only PNG headers are measured here");
    }
    png_config(data)
}

/// `png.decoder.parseIHDR` (image/png/reader.go:141) plus the chunk framing around it.
///
/// Every refusal Go can make here becomes `Undecidable` rather than an error of our own: the
/// point is to be certain when we answer, not to reproduce PNG's error strings.
fn png_config(data: &[u8]) -> ImageConfig {
    // 8 signature + 4 length + 4 type + 13 data + 4 CRC.
    const IHDR_END: usize = 33;
    if data.len() < IHDR_END {
        return ImageConfig::Undecidable("truncated before the end of IHDR");
    }

    if u32::from_be_bytes([data[8], data[9], data[10], data[11]]) != 13 {
        return ImageConfig::Undecidable("bad IHDR length");
    }
    if &data[12..16] != b"IHDR" {
        return ImageConfig::Undecidable("the first chunk is not IHDR");
    }

    let ihdr = &data[16..29];
    // `d.crc` is reset before the type and covers the type *and* the data (reader.go:938).
    let crc = crc32_ieee(&data[12..29]);
    if crc != u32::from_be_bytes([data[29], data[30], data[31], data[32]]) {
        return ImageConfig::Undecidable("IHDR checksum mismatch");
    }

    if ihdr[10] != 0 {
        return ImageConfig::Undecidable("unsupported compression method");
    }
    if ihdr[11] != 0 {
        return ImageConfig::Undecidable("unsupported filter method");
    }
    // `itNone` (0) and `itAdam7` (1) are the only interlace methods png accepts.
    if ihdr[12] > 1 {
        return ImageConfig::Undecidable("invalid interlace method");
    }

    // Go reads these as **signed** 32-bit, so a width with the top bit set is negative and the
    // `w <= 0` check refuses it — where an unsigned read would see two billion and try to
    // allocate. Reproduced with `i32::from_be_bytes` rather than a `u32` compared against a limit.
    let width = i32::from_be_bytes([ihdr[0], ihdr[1], ihdr[2], ihdr[3]]);
    let height = i32::from_be_bytes([ihdr[4], ihdr[5], ihdr[6], ihdr[7]]);
    if width <= 0 || height <= 0 {
        return ImageConfig::Undecidable("non-positive dimension");
    }
    // `nPixels != (nPixels*8)/8` on a 64-bit `int`: the product must fit in 61 bits.
    if i64::from(width).saturating_mul(i64::from(height)) >= (1_i64 << 60) {
        return ImageConfig::Undecidable("dimension overflow");
    }

    // Colour type 3 is paletted, and `DecodeConfig` keeps parsing chunks for those.
    // The depth/colour-type pairs `parseIHDR` accepts. Anything else leaves `d.cb == cbInvalid`
    // and Go answers `UnsupportedError`.
    //
    // **Paletted is in this table**, exactly as it is in Go's: `ctPaletted` has arms for depths 1,
    // 2, 4 and 8 (and none for 16). Leaving it out would refuse paletted images *here*, for the
    // wrong reason — the reason they are handed over is the chunk loop below, not their header —
    // and would make the guard that does hand them over unreachable and untestable. A mutation
    // deleting that guard survived until this table said what Go's says.
    let (depth, colour_type) = (ihdr[8], ihdr[9]);
    let supported = match colour_type {
        // ctGrayscale
        0 => matches!(depth, 1 | 2 | 4 | 8 | 16),
        // ctTrueColor, ctGrayscaleAlpha, ctTrueColorAlpha
        2 | 4 | 6 => matches!(depth, 8 | 16),
        // ctPaletted — accepted by `parseIHDR`, and handed over below for a different reason.
        3 => matches!(depth, 1 | 2 | 4 | 8),
        _ => false,
    };
    if !supported {
        return ImageConfig::Undecidable("bit depth / color type pair png does not accept");
    }

    // Colour type 3 is paletted, and `DecodeConfig` does **not** stop at IHDR for those:
    // `cbPaletted(d.cb)` keeps the chunk loop going to `dsSeentRNS`, so it can still fail on a
    // PLTE chunk long after these dimensions were read. The header is fine; the answer is not
    // ours to give.
    if colour_type == 3 {
        return ImageConfig::Undecidable("paletted: DecodeConfig reads past IHDR");
    }

    ImageConfig::Known {
        format: "png",
        width: i64::from(width),
        height: i64::from(height),
    }
}

/// CRC-32/IEEE, bitwise. Seventeen bytes per call, so the table is not worth carrying.
fn crc32_ieee(data: &[u8]) -> u32 {
    let mut crc = 0xffff_ffff_u32;
    for byte in data {
        crc ^= u32::from(*byte);
        for _ in 0..8 {
            let mask = 0_u32.wrapping_sub(crc & 1);
            crc = (crc >> 1) ^ (0xedb8_8320 & mask);
        }
    }
    !crc
}

/// Whether `uploadEmojiImage` can be certain it will **not** take the GIF branch for this
/// filename.
///
/// # The filename decides that branch, not the bytes
///
/// `isGIF := model.NewInfo(filename).MimeType == "image/gif"` (app/emoji.go:129), and
/// `NewInfo` is `mime.TypeByExtension(strings.ToLower(filepath.Ext(name)))`. So a PNG uploaded as
/// `x.gif` is walked by `CountGIFFrames` and fails, and an animated GIF uploaded as `x.png` skips
/// the 70-frame cap entirely.
///
/// # Which is why this asks for `.png` rather than "not `.gif`"
///
/// Go's `mime` package **loads the host's `/etc/mime.types` at init** on Linux, so the set of
/// extensions that map to `image/gif` is a property of the machine the Go server runs on, not of
/// its source. Testing for `.gif` would therefore be a guess about someone else's filesystem.
/// `.png` is in Go's built-in table and cannot be *re*-mapped away from `image/png` by a system
/// file (the built-in table wins), so an extension of exactly `.png` is the one answer that is
/// safe to give without consulting the host — and the GIF walk is skipped for it on every
/// machine. Every other extension is handed to Go.
///
/// Case-insensitive, because `NewInfo` lowercases the extension first.
pub fn filename_is_certainly_png(filename: &str) -> bool {
    go_path_extension(filename).eq_ignore_ascii_case(".png")
}

/// Port of `filepath.Ext` (path/filepath/path.go): everything from the **last** dot in the last
/// path element, or the empty string when that element has none.
fn go_path_extension(path: &str) -> &str {
    let start = path.rfind(['/']).map_or(0, |i| i + 1);
    let element = &path[start..];
    match element.rfind('.') {
        Some(dot) => &element[dot..],
        None => "",
    }
}

#[cfg(test)]
mod decode_config_parity {
    use super::{ImageConfig, decode_config, filename_is_certainly_png};

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!(
            "../../../fixtures/behaviour_emoji_upload.json"
        ))
        .expect("behaviour_emoji_upload.json is generated by reference/dump")
    }

    /// The corpus rows this port deliberately does **not** measure, even though Go decodes them.
    ///
    /// Listed by name rather than derived, so that widening the port has to change this list and
    /// narrowing it cannot happen silently. One entry, and the reason is in
    /// [`super::decode_config`]: `DecodeConfig` keeps reading chunks past IHDR for a paletted
    /// image, so its dimensions are not the last word on whether it decodes.
    const HANDED_TO_GO: &[&str] = &["png_paletted_8x8"];

    /// `image.DecodeConfig` itself, over PNG headers built around 128 and 1028 and around every
    /// field `parseIHDR` refuses on.
    ///
    /// Three-way, and each way is a different bug it catches:
    ///
    /// - Go decoded it → we must report the **same width and height**, or admit we did not
    ///   measure it. A wrong dimension here is a wrong HTTP status: 400 for an image Go stores,
    ///   or a stored image Go refuses.
    /// - Go failed with `ErrFormat` → `NoFormat`, the one refusal this port answers itself.
    /// - Go failed *without* `ErrFormat` → a magic matched and the body did not parse, so we must
    ///   be `Undecidable`: neither `NoFormat` (which would answer where Go's error is different)
    ///   nor `Known` (which would accept bytes Go refuses).
    #[test]
    fn decode_config_matches_go() {
        use base64::Engine;

        let oracle = oracle();
        let cases = oracle["decode_config"].as_array().expect("an array");
        assert!(cases.len() >= 25, "the corpus should cover parseIHDR");

        let mut measured = 0;
        for case in cases {
            let name = case["name"].as_str().expect("a name");
            let bytes = base64::engine::general_purpose::STANDARD
                .decode(case["bytes_base64"].as_str().expect("base64"))
                .expect("valid base64");
            let got = decode_config(&bytes);

            if case["ok"].as_bool().expect("ok") {
                if HANDED_TO_GO.contains(&name) {
                    assert!(
                        matches!(got, ImageConfig::Undecidable(_)),
                        "{name} is on the hand-to-Go list but was measured"
                    );
                    continue;
                }
                let ImageConfig::Known {
                    format,
                    width,
                    height,
                } = got
                else {
                    panic!("{name}: Go decoded this and the port did not measure it");
                };
                assert_eq!(Some(format), case["format"].as_str(), "{name}");
                assert_eq!(Some(width), case["width"].as_i64(), "{name}");
                assert_eq!(Some(height), case["height"].as_i64(), "{name}");
                measured += 1;
            } else if case["err_is_format"].as_bool().expect("err_is_format") {
                assert_eq!(got, ImageConfig::NoFormat, "{name}: Go found no magic");
            } else {
                assert!(
                    matches!(got, ImageConfig::Undecidable(_)),
                    "{name}: a magic matched and Go then failed, so this is not ours to answer"
                );
            }
        }
        assert!(
            measured >= 12,
            "only {measured} rows were actually measured; the test would pass vacuously"
        );
    }

    /// The dimensions that decide `uploadEmojiImage`'s three outcomes, read straight off the
    /// oracle so the thresholds cannot drift apart from Go's constants.
    #[test]
    fn the_thresholds_fall_where_the_constants_say() {
        use base64::Engine;

        let oracle = oracle();
        let constants = &oracle["constants"];
        assert_eq!(constants["max_emoji_width"].as_i64(), Some(128));
        assert_eq!(constants["max_emoji_height"].as_i64(), Some(128));
        assert_eq!(constants["max_emoji_original_width"].as_i64(), Some(1028));
        assert_eq!(constants["max_emoji_original_height"].as_i64(), Some(1028));
        assert_eq!(constants["max_emoji_file_size"].as_i64(), Some(1 << 19));

        let by_name = |name: &str| {
            let case = oracle["decode_config"]
                .as_array()
                .expect("an array")
                .iter()
                .find(|case| case["name"].as_str() == Some(name))
                .unwrap_or_else(|| panic!("{name} is in the corpus"));
            base64::engine::general_purpose::STANDARD
                .decode(case["bytes_base64"].as_str().expect("base64"))
                .expect("valid base64")
        };

        // Exactly at the resize threshold is *not* resized: the check is `>`, not `>=`.
        assert_eq!(
            decode_config(&by_name("png_128x128")),
            ImageConfig::Known {
                format: "png",
                width: 128,
                height: 128
            }
        );
        // One pixel over in either dimension crosses it.
        assert_eq!(
            decode_config(&by_name("png_129x128")),
            ImageConfig::Known {
                format: "png",
                width: 129,
                height: 128
            }
        );
        assert_eq!(
            decode_config(&by_name("png_128x129")),
            ImageConfig::Known {
                format: "png",
                width: 128,
                height: 129
            }
        );
        // And the same, one order of magnitude up, at the refusal threshold.
        assert_eq!(
            decode_config(&by_name("png_header_1028x1028")),
            ImageConfig::Known {
                format: "png",
                width: 1028,
                height: 1028
            }
        );
        assert_eq!(
            decode_config(&by_name("png_header_1029x1028")),
            ImageConfig::Known {
                format: "png",
                width: 1029,
                height: 1028
            }
        );
        assert_eq!(
            decode_config(&by_name("png_header_1028x1029")),
            ImageConfig::Known {
                format: "png",
                width: 1028,
                height: 1029
            }
        );
    }

    /// `model.NewInfo(name).MimeType`, and the claim this port makes about it.
    ///
    /// # An iff, not an implication
    ///
    /// Over this corpus, "the extension is `.png`" and "`mime.TypeByExtension` says `image/png`"
    /// are the **same set**, so the assertion is an equivalence rather than a one-way check.
    /// Safety only needs the forward direction — a claimed filename must never be the GIF branch
    /// — but a one-way check cannot see a port that claims *too few*: case-folding dropped from
    /// the comparison, or `filepath.Ext` reading the first dot instead of the last, would both
    /// leave the forward direction true and quietly forward requests this server can answer.
    ///
    /// The reverse direction is a claim about this corpus and not about every possible host: Go's
    /// `mime` package reads `/etc/mime.types`, so a machine could map some other extension to
    /// `image/png`. That would fail this test, which is the right outcome — it would mean the
    /// fixture was generated somewhere that does not resemble the server.
    #[test]
    fn a_png_extension_is_exactly_the_set_go_calls_image_png() {
        let oracle = oracle();
        let mut claimed = 0;
        for case in oracle["mime_by_extension"].as_array().expect("an array") {
            let filename = case["filename"].as_str().expect("a filename");
            let is_png = case["mime_type"].as_str() == Some("image/png");

            assert_eq!(
                filename_is_certainly_png(filename),
                is_png,
                "{filename}: Go says {:?}",
                case["mime_type"]
            );
            if is_png {
                claimed += 1;
                assert_eq!(
                    case["is_gif"].as_bool(),
                    Some(false),
                    "{filename} was claimed as certainly PNG"
                );
            }
        }
        assert!(claimed >= 7, "only {claimed} filenames were claimed");

        // And the direction that matters for safety, stated separately so it cannot be lost in a
        // future rewrite of the equivalence above.
        for case in oracle["mime_by_extension"].as_array().expect("an array") {
            if case["is_gif"].as_bool() == Some(true) {
                assert!(
                    !filename_is_certainly_png(case["filename"].as_str().expect("a filename")),
                    "a GIF filename must never be claimed"
                );
            }
        }
    }
}

/// What `imaging.ParseSVG` (channels/app/imaging/svg.go:22) returns: the pair, and Go's error
/// beside it rather than instead of it, because Go returns **both** and the caller reads the
/// pair whatever the error says.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SvgDimensions {
    pub width: i64,
    pub height: i64,
}

/// The failures `ParseSVG` reports. The text is not Go's — it only reaches a log line — but
/// the *presence* of an error is pinned by the oracle alongside the dimensions.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum SvgParseError {
    #[error("xml: {0}")]
    Xml(&'static str),
    #[error("scan: {0}")]
    Scan(&'static str),
    #[error("unable to extract SVG dimensions")]
    NoDimensions,
}

/// Port of `imaging.ParseSVG`: the `width`/`height` — or `viewBox` — attributes of the **first**
/// element in the document, whatever it is called.
///
/// Pinned by `fixtures/behaviour_svg.json`, which is where every rule below comes from:
///
/// - `viewBox` with exactly four whitespace-separated fields wins outright, at whatever position
///   it sits, and returns at once; with any other count it is ignored. Four fields that do not
///   scan **return early with no error** and whatever `width`/`height` came before it.
/// - `width`/`height` are `fmt.Sscan` integers ([`go_sscan_int`]): `100px` is 100, `0x10` is
///   16, `0100` is octal 64, `1e2` is 1, `-100` is -100, and a value that does not start with an
///   integer ends the parse with an error and the pair so far.
/// - Attribute names are matched on their local part (`svg:width` counts) and case-sensitively
///   (`WIDTH` does not); a repeated attribute is applied twice, so the last wins.
/// - Either dimension still zero after the first element is `unable to extract SVG dimensions`.
/// - Anything Go's XML decoder refuses before that element — an undefined entity, an encoding
///   declaration that is not UTF-8, an unquoted attribute, invalid UTF-8, a NUL — is that error
///   with `(0, 0)`; a document with no element at all is `EOF`.
pub fn parse_svg(data: &[u8]) -> (SvgDimensions, Option<SvgParseError>) {
    let mut dims = SvgDimensions::default();
    let attrs = match svg_xml::first_start_element(data) {
        Ok(attrs) => attrs,
        Err(err) => return (dims, Some(SvgParseError::Xml(err))),
    };

    for (local, value) in &attrs {
        if local == "viewBox" {
            let values: Vec<&str> = value.split_whitespace().collect();
            if values.len() == 4 {
                let (Ok(width), Ok(height)) = (go_sscan_int(values[2]), go_sscan_int(values[3]))
                else {
                    // `return svgInfo, err` — and `err` is the decoder's, which is nil.
                    return (dims, None);
                };
                dims.width = width;
                dims.height = height;
                return (dims, None);
            }
        }
        if local == "width" {
            match go_sscan_int(value) {
                Ok(width) => dims.width = width,
                Err(err) => return (dims, Some(SvgParseError::Scan(err))),
            }
        }
        if local == "height" {
            match go_sscan_int(value) {
                Ok(height) => dims.height = height,
                Err(err) => return (dims, Some(SvgParseError::Scan(err))),
            }
        }
    }

    if dims.width == 0 || dims.height == 0 {
        return (dims, Some(SvgParseError::NoDimensions));
    }
    (dims, None)
}

/// `fmt.Sscan(s, &i)` for an `int` (fmt/scan.go `scanInt` with verb `v`): skip leading space,
/// an optional sign, a base prefix (`0b`, `0o`, `0x`, or a bare `0` for octal), then the longest
/// run of that base's digits **and underscores**, which `strconv.ParseInt(tok, 0, 64)` then
/// parses — so the token stops at the first foreign character rather than requiring the value
/// to end there, and `_` placement is validated only afterwards.
pub fn go_sscan_int(s: &str) -> Result<i64, &'static str> {
    let rest = s.trim_start_matches(go_is_space);
    let mut chars = rest.chars().peekable();
    let mut tok = String::new();

    if chars.peek().is_none() {
        return Err("EOF");
    }
    if let Some(sign) = chars.next_if(|c| *c == '+' || *c == '-') {
        tok.push(sign);
    }

    // `scanBasePrefix`.
    let (digits, mut have_digits): (&str, bool) = if chars.next_if_eq(&'0').is_some() {
        tok.push('0');
        if let Some(b) = chars.next_if(|c| *c == 'b' || *c == 'B') {
            tok.push(b);
            ("01_", true)
        } else if let Some(o) = chars.next_if(|c| *c == 'o' || *c == 'O') {
            tok.push(o);
            ("01234567_", true)
        } else if let Some(x) = chars.next_if(|c| *c == 'x' || *c == 'X') {
            tok.push(x);
            ("0123456789aAbBcCdDeEfF_", true)
        } else {
            ("01234567_", true)
        }
    } else {
        ("0123456789_", false)
    };

    // `scanNumber`.
    if !have_digits {
        match chars.peek() {
            None => return Err("EOF"),
            Some(c) if digits.contains(*c) => {}
            Some(_) => return Err("expected integer"),
        }
        have_digits = true;
    }
    let _ = have_digits;
    while let Some(c) = chars.next_if(|c| digits.contains(*c)) {
        tok.push(c);
    }

    go_parse_int_base0(&tok)
}

/// `strconv.ParseInt(s, 0, 64)`: the sign, the prefix, underscores between digits only, and
/// the `int64` range — a value past it is `value out of range`, not saturation.
fn go_parse_int_base0(s: &str) -> Result<i64, &'static str> {
    let (neg, body) = match s.as_bytes().first() {
        Some(b'+') => (false, &s[1..]),
        Some(b'-') => (true, &s[1..]),
        _ => (false, s),
    };
    if body.is_empty() {
        return Err("invalid syntax");
    }
    let bytes = body.as_bytes();
    let (base, digits): (u64, &[u8]) = if bytes[0] == b'0' && bytes.len() >= 3 {
        match bytes[1].to_ascii_lowercase() {
            b'b' => (2, &bytes[2..]),
            b'o' => (8, &bytes[2..]),
            b'x' => (16, &bytes[2..]),
            _ => (8, &bytes[1..]),
        }
    } else if bytes[0] == b'0' {
        (8, &bytes[1..])
    } else {
        (10, bytes)
    };
    // `ParseUint` on `"0"` alone: the prefix loop above leaves nothing, and Go's `s = s[1:]`
    // for a bare leading zero leaves nothing too; the loop then produces 0.
    let mut value: u64 = 0;
    let mut underscores = false;
    for &b in digits {
        if b == b'_' {
            underscores = true;
            continue;
        }
        let d = match b {
            b'0'..=b'9' => u64::from(b - b'0'),
            b'a'..=b'z' => u64::from(b - b'a') + 10,
            b'A'..=b'Z' => u64::from(b - b'A') + 10,
            _ => return Err("invalid syntax"),
        };
        if d >= base {
            return Err("invalid syntax");
        }
        value = value
            .checked_mul(base)
            .and_then(|v| v.checked_add(d))
            .ok_or("value out of range")?;
    }
    if underscores && !go_underscore_ok(s) {
        return Err("invalid syntax");
    }
    let cutoff: u64 = 1 << 63;
    if !neg && value >= cutoff {
        return Err("value out of range");
    }
    if neg && value > cutoff {
        return Err("value out of range");
    }
    // Both branches are in range by the checks above: `value` is at most 2^63 when negative.
    Ok(if neg {
        (value as i64).wrapping_neg()
    } else {
        value as i64
    })
}

/// `strconv.underscoreOK`: an underscore may only sit between two digits, or between a base
/// prefix and a digit.
fn go_underscore_ok(s: &str) -> bool {
    let mut bytes = s.as_bytes();
    if let Some(b'-' | b'+') = bytes.first() {
        bytes = &bytes[1..];
    }
    let mut saw = b'^';
    let mut i = 0;
    let mut hex = false;
    if bytes.len() >= 2
        && bytes[0] == b'0'
        && matches!(bytes[1].to_ascii_lowercase(), b'b' | b'o' | b'x')
    {
        i = 2;
        saw = b'0';
        hex = bytes[1].eq_ignore_ascii_case(&b'x');
    }
    while i < bytes.len() {
        let b = bytes[i];
        if b.is_ascii_digit() || (hex && matches!(b.to_ascii_lowercase(), b'a'..=b'f')) {
            saw = b'0';
        } else if b == b'_' {
            if saw != b'0' {
                return false;
            }
            saw = b'_';
        } else {
            if saw == b'_' {
                return false;
            }
            saw = b'!';
        }
        i += 1;
    }
    saw != b'_'
}

/// `fmt`'s `isSpace` (fmt/scan.go), the table `SkipSpace` consults.
fn go_is_space(c: char) -> bool {
    matches!(
        c,
        '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ' | '\u{85}' | '\u{a0}' | '\u{1680}' | '\u{2000}'
            ..='\u{200a}' | '\u{2028}' | '\u{2029}' | '\u{202f}' | '\u{205f}' | '\u{3000}'
    )
}

/// The slice of `encoding/xml`'s decoder that `ParseSVG` exercises: everything up to the first
/// start element, and that element's attributes.
///
/// Transcribed from `Decoder.rawToken` (encoding/xml/xml.go) for the branches a document can
/// take before its root — BOM, character data (with entity checking), comments, CDATA,
/// processing instructions (with the `encoding` refusal), `<!DOCTYPE>` with an internal subset —
/// and for the attribute grammar of the element itself, in `Strict` mode. Error strings are
/// summaries, not Go's.
mod svg_xml {
    /// `(Name.Local, decoded value)` for each attribute, in document order.
    pub(super) fn first_start_element(data: &[u8]) -> Result<Vec<(String, String)>, &'static str> {
        let mut p = Parser {
            data,
            pos: 0,
            depth: 0,
        };
        // Go's decoder drops a leading byte-order mark.
        if data.starts_with(b"\xef\xbb\xbf") {
            p.pos = 3;
        }
        loop {
            match p.peek() {
                None => return Err("EOF"),
                Some(b'<') => {
                    p.pos += 1;
                    match p.peek() {
                        None => return Err("unexpected EOF"),
                        Some(b'/') => return Err("unexpected end element"),
                        Some(b'?') => {
                            p.pos += 1;
                            p.proc_inst()?;
                        }
                        Some(b'!') => {
                            p.pos += 1;
                            p.markup_declaration()?;
                        }
                        Some(_) => return p.start_element(),
                    }
                }
                Some(_) => {
                    // Character data before the root, entities checked.
                    p.text(None)?;
                }
            }
        }
    }

    struct Parser<'a> {
        data: &'a [u8],
        pos: usize,
        depth: usize,
    }

    impl Parser<'_> {
        fn peek(&self) -> Option<u8> {
            self.data.get(self.pos).copied()
        }

        fn getc(&mut self) -> Option<u8> {
            let b = self.peek()?;
            self.pos += 1;
            Some(b)
        }

        fn space(&mut self) {
            while matches!(self.peek(), Some(b' ' | b'\r' | b'\n' | b'\t')) {
                self.pos += 1;
            }
        }

        /// `<?target data?>`; the `xml` declaration's `encoding` must be UTF-8 or absent.
        fn proc_inst(&mut self) -> Result<(), &'static str> {
            let start = self.pos;
            let end = find(self.data, self.pos, b"?>").ok_or("unexpected EOF")?;
            let body = &self.data[start..end];
            self.pos = end + 2;
            let text = String::from_utf8_lossy(body);
            let (target, content) = text
                .split_once(|c: char| c.is_ascii_whitespace())
                .unwrap_or((&text, ""));
            if target.is_empty() {
                return Err("expected target name after <?");
            }
            if target == "xml" {
                if let Some(enc) = proc_inst_param("encoding", content) {
                    if !enc.is_empty() && !enc.eq_ignore_ascii_case("utf-8") {
                        return Err("encoding declared but Decoder.CharsetReader is nil");
                    }
                }
            }
            Ok(())
        }

        /// `<!-- -->`, `<![CDATA[ ]]>` or a `<!DOCTYPE …>` directive with its internal subset.
        fn markup_declaration(&mut self) -> Result<(), &'static str> {
            if self.data[self.pos..].starts_with(b"--") {
                let end = find(self.data, self.pos + 2, b"-->").ok_or("unexpected EOF")?;
                self.pos = end + 3;
                return Ok(());
            }
            if self.data[self.pos..].starts_with(b"[CDATA[") {
                let end = find(self.data, self.pos + 7, b"]]>").ok_or("unexpected EOF")?;
                self.pos = end + 3;
                return Ok(());
            }
            // A directive: read to the matching `>`, skipping quoted strings, nested `<! >`
            // and comments, and the `[ ]` internal subset.
            self.depth = 0;
            loop {
                let b = self.getc().ok_or("unexpected EOF")?;
                match b {
                    b'"' | b'\'' => while self.getc().ok_or("unexpected EOF")? != b {},
                    b'[' => self.depth += 1,
                    b']' => self.depth = self.depth.saturating_sub(1),
                    b'<' => {
                        if self.data[self.pos..].starts_with(b"!--") {
                            let end =
                                find(self.data, self.pos + 3, b"-->").ok_or("unexpected EOF")?;
                            self.pos = end + 3;
                        } else if self.peek() == Some(b'!') {
                            self.depth += 1;
                        }
                    }
                    b'>' if self.depth == 0 => return Ok(()),
                    b'>' => self.depth -= 1,
                    _ => {}
                }
            }
        }

        /// The element after `<`: its name, then attributes until `>` or `/>`.
        fn start_element(&mut self) -> Result<Vec<(String, String)>, &'static str> {
            let _name = self.name()?;
            let mut attrs = Vec::new();
            loop {
                self.space();
                let b = self.getc().ok_or("unexpected EOF")?;
                match b {
                    b'/' => {
                        if self.getc() != Some(b'>') {
                            return Err("expected /> in element");
                        }
                        return Ok(attrs);
                    }
                    b'>' => return Ok(attrs),
                    _ => self.pos -= 1,
                }
                let name = self.name()?;
                let local = name
                    .rsplit_once(':')
                    .map_or(name.as_str(), |(_, l)| l)
                    .to_owned();
                self.space();
                if self.getc() != Some(b'=') {
                    return Err("attribute name without = in element");
                }
                self.space();
                let quote = self.getc().ok_or("unexpected EOF")?;
                if quote != b'"' && quote != b'\'' {
                    return Err("unquoted or missing attribute value in element");
                }
                let value = self.text(Some(quote))?;
                attrs.push((local, value));
            }
        }

        /// `Decoder.name` — the longest run of name bytes, then `isName`.
        fn name(&mut self) -> Result<String, &'static str> {
            let start = self.pos;
            while let Some(b) = self.peek() {
                if is_name_byte(b) || b >= 0x80 {
                    self.pos += 1;
                } else {
                    break;
                }
            }
            let raw = &self.data[start..self.pos];
            let name = std::str::from_utf8(raw).map_err(|_| "invalid UTF-8")?;
            if !is_name(name) {
                return Err("invalid XML name");
            }
            Ok(name.to_owned())
        }

        /// `Decoder.text(quote, cdata=false)`: up to the closing quote (or the next `<` for
        /// character data), with entity references resolved and Go's character checks.
        fn text(&mut self, quote: Option<u8>) -> Result<String, &'static str> {
            let mut out: Vec<u8> = Vec::new();
            loop {
                let Some(b) = self.getc() else {
                    if quote.is_some() {
                        return Err("unexpected EOF");
                    }
                    break;
                };
                if Some(b) == quote {
                    break;
                }
                if b == b'<' {
                    if quote.is_some() {
                        return Err("unescaped < inside quoted string");
                    }
                    self.pos -= 1;
                    break;
                }
                if b == b'&' {
                    let end = find(self.data, self.pos, b";").ok_or("invalid character entity")?;
                    let raw = std::str::from_utf8(&self.data[self.pos..end])
                        .map_err(|_| "invalid UTF-8")?;
                    if end - self.pos > 64 || raw.is_empty() {
                        return Err("invalid character entity");
                    }
                    self.pos = end + 1;
                    let decoded: char = if let Some(num) = raw.strip_prefix('#') {
                        let code = if let Some(hex) = num.strip_prefix('x') {
                            u32::from_str_radix(hex, 16)
                        } else {
                            num.parse::<u32>()
                        }
                        .map_err(|_| "invalid character entity")?;
                        char::from_u32(code)
                            .filter(|c| is_in_character_range(*c))
                            .ok_or("invalid character entity")?
                    } else {
                        match raw {
                            "lt" => '<',
                            "gt" => '>',
                            "amp" => '&',
                            "apos" => '\'',
                            "quot" => '"',
                            _ => return Err("invalid character entity"),
                        }
                    };
                    let mut buf = [0u8; 4];
                    out.extend_from_slice(decoded.encode_utf8(&mut buf).as_bytes());
                    continue;
                }
                // `\r` and `\r\n` become `\n`.
                if b == b'\r' {
                    if self.peek() == Some(b'\n') {
                        self.pos += 1;
                    }
                    out.push(b'\n');
                    continue;
                }
                out.push(b);
            }
            let text = String::from_utf8(out).map_err(|_| "invalid UTF-8")?;
            if let Some(bad) = text.chars().find(|c| !is_in_character_range(*c)) {
                let _ = bad;
                return Err("illegal character code");
            }
            Ok(text)
        }
    }

    /// `procInst(param, s)`: the quoted value of `param="…"` in a processing instruction's
    /// data, or `None`.
    fn proc_inst_param(param: &str, s: &str) -> Option<String> {
        let idx = s.find(&format!("{param}="))?;
        let v = &s[idx + param.len() + 1..];
        let quote = v.chars().next()?;
        if quote != '"' && quote != '\'' {
            return None;
        }
        let rest = &v[1..];
        let end = rest.find(quote)?;
        Some(rest[..end].to_owned())
    }

    fn find(data: &[u8], from: usize, needle: &[u8]) -> Option<usize> {
        if from > data.len() {
            return None;
        }
        data[from..]
            .windows(needle.len())
            .position(|w| w == needle)
            .map(|i| i + from)
    }

    /// `isNameByte` (encoding/xml/xml.go).
    fn is_name_byte(b: u8) -> bool {
        b.is_ascii_alphanumeric() || matches!(b, b'_' | b':' | b'.' | b'-')
    }

    /// `isName`: a letter, `_` or `:` first, then those plus digits, `.` and `-`. Non-ASCII is
    /// admitted by Unicode class — letters anywhere, marks and digits after the first.
    fn is_name(s: &str) -> bool {
        let mut chars = s.chars();
        let Some(first) = chars.next() else {
            return false;
        };
        if !(first.is_alphabetic() || first == '_' || first == ':') {
            return false;
        }
        chars.all(|c| {
            c.is_alphanumeric() || matches!(c, '_' | ':' | '.' | '-' | '\u{b7}') || is_mark(c)
        })
    }

    fn is_mark(c: char) -> bool {
        matches!(c, '\u{300}'..='\u{36f}' | '\u{203f}' | '\u{2040}')
    }

    /// `isInCharacterRange`: the XML 1.0 `Char` production.
    fn is_in_character_range(c: char) -> bool {
        matches!(c, '\u{9}' | '\u{a}' | '\u{d}' | '\u{20}'..='\u{d7ff}' | '\u{e000}'..='\u{fffd}' | '\u{10000}'..='\u{10ffff}')
    }
}

#[cfg(test)]
mod svg_parity {
    use super::{SvgDimensions, go_sscan_int, parse_svg};

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!("../../../fixtures/behaviour_svg.json"))
            .expect("behaviour_svg.json is generated by reference/dump")
    }

    #[test]
    fn parse_svg_matches_go_over_the_corpus() {
        let oracle = oracle();
        let cases = oracle["parse_svg"].as_array().expect("an array");
        assert!(cases.len() > 50);
        for case in cases {
            let name = case["name"].as_str().unwrap();
            let svg = case["svg"].as_str().unwrap();
            let want = SvgDimensions {
                width: case["width"].as_i64().unwrap(),
                height: case["height"].as_i64().unwrap(),
            };
            let want_err = !case["err"].as_str().unwrap().is_empty();
            let (got, err) = parse_svg(svg.as_bytes());
            assert_eq!(got, want, "{name}: dimensions (err {err:?})");
            assert_eq!(err.is_some(), want_err, "{name}: error presence ({err:?})");
        }
    }

    #[test]
    fn sscan_int_stops_at_the_first_foreign_character() {
        assert_eq!(go_sscan_int("100px"), Ok(100));
        assert_eq!(go_sscan_int("1e2"), Ok(1));
        assert_eq!(go_sscan_int("0x10"), Ok(16));
        assert_eq!(go_sscan_int("0100"), Ok(64));
        assert_eq!(go_sscan_int("09"), Ok(0));
        assert_eq!(go_sscan_int("1_000"), Ok(1000));
        assert_eq!(go_sscan_int("-0b11"), Ok(-3));
        assert!(go_sscan_int("0x").is_err());
        assert!(go_sscan_int("_1").is_err());
        assert!(go_sscan_int("").is_err());
        assert!(go_sscan_int("  ").is_err());
        assert!(go_sscan_int("abc").is_err());
        assert!(go_sscan_int("9223372036854775808").is_err());
        assert_eq!(go_sscan_int("-9223372036854775808"), Ok(i64::MIN));
    }
}
