//! Port of `channels/app/user_agent.go` and the half of `github.com/avct/uasurfer` it stands on.
//!
//! # Why a user-agent parser is in scope at all
//!
//! `DoLogin` writes three props into every session it creates (app/login.go:186-193):
//!
//! ```text
//! session.AddProp(model.SessionPropPlatform, plat)
//! session.AddProp(model.SessionPropOs, os)
//! session.AddProp(model.SessionPropBrowser, fmt.Sprintf("%v/%v", bname, bversion))
//! ```
//!
//! Those land in `Sessions.Props` and are echoed verbatim by `GET /users/{user_id}/sessions`,
//! which this server already answers. They are wire format, not telemetry, so `login` cannot be
//! served without reproducing them.
//!
//! # What is ported and what is not
//!
//! uasurfer computes three things: `OS`, `Browser` and `DeviceType`. Mattermost reads the first
//! two and never the third, so `evalDevice` and everything below it is **not** ported — and
//! neither are the bot names beyond what `IsBot` needs, since a bot classification changes the OS
//! and platform to `Bot` and that *is* observable. The parse order is uasurfer's own and is load
//! bearing: `parse` short-circuits on the empty string, then runs `evalOS`, then
//! `evalBrowserName`, and only reaches `evalBrowserVersion` when neither of those reported a bot.
//!
//! # The oracle
//!
//! `fixtures/behaviour_user_agent.json` is generated by `reference/dump/behaviour_user_agent.go`,
//! which calls the **real** `uasurfer.Parse` over a corpus and records both its raw output and
//! the three props Mattermost derives. The `go_parity` module below asserts this port against
//! every row, field by field, so the parser is checked against Go's answer rather than against a
//! reading of Go's source.
//!
//! Two of Go's habits survive here because they are visible on the wire:
//!
//! - **`Version.parse` is not a version parser.** It walks the string three times pulling out
//!   runs of digits with an idiosyncratic leading-zero rule, and it is the reason
//!   `Chrome/127.0.0.0` reports a version of `127.0` while `Chrome/49.0.2623.112` reports
//!   `49.0.2623` — the formatter drops the patch only when it is zero.
//! - **`getBrowserName` renames `BrowserIE` to "Edge" when the major version exceeds 11**, so the
//!   browser *version* decides the browser *name*, and the version is computed after the name.

use std::fmt::Write as _;

/// uasurfer's `Platform` (uasurfer.go:110), restricted to the variants
/// `channels/app/user_agent.go` can observe.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    Unknown,
    Windows,
    Mac,
    Linux,
    IPad,
    IPhone,
    IPod,
    Blackberry,
    WindowsPhone,
    Playstation,
    Xbox,
    Nintendo,
    Bot,
}

/// uasurfer's `OSName` (uasurfer.go:82).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OsName {
    Unknown,
    WindowsPhone,
    Windows,
    MacOSX,
    IOS,
    Android,
    Blackberry,
    ChromeOS,
    Kindle,
    WebOS,
    Linux,
    Playstation,
    Xbox,
    Nintendo,
    Bot,
}

/// uasurfer's `BrowserName` (uasurfer.go:36). The declaration order matters: `IsBot` is
/// `BrowserBot <= name <= BrowserYahooBot`, a **range check over the enum's integer values**, so
/// the bot block has to stay contiguous and in place. [`BrowserName::is_bot`] reproduces that as
/// an explicit list rather than a comparison, because a Rust enum's discriminants are not the
/// thing a reader would check.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BrowserName {
    Unknown,
    Chrome,
    IE,
    Safari,
    Firefox,
    Android,
    Opera,
    Blackberry,
    UCBrowser,
    Silk,
    Nokia,
    NetFront,
    QQ,
    Maxthon,
    SogouExplorer,
    Spotify,
    Nintendo,
    Samsung,
    Yandex,
    CocCoc,
    // The bot block begins here and must stay contiguous — see the type's doc comment.
    Bot,
    AppleBot,
    BaiduBot,
    BingBot,
    DuckDuckGoBot,
    FacebookBot,
    GoogleBot,
    LinkedInBot,
    MsnBot,
    PingdomBot,
    TwitterBot,
    YandexBot,
    CocCocBot,
    YahooBot,
}

impl BrowserName {
    /// The `BrowserBot <= n <= BrowserYahooBot` range of `UserAgent.IsBot` (uasurfer.go:176).
    fn is_bot(self) -> bool {
        matches!(
            self,
            BrowserName::Bot
                | BrowserName::AppleBot
                | BrowserName::BaiduBot
                | BrowserName::BingBot
                | BrowserName::DuckDuckGoBot
                | BrowserName::FacebookBot
                | BrowserName::GoogleBot
                | BrowserName::LinkedInBot
                | BrowserName::MsnBot
                | BrowserName::PingdomBot
                | BrowserName::TwitterBot
                | BrowserName::YandexBot
                | BrowserName::CocCocBot
                | BrowserName::YahooBot
        )
    }
}

/// uasurfer's `Version` (uasurfer.go:131). Three `int`s, defaulting to zero.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Version {
    pub major: i64,
    pub minor: i64,
    pub patch: i64,
}

/// uasurfer's `UserAgent`, minus `DeviceType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UserAgent {
    pub platform: Platform,
    pub os_name: OsName,
    pub os_version: Version,
    pub browser_name: BrowserName,
    pub browser_version: Version,
}

impl Default for UserAgent {
    fn default() -> Self {
        UserAgent {
            platform: Platform::Unknown,
            os_name: OsName::Unknown,
            os_version: Version::default(),
            browser_name: BrowserName::Unknown,
            browser_version: Version::default(),
        }
    }
}

impl UserAgent {
    /// `UserAgent.IsBot` (uasurfer.go:175), minus the `DeviceType` it also sets.
    fn is_bot(&self) -> bool {
        self.browser_name.is_bot() || self.os_name == OsName::Bot || self.platform == Platform::Bot
    }

    /// `UserAgent.maybeBot` (system.go:105). Returns whether the agent was a bot, and rewrites
    /// the OS fields when it was — which is why a bot's `platform` prop is `Unknown` rather than
    /// whatever its UA claimed: `PlatformBot` has no entry in Mattermost's `platformNames`.
    fn maybe_bot(&mut self) -> bool {
        if self.is_bot() {
            self.platform = Platform::Bot;
            self.os_name = OsName::Bot;
            return true;
        }
        false
    }
}

/// Port of `uasurfer.Parse` (uasurfer.go:190) together with `parse` (uasurfer.go:205).
///
/// The three-way switch is the whole control flow and the order is load bearing:
///
/// 1. an **empty** normalised string is all-unknown and nothing else runs;
/// 2. `evalOS` runs and, if it reported a bot, nothing else runs;
/// 3. `evalBrowserName` runs and, if it reported a bot, nothing else runs;
/// 4. only then is the browser *version* evaluated.
///
/// So a bot's browser version is always `0.0`, and so is that of anything whose OS evaluation
/// tripped the bot check. `evalDevice` is the fourth step in Go and is not ported — Mattermost
/// never reads `DeviceType`.
#[must_use]
pub fn parse(raw: &str) -> UserAgent {
    let ua = normalise(raw);
    let mut dest = UserAgent::default();

    if ua.is_empty() {
        return dest;
    }
    if eval_os(&mut dest, &ua) {
        return dest;
    }
    if eval_browser_name(&mut dest, &ua) {
        return dest;
    }
    eval_browser_version(&mut dest, &ua);
    dest
}

/// Port of `normalise` (uasurfer.go:215).
///
/// Go lowers ASCII byte-wise into a 1024-byte stack buffer and falls back to `strings.ToLower`
/// the moment it meets a byte above 127 — or when the string is longer than 1024. Both paths
/// produce the same answer for ASCII; for anything else the fallback does full Unicode
/// lowercasing. `str::to_lowercase` is Rust's equivalent of the fallback, and `is_ascii` picks
/// the same branch Go's `copyLower` does, so the two agree without reproducing the buffer.
fn normalise(raw: &str) -> String {
    if raw.is_ascii() {
        raw.to_ascii_lowercase()
    } else {
        raw.to_lowercase()
    }
}

// ---------------------------------------------------------------------------------------------
// system.go
// ---------------------------------------------------------------------------------------------

/// Port of `UserAgent.evalOS` (system.go:12).
///
/// # The platform group, and the two ways of not having one
///
/// Go slices the string between the first `(` and the first `)`. When `)` comes *before* `(`
/// — a malformed agent — both indices are reset to `0` and `len(ua)`, so the "platform group" is
/// the entire string **including its leading byte**, because the slice is `ua[s+1:e]`. When there
/// is no `)` at all, only `e` is reset, so the group starts one byte after the `(`. And when
/// there is no `(` either, `s` is `-1` and `s+1` is `0` — the whole string again. Those three
/// shapes are in the corpus for exactly this reason.
fn eval_os(dest: &mut UserAgent, ua: &str) -> bool {
    let bytes = ua.as_bytes();
    let mut s = index_byte(bytes, b'(');
    let mut e = index_byte(bytes, b')');
    if s > e {
        s = 0;
        e = bytes.len() as isize;
    }
    if e == -1 {
        e = bytes.len() as isize;
    }

    // `ua[s+1:e]`. `s` is -1 when there is no '(' at all, so `s+1` is 0.
    let start = (s + 1).max(0) as usize;
    let end = (e.max(0) as usize).min(bytes.len());
    let agent_platform = if start <= end { &ua[start..end] } else { "" };

    let specs = match agent_platform.find(';') {
        Some(at) => &agent_platform[..at],
        None => agent_platform,
    };

    if specs == "android" {
        eval_linux(dest, ua, agent_platform);
    } else if specs == "bb10" || specs == "playbook" {
        dest.platform = Platform::Blackberry;
        dest.os_name = OsName::Blackberry;
    } else if specs == "x11" || specs == "linux" {
        eval_linux(dest, ua, agent_platform);
    } else if specs.starts_with("ipad")
        || specs.starts_with("iphone")
        || specs.starts_with("ipod touch")
        || specs.starts_with("ipod")
    {
        eval_ios(dest, specs, agent_platform);
    } else if specs == "macintosh" {
        eval_macintosh(dest, ua);
    } else if ua.contains("blackberry") || ua.contains("playbook") {
        dest.platform = Platform::Blackberry;
        dest.os_name = OsName::Blackberry;
    } else if agent_platform.contains("windows phone ") {
        eval_windows_phone(dest, agent_platform);
    } else if ua.contains("windows ") || ua.contains("microsoft-cryptoapi") {
        eval_windows(dest, ua);
    } else if ua.contains("kindle/") || amazon_fire_fingerprint(agent_platform) {
        dest.platform = Platform::Linux;
        dest.os_name = OsName::Kindle;
    } else if ua.contains("linux") {
        eval_linux(dest, ua, agent_platform);
    } else if ua.contains("webos") || ua.contains("hpwos") {
        dest.platform = Platform::Linux;
        dest.os_name = OsName::WebOS;
    } else if ua.contains("nintendo") {
        dest.platform = Platform::Nintendo;
        dest.os_name = OsName::Nintendo;
    } else if ua.contains("playstation") || ua.contains("vita") || ua.contains("psp") {
        dest.platform = Platform::Playstation;
        dest.os_name = OsName::Playstation;
    } else if ua.contains("android") {
        eval_linux(dest, ua, agent_platform);
    } else if ua.contains("cfnetwork") && ua.contains("darwin") {
        eval_macintosh(dest, ua);
    } else {
        dest.platform = Platform::Unknown;
        dest.os_name = OsName::Unknown;
    }

    dest.maybe_bot()
}

/// `strings.IndexRune` on an ASCII byte: the index, or -1.
fn index_byte(haystack: &[u8], needle: u8) -> isize {
    match haystack.iter().position(|b| *b == needle) {
        Some(at) => at as isize,
        None => -1,
    }
}

/// Port of `amazonFireFingerprint`, `regexp.MustCompile("\\s(k[a-z]{3,5}|sd\\d{4}ur)\\s")`
/// (system.go:10), matched anywhere in the string.
///
/// Written out rather than pulled in as a regex crate: it is one alternation over ASCII, and a
/// dependency added for four lines of matching is a dependency the next reader has to audit.
/// `\s` in Go's regexp is `[\t\n\f\r ]` — **not** `\v`, and not any Unicode space.
fn amazon_fire_fingerprint(text: &str) -> bool {
    let bytes = text.as_bytes();
    for start in 0..bytes.len() {
        if !is_go_space(bytes[start]) {
            continue;
        }
        // `k[a-z]{3,5}` — greedy, but a regex search succeeds on any length that lets the
        // trailing `\s` match, so every length in range is tried.
        if bytes.get(start + 1) == Some(&b'k') {
            for run in 3..=5usize {
                let close = start + 2 + run;
                if close < bytes.len()
                    && bytes[start + 2..close].iter().all(u8::is_ascii_lowercase)
                    && is_go_space(bytes[close])
                {
                    return true;
                }
            }
        }
        // `sd\d{4}ur`
        let close = start + 1 + 8;
        if close < bytes.len()
            && &bytes[start + 1..start + 3] == b"sd"
            && bytes[start + 3..start + 7].iter().all(u8::is_ascii_digit)
            && &bytes[start + 7..start + 9] == b"ur"
            && is_go_space(bytes[close])
        {
            return true;
        }
    }
    false
}

/// Go's `regexp` `\s`: `[\t\n\f\r ]`.
fn is_go_space(byte: u8) -> bool {
    matches!(byte, b'\t' | b'\n' | 0x0c | b'\r' | b' ')
}

/// Port of `UserAgent.evalLinux` (system.go:117).
fn eval_linux(dest: &mut UserAgent, ua: &str, agent_platform: &str) {
    if ua.contains("kindle") || amazon_fire_fingerprint(agent_platform) {
        dest.platform = Platform::Linux;
        dest.os_name = OsName::Kindle;
        find_version_number(&mut dest.os_version, agent_platform, "android ");
    } else if ua.contains("android") || ua.contains("googletv") {
        dest.platform = Platform::Linux;
        dest.os_name = OsName::Android;
        find_version_number(&mut dest.os_version, agent_platform, "android ");
    } else if ua.contains("cros") {
        dest.platform = Platform::Linux;
        dest.os_name = OsName::ChromeOS;
    } else if ua.contains("webos") || ua.contains("hpwos") {
        dest.platform = Platform::Linux;
        dest.os_name = OsName::WebOS;
    } else {
        // Go's last two arms — the `x11|bsd|suse|debian|ubuntu` case and the `default` — assign
        // exactly the same pair, so they are folded. Kept as one arm deliberately: splitting it
        // would invite a reader to make them differ.
        dest.platform = Platform::Linux;
        dest.os_name = OsName::Linux;
    }
}

/// Port of `UserAgent.evaliOS` (system.go:157).
fn eval_ios(dest: &mut UserAgent, ua_platform: &str, agent_platform: &str) {
    if ua_platform.starts_with("iphone") {
        dest.platform = Platform::IPhone;
        dest.os_name = OsName::IOS;
        get_ios_version(&mut dest.os_version, agent_platform);
    } else if ua_platform.starts_with("ipad") {
        dest.platform = Platform::IPad;
        dest.os_name = OsName::IOS;
        get_ios_version(&mut dest.os_version, agent_platform);
    } else if ua_platform.starts_with("ipod touch") || ua_platform.starts_with("ipod") {
        dest.platform = Platform::IPod;
        dest.os_name = OsName::IOS;
        get_ios_version(&mut dest.os_version, agent_platform);
    } else {
        // Unreachable from `evalOS`, whose guard is the same four prefixes. Reproduced because
        // it is not obviously unreachable and the default is *iPad*, not unknown.
        dest.platform = Platform::IPad;
        dest.os_name = OsName::Unknown;
    }
}

/// Port of `UserAgent.evalWindowsPhone` (system.go:182).
///
/// The platform is set unconditionally and the *name* only when a version parses — so a Windows
/// Phone UA with an unparseable version is platform `WindowsPhone`, os `Unknown`, which
/// Mattermost renders as `"Windows Phone"` / `""`.
fn eval_windows_phone(dest: &mut UserAgent, agent_platform: &str) {
    dest.platform = Platform::WindowsPhone;
    if find_version_number(&mut dest.os_version, agent_platform, "windows phone os ")
        || find_version_number(&mut dest.os_version, agent_platform, "windows phone ")
    {
        dest.os_name = OsName::WindowsPhone;
    } else {
        dest.os_name = OsName::Unknown;
    }
}

/// Port of `UserAgent.evalWindows` (system.go:192).
fn eval_windows(dest: &mut UserAgent, ua: &str) {
    if ua.contains("xbox") {
        dest.platform = Platform::Xbox;
        dest.os_name = OsName::Xbox;
        if !find_version_number(&mut dest.os_version, ua, "windows nt ") {
            dest.os_version = Version {
                major: 6,
                minor: 0,
                patch: 0,
            };
        }
    } else if !ua.contains("windows ") {
        // Reached via the `microsoft-cryptoapi` arm of `evalOS`.
        dest.platform = Platform::Windows;
        dest.os_name = OsName::Unknown;
    } else if ua.contains("windows nt ")
        && find_version_number(&mut dest.os_version, ua, "windows nt ")
    {
        dest.platform = Platform::Windows;
        dest.os_name = OsName::Windows;
    } else if ua.contains("windows xp") {
        dest.platform = Platform::Windows;
        dest.os_name = OsName::Windows;
        dest.os_version = Version {
            major: 5,
            minor: 1,
            patch: 0,
        };
    } else {
        dest.platform = Platform::Windows;
        dest.os_name = OsName::Unknown;
    }
}

/// Port of `UserAgent.evalMacintosh` (system.go:222).
fn eval_macintosh(dest: &mut UserAgent, ua_platform_group: &str) {
    dest.platform = Platform::Mac;
    if let Some(at) = ua_platform_group.find("os x ") {
        dest.os_name = OsName::MacOSX;
        parse_version(&mut dest.os_version, &ua_platform_group[at + 5..]);
        return;
    }
    dest.os_name = OsName::Unknown;
}

/// Port of `Version.findVersionNumber` (system.go:232).
fn find_version_number(version: &mut Version, text: &str, marker: &str) -> bool {
    match text.find(marker) {
        Some(at) => parse_version(version, &text[at + marker.len()..]),
        None => false,
    }
}

/// Port of `OS.getiOSVersion` (system.go:241).
///
/// Note the fall-through: when neither marker is present it parses the platform group **from the
/// start**, which for `iphone; cpu …` begins with a letter and therefore parses nothing. That is
/// why `Mattermost Mobile/2.19.0 (iPhone; iOS 17.5.1)` records an OS version of `0.0.0` even
/// though the string plainly says 17.5.1.
fn get_ios_version(version: &mut Version, ua_platform_group: &str) {
    if let Some(at) = ua_platform_group.find("cpu iphone os ") {
        parse_version(version, &ua_platform_group[at + 14..]);
        return;
    }
    if let Some(at) = ua_platform_group.find("cpu os ") {
        parse_version(version, &ua_platform_group[at + 7..]);
        return;
    }
    parse_version(version, ua_platform_group);
}

/// Port of `Version.parse` (system.go:272), which is **not** a version parser and must not be
/// replaced by one.
///
/// It refuses outright unless the first byte is a digit, and then loops three times pulling one
/// number out of the front of the remaining string. Inside each pass:
///
/// - a non-digit ends the number and the remainder restarts **after** it, so `10_15_7` yields
///   10, 15, 7 exactly as `10.15.7` does;
/// - the first digit seeds the value; a subsequent digit while the value is still `0` is either
///   another `0` (skipped, and the pass continues) or a non-zero, at which point the remainder
///   restarts **at** that digit and the pass ends with the value still `0`. So `"0a"` is a major
///   of 0, `"01"` is a major of 0 *and* a minor of 1, and `"007"` is 0 then 7 — a leading zero is
///   not stripped, it consumes a whole pass;
/// - reaching the end of the string empties it, so the remaining passes see `""` and contribute
///   zero.
///
/// Every one of those is observable in `Chrome/127.0.0.0`, which becomes `127.0` and not `127`.
fn parse_version(version: &mut Version, text: &str) -> bool {
    let bytes = text.as_bytes();
    if bytes.is_empty() || !bytes[0].is_ascii_digit() {
        return false;
    }

    let mut rest: &[u8] = bytes;
    for pass in 0..3 {
        let mut empty = true;
        let mut val: i64 = 0;
        let last = rest.len().wrapping_sub(1);

        for k in 0..rest.len() {
            let c = rest[k];
            if c.is_ascii_digit() {
                if empty {
                    val = i64::from(c - b'0');
                    empty = false;
                    if k == last {
                        rest = &rest[..0];
                    }
                    continue;
                }
                if val == 0 {
                    if c == b'0' {
                        if k == last {
                            rest = &rest[..0];
                        }
                        continue;
                    }
                    rest = &rest[k..];
                    break;
                }
                val = 10 * val + i64::from(c - b'0');
                if k == last {
                    rest = &rest[..0];
                }
                continue;
            }
            rest = &rest[k + 1..];
            break;
        }

        match pass {
            0 => version.major = val,
            1 => version.minor = val,
            _ => version.patch = val,
        }
    }
    true
}

// ---------------------------------------------------------------------------------------------
// browser.go
// ---------------------------------------------------------------------------------------------

/// Port of `UserAgent.evalBrowserName` (browser.go:22).
///
/// # The `goto notwebkit`
///
/// Go's webkit switch ends in `default: goto notwebkit`, which jumps **out** of the switch to the
/// label below it — so an agent that says `applewebkit` but matches none of the webkit arms is
/// evaluated a second time against the non-webkit list. Modelled here by letting the webkit
/// branch return `None` and falling through, which is the same control flow without the label.
fn eval_browser_name(dest: &mut UserAgent, ua: &str) -> bool {
    // Blackberry goes first because it reads as MSIE and Safari.
    if ua.contains("blackberry")
        || ua.contains("playbook")
        || ua.contains("bb10")
        || ua.contains("rim ")
    {
        dest.browser_name = BrowserName::Blackberry;
        return dest.maybe_bot();
    }

    if ua.contains("applewebkit")
        && let Some(name) = webkit_browser_name(ua)
    {
        dest.browser_name = name;
        return dest.maybe_bot();
    }

    dest.browser_name = if ua.contains("qq/") || ua.contains("qqbrowser/") {
        BrowserName::QQ
    } else if ua.contains("msie") || ua.contains("trident") {
        BrowserName::IE
    } else if ua.contains("gecko")
        && (ua.contains("firefox")
            || ua.contains("iceweasel")
            || ua.contains("seamonkey")
            || ua.contains("icecat"))
    {
        BrowserName::Firefox
    } else if ua.contains("presto") || ua.contains("opera") {
        BrowserName::Opera
    } else if ua.contains("ucbrowser") {
        BrowserName::UCBrowser
    } else if ua.contains("applebot") {
        BrowserName::AppleBot
    } else if ua.contains("baiduspider") {
        BrowserName::BaiduBot
    } else if ua.contains("adidxbot") || ua.contains("bingbot") || ua.contains("bingpreview") {
        BrowserName::BingBot
    } else if ua.contains("duckduckbot") {
        BrowserName::DuckDuckGoBot
    } else if ua.contains("facebot") || ua.contains("facebookexternalhit") {
        BrowserName::FacebookBot
    } else if ua.contains("googlebot") {
        BrowserName::GoogleBot
    } else if ua.contains("linkedinbot") {
        BrowserName::LinkedInBot
    } else if ua.contains("msnbot") {
        BrowserName::MsnBot
    } else if ua.contains("pingdom.com_bot") {
        BrowserName::PingdomBot
    } else if ua.contains("twitterbot") {
        BrowserName::TwitterBot
    } else if ua.contains("yandex") || ua.contains("yadirectfetcher") {
        BrowserName::YandexBot
    } else if ua.contains("yahoo") {
        BrowserName::YahooBot
    } else if ua.contains("coccocbot") {
        BrowserName::CocCocBot
    } else if ua.contains("phantomjs") {
        BrowserName::Bot
    } else {
        BrowserName::Unknown
    };

    dest.maybe_bot()
}

/// The `applewebkit` switch of `evalBrowserName`. `None` is Go's `goto notwebkit`.
///
/// The last three arms all answer `Safari` and are deliberately **not** folded into one
/// disjunction: they are three separate cases in browser.go:80-92 with three different reasons —
/// a full webkit signature, an iOS device with no "safari" token at all, and Google's iPhone
/// search app. Merging them would make the next upstream change to any one of them a silent
/// three-way edit. Hence the `allow`.
#[allow(clippy::if_same_then_else)]
fn webkit_browser_name(ua: &str) -> Option<BrowserName> {
    Some(if ua.contains("googlebot") {
        BrowserName::GoogleBot
    } else if ua.contains("qq/") || ua.contains("qqbrowser/") {
        BrowserName::QQ
    } else if ua.contains("opr/") || ua.contains("opios/") {
        BrowserName::Opera
    } else if ua.contains("silk/") {
        BrowserName::Silk
    } else if ua.contains("edg/")
        || ua.contains("edgios/")
        || ua.contains("edga/")
        || ua.contains("edge/")
        || ua.contains("iemobile/")
        || ua.contains("msie ")
    {
        BrowserName::IE
    } else if ua.contains("ucbrowser/") || ua.contains("ucweb/") {
        BrowserName::UCBrowser
    } else if ua.contains("nintendobrowser/") {
        BrowserName::Nintendo
    } else if ua.contains("samsungbrowser/") {
        BrowserName::Samsung
    } else if ua.contains("coc_coc_browser/") {
        BrowserName::CocCoc
    } else if ua.contains("yabrowser/") {
        BrowserName::Yandex
    } else if ua.contains("chrome/")
        || ua.contains("crios/")
        || ua.contains("chromium/")
        || ua.contains("crmo/")
    {
        // Edge, Silk and the other chrome-identifying browsers are all above this arm on purpose.
        BrowserName::Chrome
    } else if ua.contains("android")
        && !ua.contains("chrome/")
        && ua.contains("version/")
        && !ua.contains("like android")
    {
        BrowserName::Android
    } else if ua.contains("fxios") {
        BrowserName::Firefox
    } else if ua.contains(" spotify/") {
        BrowserName::Spotify
    } else if ua.contains("applebot") {
        BrowserName::AppleBot
    } else if ua.contains("like gecko")
        && ua.contains("mozilla/")
        && ua.contains("safari/")
        && !ua.contains("linux")
        && !ua.contains("android")
        && !ua.contains("browser/")
        && !ua.contains("os/")
        && !ua.contains("yabrowser/")
    {
        BrowserName::Safari
    } else if ua.contains("iphone") || ua.contains("ipad") {
        BrowserName::Safari
    } else if ua.contains(" gsa/") {
        BrowserName::Safari
    } else {
        return None;
    })
}

/// Port of `UserAgent.evalBrowserVersion` (browser.go:163).
///
/// The generic `version/#` probe runs first for every browser **except** Chrome — Go's comment
/// says Android vendors hijack that field — and returns immediately if it finds a number. Safari
/// has no version token of its own at all: it copies the *OS* version and adds one below major 4,
/// which is a rule from the iOS 3 era that still fires on the corpus.
fn eval_browser_version(dest: &mut UserAgent, ua: &str) {
    if dest.browser_name != BrowserName::Chrome
        && find_version_number(&mut dest.browser_version, ua, "version/")
    {
        return;
    }

    match dest.browser_name {
        BrowserName::Chrome => {
            let _ = find_version_number(&mut dest.browser_version, ua, "chrome/")
                || find_version_number(&mut dest.browser_version, ua, "crios/")
                || find_version_number(&mut dest.browser_version, ua, "crmo/");
        }
        BrowserName::Yandex => {
            find_version_number(&mut dest.browser_version, ua, "yabrowser/");
        }
        BrowserName::QQ => {
            if find_version_number(&mut dest.browser_version, ua, "qq/") {
                return;
            }
            find_version_number(&mut dest.browser_version, ua, "qqbrowser/");
        }
        BrowserName::IE => {
            if find_version_number(&mut dest.browser_version, ua, "msie ")
                || find_version_number(&mut dest.browser_version, ua, "edge/")
                || find_version_number(&mut dest.browser_version, ua, "edgios/")
                || find_version_number(&mut dest.browser_version, ua, "edga/")
                || find_version_number(&mut dest.browser_version, ua, "edg/")
            {
                return;
            }

            // Trident 3-7 map to MSIE 7-11 by adding four.
            if find_version_number(&mut dest.browser_version, ua, "trident/")
                && dest.browser_version.major >= 3
                && dest.browser_version.major <= 7
            {
                dest.browser_version.major += 4;
            }
        }
        BrowserName::Firefox => {
            let _ = find_version_number(&mut dest.browser_version, ua, "firefox/")
                || find_version_number(&mut dest.browser_version, ua, "fxios/");
        }
        BrowserName::Safari => {
            dest.browser_version = dest.os_version;
            if dest.browser_version.major <= 3 && dest.browser_version.major >= 1 {
                dest.browser_version.major += 1;
            }
        }
        BrowserName::UCBrowser => {
            find_version_number(&mut dest.browser_version, ua, "ucbrowser/");
        }
        BrowserName::Opera => {
            let _ = find_version_number(&mut dest.browser_version, ua, "opr/")
                || find_version_number(&mut dest.browser_version, ua, "opios/")
                || find_version_number(&mut dest.browser_version, ua, "opera/");
        }
        BrowserName::Silk => {
            find_version_number(&mut dest.browser_version, ua, "silk/");
        }
        BrowserName::Spotify => {
            find_version_number(&mut dest.browser_version, ua, "spotify/");
        }
        BrowserName::CocCoc => {
            find_version_number(&mut dest.browser_version, ua, "coc_coc_browser/");
        }
        _ => {}
    }
}

// ---------------------------------------------------------------------------------------------
// channels/app/user_agent.go — the Mattermost layer
// ---------------------------------------------------------------------------------------------

/// `maxUserAgentVersionLength` (user_agent.go:13). MM-55320: caps the version string a client can
/// make the server store.
const MAX_USER_AGENT_VERSION_LENGTH: usize = 128;

/// The three props `DoLogin` writes, as it writes them.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionUserAgentProps {
    /// `model.SessionPropPlatform`.
    pub platform: String,
    /// `model.SessionPropOs`. Genuinely `""` for anything uasurfer does not recognise, which
    /// includes every `curl` and every plain HTTP client.
    pub os: String,
    /// `model.SessionPropBrowser`, already joined as `fmt.Sprintf("%v/%v", name, version)`. It is
    /// one prop in Go, not two, so it is one field here.
    pub browser: String,
}

/// Everything `DoLogin` derives from one `User-Agent` header (app/login.go:183-193).
#[must_use]
pub fn session_props(raw_user_agent: &str) -> SessionUserAgentProps {
    let ua = parse(raw_user_agent);
    SessionUserAgentProps {
        platform: platform_name(&ua, raw_user_agent).to_owned(),
        os: os_name(&ua, raw_user_agent).to_owned(),
        browser: format!(
            "{}/{}",
            browser_name(&ua, raw_user_agent),
            browser_version(&ua, raw_user_agent)
        ),
    }
}

/// Port of `getPlatformName` (user_agent.go:27).
///
/// The `Mattermost Mobile/` fallback fires only when uasurfer found **nothing**, and its last arm
/// is `Linux` — so a mobile agent with no recognisable platform is reported as Linux/Android, not
/// as unknown. Note the substring test is against the **raw** header, not the lowercased one, so
/// the capitalisation of `Mattermost Mobile/`, `iPhone` and `iPad` is significant.
fn platform_name(ua: &UserAgent, raw: &str) -> &'static str {
    let mut platform = ua.platform;

    if platform == Platform::Unknown && raw.contains("Mattermost Mobile/") {
        platform = if raw.contains("iPhone") {
            Platform::IPhone
        } else if raw.contains("iPad") {
            Platform::IPad
        } else {
            Platform::Linux
        };
    }

    match platform {
        Platform::Unknown => "Unknown",
        Platform::Windows => "Windows",
        Platform::Mac => "Macintosh",
        Platform::Linux => "Linux",
        Platform::IPad => "iPad",
        Platform::IPhone => "iPhone",
        Platform::IPod => "iPod",
        Platform::Blackberry => "BlackBerry",
        Platform::WindowsPhone => "Windows Phone",
        // `platformNames` has no entry for Playstation, Xbox, Nintendo or Bot, so Go's
        // `name, ok := platformNames[platform]; if !ok` returns the Unknown entry for all four.
        Platform::Playstation | Platform::Xbox | Platform::Nintendo | Platform::Bot => "Unknown",
    }
}

/// Port of `getOSName` (user_agent.go:61).
///
/// # Windows is a table of marketing names and the table has holes
///
/// NT 5.0/5.1/5.2/6.0/6.1/6.2/6.3 and major 10 have names; **NT 6.4 and NT 11 do not** and fall
/// to a bare `"Windows"`. The `major == 10` arm ignores the minor entirely, so NT 10.1 is also
/// "Windows 10". A port that mapped NT versions arithmetically would get all three wrong.
fn os_name(ua: &UserAgent, raw: &str) -> &'static str {
    if ua.os_name == OsName::Windows {
        let (major, minor) = (ua.os_version.major, ua.os_version.minor);
        return match (major, minor) {
            (5, 0) => "Windows 2000",
            (5, 1) => "Windows XP",
            (5, 2) => "Windows XP x64 Edition",
            (6, 0) => "Windows Vista",
            (6, 1) => "Windows 7",
            (6, 2) => "Windows 8",
            (6, 3) => "Windows 8.1",
            (10, _) => "Windows 10",
            _ => "Windows",
        };
    }

    let mut name = ua.os_name;
    if name == OsName::Unknown && raw.contains("Mattermost Mobile/") {
        // Both iPhone and iPad map to iOS here; only the *platform* tells them apart.
        name = if raw.contains("iPhone") || raw.contains("iPad") {
            OsName::IOS
        } else {
            OsName::Android
        };
    }

    match name {
        OsName::Unknown => "",
        OsName::WindowsPhone => "Windows Phone",
        // Unreachable: the `Windows` arm returned above. Kept so the match is exhaustive over the
        // enum rather than over a reading of the control flow.
        OsName::Windows => "Windows",
        OsName::MacOSX => "Mac OS",
        OsName::IOS => "iOS",
        OsName::Android => "Android",
        OsName::Blackberry => "BlackBerry",
        OsName::ChromeOS => "Chrome OS",
        OsName::Kindle => "Kindle",
        OsName::WebOS => "webOS",
        OsName::Linux => "Linux",
        // `osNames` has no entry for these four, so Go returns the `OSUnknown` entry — `""`.
        OsName::Playstation | OsName::Xbox | OsName::Nintendo | OsName::Bot => "",
    }
}

/// Port of `getBrowserName` (user_agent.go:169).
///
/// # Three substring checks run before uasurfer's answer is consulted at all
///
/// `Electron` **or** `Mattermost`-but-not-`Mattermost Mobile` is "Desktop App";
/// `Mattermost Mobile` is "Mobile App"; `mmctl` is "mmctl". All three are on the **raw** header.
/// The first is why the Mattermost desktop client — which is Chrome — never reports as Chrome.
fn browser_name(ua: &UserAgent, raw: &str) -> &'static str {
    if raw.contains("Electron")
        || (raw.contains("Mattermost") && !raw.contains("Mattermost Mobile"))
    {
        return "Desktop App";
    }
    if raw.contains("Mattermost Mobile") {
        return "Mobile App";
    }
    if raw.contains("mmctl") {
        return "mmctl";
    }

    if ua.browser_name == BrowserName::IE && ua.browser_version.major > 11 {
        return "Edge";
    }

    match ua.browser_name {
        BrowserName::Chrome => "Chrome",
        BrowserName::IE => "Internet Explorer",
        BrowserName::Safari => "Safari",
        BrowserName::Firefox => "Firefox",
        BrowserName::Android => "Android",
        BrowserName::Opera => "Opera",
        BrowserName::Blackberry => "BlackBerry",
        // Everything else — including every bot and every browser uasurfer names but Mattermost
        // does not — has no entry in `browserNames`, so Go falls back to the Unknown entry.
        _ => "Unknown",
    }
}

/// Port of `getBrowserVersion` (user_agent.go:134) over `versionPrefixes` (user_agent.go:127).
///
/// The four prefixes are tried **in order** against the raw header and the first hit wins, taking
/// the whitespace-delimited field that follows it. So a desktop agent reading
/// `Mattermost/5.10.0 Chrome/126…` reports `5.10.0` and never reaches uasurfer. A prefix with
/// nothing after it (`"Mattermost/"`) has no fields and falls through to the next prefix, and
/// then to uasurfer.
fn browser_version(ua: &UserAgent, raw: &str) -> String {
    for prefix in ["Mattermost Mobile/", "Mattermost/", "mmctl/", "Franz/"] {
        if let Some((_, after)) = raw.split_once(prefix)
            && let Some(field) = after.split_ascii_whitespace().next()
        {
            return limit_string_length(field, MAX_USER_AGENT_VERSION_LENGTH).to_owned();
        }
    }
    ua_version(ua.browser_version)
}

/// Port of `limitStringLength` (user_agent.go:146). Counted in **bytes**, and the truncation is a
/// raw slice — so a multi-byte character straddling the limit would be cut in half. Rust cannot
/// slice a `str` there, so the cut falls back to the last character boundary at or below the
/// limit; the only way to reach it is a version field of more than 128 bytes containing non-ASCII,
/// which no client sends and which Go would answer with invalid UTF-8 anyway.
fn limit_string_length(field: &str, limit: usize) -> &str {
    if field.len() <= limit {
        return field;
    }
    let mut end = limit;
    while end > 0 && !field.is_char_boundary(end) {
        end -= 1;
    }
    &field[..end]
}

/// Port of `getUAVersion` (user_agent.go:151). **Two components when the patch is zero**, three
/// otherwise — so `127.0.0.0` renders as `127.0` and `49.0.2623.112` as `49.0.2623`.
fn ua_version(version: Version) -> String {
    let mut out = String::new();
    if version.patch == 0 {
        let _ = write!(out, "{}.{}", version.major, version.minor);
    } else {
        let _ = write!(out, "{}.{}.{}", version.major, version.minor, version.patch);
    }
    out
}

/// Port of `utils.IsMobileRequest` (channels/utils/utils.go:232).
///
/// Five case-sensitive substrings on the raw header and nothing else — no parsing, and no
/// agreement with [`parse`]. `DoLogin` uses it to choose between `SessionLengthMobileInHours` and
/// `SessionLengthWebInHours`, so a desktop browser whose UA happens to say "Mobile" gets the
/// mobile session length. That is Go's rule; it is also why an explicit `device_id` overrides it
/// (app/login.go:155).
#[must_use]
pub fn is_mobile_request(raw_user_agent: &str) -> bool {
    if raw_user_agent.is_empty() {
        return false;
    }
    ["Mobile", "Android", "iOS", "iPhone", "iPad"]
        .iter()
        .any(|keyword| raw_user_agent.contains(keyword))
}

#[cfg(test)]
mod go_parity {
    use super::*;

    const CORPUS: &str = include_str!("../../../fixtures/behaviour_user_agent.json");

    fn version_of(value: &serde_json::Value) -> Version {
        let parts = value.as_array().expect("a three-element version");
        Version {
            major: parts[0].as_i64().expect("major"),
            minor: parts[1].as_i64().expect("minor"),
            patch: parts[2].as_i64().expect("patch"),
        }
    }

    fn platform_of(name: &str) -> Platform {
        match name {
            "Unknown" => Platform::Unknown,
            "Windows" => Platform::Windows,
            "Mac" => Platform::Mac,
            "Linux" => Platform::Linux,
            "iPad" => Platform::IPad,
            "iPhone" => Platform::IPhone,
            "iPod" => Platform::IPod,
            "Blackberry" => Platform::Blackberry,
            "WindowsPhone" => Platform::WindowsPhone,
            "Playstation" => Platform::Playstation,
            "Xbox" => Platform::Xbox,
            "Nintendo" => Platform::Nintendo,
            "Bot" => Platform::Bot,
            other => panic!("unmodelled platform {other}"),
        }
    }

    fn os_of(name: &str) -> OsName {
        match name {
            "Unknown" => OsName::Unknown,
            "WindowsPhone" => OsName::WindowsPhone,
            "Windows" => OsName::Windows,
            "MacOSX" => OsName::MacOSX,
            "iOS" => OsName::IOS,
            "Android" => OsName::Android,
            "Blackberry" => OsName::Blackberry,
            "ChromeOS" => OsName::ChromeOS,
            "Kindle" => OsName::Kindle,
            "WebOS" => OsName::WebOS,
            "Linux" => OsName::Linux,
            "Playstation" => OsName::Playstation,
            "Xbox" => OsName::Xbox,
            "Nintendo" => OsName::Nintendo,
            "Bot" => OsName::Bot,
            other => panic!("unmodelled os {other}"),
        }
    }

    fn browser_of(name: &str) -> BrowserName {
        match name {
            "Unknown" => BrowserName::Unknown,
            "Chrome" => BrowserName::Chrome,
            "IE" => BrowserName::IE,
            "Safari" => BrowserName::Safari,
            "Firefox" => BrowserName::Firefox,
            "Android" => BrowserName::Android,
            "Opera" => BrowserName::Opera,
            "Blackberry" => BrowserName::Blackberry,
            "UCBrowser" => BrowserName::UCBrowser,
            "Silk" => BrowserName::Silk,
            "Nokia" => BrowserName::Nokia,
            "NetFront" => BrowserName::NetFront,
            "QQ" => BrowserName::QQ,
            "Maxthon" => BrowserName::Maxthon,
            "SogouExplorer" => BrowserName::SogouExplorer,
            "Spotify" => BrowserName::Spotify,
            "Nintendo" => BrowserName::Nintendo,
            "Samsung" => BrowserName::Samsung,
            "Yandex" => BrowserName::Yandex,
            "CocCoc" => BrowserName::CocCoc,
            "Bot" => BrowserName::Bot,
            "AppleBot" => BrowserName::AppleBot,
            "BaiduBot" => BrowserName::BaiduBot,
            "BingBot" => BrowserName::BingBot,
            "DuckDuckGoBot" => BrowserName::DuckDuckGoBot,
            "FacebookBot" => BrowserName::FacebookBot,
            "GoogleBot" => BrowserName::GoogleBot,
            "LinkedInBot" => BrowserName::LinkedInBot,
            "MsnBot" => BrowserName::MsnBot,
            "PingdomBot" => BrowserName::PingdomBot,
            "TwitterBot" => BrowserName::TwitterBot,
            "YandexBot" => BrowserName::YandexBot,
            "CocCocBot" => BrowserName::CocCocBot,
            "YahooBot" => BrowserName::YahooBot,
            other => panic!("unmodelled browser {other}"),
        }
    }

    /// Every row of the corpus, parser fields **and** derived props.
    ///
    /// Asserting the raw uasurfer fields separately from the props is the point: the props
    /// collapse several parser states onto the same string (every unrecognised OS is `""`), so a
    /// parser that got the enum wrong could still produce the right prop on most of the corpus.
    #[test]
    fn every_corpus_agent_parses_as_go_parses_it() {
        let corpus: serde_json::Value = serde_json::from_str(CORPUS).expect("the fixture is JSON");
        let rows = corpus["user_agent"].as_array().expect("an array of cases");
        assert!(rows.len() >= 40, "the corpus lost rows: {}", rows.len());

        for row in rows {
            let raw = row["user_agent"].as_str().expect("a user agent");
            let parsed = parse(raw);

            assert_eq!(
                parsed.platform,
                platform_of(row["platform_enum"].as_str().expect("a platform")),
                "platform for {raw:?}"
            );
            assert_eq!(
                parsed.os_name,
                os_of(row["os_name_enum"].as_str().expect("an os")),
                "os for {raw:?}"
            );
            assert_eq!(
                parsed.os_version,
                version_of(&row["os_version"]),
                "os version for {raw:?}"
            );
            assert_eq!(
                parsed.browser_name,
                browser_of(row["browser_name_enum"].as_str().expect("a browser")),
                "browser for {raw:?}"
            );
            assert_eq!(
                parsed.browser_version,
                version_of(&row["browser_version"]),
                "browser version for {raw:?}"
            );

            let props = session_props(raw);
            assert_eq!(
                props.platform,
                row["prop_platform"].as_str().expect("a platform prop"),
                "platform prop for {raw:?}"
            );
            assert_eq!(
                props.os,
                row["prop_os"].as_str().expect("an os prop"),
                "os prop for {raw:?}"
            );
            assert_eq!(
                props.browser,
                row["prop_browser"].as_str().expect("a browser prop"),
                "browser prop for {raw:?}"
            );

            assert_eq!(
                is_mobile_request(raw),
                row["is_mobile_request"].as_bool().expect("a mobile flag"),
                "IsMobileRequest for {raw:?}"
            );
        }
    }

    /// The corpus is not vacuous: it separates the values a port could confuse.
    ///
    /// A fixture in which every row answered `Unknown`/`""`/`Unknown/0.0` would pass the test
    /// above against a `parse` that did nothing at all. This asserts the corpus actually spans
    /// the answers.
    #[test]
    fn the_corpus_discriminates() {
        let corpus: serde_json::Value = serde_json::from_str(CORPUS).expect("the fixture is JSON");
        let rows = corpus["user_agent"].as_array().expect("an array of cases");

        let platforms: std::collections::BTreeSet<&str> = rows
            .iter()
            .filter_map(|r| r["prop_platform"].as_str())
            .collect();
        let oses: std::collections::BTreeSet<&str> =
            rows.iter().filter_map(|r| r["prop_os"].as_str()).collect();
        let browsers: std::collections::BTreeSet<&str> = rows
            .iter()
            .filter_map(|r| r["prop_browser"].as_str())
            .collect();

        assert!(
            platforms.len() >= 5,
            "only {} distinct platforms: {platforms:?}",
            platforms.len()
        );
        assert!(
            oses.len() >= 9,
            "only {} distinct os names: {oses:?}",
            oses.len()
        );
        assert!(
            browsers.len() >= 12,
            "only {} distinct browser strings: {browsers:?}",
            browsers.len()
        );
        assert!(
            rows.iter().any(|r| r["is_mobile_request"] == true)
                && rows.iter().any(|r| r["is_mobile_request"] == false),
            "IsMobileRequest never differs across the corpus"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `Version.parse`'s leading-zero rule, which is the single least guessable thing in this
    /// file. Transcribed from system.go:272 rather than from a fixture because it is a unit the
    /// corpus only reaches through whole agents.
    #[test]
    fn version_parse_reproduces_gos_digit_walk() {
        let cases: &[(&str, bool, Version)] = &[
            // Refused outright: the first byte must be a digit.
            ("", false, Version::default()),
            ("a1.2.3", false, Version::default()),
            (".1", false, Version::default()),
            // The ordinary shape.
            (
                "1.2.3",
                true,
                Version {
                    major: 1,
                    minor: 2,
                    patch: 3,
                },
            ),
            // Underscores separate exactly as dots do — any non-digit ends the number.
            (
                "10_15_7",
                true,
                Version {
                    major: 10,
                    minor: 15,
                    patch: 7,
                },
            ),
            // Running out of string leaves the later components at zero.
            (
                "127",
                true,
                Version {
                    major: 127,
                    minor: 0,
                    patch: 0,
                },
            ),
            // A leading zero followed by a non-zero digit ends the pass with the value still 0
            // and restarts the next pass **at** that digit — so "01" is 0 then 1, not 1.
            (
                "01",
                true,
                Version {
                    major: 0,
                    minor: 1,
                    patch: 0,
                },
            ),
            // Repeated zeroes are skipped within the pass, but the first *non*-zero still ends
            // it — so "007" is a major of 0 and a minor of 7, not a major of 7. Confirmed by
            // the oracle: the corpus carries `… Mac OS X 007)`.
            (
                "007",
                true,
                Version {
                    major: 0,
                    minor: 7,
                    patch: 0,
                },
            ),
            // Four components: the fourth is simply never read.
            (
                "127.0.6533.107",
                true,
                Version {
                    major: 127,
                    minor: 0,
                    patch: 6533,
                },
            ),
            // Trailing junk after the third number is ignored.
            (
                "17.5 Mobile/15E148",
                true,
                Version {
                    major: 17,
                    minor: 5,
                    patch: 0,
                },
            ),
        ];

        for (input, ok, want) in cases {
            let mut got = Version::default();
            assert_eq!(parse_version(&mut got, input), *ok, "return for {input:?}");
            assert_eq!(got, *want, "value for {input:?}");
        }
    }

    /// The version *formatter* drops the patch only when it is zero, which is why two clients on
    /// the same Chrome line report different-looking versions.
    #[test]
    fn the_version_formatter_is_two_or_three_components() {
        assert_eq!(
            ua_version(Version {
                major: 127,
                minor: 0,
                patch: 0
            }),
            "127.0"
        );
        assert_eq!(
            ua_version(Version {
                major: 49,
                minor: 0,
                patch: 2623
            }),
            "49.0.2623"
        );
        assert_eq!(ua_version(Version::default()), "0.0");
    }

    /// The four `versionPrefixes` are tried in order and the *first* that has a field after it
    /// wins — so a desktop agent that names both `Mattermost/` and `Chrome/` reports the former,
    /// and `"Mattermost/"` with nothing after it falls through.
    #[test]
    fn the_version_prefixes_are_ordered_and_may_fall_through() {
        let desktop = "Mattermost/5.10.0 Chrome/126.0.6478.127 Electron/31.2.0";
        assert_eq!(browser_version(&parse(desktop), desktop), "5.10.0");

        // Mobile is tried before the desktop prefix, and "Mattermost Mobile/" contains
        // "Mattermost" — so an agent carrying both reports the mobile version.
        let both = "Mattermost Mobile/2.19.0 Mattermost/5.10.0";
        assert_eq!(browser_version(&parse(both), both), "2.19.0");

        // Nothing after the prefix: no fields, so the loop continues and uasurfer answers.
        let empty = "Mattermost/";
        assert_eq!(browser_version(&parse(empty), empty), "0.0");
    }

    /// Version fields are capped at 128 **bytes**, so a client cannot make the server store an
    /// unbounded string in `Sessions.Props` (MM-55320).
    #[test]
    fn a_long_version_field_is_truncated_at_128_bytes() {
        let long = format!("mmctl/{}", "9".repeat(500));
        assert_eq!(browser_version(&parse(&long), &long).len(), 128);
    }

    /// `getBrowserName`'s first three checks run on the **raw** header, before uasurfer's answer
    /// is consulted — so the desktop client, which is Chromium, never reports as Chrome.
    #[test]
    fn the_mattermost_clients_shadow_the_real_browser() {
        let desktop = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 \
                       (KHTML, like Gecko) Mattermost/5.10.0 Chrome/126.0.6478.127 \
                       Electron/31.2.0 Safari/537.36";
        assert_eq!(parse(desktop).browser_name, BrowserName::Chrome);
        assert_eq!(browser_name(&parse(desktop), desktop), "Desktop App");

        let mobile = "Mattermost Mobile/2.19.0 (Linux; Android 14)";
        assert_eq!(browser_name(&parse(mobile), mobile), "Mobile App");

        let cli = "mmctl/10.5.0";
        assert_eq!(browser_name(&parse(cli), cli), "mmctl");
    }

    /// `IsMobileRequest` is a case-sensitive substring scan on the raw header and agrees with
    /// nothing else here. Both halves matter: it is what chooses the session length.
    #[test]
    fn is_mobile_request_is_five_case_sensitive_substrings() {
        assert!(!is_mobile_request(""));
        assert!(!is_mobile_request("curl/8.5.0"));
        assert!(!is_mobile_request("mobile"), "lowercase does not match");
        assert!(!is_mobile_request("android"));
        assert!(is_mobile_request("Mobile"));
        assert!(is_mobile_request("Android"));
        assert!(is_mobile_request("iOS"));
        assert!(is_mobile_request("iPhone"));
        assert!(is_mobile_request("iPad"));
        // A desktop browser whose UA happens to carry "Mobile" is treated as mobile.
        assert!(is_mobile_request(
            "Mozilla/5.0 (Linux; Android 14) Chrome/127.0.0.0 Mobile Safari/537.36"
        ));
    }

    /// The Amazon Fire fingerprint, which is the one regular expression in uasurfer. Both
    /// alternatives, the length bounds on the first, and the requirement that the match be
    /// **surrounded** by whitespace.
    #[test]
    fn the_amazon_fire_fingerprint_matches_what_the_regex_matches() {
        assert!(amazon_fire_fingerprint(" kftt "));
        assert!(amazon_fire_fingerprint("x kfabcd y"));
        assert!(amazon_fire_fingerprint(
            "linux; u; android 4.0.3; en-us; kftt build/iml74k"
        ));
        assert!(amazon_fire_fingerprint(" sd4930ur "));
        // Three to five letters after the k, no more and no fewer.
        assert!(!amazon_fire_fingerprint(" kf "));
        assert!(!amazon_fire_fingerprint(" kabcdef "));
        // Both ends need whitespace.
        assert!(!amazon_fire_fingerprint("kftt "));
        assert!(!amazon_fire_fingerprint(" kftt"));
        // Digits are not `[a-z]`.
        assert!(!amazon_fire_fingerprint(" k123 "));
        // `sd\d{4}ur` needs exactly four digits.
        assert!(!amazon_fire_fingerprint(" sd493ur "));
        assert!(!amazon_fire_fingerprint(" sd49300ur "));
    }
}
