//! Port of `server/public/shared/markdown` — Mattermost's hand-written CommonMark subset, "not a
//! full implementation" by its own description, and deliberately **not** replaced by a general
//! CommonMark crate: the server's mention engine (`app/notification.go:1437`,
//! `getExplicitMentions`), the `mmaction://` id scan ([D-044]) and the link-metadata scan
//! (`app/post_metadata.go:777`) walk this parser's tree, so what it does and does not recognise
//! is wire behaviour. Every quirk of the Go package is reproduced and pinned by
//! `fixtures/behaviour_markdown.json` (558 inputs, generated by
//! `reference/dump/behaviour_markdown.go`); see `go_parity` at the bottom of this file.
//!
//! What the server calls: [`inspect`] and [`set_max_post_runes`]. Everything else is here
//! because the parity oracle needs it ([`render_html`] is Go's own test renderer) or because
//! the Go API exports it.
//!
//! **Not** in this subset, and therefore plain text: emphasis, headings, thematic breaks, HTML
//! blocks and inline HTML, `<...>` autolinks, and tables. What *is* recognised: paragraphs with
//! soft and hard breaks, backslash escapes, code spans, fenced and indented code, block quotes,
//! bullet and ordered lists, inline and reference links and images (with a non-standard
//! `=WxH` image dimension suffix), `[label]: dest "title"` definitions, `scheme://` and `www.`
//! autolinks, HTML character references, and `:emoji:`.
//!
//! Licence: Apache-2.0, like `mm-model` — this crate derives only from `server/public/`.

pub mod autolink;
pub mod blocks;
pub mod emoji;
pub mod go_unicode_generated;
pub mod html;
pub mod html_entities;
pub mod inlines;
pub mod inspect;
pub mod lines;
pub mod links;
pub mod markdown;
pub mod reference_definition;
pub mod unicode;

pub use blocks::{
    Block, BlockQuote, Document, FencedCode, FencedCodeLine, IndentedCode, IndentedCodeLine, List,
    ListItem, MAX_NESTING_DEPTH, Paragraph, parse_blocks,
};
pub use html::{render_block_html, render_html, render_inline_html};
pub use inlines::{
    Autolink, CodeSpan, Emoji, Inline, InlineLinkOrImage, ReferenceLinkOrImage, Text,
    character_reference, merge_inline_text, parse_inlines, unescape,
};
pub use inspect::{
    DEFAULT_MAX_POST_RUNES, Node, inspect, inspect_block, inspect_inline, max_len,
    set_max_post_runes,
};
pub use lines::parse_lines;
pub use markdown::Range;
pub use reference_definition::ReferenceDefinition;

/// The `[]*ReferenceDefinition` half of `Parse`'s result: every definition in the document, in
/// the order the paragraphs holding them were closed. Lookups take the first match.
pub type ReferenceDefinitions<'a> = Vec<ReferenceDefinition<'a>>;

/// Port of `markdown.Parse` (markdown.go:154). An input longer than [`max_len`] bytes parses to
/// an empty document with no definitions; nothing is truncated.
pub fn parse(markdown: &str) -> (Document<'_>, ReferenceDefinitions<'_>) {
    if markdown.len() > max_len() {
        return (Document::default(), Vec::new());
    }
    blocks::parse_unchecked(markdown)
}

#[cfg(test)]
mod go_parity;
