//! Parity against goldmark itself: `fixtures/behaviour_goldmark.json`, generated by
//! `reference/dump/behaviour_goldmark.go` (`go run . -only goldmark`). Every case is converted
//! under six configurations and parsed under GFM, and each result must equal Go's byte for byte.
//!
//! Failures are collected rather than stopping at the first, so one run shows the extent of a
//! divergence.

use gogoldmark::ast::{Ast, AutoLinkType, NodeData, NodeId, NodeType};
use gogoldmark::{Extension, Markdown, convert};
use serde_json::{Value, json};

fn fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/behaviour_goldmark.json"
    );
    let blob = std::fs::read_to_string(path).expect("fixture present");
    serde_json::from_str(&blob).expect("fixture parses")
}

/// Go's `encoding/json` string coercion: every byte of an invalid sequence becomes U+FFFD.
fn go_string(b: &[u8]) -> String {
    let mut out = String::new();
    let mut rest = b;
    loop {
        match std::str::from_utf8(rest) {
            Ok(s) => {
                out.push_str(s);
                return out;
            }
            Err(e) => {
                let (ok, bad) = rest.split_at(e.valid_up_to());
                out.push_str(std::str::from_utf8(ok).unwrap());
                let n = e.error_len().unwrap_or(bad.len());
                for _ in 0..n {
                    out.push('\u{FFFD}');
                }
                rest = &bad[n..];
            }
        }
    }
}

/// The AST as `goldmarkASTNode` (behaviour_goldmark.go) serialises it: pre-order, with depth.
fn ast_json(ast: &Ast, root: NodeId, src: &[u8]) -> Value {
    let mut out = Vec::new();
    let mut stack = vec![(root, 0usize)];
    while let Some((n, depth)) = stack.pop() {
        out.push(node_json(ast, n, depth, src));
        let children = ast.children(n);
        for &c in children.iter().rev() {
            stack.push((c, depth + 1));
        }
    }
    Value::Array(out)
}

fn node_json(ast: &Ast, n: NodeId, depth: usize, src: &[u8]) -> Value {
    let mut m = serde_json::Map::new();
    m.insert("kind".into(), json!(ast.kind(n).name()));
    m.insert("depth".into(), json!(depth));
    if ast.node_type(n) == NodeType::Block {
        let lines: Vec<Value> = ast
            .lines(n)
            .as_slice()
            .iter()
            .map(|s| json!(go_string(&s.value(src))))
            .collect();
        m.insert("lines".into(), Value::Array(lines));
        m.insert(
            "blank_previous_lines".into(),
            json!(ast.has_blank_previous_lines(n)),
        );
    }
    m.insert("raw".into(), json!(ast.is_raw(n)));
    match ast.data(n) {
        NodeData::Heading { level } => {
            m.insert("level".into(), json!(level));
        }
        NodeData::List {
            marker,
            is_tight,
            start,
        } => {
            m.insert("marker".into(), json!((*marker as char).to_string()));
            m.insert("tight".into(), json!(is_tight));
            m.insert("start".into(), json!(start));
        }
        NodeData::ListItem { offset } => {
            m.insert("offset".into(), json!(offset));
        }
        NodeData::FencedCodeBlock { info } => {
            if let Some(i) = info {
                m.insert("info".into(), json!(go_string(&i.value(src))));
            }
            let lang =
                gogoldmark::html::fenced_code_block_language(ast, n, src).unwrap_or_default();
            m.insert("language".into(), json!(go_string(&lang)));
        }
        NodeData::HTMLBlock { typ, closure_line } => {
            m.insert("html_type".into(), json!(typ));
            if closure_line.start >= 0 {
                m.insert("closure".into(), json!(go_string(&closure_line.value(src))));
            }
        }
        NodeData::LinkReferenceDefinition {
            label,
            destination,
            title,
        } => {
            m.insert("label".into(), json!(go_string(label)));
            m.insert("destination".into(), json!(go_string(destination)));
            if let Some(t) = title {
                m.insert("title".into(), json!(go_string(t)));
            }
        }
        NodeData::Text { segment, .. } => {
            m.insert("value".into(), json!(go_string(&segment.value(src))));
            m.insert("soft_line_break".into(), json!(ast.soft_line_break(n)));
            m.insert("hard_line_break".into(), json!(ast.hard_line_break(n)));
        }
        NodeData::String { value, .. } => {
            m.insert("value".into(), json!(go_string(value)));
            m.insert("code".into(), json!(ast.is_code(n)));
        }
        NodeData::Emphasis { level } => {
            m.insert("level".into(), json!(level));
        }
        NodeData::Link {
            destination, title, ..
        }
        | NodeData::Image {
            destination, title, ..
        } => {
            m.insert("destination".into(), json!(go_string(destination)));
            if let Some(t) = title {
                m.insert("title".into(), json!(go_string(t)));
            }
        }
        NodeData::AutoLink { typ, value, .. } => {
            let t = match typ {
                AutoLinkType::Email => 1,
                AutoLinkType::Url => 2,
            };
            m.insert("autolink_type".into(), json!(t));
            let url = gogoldmark::html::auto_link_url(ast, n, src);
            m.insert("url".into(), json!(go_string(&url)));
            m.insert("label".into(), json!(go_string(&value.value(src))));
        }
        NodeData::RawHTML { segments } => {
            let segs: Vec<Value> = segments
                .as_slice()
                .iter()
                .map(|s| json!(go_string(&s.value(src))))
                .collect();
            m.insert("segments".into(), Value::Array(segs));
        }
        NodeData::TableCell { alignment } => {
            m.insert("alignment".into(), json!(alignment.as_str()));
        }
        NodeData::Table { alignments } => {
            let al: Vec<&str> = alignments.iter().map(|a| a.as_str()).collect();
            m.insert("alignments".into(), json!(al));
        }
        NodeData::TaskCheckBox { checked } => {
            m.insert("checked".into(), json!(checked));
        }
        _ => {}
    }
    Value::Object(m)
}

const CONFIGS: [(&str, &[Extension]); 6] = [
    ("html", &[]),
    ("strikethrough", &[Extension::Strikethrough]),
    ("table", &[Extension::Table]),
    ("linkify", &[Extension::Linkify]),
    ("tasklist", &[Extension::TaskList]),
    ("gfm", &[Extension::Gfm]),
];

/// A configuration's expected HTML: the fixture omits a column that equals `html`.
fn expected<'a>(c: &'a Value, key: &str) -> &'a str {
    c.get(key)
        .and_then(Value::as_str)
        .unwrap_or_else(|| c["html"].as_str().unwrap())
}

fn report(failures: &[String], total: usize) {
    if !failures.is_empty() {
        let shown: Vec<&String> = failures.iter().take(25).collect();
        panic!(
            "{} of {} checks diverge from goldmark; first {}:\n{}",
            failures.len(),
            total,
            shown.len(),
            shown
                .iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join("\n---\n")
        );
    }
}

#[test]
fn fixture_is_populated() {
    let f = fixture();
    assert_eq!(f["goldmark_version"], "v1.8.2");
    let cases = f["cases"].as_array().unwrap();
    // 652 spec examples, the shipped extension/extra cases, the chat corpus and 3000 fuzz inputs.
    assert!(cases.len() > 3800, "{}", cases.len());
    for prefix in [
        "spec-",
        "linkify-",
        "table-",
        "strikethrough-",
        "tasklist-",
        "chat-",
        "fuzz-",
        "linkfuzz-",
        "linefuzz-",
        "charfuzz-",
    ] {
        assert!(
            cases
                .iter()
                .any(|c| c["id"].as_str().unwrap().starts_with(prefix)),
            "{prefix}"
        );
    }
    // Each configuration must differ from plain CommonMark somewhere, or its column proves
    // nothing about the extension.
    for (key, _) in &CONFIGS[1..] {
        assert!(
            cases.iter().any(|c| expected(c, key) != c["html"]),
            "{key} never differs from html"
        );
    }
    assert!(cases.iter().filter(|c| c.get("ast").is_some()).count() > 5000);
}

#[test]
fn html_matches_goldmark() {
    let f = fixture();
    let cases = f["cases"].as_array().unwrap();
    let mut failures = Vec::new();
    let mut total = 0;
    for c in cases {
        let input = c["input"].as_str().unwrap();
        for (key, exts) in CONFIGS {
            total += 1;
            let got = convert(input, exts);
            let want = expected(c, key);
            if got != want {
                failures.push(format!(
                    "{} [{}]\ninput: {:?}\nwant:  {:?}\ngot:   {:?}",
                    c["id"], key, input, want, got
                ));
            }
        }
    }
    report(&failures, total);
}

#[test]
fn ast_matches_goldmark() {
    let f = fixture();
    let cases = f["cases"].as_array().unwrap();
    let md = Markdown::new(&[Extension::Gfm]);
    let mut failures = Vec::new();
    for c in cases {
        if c.get("ast").is_none() {
            continue;
        }
        let input = c["input"].as_str().unwrap();
        let ast = md.parser().parse(input.as_bytes());
        let got = ast_json(&ast, ast.root(), input.as_bytes());
        if got != c["ast"] {
            failures.push(format!(
                "{}\ninput: {:?}\nwant: {}\ngot:  {}",
                c["id"], input, c["ast"], got
            ));
        }
    }
    report(&failures, cases.len());
}

/// Inputs Mattermost's 16,383-character message limit allows that stress nesting depth and
/// goldmark's delimiter and bracket bookkeeping. No oracle: the check is that each finishes (the
/// walk, the block closer and the renderer are iterative here where goldmark recurses) and
/// produces output.
#[test]
fn pathological_inputs_terminate() {
    let n = 4000;
    let inputs = [
        "> ".repeat(n / 2) + "x",
        "- ".repeat(n / 2) + "x",
        "*a ".repeat(n / 6) + &"b* ".repeat(n / 6),
        "[".repeat(n / 2) + &"]".repeat(n / 2),
        "[a](".repeat(n / 4),
        "`a``".repeat(n / 4),
        "_a_".repeat(n / 3),
        "~~a".repeat(n / 3),
        "![".repeat(n / 2),
        "|a".repeat(n / 2) + "\n" + &"|-".repeat(n / 2),
    ];
    for input in &inputs {
        assert!(!convert(input, &[Extension::Gfm]).is_empty());
    }
}
