// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.

//! The database driver, which a plugin uses to reach the server's own connection (db_rpc.go). Every error crosses as `encodableError` made it, and comes back through `decodableError`.

#![allow(clippy::too_many_lines)]

use std::future::Future;
use std::sync::Arc;

use go_netrpc::{Server, ServiceError};

use super::{DriverClient, NotImplemented};

/// The database a plugin queries through the host. A host implements it over its own
/// connection pool; nothing here opens one.
pub trait Driver: Send + Sync + 'static {
    /// Go: `Conn(isMaster bool) (string, error)`
    ///
    /// ```text
    /// Connection
    /// ```
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn conn(
        &self,
        args: bool,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbStrErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `ConnClose(connID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn conn_close(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `ConnExec(connID string, q string, args []driver.NamedValue) (plugin.ResultContainer, error)`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn conn_exec(
        &self,
        args: super::super::wire::plugin::Z_DbConnArgs,
    ) -> impl Future<
        Output = Result<super::super::wire::plugin::Z_DbResultContErrReturn, NotImplemented>,
    > + Send {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `ConnPing(connID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn conn_ping(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `ConnQuery(connID string, q string, args []driver.NamedValue) (string, error)`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn conn_query(
        &self,
        args: super::super::wire::plugin::Z_DbConnArgs,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbStrErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsClose(rowsID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_close(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsColumnTypeDatabaseTypeName(rowsID string, index int) string`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_column_type_database_type_name(
        &self,
        args: super::super::wire::plugin::Z_DbRowsColumnArg,
    ) -> impl Future<Output = Result<::std::string::String, NotImplemented>> + Send {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsColumnTypePrecisionScale(rowsID string, index int) (int64, int64, bool)`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_column_type_precision_scale(
        &self,
        args: super::super::wire::plugin::Z_DbRowsColumnArg,
    ) -> impl Future<
        Output = Result<
            super::super::wire::plugin::Z_DbRowsColumnTypePrecisionScaleReturn,
            NotImplemented,
        >,
    > + Send {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsColumns(rowsID string) []string`
    ///
    /// ```text
    /// Rows
    /// ```
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_columns(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbStrSliceReturn, NotImplemented>>
    + Send {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsHasNextResultSet(rowsID string) bool`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_has_next_result_set(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbBoolReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsNext(rowsID string, dest []driver.Value) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_next(
        &self,
        args: super::super::wire::plugin::Z_DbRowScanArg,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbRowScanReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `RowsNextResultSet(rowsID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn rows_next_result_set(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `Stmt(connID string, q string) (string, error)`
    ///
    /// ```text
    /// Statement
    /// ```
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn stmt(
        &self,
        args: super::super::wire::plugin::Z_DbStmtArgs,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbStrErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `StmtClose(stID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn stmt_close(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `StmtExec(stID string, args []driver.NamedValue) (plugin.ResultContainer, error)`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn stmt_exec(
        &self,
        args: super::super::wire::plugin::Z_DbStmtQueryArgs,
    ) -> impl Future<
        Output = Result<super::super::wire::plugin::Z_DbResultContErrReturn, NotImplemented>,
    > + Send {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `StmtNumInput(stID string) int`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn stmt_num_input(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbIntReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `StmtQuery(stID string, args []driver.NamedValue) (string, error)`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn stmt_query(
        &self,
        args: super::super::wire::plugin::Z_DbStmtQueryArgs,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbStrErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `Tx(connID string, opts driver.TxOptions) (string, error)`
    ///
    /// ```text
    /// Transaction
    /// ```
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn tx(
        &self,
        args: super::super::wire::plugin::Z_DbTxArgs,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbStrErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `TxCommit(txID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn tx_commit(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }

    /// Go: `TxRollback(txID string) error`
    ///
    /// The default answers as a host without a driver would: the call fails.
    fn tx_rollback(
        &self,
        args: ::std::string::String,
    ) -> impl Future<Output = Result<super::super::wire::plugin::Z_DbErrReturn, NotImplemented>> + Send
    {
        let _ = args;
        async { Err(NotImplemented) }
    }
}

/// Register every driver method on `server` as `Plugin.<Method>`.
pub fn register_driver<T: Driver>(server: &mut Server, implementation: &Arc<T>) {
    let this = Arc::clone(implementation);
    server.register("Plugin.Conn", move |args: bool| {
        let this = Arc::clone(&this);
        async move {
            this.conn(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register("Plugin.ConnClose", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.conn_close(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.ConnExec",
        move |args: super::super::wire::plugin::Z_DbConnArgs| {
            let this = Arc::clone(&this);
            async move {
                this.conn_exec(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register("Plugin.ConnPing", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.conn_ping(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.ConnQuery",
        move |args: super::super::wire::plugin::Z_DbConnArgs| {
            let this = Arc::clone(&this);
            async move {
                this.conn_query(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register("Plugin.RowsClose", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.rows_close(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.RowsColumnTypeDatabaseTypeName",
        move |args: super::super::wire::plugin::Z_DbRowsColumnArg| {
            let this = Arc::clone(&this);
            async move {
                this.rows_column_type_database_type_name(args)
                    .await
                    .map_err(|NotImplemented| {
                        ServiceError("the host has no database driver".into())
                    })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.RowsColumnTypePrecisionScale",
        move |args: super::super::wire::plugin::Z_DbRowsColumnArg| {
            let this = Arc::clone(&this);
            async move {
                this.rows_column_type_precision_scale(args)
                    .await
                    .map_err(|NotImplemented| {
                        ServiceError("the host has no database driver".into())
                    })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register("Plugin.RowsColumns", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.rows_columns(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.RowsHasNextResultSet",
        move |args: ::std::string::String| {
            let this = Arc::clone(&this);
            async move {
                this.rows_has_next_result_set(args)
                    .await
                    .map_err(|NotImplemented| {
                        ServiceError("the host has no database driver".into())
                    })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.RowsNext",
        move |args: super::super::wire::plugin::Z_DbRowScanArg| {
            let this = Arc::clone(&this);
            async move {
                this.rows_next(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.RowsNextResultSet",
        move |args: ::std::string::String| {
            let this = Arc::clone(&this);
            async move {
                this.rows_next_result_set(args)
                    .await
                    .map_err(|NotImplemented| {
                        ServiceError("the host has no database driver".into())
                    })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.Stmt",
        move |args: super::super::wire::plugin::Z_DbStmtArgs| {
            let this = Arc::clone(&this);
            async move {
                this.stmt(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register("Plugin.StmtClose", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.stmt_close(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.StmtExec",
        move |args: super::super::wire::plugin::Z_DbStmtQueryArgs| {
            let this = Arc::clone(&this);
            async move {
                this.stmt_exec(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register("Plugin.StmtNumInput", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.stmt_num_input(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.StmtQuery",
        move |args: super::super::wire::plugin::Z_DbStmtQueryArgs| {
            let this = Arc::clone(&this);
            async move {
                this.stmt_query(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register(
        "Plugin.Tx",
        move |args: super::super::wire::plugin::Z_DbTxArgs| {
            let this = Arc::clone(&this);
            async move {
                this.tx(args).await.map_err(|NotImplemented| {
                    ServiceError("the host has no database driver".into())
                })
            }
        },
    );
    let this = Arc::clone(implementation);
    server.register("Plugin.TxCommit", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.tx_commit(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
    let this = Arc::clone(implementation);
    server.register("Plugin.TxRollback", move |args: ::std::string::String| {
        let this = Arc::clone(&this);
        async move {
            this.tx_rollback(args)
                .await
                .map_err(|NotImplemented| ServiceError("the host has no database driver".into()))
        }
    });
}

impl DriverClient {
    /// Go: `Conn(isMaster bool) (string, error)`
    ///
    /// ```text
    /// Connection
    /// ```
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn conn(&self, args: bool) -> super::super::wire::plugin::Z_DbStrErrReturn {
        self.call("Conn", &args).await
    }

    /// Go: `ConnClose(connID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn conn_close(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("ConnClose", &args).await
    }

    /// Go: `ConnExec(connID string, q string, args []driver.NamedValue) (plugin.ResultContainer, error)`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn conn_exec(
        &self,
        args: super::super::wire::plugin::Z_DbConnArgs,
    ) -> super::super::wire::plugin::Z_DbResultContErrReturn {
        self.call("ConnExec", &args).await
    }

    /// Go: `ConnPing(connID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn conn_ping(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("ConnPing", &args).await
    }

    /// Go: `ConnQuery(connID string, q string, args []driver.NamedValue) (string, error)`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn conn_query(
        &self,
        args: super::super::wire::plugin::Z_DbConnArgs,
    ) -> super::super::wire::plugin::Z_DbStrErrReturn {
        self.call("ConnQuery", &args).await
    }

    /// Go: `RowsClose(rowsID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_close(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("RowsClose", &args).await
    }

    /// Go: `RowsColumnTypeDatabaseTypeName(rowsID string, index int) string`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_column_type_database_type_name(
        &self,
        args: super::super::wire::plugin::Z_DbRowsColumnArg,
    ) -> ::std::string::String {
        self.call("RowsColumnTypeDatabaseTypeName", &args).await
    }

    /// Go: `RowsColumnTypePrecisionScale(rowsID string, index int) (int64, int64, bool)`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_column_type_precision_scale(
        &self,
        args: super::super::wire::plugin::Z_DbRowsColumnArg,
    ) -> super::super::wire::plugin::Z_DbRowsColumnTypePrecisionScaleReturn {
        self.call("RowsColumnTypePrecisionScale", &args).await
    }

    /// Go: `RowsColumns(rowsID string) []string`
    ///
    /// ```text
    /// Rows
    /// ```
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_columns(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbStrSliceReturn {
        self.call("RowsColumns", &args).await
    }

    /// Go: `RowsHasNextResultSet(rowsID string) bool`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_has_next_result_set(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbBoolReturn {
        self.call("RowsHasNextResultSet", &args).await
    }

    /// Go: `RowsNext(rowsID string, dest []driver.Value) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_next(
        &self,
        args: super::super::wire::plugin::Z_DbRowScanArg,
    ) -> super::super::wire::plugin::Z_DbRowScanReturn {
        self.call("RowsNext", &args).await
    }

    /// Go: `RowsNextResultSet(rowsID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn rows_next_result_set(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("RowsNextResultSet", &args).await
    }

    /// Go: `Stmt(connID string, q string) (string, error)`
    ///
    /// ```text
    /// Statement
    /// ```
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn stmt(
        &self,
        args: super::super::wire::plugin::Z_DbStmtArgs,
    ) -> super::super::wire::plugin::Z_DbStrErrReturn {
        self.call("Stmt", &args).await
    }

    /// Go: `StmtClose(stID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn stmt_close(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("StmtClose", &args).await
    }

    /// Go: `StmtExec(stID string, args []driver.NamedValue) (plugin.ResultContainer, error)`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn stmt_exec(
        &self,
        args: super::super::wire::plugin::Z_DbStmtQueryArgs,
    ) -> super::super::wire::plugin::Z_DbResultContErrReturn {
        self.call("StmtExec", &args).await
    }

    /// Go: `StmtNumInput(stID string) int`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn stmt_num_input(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbIntReturn {
        self.call("StmtNumInput", &args).await
    }

    /// Go: `StmtQuery(stID string, args []driver.NamedValue) (string, error)`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn stmt_query(
        &self,
        args: super::super::wire::plugin::Z_DbStmtQueryArgs,
    ) -> super::super::wire::plugin::Z_DbStrErrReturn {
        self.call("StmtQuery", &args).await
    }

    /// Go: `Tx(connID string, opts driver.TxOptions) (string, error)`
    ///
    /// ```text
    /// Transaction
    /// ```
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn tx(
        &self,
        args: super::super::wire::plugin::Z_DbTxArgs,
    ) -> super::super::wire::plugin::Z_DbStrErrReturn {
        self.call("Tx", &args).await
    }

    /// Go: `TxCommit(txID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn tx_commit(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("TxCommit", &args).await
    }

    /// Go: `TxRollback(txID string) error`
    ///
    /// A failed call is logged and answers zero values, as Go's client does.
    pub async fn tx_rollback(
        &self,
        args: ::std::string::String,
    ) -> super::super::wire::plugin::Z_DbErrReturn {
        self.call("TxRollback", &args).await
    }
}

/// Invoke `$m!` with every driver method as `(method, "GoName", Args, Returns),`.
#[doc(hidden)]
#[macro_export]
macro_rules! for_each_driver_method {
    ($m:ident) => {
        $m! {
            (conn, "Conn", bool, $crate::wire::plugin::Z_DbStrErrReturn),
            (conn_close, "ConnClose", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
            (conn_exec, "ConnExec", $crate::wire::$crate::wire::wire::plugin::Z_DbConnArgs, $crate::wire::plugin::Z_DbResultContErrReturn),
            (conn_ping, "ConnPing", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
            (conn_query, "ConnQuery", $crate::wire::$crate::wire::wire::plugin::Z_DbConnArgs, $crate::wire::plugin::Z_DbStrErrReturn),
            (rows_close, "RowsClose", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
            (rows_column_type_database_type_name, "RowsColumnTypeDatabaseTypeName", $crate::wire::$crate::wire::wire::plugin::Z_DbRowsColumnArg, ::std::string::String),
            (rows_column_type_precision_scale, "RowsColumnTypePrecisionScale", $crate::wire::$crate::wire::wire::plugin::Z_DbRowsColumnArg, $crate::wire::plugin::Z_DbRowsColumnTypePrecisionScaleReturn),
            (rows_columns, "RowsColumns", ::std::string::String, $crate::wire::plugin::Z_DbStrSliceReturn),
            (rows_has_next_result_set, "RowsHasNextResultSet", ::std::string::String, $crate::wire::plugin::Z_DbBoolReturn),
            (rows_next, "RowsNext", $crate::wire::$crate::wire::wire::plugin::Z_DbRowScanArg, $crate::wire::plugin::Z_DbRowScanReturn),
            (rows_next_result_set, "RowsNextResultSet", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
            (stmt, "Stmt", $crate::wire::$crate::wire::wire::plugin::Z_DbStmtArgs, $crate::wire::plugin::Z_DbStrErrReturn),
            (stmt_close, "StmtClose", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
            (stmt_exec, "StmtExec", $crate::wire::$crate::wire::wire::plugin::Z_DbStmtQueryArgs, $crate::wire::plugin::Z_DbResultContErrReturn),
            (stmt_num_input, "StmtNumInput", ::std::string::String, $crate::wire::plugin::Z_DbIntReturn),
            (stmt_query, "StmtQuery", $crate::wire::$crate::wire::wire::plugin::Z_DbStmtQueryArgs, $crate::wire::plugin::Z_DbStrErrReturn),
            (tx, "Tx", $crate::wire::$crate::wire::wire::plugin::Z_DbTxArgs, $crate::wire::plugin::Z_DbStrErrReturn),
            (tx_commit, "TxCommit", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
            (tx_rollback, "TxRollback", ::std::string::String, $crate::wire::plugin::Z_DbErrReturn),
        }
    };
}
