//! gobwire against Go's encoding/gob, both directions, over the corpus in `fixtures/gob/`
//! (generated by `reference/dump/gob`).
//!
//! * **Go → Rust.** Every stream Go wrote is decoded into the Rust mirror of the Go type Go
//!   decoded it into, and must yield what Go's decoder yielded — or fail where Go failed.
//! * **Wire.** Every stream decodes dynamically into exactly what Go sent.
//! * **Rust → Go.** What Rust decoded is re-encoded by Rust and handed back to Go, which must
//!   decode it into the same values it decoded from its own stream.
//!
//! Where Rust and Go deliberately differ, the case is listed in `DIVERGENCES` with the reason,
//! and the test asserts the divergence rather than skipping the case.

mod common;

use std::collections::HashMap;

use common::{Case, cases, decode_typed, for_each_value, go_echo, read, render, render_typed};
use gobwire::{BinaryBytes, Complex, Dynamic, Encode, Encoder, GoTime, Gob, GobBytes, Interface};
use serde_json::Value as Json;

// ─── Rust mirrors of reference/dump/gob's types ────────────────────────────────────────────

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Scalars {
    b: bool,
    i: i64,
    i8: i8,
    i16: i16,
    i32: i32,
    i64: i64,
    u: u64,
    u8: u8,
    u16: u16,
    u32: u32,
    u64: u64,
    uptr: usize,
    f32: f32,
    f64: f64,
    c128: Complex,
    s: String,
    bytes: Vec<u8>,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Inner {
    n: i64,
    s: String,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Zeros {
    b: bool,
    i: i64,
    f: f64,
    s: String,
    bytes: Vec<u8>,
    p: Option<i64>,
    #[gob(name = "PZ")]
    pz: Option<i64>,
    #[gob(name = "PS")]
    ps: Option<Inner>,
    e: Inner,
    a: [i64; 2],
    m: HashMap<String, i64>,
    #[gob(name = "ME")]
    me: HashMap<String, i64>,
    #[gob(name = "SL")]
    sl: Vec<i64>,
    #[gob(name = "IF")]
    iface: Option<Interface>,
    last: String,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Nested {
    ptr: Option<Inner>,
    val: Inner,
    slice: Vec<Inner>,
    ptr_slice: Vec<Option<Inner>>,
    arr: [Inner; 3],
    map: HashMap<String, Inner>,
    int_map: HashMap<i64, String>,
    ptr_map: HashMap<String, Option<Inner>>,
    matrix: Vec<Vec<i64>>,
    blobs: Vec<Vec<u8>>,
    strings: Vec<String>,
    floats: Vec<f64>,
    bools: [bool; 2],
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Ifaces {
    s: Option<Interface>,
    f: Option<Interface>,
    i: Option<Interface>,
    m: Option<Interface>,
    l: Option<Interface>,
    p: Option<Interface>,
    v: Option<Interface>,
    err: Option<Interface>,
    nest: Option<Interface>,
    t: Option<Interface>,
    nil: Option<Interface>,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Marshalers {
    t: GoTime,
    #[gob(name = "TZ")]
    tz: GoTime,
    #[gob(name = "TL")]
    tl: GoTime,
    t_neg: GoTime,
    u: BinaryBytes,
    p: Option<BinaryBytes>,
    /// `Celsius` implements only `MarshalText`, which gob ignores: it travels as a float.
    txt: f64,
    big: Option<GobBytes>,
    zero_t: GoTime,
    zero_fixed: GoTime,
    after: String,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Recursive {
    name: String,
    kids: Vec<Option<Recursive>>,
    next: Option<Box<Recursive>>,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Wide {
    keep: String,
    nums: Vec<i64>,
    blob: Vec<u8>,
    tree: Option<Recursive>,
    map: HashMap<String, Vec<Inner>>,
    iface: Option<Interface>,
    nils_iface: Vec<Option<Interface>>,
    time: GoTime,
    arr: [Inner; 2],
    c: Complex,
    last: i64,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct WideNoNils {
    keep: String,
    nums: Vec<i64>,
    blob: Vec<u8>,
    tree: Option<Recursive>,
    map: HashMap<String, Vec<Inner>>,
    iface: Option<Interface>,
    time: GoTime,
    arr: [Inner; 2],
    c: Complex,
    last: i64,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Narrow {
    keep: String,
    last: i64,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Small {
    i8: i8,
    u8: u8,
    f32: f32,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Big {
    i8: i64,
    u8: u64,
    f32: f64,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct U16s {
    n: u16,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct U64s {
    n: u64,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct ArrSmall {
    a: [i64; 2],
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct ArrBig {
    a: [i64; 3],
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Unrelated {
    nothing: String,
    in_common: i64,
}

macro_rules! one_field {
    ($($name:ident: $t:ty),*) => {$(
        #[derive(Gob, Debug, Default, Clone, PartialEq)]
        struct $name {
            n: $t,
        }
    )*};
}

one_field!(
    Ints: i64,
    Uints: u64,
    Strs: String,
    Floats: f64,
    IntSlice: Vec<i64>,
    IntArr: [i64; 1],
    StrMap: HashMap<String, i64>,
    IntMap: HashMap<i64, i64>,
    IfaceField: Option<Interface>,
    StructField: Inner
);

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Meta {
    emojis: Vec<Inner>,
    count: i64,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Post {
    id: String,
    create_at: i64,
    message: String,
    props: HashMap<String, Option<Interface>>,
    file_ids: Vec<String>,
    remote_id: Option<String>,
    pinned: bool,
    metadata: Option<Meta>,
    reply_to: Vec<Inner>,
}

#[derive(Gob, Debug, Default, Clone, PartialEq)]
struct Merge {
    keep: String,
    change: String,
    ptr: Option<Inner>,
    slice: Vec<Inner>,
    short: Vec<Inner>,
    arr: [Inner; 2],
    map: HashMap<String, Inner>,
    iface: Option<Interface>,
    bytes: Vec<u8>,
    nested: Inner,
}

// ─── the harness ───────────────────────────────────────────────────────────────────────────

/// What Rust made of a case: renderings of the decoded values, and the Rust re-encoding of them
/// as one stream — or the decode error.
struct Outcome {
    rendered: Vec<Json>,
    reencoded: Vec<u8>,
}

fn typed<T: gobwire::Decode + Encode + Default>(case: &Case) -> gobwire::Result<Outcome> {
    let values = decode_typed::<T>(case)?;
    let mut enc = Encoder::new();
    let mut reencoded = Vec::new();
    for v in &values {
        enc.encode_into(v, &mut reencoded)?;
    }
    Ok(Outcome {
        rendered: values.iter().map(|v| render_typed(v)).collect(),
        reencoded,
    })
}

fn run(case: &Case) -> gobwire::Result<Outcome> {
    match case.decode_as.as_str() {
        "Scalars" => typed::<Scalars>(case),
        "Inner" => typed::<Inner>(case),
        "*Inner" => typed::<Option<Inner>>(case),
        "Zeros" => typed::<Zeros>(case),
        "Nested" => typed::<Nested>(case),
        "Ifaces" => typed::<Ifaces>(case),
        "Marshalers" => typed::<Marshalers>(case),
        "Recursive" => typed::<Recursive>(case),
        "Wide" => typed::<Wide>(case),
        "WideNoNils" => typed::<WideNoNils>(case),
        "Narrow" => typed::<Narrow>(case),
        "Small" => typed::<Small>(case),
        "Big" => typed::<Big>(case),
        "ArrSmall" => typed::<ArrSmall>(case),
        "U16s" => typed::<U16s>(case),
        "U64s" => typed::<U64s>(case),
        "[]Unrelated" => typed::<Vec<Unrelated>>(case),
        "ArrBig" => typed::<ArrBig>(case),
        "Unrelated" => typed::<Unrelated>(case),
        "Ints" => typed::<Ints>(case),
        "Uints" => typed::<Uints>(case),
        "Strs" => typed::<Strs>(case),
        "Floats" => typed::<Floats>(case),
        "IntSlice" => typed::<IntSlice>(case),
        "IntArr" => typed::<IntArr>(case),
        "StrMap" => typed::<StrMap>(case),
        "IntMap" => typed::<IntMap>(case),
        "IfaceField" => typed::<IfaceField>(case),
        "StructField" => typed::<StructField>(case),
        "Post" => typed::<Post>(case),
        "Merge" => typed::<Merge>(case),
        "string" => typed::<String>(case),
        "int" => typed::<i64>(case),
        "[]string" => typed::<Vec<String>>(case),
        "map[string]int" => typed::<HashMap<String, i64>>(case),
        "any" => typed::<Option<Interface>>(case),
        "time.Time" => typed::<GoTime>(case),
        other => panic!("no Rust mirror for Go type {other:?}; add one to go_parity.rs"),
    }
}

/// Cases where Rust and Go deliberately or unavoidably differ, and how.
enum Divergence {
    /// Go's decoder fails on its own stream; Rust decodes it.
    GoDecoderBug,
    /// Rust decodes as Go does, but a Rust re-encoding cannot express the named field, so Go
    /// reads back a different value there.
    Reencode(&'static str),
    /// Go itself does not round-trip the named field: Go decoding what Go would re-encode yields
    /// a different value. Rust writes Go's bytes, so Go drifts the same way reading them.
    GoNotIdempotent(&'static str),
}

fn divergence(name: &str) -> Option<Divergence> {
    match name {
        // decode.go, ignoreInterface: skipping an interface that defines its concrete type
        // inline fails ("field numbers out of bounds"); skipping a nil interface reads a type
        // sequence that is not there. Rust skips both correctly.
        "skip_iface_inline_type" | "skip_nil_iface" => Some(Divergence::GoDecoderBug),
        // `ME map[string]int{}` is an empty non-nil map, which Go sends; a Rust HashMap cannot be
        // nil, so an empty one re-encodes as the nil a zero Go struct holds.
        "zeros" => Some(Divergence::Reencode("ME")),
        // time.go: MarshalBinary writes the seconds part of a negative offset signed and
        // UnmarshalBinary adds it back unsigned, so -01:00:01 comes back 256 s east, and again on
        // every further round trip.
        "marshalers" => Some(Divergence::GoNotIdempotent("TNeg")),
        _ => None,
    }
}

fn without(values: &[Json], field: &str) -> Vec<Json> {
    let mut out = values.to_vec();
    for v in &mut out {
        if let Some(o) = v.as_object_mut() {
            o.remove(field);
        }
    }
    out
}

#[test]
fn every_case_has_a_distinct_name_and_fixture() {
    let cases = cases();
    assert!(cases.len() >= 40, "corpus shrank to {}", cases.len());
    let mut names: Vec<_> = cases.iter().map(|c| &c.name).collect();
    names.sort();
    names.dedup();
    assert_eq!(names.len(), cases.len());
    for c in &cases {
        assert!(!read(&c.stream).is_empty(), "{}", c.name);
    }
}

/// Go → Rust, typed: Rust decodes what Go decoded, and fails where Go failed.
#[test]
fn typed_decode_matches_go() {
    let mut failures = Vec::new();
    for case in cases() {
        let outcome = run(&case);
        match (&case.error, outcome, divergence(&case.name)) {
            (Some(go_err), Ok(o), Some(Divergence::GoDecoderBug)) => {
                // Rust decodes where Go's skip is broken: check it got the fields it kept.
                assert_eq!(
                    o.rendered.len(),
                    1,
                    "{}: Go failed with {go_err}",
                    case.name
                );
            }
            (Some(go_err), Ok(o), _) => failures.push(format!(
                "{}: Go failed ({go_err}) but Rust decoded {:?}",
                case.name, o.rendered
            )),
            (None, Err(e), _) => failures.push(format!("{}: Rust failed: {e}", case.name)),
            (Some(_), Err(_), _) => {}
            (None, Ok(o), Some(Divergence::Reencode(field))) => {
                // Rendering goes through a Rust re-encoding, so the field is lost here too.
                assert_ne!(
                    o.rendered, case.decoded,
                    "{}: divergence no longer happens",
                    case.name
                );
                if o.rendered != without(&case.decoded, field) {
                    failures.push(format!("{}: beyond the {field} divergence", case.name));
                }
            }
            (None, Ok(o), _) => {
                if o.rendered != case.decoded {
                    failures.push(format!(
                        "{}:\n  go   {}\n  rust {}",
                        case.name,
                        Json::Array(case.decoded.clone()),
                        Json::Array(o.rendered)
                    ));
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} of the corpus differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Wire: dynamic decoding sees exactly what Go sent.
#[test]
fn dynamic_decode_matches_the_wire() {
    let mut failures = Vec::new();
    for case in cases() {
        let mut rendered = Vec::new();
        let result = for_each_value(&read(&case.stream), |dec| {
            let d: Dynamic = dec.decode()?;
            rendered.push(render(&d.ty, &d.value));
            Ok(())
        });
        match (case.name.as_str(), result) {
            // A recursive type has no dynamic shape.
            ("recursive", Err(gobwire::Error::Unsupported(_))) => {}
            ("skip_wide", Err(gobwire::Error::Unsupported(_))) => {}
            (_, Err(e)) => failures.push(format!("{}: {e}", case.name)),
            (_, Ok(_)) if rendered != case.wire => failures.push(format!(
                "{}:\n  wire {}\n  rust {}",
                case.name,
                Json::Array(case.wire.clone()),
                Json::Array(rendered)
            )),
            _ => {}
        }
    }
    assert!(
        failures.is_empty(),
        "{} differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Rust → Go: Go decodes Rust's re-encoding into what it decoded from its own stream.
#[test]
fn go_decodes_what_rust_encodes() {
    let mut failures = Vec::new();
    let mut checked = 0;
    for case in cases() {
        if case.error.is_some() {
            continue;
        }
        let Ok(outcome) = run(&case) else { continue };
        let echo = go_echo(&case.decode_as, &outcome.reencoded, case.base.as_deref());
        checked += 1;
        if let Some(e) = &echo.error {
            failures.push(format!(
                "{}: Go could not decode Rust's stream: {e}",
                case.name
            ));
            continue;
        }
        match divergence(&case.name) {
            Some(Divergence::Reencode(field) | Divergence::GoNotIdempotent(field)) => {
                assert_ne!(
                    echo.decoded[0].get(field),
                    case.decoded[0].get(field),
                    "{}: the {field} divergence no longer happens",
                    case.name
                );
                if without(&echo.decoded, field) != without(&case.decoded, field) {
                    failures.push(format!("{}: beyond the {field} divergence", case.name));
                }
            }
            _ if echo.decoded != case.decoded => failures.push(format!(
                "{}:\n  go-from-go   {}\n  go-from-rust {}",
                case.name,
                Json::Array(case.decoded.clone()),
                Json::Array(echo.decoded)
            )),
            _ => {}
        }
    }
    assert!(checked >= 20, "only {checked} cases reached Go");
    assert!(
        failures.is_empty(),
        "{} differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Rust → Go, dynamic: a value held only dynamically re-encodes into something Go decodes into
/// the original Go type.
#[test]
fn go_decodes_dynamic_reencoding() {
    let mut failures = Vec::new();
    for case in cases() {
        if case.error.is_some() || case.base.is_some() {
            continue;
        }
        let mut enc = Encoder::new();
        let mut stream = Vec::new();
        let result = for_each_value(&read(&case.stream), |dec| {
            let d: Dynamic = dec.decode()?;
            enc.encode_into(&d, &mut stream)
        });
        if matches!(result, Err(gobwire::Error::Unsupported(_))) {
            continue;
        }
        result.unwrap();
        let echo = go_echo(&case.decode_as, &stream, None);
        if echo.error.is_some() || echo.decoded != case.decoded {
            failures.push(format!(
                "{}: {:?} {}",
                case.name,
                echo.error,
                Json::Array(echo.decoded)
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Go's skip bug is only reachable when a type is defined inside the skipped interface. This
/// encoder always defines types in messages of their own before the value, so Go can skip
/// anything Rust sends.
#[test]
fn go_can_skip_what_rust_sends() {
    let wide = WideNoNils {
        keep: "kept".into(),
        iface: Some(
            Interface::new(
                gobwire::names::STRING_ANY_MAP,
                &HashMap::from([("k".to_string(), Some(Interface::string("v")))]),
            )
            .unwrap(),
        ),
        last: 99,
        ..Default::default()
    };
    let nils = Wide {
        keep: "kept".into(),
        nils_iface: vec![None, Some(Interface::string("x"))],
        last: 99,
        ..Default::default()
    };
    for (label, stream) in [
        ("inline type", Encoder::new().encode(&wide).unwrap()),
        ("nil iface", Encoder::new().encode(&nils).unwrap()),
    ] {
        let echo = go_echo("Narrow", &stream, None);
        if label == "nil iface" {
            // The nil-interface bug is in Go's skip itself and no encoding avoids it.
            assert!(
                echo.error.is_some(),
                "{label}: Go's nil-interface skip bug is fixed; revisit"
            );
        } else {
            assert_eq!(echo.error, None, "{label}");
            assert_eq!(
                echo.decoded,
                vec![serde_json::json!({"Keep": "kept", "Last": 99})],
                "{label}"
            );
        }
    }
}
