package main

// Behavioural oracle for **Go's `text/template` and `html/template`**, which `crates/gotemplate`
// ports byte for byte. Written to fixtures/behaviour_gotemplate.json; `-only gotemplate` runs it
// alone. It also writes crates/gotemplate/src/unicode_tables.rs, the `unicode.IsPrint`,
// `IsLetter` and `IsDigit` tables the lexer, `strconv.Quote` and `JSEscape` read.
//
// Three corpora:
//
//   - `mattermost`: every template name Mattermost's real `templates.New(dir)` (a `ParseGlob` of
//     `server/templates/*.html`) defines, executed through `Container.RenderToString` with a fully
//     populated `templates.Data` in five variants chosen to exercise escaping (markup and quotes,
//     `javascript:` URLs, spaces and `%` in URLs, non-ASCII, trusted `template.HTML` and
//     `template.URL`, empty strings for every `{{if}}`, a nil Props map). Each variant runs every
//     name in sorted order on ONE container, as a long-lived server does — html/template escapes
//     lazily and remembers what it derived, so order is part of what is recorded.
//   - `html`: a targeted escaper corpus — each case is a template set, the names executed in
//     order, and the data; it records every output or error.
//   - `text`: the same shape through `text/template`, including parse errors.
//
// Data crosses to Rust as a type-tagged JSON graph built by reflection from the very Go value the
// template executed against (see gotemplateEncode), so the Rust test rebuilds an identical
// `Value` rather than a hand-written approximation.
//
// Determinism: fixed corpora, no clock, no randomness, no map iteration in the output path.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	htmltemplate "html/template"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"slices"
	"sort"
	"strconv"
	"strings"
	texttemplate "text/template"
	"unicode"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/v8/channels/app/email"
	"github.com/mattermost/mattermost/server/v8/platform/shared/templates"
)

// gotemplateTemplatesDir is Mattermost's template directory, relative to reference/dump.
const gotemplateTemplatesDir = "../mattermost/server/templates"

func writeGotemplateUnicodeTables(rustDir string) error {
	var b strings.Builder
	header := []string{
		"//! @generated by `reference/dump/behaviour_gotemplate.go` from Go's `unicode` package.",
		"//! DO NOT EDIT — re-run `cd reference/dump && go run . -only gotemplate` instead.",
		"//!",
		"//! `unicode.IsPrint` (read by `strconv.Quote`, `%q` and text/template's `JSEscape`) and",
		"//! `unicode.IsLetter` / `unicode.IsDigit` (the template lexer's `isAlphaNumeric`), as range",
		"//! tables. Unicode version: the **Go toolchain's**, not the Rust toolchain's.",
		"//!",
		"//! Sorted and non-overlapping, so a binary search applies.",
		"",
	}
	b.WriteString(strings.Join(header, "\n"))
	emitRanges(&b, "IS_PRINT_RANGES", "unicode.IsPrint", scanRuneRanges(unicode.IsPrint))
	emitRanges(&b, "IS_LETTER_RANGES", "unicode.IsLetter", scanRuneRanges(unicode.IsLetter))
	emitRanges(&b, "IS_DIGIT_RANGES", "unicode.IsDigit", scanRuneRanges(unicode.IsDigit))
	path := filepath.Join(rustDir, "unicode_tables.rs")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}

// writeGotemplateEntityTable emits crates/gotemplate/src/html/entity_table.rs: every named
// character reference `html.UnescapeString` knows (Go keeps the map unexported, so the names are
// read from the toolchain's own html/entity.go and each one's expansion is taken from
// UnescapeString itself, never from the source text). html/template decodes attribute values
// with it before running its context transitions.
func writeGotemplateEntityTable(rustDir string) error {
	src, err := os.ReadFile(filepath.Join(runtime.GOROOT(), "src", "html", "entity.go"))
	if err != nil {
		return err
	}
	re := regexp.MustCompile(`(?m)^\s*"([A-Za-z0-9]+;?)":`)
	names := map[string]bool{}
	for _, m := range re.FindAllStringSubmatch(string(src), -1) {
		names[m[1]] = true
	}
	var sorted []string
	for n := range names {
		sorted = append(sorted, n)
	}
	sort.Strings(sorted)
	var b strings.Builder
	b.WriteString("//! @generated by `reference/dump/behaviour_gotemplate.go` from Go's `html` package.\n")
	b.WriteString("//! DO NOT EDIT — re-run `cd reference/dump && go run . -only gotemplate` instead.\n")
	b.WriteString("//!\n")
	b.WriteString("//! Every named character reference `html.UnescapeString` decodes, with its expansion as\n")
	b.WriteString("//! `html.UnescapeString(\"&\" + name)` returns it. Sorted by name for a binary search.\n\n")
	fmt.Fprintf(&b, "/// The %d entity names (with their `;` where the name has one) and expansions.\n", len(sorted))
	b.WriteString("#[rustfmt::skip]\npub(crate) static ENTITIES: &[(&str, &str)] = &[\n")
	for _, n := range sorted {
		probe := "&" + n
		if !strings.HasSuffix(n, ";") {
			// A name without its semicolon only decodes where no longer name matches; probe it
			// followed by a character that cannot extend a name.
			probe += " "
		}
		out := html.UnescapeString(probe)
		out = strings.TrimSuffix(out, " ")
		if out == strings.TrimSuffix(probe, " ") {
			return fmt.Errorf("entity %q did not decode", n)
		}
		fmt.Fprintf(&b, "    (%s, %s),\n", rustStringLiteral(n), rustStringLiteral(out))
	}
	b.WriteString("];\n")
	path := filepath.Join(rustDir, "html", "entity_table.rs")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d entities)\n", path, len(sorted))
	return nil
}

// rustStringLiteral quotes s as a Rust string literal, escaping everything outside printable
// ASCII so the generated file is plain ASCII.
func rustStringLiteral(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r >= 0x20 && r < 0x7f:
			b.WriteRune(r)
		default:
			fmt.Fprintf(&b, "\\u{%x}", r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// gotemplateEncode turns a Go value into the type-tagged graph the Rust test decodes into a
// `gotemplate::Value`. Structs are flattened to the fields `FieldByName` can reach (promoted
// fields of embedded structs included, shadowed ones excluded), which is what a template sees.
func gotemplateEncode(v reflect.Value) any {
	if !v.IsValid() {
		return map[string]any{"t": "nil"}
	}
	switch v.Kind() {
	case reflect.Interface:
		if v.IsNil() {
			return map[string]any{"t": "nil"}
		}
		return gotemplateEncode(v.Elem())
	case reflect.Pointer:
		if v.IsNil() {
			return map[string]any{"t": "ptr", "v": nil, "type": v.Type().String()}
		}
		return map[string]any{"t": "ptr", "v": gotemplateEncode(v.Elem())}
	case reflect.Bool:
		return map[string]any{"t": "bool", "v": v.Bool()}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return map[string]any{"t": "int", "v": v.Int()}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"t": "float", "v": strconv.FormatFloat(v.Float(), 'g', -1, 64)}
	case reflect.String:
		tag := "string"
		switch v.Type() {
		case reflect.TypeOf(htmltemplate.HTML("")):
			tag = "html"
		case reflect.TypeOf(htmltemplate.URL("")):
			tag = "url"
		case reflect.TypeOf(htmltemplate.CSS("")):
			tag = "css"
		case reflect.TypeOf(htmltemplate.JS("")):
			tag = "js"
		case reflect.TypeOf(htmltemplate.JSStr("")):
			tag = "jsstr"
		case reflect.TypeOf(htmltemplate.HTMLAttr("")):
			tag = "htmlattr"
		case reflect.TypeOf(htmltemplate.Srcset("")):
			tag = "srcset"
		}
		return map[string]any{"t": tag, "v": v.String()}
	case reflect.Slice, reflect.Array:
		items := make([]any, 0, v.Len())
		for i := 0; i < v.Len(); i++ {
			items = append(items, gotemplateEncode(v.Index(i)))
		}
		return map[string]any{"t": "list", "v": items}
	case reflect.Map:
		m := map[string]any{}
		iter := v.MapRange()
		for iter.Next() {
			m[iter.Key().String()] = gotemplateEncode(iter.Value())
		}
		return map[string]any{"t": "map", "v": m}
	case reflect.Struct:
		t := v.Type()
		fields := []any{}
		for _, f := range reflect.VisibleFields(t) {
			if !f.IsExported() {
				continue
			}
			sf, ok := t.FieldByName(f.Name)
			if !ok || !slices.Equal(sf.Index, f.Index) {
				continue
			}
			fields = append(fields, []any{f.Name, gotemplateEncode(v.FieldByIndex(f.Index))})
		}
		return map[string]any{"t": "struct", "name": t.String(), "v": fields}
	}
	panic(fmt.Sprintf("gotemplateEncode: unsupported kind %s", v.Kind()))
}

func gotemplateEncodeAny(x any) any {
	return gotemplateEncode(reflect.ValueOf(x))
}

func gtErrString(err error) any {
	if err == nil {
		return nil
	}
	return err.Error()
}

// ---------------------------------------------------------------------------------------------
// The Mattermost corpus.

// postData mirrors channels/app/email.postData (unexported there) field for field. Only its type
// name differs, and a type name is only ever visible in an error message.
type postData struct {
	SenderName               string
	ChannelName              string
	Message                  htmltemplate.HTML
	MessageURL               string
	SenderPhoto              string
	PostPhoto                string
	Time                     string
	ShowChannelIcon          bool
	OtherChannelMembersCount int
	MessageAttachments       []*email.EmailMessageAttachment
}

// webBrowser, webMattermostApp and webSystemBrowser mirror channels/web's Browser, MattermostApp
// and SystemBrowser (unsupported_browser.go) field for field; importing channels/web would pull
// its whole dependency tree into this generator.
type webBrowser struct {
	LogoSrc                string
	Title                  string
	SupportedVersionString string
	Src                    string
	GetLatestString        string
}

type webMattermostApp struct {
	LogoSrc                string
	Title                  string
	SupportedVersionString string
	Label                  string
	Link                   string
	InstallGuide           string
	InstallGuideLink       string
}

type webSystemBrowser struct {
	LogoSrc                string
	Title                  string
	SupportedVersionString string
	LabelOpen              string
	LinkOpen               string
	LinkMakeDefault        string
	OrString               string
	MakeDefaultString      string
}

var gotemplatePropRe = regexp.MustCompile(`\.Props\.([A-Za-z0-9_]+)`)
var gotemplateHTMLRe = regexp.MustCompile(`\.HTML\.([A-Za-z0-9_]+)`)

func gotemplateIsURLKey(k string) bool {
	for _, s := range []string{"URL", "Url", "Link", "Src", "Photo", "Icon", "Subpath", "Path"} {
		if strings.Contains(k, s) {
			return true
		}
	}
	return false
}

func sp(s string) *string { return &s }

// gotemplateMattermostData builds one variant of the data graph. Every key any template reads is
// populated, each with a value that names its key so a misplaced substitution cannot pass.
func gotemplateMattermostData(variant string, props, htmls []string) templates.Data {
	if variant == "missing" {
		return templates.Data{}
	}
	d := templates.Data{Props: map[string]any{}, HTML: map[string]htmltemplate.HTML{}}
	for i, k := range props {
		switch variant {
		case "escape":
			if gotemplateIsURLKey(k) {
				d.Props[k] = "https://ex.com/" + k + "/a b/é?q=<1>&r='2'&p=100%#f\"g"
			} else {
				d.Props[k] = k + ` <b>&amp;</b> "dq" 'sq' é 日本 +1`
			}
		case "javascript":
			if gotemplateIsURLKey(k) {
				d.Props[k] = "javascript:alert(\"" + k + "\")"
			} else {
				d.Props[k] = k + " ünï\u2028\u00a0\x00 </script> `${x}`"
			}
		case "empty":
			d.Props[k] = ""
		case "typed":
			switch {
			case gotemplateIsURLKey(k):
				d.Props[k] = htmltemplate.URL("javascript:trusted('" + k + "')")
			case i%5 == 0:
				d.Props[k] = i*7 + 1
			case i%5 == 1:
				d.Props[k] = sp(k + " <ptr>")
			case i%5 == 2:
				d.Props[k] = (*string)(nil)
			case i%5 == 3:
				d.Props[k] = i%2 == 0
			default:
				d.Props[k] = htmltemplate.HTML("<i>" + k + "</i> &amp; <b>x</b>")
			}
		}
	}
	for _, k := range htmls {
		switch variant {
		case "escape":
			d.HTML[k] = htmltemplate.HTML("<strong>" + k + "</strong> &amp; <a href=\"/x?a=1&b=2\">link</a>")
		case "javascript":
			d.HTML[k] = htmltemplate.HTML("<script>alert('" + k + "')</script>")
		case "empty":
			d.HTML[k] = ""
		case "typed":
			d.HTML[k] = htmltemplate.HTML("<em>" + k + "</em>")
		}
	}
	text := func(k string) string {
		switch variant {
		case "escape":
			return k + ` <i>&</i> "q" 'a' é`
		case "javascript":
			return "javascript:" + k + "()"
		case "typed":
			return k + " typed"
		}
		return ""
	}
	url := func(k string) string {
		switch variant {
		case "escape":
			return "https://ex.com/" + k + "?a=b c&d=<e>"
		case "javascript":
			return "javascript:alert('" + k + "')"
		case "typed":
			return "mailto:" + k + "@ex.com"
		}
		return ""
	}
	if variant != "empty" {
		attachment := &email.EmailMessageAttachment{
			MessageAttachment: model.MessageAttachment{
				Fallback:   text("Fallback"),
				Color:      map[string]string{"escape": "#ff0000", "javascript": "expression(alert(1))", "typed": "red; background: url(x)"}[variant],
				AuthorName: text("AuthorName"),
				AuthorLink: url("AuthorLink"),
				AuthorIcon: url("AuthorIcon"),
				Title:      text("Title"),
				TitleLink:  url("TitleLink"),
				ImageURL:   url("ImageURL"),
				ThumbURL:   url("ThumbURL"),
				Footer:     text("Footer"),
				FooterIcon: url("FooterIcon"),
			},
			Pretext: htmltemplate.HTML("<p>" + text("Pretext") + "</p>"),
			Text:    htmltemplate.HTML("<p>" + text("Text") + "</p>"),
			FieldRows: []email.FieldRow{
				{Cells: []*model.MessageAttachmentField{{Title: text("Cell1"), Value: text("Value1")}}},
				{Cells: []*model.MessageAttachmentField{{Title: text("Cell2"), Value: 42}, {Title: text("Cell3"), Value: nil}}},
			},
		}
		d.Props["Posts"] = []postData{
			{
				SenderName:               text("SenderName"),
				ChannelName:              text("ChannelName"),
				Message:                  htmltemplate.HTML("<p>" + text("Message") + "</p>"),
				MessageURL:               url("MessageURL"),
				SenderPhoto:              url("SenderPhoto"),
				PostPhoto:                url("PostPhoto"),
				Time:                     text("Time"),
				ShowChannelIcon:          true,
				OtherChannelMembersCount: 3,
				MessageAttachments:       []*email.EmailMessageAttachment{attachment},
			},
			{
				SenderName:  text("SenderName2"),
				Message:     htmltemplate.HTML(text("Message2")),
				MessageURL:  "",
				SenderPhoto: url("SenderPhoto2"),
			},
		}
		d.Props["Browsers"] = []webBrowser{
			{LogoSrc: url("LogoSrc"), Title: text("BrowserTitle"), SupportedVersionString: text("Version"), Src: url("Src"), GetLatestString: text("GetLatest")},
			{LogoSrc: url("LogoSrc2"), Title: text("BrowserTitle2")},
		}
		d.Props["App"] = webMattermostApp{LogoSrc: url("AppLogo"), Title: text("AppTitle"), SupportedVersionString: text("AppVersion"), Label: text("AppLabel"), Link: url("AppLink"), InstallGuide: text("InstallGuide"), InstallGuideLink: url("InstallGuideLink")}
		d.Props["SystemBrowser"] = webSystemBrowser{LogoSrc: url("SysLogo"), Title: text("SysTitle"), SupportedVersionString: text("SysVersion"), LabelOpen: text("LabelOpen"), LinkOpen: url("LinkOpen"), LinkMakeDefault: url("LinkMakeDefault"), OrString: text("Or"), MakeDefaultString: text("MakeDefault")}
		d.Props["BulletListItems"] = []string{text("Bullet1"), text("Bullet2")}
	} else {
		d.Props["Posts"] = []postData{}
		d.Props["Browsers"] = []webBrowser{}
		d.Props["App"] = webMattermostApp{}
		d.Props["SystemBrowser"] = nil
		d.Props["BulletListItems"] = []string(nil)
	}
	return d
}

func gotemplateMattermostCorpus() (map[string]any, error) {
	files, err := filepath.Glob(filepath.Join(gotemplateTemplatesDir, "*.html"))
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	propSet, htmlSet := map[string]bool{}, map[string]bool{}
	var fileRecords []any
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		fileRecords = append(fileRecords, map[string]any{"name": filepath.Base(f), "len": len(b)})
		for _, m := range gotemplatePropRe.FindAllStringSubmatch(string(b), -1) {
			propSet[m[1]] = true
		}
		for _, m := range gotemplateHTMLRe.FindAllStringSubmatch(string(b), -1) {
			htmlSet[m[1]] = true
		}
	}
	// Structured props are set explicitly.
	for _, k := range []string{"Posts", "Browsers", "App", "SystemBrowser", "BulletListItems"} {
		delete(propSet, k)
	}
	props := gtSortedKeys(propSet)
	htmls := gtSortedKeys(htmlSet)

	probe, err := templates.New(gotemplateTemplatesDir)
	if err != nil {
		return nil, err
	}
	_ = probe
	// The template names come from a parse of the same files through html/template itself.
	set, err := htmltemplate.ParseGlob(filepath.Join(gotemplateTemplatesDir, "*.html"))
	if err != nil {
		return nil, err
	}
	var names []string
	for _, t := range set.Templates() {
		names = append(names, t.Name())
	}
	sort.Strings(names)

	var variants []any
	for _, variant := range []string{"escape", "javascript", "empty", "typed", "missing"} {
		container, err := templates.New(gotemplateTemplatesDir)
		if err != nil {
			return nil, err
		}
		data := gotemplateMattermostData(variant, props, htmls)
		var runs []any
		for _, name := range names {
			out, err := container.RenderToString(name, data)
			runs = append(runs, map[string]any{"name": name, "out": out, "err": gtErrString(err)})
		}
		variants = append(variants, map[string]any{
			"variant": variant,
			"data":    gotemplateEncodeAny(data),
			"runs":    runs,
		})
	}
	return map[string]any{
		"files":    fileRecords,
		"names":    names,
		"variants": variants,
	}, nil
}

func gtSortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------------------------------------
// The targeted corpora.

// gtCase is one template set: its sources parsed in order (the first becomes the set's root, the
// rest `New(name).Parse`), then each name in Exec executed in order against Data.
type gtCase struct {
	Name    string
	Sources [][2]string
	Exec    []string
	Data    any
	Option  string
}

func gtOne(name, src string, data any) gtCase {
	return gtCase{Name: name, Sources: [][2]string{{"t", src}}, Exec: []string{"t"}, Data: data}
}

type gtSample struct {
	Name string
	V    any
}

func gtValues() []gtSample {
	type person struct {
		Name string
		Age  int
	}
	return []gtSample{
		{"markup", `<a href="x">O'Reilly & "co"</a>`},
		{"nonascii", "héllo 日本 \u2028\u2029 \u00a0 \ufffd"},
		{"jsurl", "javascript:alert(1)"},
		{"jsurl_upper", " JavaScript:alert(1)"},
		{"spaces_pct", "/path with space?q=a b&r=100%&s=%41#frag"},
		{"mailto", "mailto:x@y.com"},
		{"http", "HTTP://Example.com/x?y=1"},
		{"relative_colon", "/a:b"},
		{"html", htmltemplate.HTML(`<b>bold</b> &amp; <i title="t">x</i> <script>s()</script>`)},
		{"url", htmltemplate.URL("javascript:ok(1)")},
		{"css", htmltemplate.CSS("color: red")},
		{"js", htmltemplate.JS("alert(1)")},
		{"jsstr", htmltemplate.JSStr(`a\"b'c`)},
		{"attr", htmltemplate.HTMLAttr(` checked="checked"`)},
		{"srcset_typed", htmltemplate.Srcset("a.png 1x, b.png 2x")},
		{"empty", ""},
		{"int", 42},
		{"negint", -7},
		{"float", 3.5},
		{"bigfloat", 1e21},
		{"bool", true},
		{"nil", nil},
		{"nilptr", (*string)(nil)},
		{"ptr", sp("pointed <at>")},
		{"list", []any{1, "a<b", nil, true}},
		{"map", map[string]any{"b": 2, "a": "x&y"}},
		{"struct", person{Name: "Ann <3", Age: 30}},
		{"controls", "\x00\t\n\x7f\x1f\u0085"},
		{"css_expr", "expression(alert(1))"},
		{"css_ok", "#fff"},
		{"css_moz", "-moz-binding:url(x)"},
		{"css_dashes", "a--b"},
		{"srcset", "a.png 1x, javascript:x 2x, /b%20c.png  3w , , ok.png"},
		{"script_close", "</script><script>alert(1)</script><!--"},
		{"backtick", "`${x}` $ { }"},
		{"regexp", `.*+?^$()[]{}|/\-`},
		{"entities", "&lt; &amp;amp; &#39;"},
		{"quotes_ws", "a b\"c'd=e`f\tg\nh"},
		{"plus", "1+1=2"},
		{"ls", "a\u2028b"},
	}
}

func gtContexts() []gtSample {
	return []gtSample{
		{"text", `<p>{{.}}</p>`},
		{"title", `<title>{{.}}</title>`},
		{"textarea", `<textarea>{{.}}</textarea>`},
		{"attr_dq", `<p title="{{.}}">`},
		{"attr_sq", `<p title='{{.}}'>`},
		{"attr_uq", `<p title={{.}}>`},
		{"attr_name", `<p {{.}}="x">`},
		{"attr_name_bare", `<input {{.}}>`},
		{"attr_name_uq_value", `<input {{.}}=v>`},
		{"url_dq", `<a href="{{.}}">`},
		{"url_uq", `<a href={{.}}>`},
		{"url_sq", `<a href='{{.}}'>`},
		{"url_prefix", `<a href="/p/{{.}}">`},
		{"url_query", `<a href="/p?q={{.}}">`},
		{"url_frag", `<a href="/p#{{.}}">`},
		{"url_then_path", `<a href="{{.}}/x?y">`},
		{"url_src", `<img src="{{.}}">`},
		{"url_data_attr", `<a data-href="{{.}}">`},
		{"url_xmlns", `<a xmlns:foo="{{.}}">`},
		{"url_ns_attr", `<a foo:href="{{.}}">`},
		{"url_background", `<td background="{{.}}">`},
		{"srcset", `<img srcset="{{.}}">`},
		{"srcset_after", `<img srcset="a.png {{.}}">`},
		{"css_value", `<style>p { color: {{.}} }</style>`},
		{"css_dq", `<style>p { font-family: "{{.}}" }</style>`},
		{"css_sq", `<style>p { font-family: '{{.}}' }</style>`},
		{"css_url", `<style>p { background: url({{.}}) }</style>`},
		{"css_url_dq", `<style>p { background: url("{{.}}") }</style>`},
		{"css_url_sq", `<style>p { background: url('/i/{{.}}') }</style>`},
		{"style_attr", `<p style="color: {{.}}">`},
		{"style_attr_url", `<p style="background: url('{{.}}')">`},
		{"js_value", `<script>var x = {{.}};</script>`},
		{"js_dq", `<script>var s = "{{.}}";</script>`},
		{"js_sq", `<script>var s = '{{.}}';</script>`},
		{"js_tmpl", "<script>var s = `a{{.}}b`;</script>"},
		{"js_tmpl_expr", "<script>var s = `a${ {{.}} }b`;</script>"},
		{"js_regexp", `<script>var r = /a{{.}}b/;</script>`},
		{"js_div", `<script>var r = y / {{.}} / 2;</script>`},
		{"js_line_cmt", "<script>// c {{.}}\nx = 1</script>"},
		{"js_block_cmt", `<script>/* c {{.}} */ x = 1</script>`},
		{"js_onclick", `<button onclick="f({{.}})">`},
		{"js_onclick_str", `<button onclick='f("{{.}}")'>`},
		{"js_onclick_uq", `<button onclick=f({{.}})>`},
		{"js_json_type", `<script type="application/json">{{.}}</script>`},
		{"js_text_type", `<script type="text/template">{{.}}</script>`},
		{"html_cmt", `<!-- {{.}} -->a`},
		{"meta_refresh", `<meta http-equiv="refresh" content="0; url={{.}}">`},
		{"meta_content", `<meta name="d" content="{{.}}">`},
		{"lt_text", `a < b {{.}}`},
		{"tag_open", `<{{.}}`},
		{"doctype", `<!DOCTYPE html><p>{{.}}</p>`},
	}
}

func gtHTMLCorpus() []gtCase {
	var cases []gtCase
	for _, ctx := range gtContexts() {
		for _, v := range gtValues() {
			cases = append(cases, gtOne("ctx/"+ctx.Name+"/"+v.Name, ctx.V.(string), map[string]any{"v": v.V}))
		}
	}
	// The context templates above read `.`; make them read the map entry instead.
	for i := range cases {
		cases[i].Sources[0][1] = strings.ReplaceAll(cases[i].Sources[0][1], "{{.}}", "{{.v}}")
	}

	add := func(c gtCase) { cases = append(cases, c) }
	data := map[string]any{
		"S": "<s&'\">", "U": "javascript:x()", "E": "", "N": 7, "L": []any{"a<", "b>", "c&"},
		"M": map[string]any{"k1": "v<1>", "k2": "v2"}, "B": true, "F": false, "H": htmltemplate.HTML("<b>h</b>"),
		"NP": (*string)(nil), "Z": nil,
	}
	one := func(name, src string) { add(gtOne(name, src, data)) }
	// dataP adds a non-nil pointer. fmt prints a pointer nested inside a container as its address,
	// so it is only used by cases that print it at top level, where it is dereferenced.
	dataP := map[string]any{}
	for k, v := range data {
		dataP[k] = v
	}
	dataP["P"] = sp("<p>")
	oneP := func(name, src string) { add(gtOne(name, src, dataP)) }

	// Text: comment stripping, `<` escaping, doctype, conditional comments (Mattermost's MSO blocks).
	one("text/comment_stripped", "a<!-- x -->b{{.S}}c")
	one("text/comment_unclosed", "a<!--b {{.S}}")
	one("text/comment_then_action", "<!--[if mso]><table><![endif]-->{{.S}}<!--[if !mso]><!-- -->x<!--<![endif]-->")
	one("text/lt_heart", "I <3 ponies {{.S}} a<b")
	one("text/doctype_lower", "<!doctype html>{{.S}}")
	one("text/entity_in_text", "&amp; &lt; {{.S}}")
	one("text/tag_attrs", `<a b c=d e='f' g="h">{{.S}}</a>`)
	one("text/end_tag_script", "<script>x = 1</script>{{.S}}")
	one("text/script_in_string", `<script>var s = "</script>";</script>{{.S}}`)
	one("text/style_block_cmt", "<style>/* c */ p { color: {{.S}} } // x\n</style>")
	one("text/js_cmt_newline", "<script>/* a\nb */ x = {{.N}}</script>")
	one("text/js_html_cmt", "<script><!-- x\n{{.N}} --> y\nz = {{.N}}</script>")
	one("text/js_hashbang", "<script>#! x\ny = {{.N}}</script>")
	one("text/uppercase_tags", `<SCRIPT>var x = {{.S}}</SCRIPT><A HREF="{{.U}}">`)
	one("text/tag_with_dash", `<my-el data-x="{{.S}}">`)
	one("text/textarea_end", "<textarea>{{.S}}</textarea >after {{.S}}")
	one("text/title_nested_tag", "<title><b>{{.S}}</b></title>")

	// Values of every kind in text context.
	oneP("kinds/all", "{{.S}}|{{.E}}|{{.N}}|{{.L}}|{{.M}}|{{.B}}|{{.H}}|{{.P}}|{{.NP}}|{{.Z}}|{{.Missing}}|{{.M.k1}}|{{.M.none}}")
	oneP("kinds/in_attr", `<p a="{{.L}}" b="{{.M}}" c="{{.P}}" d="{{.NP}}" e="{{.Z}}" f="{{.H}}">`)
	oneP("kinds/in_js", `<script>var a = [{{.S}}, {{.N}}, {{.L}}, {{.M}}, {{.B}}, {{.H}}, {{.P}}, {{.NP}}, {{.Z}}, {{.Missing}}];</script>`)
	one("kinds/in_url", `<a href="{{.L}}" title="{{.N}}"><a href="/{{.M}}">`)
	add(gtOne("kinds/js_float", `<script>var f = [{{.a}}, {{.b}}, {{.c}}, {{.d}}, {{.e}}];</script>`, map[string]any{"a": 1e21, "b": 1e-7, "c": 0.1, "d": -0.0, "e": 100.0}))
	add(gtOne("kinds/js_nan", `<script>var f = {{.}};</script>`, math.NaN()))
	add(gtOne("kinds/js_struct", `<script>var f = {{.}};</script>`, struct {
		A string
		B []int
		C map[string]any
		D *string
	}{"x<", []int{1, 2}, map[string]any{"z": nil}, nil}))
	add(gtOne("kinds/js_ident_pad", `<script>var f = typeof{{.}}in x;</script>`, 12))

	// Predefined escapers.
	one("predef/html_pipe", "{{.S | html}}")
	one("predef/html_call", "{{html .S}}")
	one("predef/html_args", "{{html .S .N}}")
	one("predef/urlquery_query", `<a href="/?q={{.S | urlquery}}">`)
	one("predef/urlquery_call", `<a href="/?q={{urlquery .S .N}}">`)
	one("predef/html_in_attr", `<p title="{{.S | html}}">`)
	one("predef/print_html", "{{print .S .N | html}}")
	one("predef/html_not_last", "{{.S | html | print}}")
	one("predef/html_uq_attr", "<p title={{.S | html}}>")
	one("predef/urlquery_in_url_start", `<a href="{{.S | urlquery}}">`)
	one("predef/js_builtin", `<script>var s = "{{js .S}}";</script>`)
	one("predef/html_in_script", `<script>var s = {{html .S}};</script>`)

	// {{template}} into contexts: derived templates.
	subs := [][2]string{{"t", ""}, {"sub", `{{.}}`}}
	for _, ctx := range []gtSample{
		{"text", `<p>{{template "sub" .S}}</p>`},
		{"attr", `<p title="{{template "sub" .S}}">`},
		{"url", `<a href="{{template "sub" .U}}">`},
		{"url_query", `<a href="/x?{{template "sub" .S}}">`},
		{"js", `<script>var x = {{template "sub" .S}};</script>`},
		{"js_str", `<script>var x = "{{template "sub" .S}}";</script>`},
		{"css", `<p style="color: {{template "sub" .S}}">`},
		{"rcdata", `<title>{{template "sub" .S}}</title>`},
		{"twice", `<p title="{{template "sub" .S}}">{{template "sub" .S}}<a href="{{template "sub" .U}}">`},
		{"nil_dot", `<p>[{{template "sub"}}]`},
	} {
		c := gtCase{Name: "tmpl/" + ctx.Name, Sources: [][2]string{{"t", ctx.V.(string)}, subs[1]}, Exec: []string{"t", "sub"}, Data: data}
		add(c)
	}
	// Sequences on one set: order-dependent derivation.
	add(gtCase{Name: "seq/sub_first", Sources: [][2]string{{"t", `<a href="{{template "sub" .U}}">`}, {"sub", `x{{.}}<!-- c -->`}}, Exec: []string{"sub", "t", "sub"}, Data: data})
	add(gtCase{Name: "seq/t_first", Sources: [][2]string{{"t", `<a href="{{template "sub" .U}}">`}, {"sub", `x{{.}}<!-- c -->`}}, Exec: []string{"t", "sub", "t"}, Data: data})
	add(gtCase{Name: "seq/text_then_attr", Sources: [][2]string{{"a", `<p>{{template "sub" .S}}</p>`}, {"b", `<p title="{{template "sub" .S}}">`}, {"sub", `{{.}}<b>`}}, Exec: []string{"a", "b", "sub"}, Data: data})
	add(gtCase{Name: "seq/attr_then_text", Sources: [][2]string{{"a", `<p>{{template "sub" .S}}</p>`}, {"b", `<p title="{{template "sub" .S}}">`}, {"sub", `{{.}}`}}, Exec: []string{"b", "a", "sub"}, Data: data})
	add(gtCase{Name: "seq/error_sticky", Sources: [][2]string{{"t", `<a href="{{.U}}`}, {"u", `{{.S}}`}}, Exec: []string{"t", "t", "u", "nope"}, Data: data})
	add(gtCase{Name: "seq/define_in_file", Sources: [][2]string{{"f.html", "{{define \"a\"}}<b>{{.S}}</b>{{end}}\n  {{define \"b\"}}{{template \"a\" .}}<i>{{.N}}</i>{{end}}\n"}}, Exec: []string{"b", "a", "f.html"}, Data: data})
	add(gtCase{Name: "seq/block", Sources: [][2]string{{"t", `<p>{{block "blk" .S}}[{{.}}]{{end}}</p>`}}, Exec: []string{"t", "blk"}, Data: data})
	add(gtCase{Name: "seq/redefine", Sources: [][2]string{{"a.html", `{{define "x"}}one {{.S}}{{end}}`}, {"b.html", `{{define "x"}}two {{.S}}{{end}}`}}, Exec: []string{"x", "a.html"}, Data: data})
	add(gtCase{Name: "seq/empty_redefine", Sources: [][2]string{{"a.html", `{{define "x"}}one {{.S}}{{end}}`}, {"b.html", `{{define "x"}} {{/* c */}} {{end}}`}}, Exec: []string{"x"}, Data: data})
	add(gtCase{Name: "seq/recursive", Sources: [][2]string{{"t", `{{define "r"}}{{if .}}<i>{{index . 0}}</i>{{template "r" (slice . 1)}}{{end}}{{end}}{{template "r" .L}}`}}, Exec: []string{"t", "r"}, Data: data})

	// Branch joins.
	one("join/if_same", `<p>{{if .B}}<b>{{.S}}</b>{{else}}<i>{{.S}}</i>{{end}}</p>`)
	one("join/if_attr_nudge", `<p title={{if .B}}{{.S}}{{end}}>`)
	one("join/if_url_parts", `<a href="{{if .B}}/a?x={{.S}}{{else}}/b/{{.S}}{{end}}">`)
	one("join/if_url_ambiguous", `<a href="{{if .B}}/a?{{end}}{{.S}}">`)
	one("join/if_diff_ctx", `{{if .B}}<a href="{{else}}<a title="{{end}}x">`)
	one("join/if_js_ctx", `<script>{{if .B}}x = {{else}}x{{end}} / 2 / 1</script>`)
	one("join/if_js_ctx_slash_ambig", `<script>{{if .B}}x ={{else}}x{{end}}/foo/</script>`)
	one("join/with", `{{with .M}}<b>{{.k1}}</b>{{else}}none{{end}}`)
	one("join/with_else_with", `{{with .Missing}}a{{else with .M}}<b>{{.k2}}</b>{{end}}`)
	one("join/else_if", `{{if .F}}a{{else if .B}}<b>{{.S}}</b>{{else}}c{{end}}`)
	one("range/list", `{{range .L}}<p>{{.}}</p>{{else}}empty{{end}}`)
	one("range/kv", `{{range $i, $v := .L}}<p title="{{$i}}">{{$v}}</p>{{end}}`)
	one("range/map", `{{range $k, $v := .M}}<a href="/{{$k}}?v={{$v}}">{{end}}`)
	one("range/else_empty", `{{range .E}}x{{else}}<b>{{.S}}</b>{{end}}`)
	one("range/reentry", `{{range .L}}<a href="{{.}}{{end}}">`)
	one("range/break", `{{range .L}}{{if eq . "b>"}}{{break}}{{end}}<b>{{.}}</b>{{end}}`)
	one("range/continue", `{{range .L}}{{if eq . "b>"}}{{continue}}{{end}}<b>{{.}}</b>{{end}}`)
	one("range/break_ctx_error", `{{range .L}}<a href="{{if .}}{{break}}{{end}}">{{end}}`)
	one("range/int", `{{range 3}}<b>{{.}}</b>{{end}}`)

	// Escaper errors.
	one("err/end_ctx", `<a href="{{.U}}`)
	one("err/end_ctx_script", `<script>var x = 1`)
	one("err/unquoted_attr_char", `<p title=a'b>{{.S}}`)
	one("err/attr_name_quote", `<p a"b>{{.S}}`)
	one("err/attr_name_lt", `<p a<b>{{.S}}`)
	one("err/tag_bad", `<p ="x">{{.S}}`)
	one("err/js_partial_escape", `<script>var s = "\{{.S}}";</script>`)
	one("err/js_partial_charset", `<script>var r = /[{{.S}}]/;</script>`)
	one("err/css_partial_escape", `<style>p { content: "\{{.S}}" }</style>`)
	one("err/no_such_template", `{{template "nope" .}}`)
	one("err/output_ctx", `{{define "r"}}<a href="{{template "r"}}{{end}}{{template "r"}}`)
	one("err/predef_uq", `<p title={{.S | html}}>`)
	one("err/js_tmpl_partial", "<script>var s = `\\{{.S}}`;</script>")
	one("err/after_error_ok", `{{.S}}`)

	// JS details.
	one("js/brace_depth", "<script>var s = `${ {a: {{.S}} } }` + {{.S}};</script>")
	one("js/regexp_close", `<script>var r = /a<\/script>b/; x = {{.S}}</script>`)
	one("js/keywords", `<script>return /{{.S}}/.test(x); typeof {{.N}}</script>`)
	one("js/postfix", `<script>x++ / {{.N}}; y-- / {{.N}}; z = a - -{{.N}}</script>`)
	one("js/dot_number", `<script>x = 42. / {{.N}}; y = . /{{.S}}/</script>`)
	one("js/script_type_module", `<script type="module">let v = {{.S}}</script>`)
	one("js/script_in_attr_value", `<a onclick="var s = '</script>'; f({{.S}})">`)
	one("js/special_tags_in_string", `<script>var s = "<!-- <script> </SCRIPT";</script>`)

	// Attribute and URL details.
	one("attr/entity_decoded_js", `<button onclick="alert(&quot;{{.S}}&quot;)">`)
	one("attr/entity_decoded_url", `<a href="&#x6a;avascript:{{.S}}">`)
	one("attr/unquoted_space_ends", `<a href=/x/{{.S}} title={{.S}}>`)
	one("attr/value_less", `<input checked title="{{.S}}">`)
	one("attr/dynamic_name_value", `<input {{.E}}="{{.S}}" {{.S}}={{.S}}>`)
	one("attr/attr_typed_name", `<input {{.A}}>`)
	add(gtOne("attr/attr_typed", `<input {{.}}>`, htmltemplate.HTMLAttr(`checked`)))
	add(gtOne("attr/onx_name", `<input {{.}}="x">`, "onclick"))
	add(gtOne("attr/href_name", `<input {{.}}="x">`, "href"))
	add(gtOne("attr/upper_name", `<input {{.}}="x">`, "TITLE"))
	add(gtOne("attr/bad_name", `<input {{.}}="x">`, "a-b"))
	one("url/norm_then_escape", `<a href="{{.S}}/{{.S}}?{{.S}}#{{.S}}">`)
	add(gtOne("url/pct_kept", `<a href="{{.}}">`, "/a%20b%zz%2"))
	add(gtOne("url/pct_query", `<a href="/?q={{.}}">`, "a%20b%zz"))
	add(gtOne("url/typed_url_query", `<a href="/?q={{.}}">`, htmltemplate.URL("a b&c")))
	add(gtOne("url/typed_url_srcset", `<img srcset="{{.}}">`, htmltemplate.URL("a b,c.png")))
	add(gtOne("url/html_in_url", `<a href="{{.}}">`, htmltemplate.HTML("<b>x</b>")))
	add(gtOne("url/leading_space_js", `<a href="{{.}}">`, " javascript:x"))
	add(gtOne("url/tab_colon", `<a href="{{.}}">`, "java\tscript:x"))
	one("css/url_unquoted_break", `<style>p { background: url(/a/{{.S}}) }</style>`)
	one("css/escape_in_str", `<style>p { content: "a\"{{.S}}" }</style>`)
	add(gtOne("css/decode_escapes", `<p style="color: {{.}}">`, `\65 xpression(1)`))
	add(gtOne("css/decode_escapes2", `<p style="color: {{.}}">`, `\\ \41\42 x`))
	add(gtOne("css/typed_css", `<p style="{{.}}">`, htmltemplate.CSS("color: red; background: url(x)")))
	add(gtOne("css/in_str_escaper", `<style>p { content: "{{.}}" }</style>`, "a\x00b\t\n\"&'()+/:;<>\\{}c 1"))
	add(gtOne("html/strip_tags_attr", `<p title="{{.}}">`, htmltemplate.HTML(`<b title="1>2">x</b> &amp; y<script>z</script> <3`)))
	add(gtOne("html/strip_tags_uq", `<p title={{.}}>`, htmltemplate.HTML(`<b>x y</b>`)))
	add(gtOne("html/rcdata_html", `<title>{{.}}</title>`, htmltemplate.HTML(`<b>x</b> &amp; y`)))
	add(gtOne("html/nospace_empty", `<p title={{.}}>`, ""))
	add(gtOne("html/nospace_bad_runes", `<p title={{.}}>`, "a\ufdd0b\ufff0c\uffff"))

	// Parse errors through html/template.
	one("parse/unclosed", `{{.S`)
	one("parse/undefined_fn", `{{nope .S}}`)

	return cases
}

func gtTextCorpus() []gtCase {
	var cases []gtCase
	add := func(c gtCase) { cases = append(cases, c) }
	type inner struct {
		X string
		Y *string
		Z any
	}
	type outer struct {
		Name  string
		Inner inner
		PI    *inner
		NilPI *inner
		List  []string
		Map   map[string]int
		Any   any
		Low   int
	}
	data := map[string]any{
		"S": "str<&>", "E": "", "N": 42, "Neg": -3, "F": 2.5, "B": true, "Fa": false,
		"L": []any{"a", 2, nil, 3.5}, "LS": []string{"x", "y", "z"}, "EL": []any{},
		"M": map[string]any{"b": 1, "a": "A", "c": nil}, "EM": map[string]any{},
		"P": sp("ptr"), "NP": (*string)(nil), "Z": nil, "H": htmltemplate.HTML("<b>"),
		"Q": struct {
			A string
			B int
			C []string
			D map[string]any
			E any
		}{"qa", 2, []string{"c1"}, map[string]any{"d": 1.5}, nil},
		"O": outer{Name: "o", Inner: inner{X: "ix", Y: sp("iy")}, PI: &inner{X: "px"}, List: []string{"l1", "l2"}, Map: map[string]int{"k": 1}, Any: 5, Low: 9},
		"Big": 1e21, "Small": 1e-7, "Tenth": 0.1, "Whole": 3.0, "NegZero": math.Copysign(0, -1), "NaN": math.NaN(), "Inf": math.Inf(1),
	}
	t := func(name, src string) { add(gtOne(name, src, data)) }

	// Printing.
	t("print/kinds", "{{.S}}|{{.E}}|{{.N}}|{{.Neg}}|{{.F}}|{{.B}}|{{.L}}|{{.LS}}|{{.EL}}|{{.M}}|{{.EM}}|{{.P}}|{{.NP}}|{{.Z}}|{{.H}}|{{.Missing}}")
	t("print/floats", "{{.Big}}|{{.Small}}|{{.Tenth}}|{{.Whole}}|{{.NegZero}}|{{.NaN}}|{{.Inf}}")
	t("print/struct", "{{.Q}}|{{.O.PI}}|{{.O.NilPI}}|{{.O.Inner.Y}}|{{.O.Map}}|{{.O.List}}|{{.O.Any}}")
	t("print/constants", "{{1}}|{{1.5}}|{{1e3}}|{{0x10}}|{{0o17}}|{{0b101}}|{{'a'}}|{{'\\n'}}|{{1_000}}|{{-5}}|{{+5}}|{{.5}}|{{0x1p-2}}|{{true}}|{{\"s\\t\"}}|{{`raw`}}|{{017}}")
	t("print/nil_command", "{{nil}}")
	add(gtOne("print/dot", "{{.}}", map[string]any{"a": []any{1, "x", nil}, "b": map[string]any{"c": 2.5}, "n": nil}))
	add(gtOne("print/dot_nil", "[{{.}}]", nil))
	add(gtOne("print/dot_string", "[{{.}}]", "x"))
	add(gtOne("print/html_type", "{{.}}", htmltemplate.HTML("<b>")))

	// Fields and missing keys.
	t("field/missing_map", "[{{.Missing}}][{{.M.zz}}][{{.M.c}}]")
	t("field/missing_chain", "[{{.Missing.X.Y}}]")
	t("field/nil_value_chain", "[{{.M.c.X}}]")
	t("field/on_string", "{{.S.X}}")
	t("field/on_int", "{{.N.X}}")
	t("field/nil_ptr", "{{.NP.X}}")
	t("field/struct_missing", "{{.O.Nope}}")
	t("field/struct_nilptr_field", "{{.O.NilPI.X}}")
	t("field/struct_ptr_field", "{{.O.PI.X}}|{{.O.PI.Y}}|{{.O.PI.Z}}")
	t("field/with_args", "{{.O.Name 1}}")
	t("field/map_with_args", "{{.M.a 1}}")
	t("field/list", "{{.L.X}}")
	t("field/chain_paren", "{{(.O).Inner.X}}|{{(index .L 0)}}")
	t("field/chain_nil", "{{(nil).X}}")
	t("field/var_chain", "{{$x := .O}}{{$x.Inner.X}}|{{$.S}}")
	add(gtCase{Name: "field/missingkey_zero", Sources: [][2]string{{"t", "[{{.Missing}}][{{.M.zz}}]"}}, Exec: []string{"t"}, Data: data, Option: "missingkey=zero"})
	add(gtCase{Name: "field/missingkey_error", Sources: [][2]string{{"t", "[{{.M.zz}}]"}}, Exec: []string{"t"}, Data: data, Option: "missingkey=error"})
	add(gtCase{Name: "field/missingkey_error_nil", Sources: [][2]string{{"t", "[{{.Missing.X}}]"}}, Exec: []string{"t"}, Data: data, Option: "missingkey=error"})
	add(gtOne("field/on_nil_data", "[{{.X}}]", nil))

	// Control structures.
	t("if/truthiness", "{{if .S}}S{{end}}{{if .E}}E{{end}}{{if .N}}N{{end}}{{if .F}}F{{end}}{{if .Fa}}Fa{{end}}{{if .L}}L{{end}}{{if .EL}}EL{{end}}{{if .M}}M{{end}}{{if .EM}}EM{{end}}{{if .P}}P{{end}}{{if .NP}}NP{{end}}{{if .Z}}Z{{end}}{{if .O}}O{{end}}{{if .Missing}}Mi{{end}}{{if 0}}0{{end}}{{if 0.0}}0.0{{end}}{{if .H}}H{{end}}")
	t("if/else_chain", "{{if .Fa}}a{{else if .E}}b{{else if .N}}c{{else}}d{{end}}")
	t("with/else", "{{with .E}}x{{else}}empty{{end}}|{{with .S}}{{.}}{{end}}|{{with $x := .N}}{{$x}}{{end}}")
	t("with/else_with", "{{with .E}}x{{else with .S}}[{{.}}]{{end}}")
	t("range/list", "{{range .L}}[{{.}}]{{end}}")
	t("range/kv", "{{range $i, $e := .LS}}{{$i}}={{$e}};{{end}}")
	t("range/map", "{{range $k, $v := .M}}{{$k}}={{$v}};{{end}}")
	t("range/map_one_var", "{{range $v := .M}}{{$v}};{{end}}")
	t("range/else", "{{range .EL}}x{{else}}none{{end}}|{{range .Missing}}x{{else}}nil{{end}}")
	t("range/int", "{{range 3}}{{.}}{{end}}|{{range $i := 2}}{{$i}}{{end}}|{{range 0}}x{{else}}zero{{end}}")
	t("range/int_two_vars", "{{range $i, $j := 3}}{{end}}")
	t("range/break_continue", "{{range .LS}}{{if eq . \"y\"}}{{continue}}{{end}}{{.}}{{if eq . \"z\"}}{{break}}{{end}}{{end}}")
	t("range/assign", "{{$x := 0}}{{range $x = .LS}}{{end}}{{$x}}|{{$i := 0}}{{$e := 0}}{{range $i, $e = .LS}}{{end}}{{$i}}{{$e}}")
	t("range/string", "{{range .S}}{{.}}{{end}}")
	t("range/dollar", "{{range .LS}}{{$.N}}{{end}}")
	t("vars/scope", "{{$x := 1}}{{if true}}{{$x = 2}}{{$y := 3}}{{end}}{{$x}}")
	t("vars/decl_no_print", "{{$x := .S}}[{{$x}}]")
	t("vars/two_decl_non_range", "{{$a, $b := 1}}")
	t("vars/range_three", "{{range $a, $b, $c := .L}}{{end}}")

	// Functions.
	t("fn/and_or", "{{and 1 0 2}}|{{and 1 2}}|{{or 0 \"\" 3}}|{{or 0 \"\"}}|{{and .N .S}}|{{or .Missing .S}}|{{.N | and 1}}|{{0 | or 5}}")
	t("fn/and_short_circuit", "{{and 0 (index .L 99)}}|{{or 1 (index .L 99)}}")
	t("fn/not", "{{not .S}}|{{not .E}}|{{not .Missing}}|{{not 0}}")
	t("fn/len", "{{len .S}}|{{len .L}}|{{len .M}}|{{len .P}}|{{len \"héllo\"}}")
	t("fn/len_int", "{{len .N}}")
	t("fn/len_nilptr", "{{len .NP}}")
	t("fn/len_missing", "{{len .Missing}}")
	t("fn/index", "{{index .L 0}}|{{index .LS 2}}|{{index .M \"a\"}}|{{index .M \"zz\"}}|{{index .S 1}}|{{index .O.Map \"k\"}}")
	// A map whose element type is not interface{}: index of an absent key is the element
	// type's zero value (0 here). The Rust model's maps are map[string]interface {}.
	t("fn/index_typed_map_missing", "{{index .O.Map \"none\"}}")
	t("fn/index_oob", "{{index .L 99}}")
	t("fn/index_nil", "{{index nil 1}}")
	t("fn/index_bad", "{{index .N 1}}")
	t("fn/index_key_type", "{{index .M 1}}")
	t("fn/slice", "{{slice .LS 1}}|{{slice .LS 1 2}}|{{slice .S 1 3}}|{{slice .LS}}")
	t("fn/slice_bad", "{{slice .LS 2 1}}")
	t("fn/cmp", "{{eq 1 1}}|{{eq .N 42}}|{{eq .S \"str<&>\"}}|{{eq 1 2 3 1}}|{{ne 1 2}}|{{lt 1 2}}|{{le 2 2}}|{{gt \"b\" \"a\"}}|{{ge 1.5 2.5}}|{{eq .H \"<b>\"}}|{{eq .Missing .Z}}|{{eq .B true}}")
	t("fn/cmp_incompatible", "{{eq 1 \"1\"}}")
	t("fn/cmp_lt_bool", "{{lt true false}}")
	t("fn/cmp_nil", "{{eq .Z nil}}")
	t("fn/cmp_noargs", "{{eq 1}}")
	t("fn/cmp_maps", "{{eq .M .M}}")
	t("fn/print", "{{print 1 2 \"a\" \"b\" 3 .Z .B}}|{{println 1 \"a\"}}|{{print}}|{{print .NP .H}}")
	t("fn/printf", `{{printf "%d|%5d|%-5d|%05d|%+d|%x|%X|%o|%b|%c|%U|%q" 42 42 42 42 42 255 255 8 5 65 9731 65}}`)
	t("fn/printf_str", `{{printf "%s|%q|%v|%10s|%-10s|%.2s|%x|% x|%#q|%+q" "hé" "a\"b" "v" "r" "l" "abc" "hi" "hi" "back" "é"}}`)
	t("fn/printf_float", `{{printf "%f|%.2f|%e|%E|%g|%G|%8.3f|%-8.2f|%+.1f|%v|%.0f|%.1f|%.2f|%.3g" 3.14159 2.675 1234.5678 0.000123 1e21 1e-7 3.14159 2.5 2.5 0.1 2.5 0.25 0.125 1234.5}}`)
	t("fn/printf_misc", `{{printf "%t|%v|%v|%v|%v|%%|%d|%s|%d" true .L .M .Q nil 1 .LS .Q}}`)
	t("fn/printf_errors", `{{printf "%d|%s|%z|%d" "str" 5 1}}|{{printf "%d %d" 1}}|{{printf "%d" 1 2 "x"}}|{{printf "%!"}}|{{printf "%"}}`)
	t("fn/printf_star", `{{printf "%*d|%-*d|%.*f" 5 1 4 2 2 3.14159}}`)
	t("fn/printf_ptr", `{{printf "%s|%v|%d" .NP .NP .Z}}`)
	t("fn/printf_nonstring_format", `{{printf .N}}`)
	t("fn/printf_nil_format", `{{printf nil}}`)
	t("fn/printf_html_format", `{{printf .H}}`)
	t("fn/html_js_urlquery", `{{html .S "'"}}|{{js "a'b\"c<d>e&f=g\\h\u2028\x01"}}|{{urlquery "a b&c=d/é"}}|{{html .Missing}}|{{js 1 2}}|{{urlquery .P}}`)
	t("fn/call", `{{call .S}}`)
	t("fn/wrong_args", `{{len 1 2}}`)
	t("fn/not_a_function_arg", `{{.S 1}}`)
	t("fn/pipe_final", `{{"x" | printf "%s-%s" "y"}}`)
	t("fn/pipe_into_nonfunc", `{{1 | .S}}`)
	t("fn/string_arg_type", `{{printf "%s" .N | printf}}`)

	// Templates.
	add(gtCase{Name: "tmpl/define_call", Sources: [][2]string{{"t", `{{define "a"}}A{{.}}{{end}}[{{template "a" .S}}][{{template "a"}}]`}}, Exec: []string{"t"}, Data: data})
	add(gtCase{Name: "tmpl/not_defined", Sources: [][2]string{{"t", `{{template "zz"}}`}}, Exec: []string{"t"}, Data: data})
	add(gtCase{Name: "tmpl/exec_missing", Sources: [][2]string{{"t", `x`}}, Exec: []string{"nope"}, Data: data})
	add(gtCase{Name: "tmpl/block", Sources: [][2]string{{"t", `<{{block "b" .N}}{{.}}{{end}}>`}, {"u", `{{define "b"}}override{{end}}`}}, Exec: []string{"t", "b"}, Data: data})
	add(gtCase{Name: "tmpl/vars_not_inherited", Sources: [][2]string{{"t", `{{$x := 1}}{{define "a"}}{{$x}}{{end}}`}}, Exec: []string{"t"}, Data: data})
	add(gtCase{Name: "tmpl/multiple_definition", Sources: [][2]string{{"t", `{{define "a"}}1{{end}}{{define "a"}}2{{end}}`}}, Exec: []string{"t"}, Data: data})
	add(gtCase{Name: "tmpl/redefine_later", Sources: [][2]string{{"t", `{{define "a"}}1{{end}}`}, {"u", `{{define "a"}}2{{end}}`}}, Exec: []string{"a"}, Data: data})
	add(gtCase{Name: "tmpl/error_in_define", Sources: [][2]string{{"f.tmpl", "line1\n{{define \"a\"}}\n  {{.S.X}}\n{{end}}"}}, Exec: []string{"a"}, Data: data})

	// Whitespace, comments, trim markers.
	t("lex/trim", "a  {{- .S -}}  b|{{- 3}}|{{-3}}|  {{- /* c */ -}}  |x {{/* c */}} y")
	t("lex/trim_newlines", "a\n\n{{- .N}}\n\n{{.N -}}\n\nb")
	t("lex/comment_multiline", "a{{/* line1\nline2 */}}b")

	// Parse errors.
	for _, pe := range [][2]string{
		{"unclosed_action", "a {{.S"},
		{"unclosed_action_newline", "a {{.S\n\nb"},
		{"unexpected_eof", "{{if .S}}x"},
		{"undefined_var", "{{$x}}"},
		{"undefined_fn", "{{nope 1}}"},
		{"bad_number", "{{3k}}"},
		{"unterminated_string", "{{\"abc}}"},
		{"unterminated_raw", "{{`abc}}"},
		{"unterminated_char", "{{'a}}"},
		{"missing_if_value", "{{if}}x{{end}}"},
		{"else_outside", "{{else}}"},
		{"end_outside", "{{end}}"},
		{"break_outside", "{{break}}"},
		{"continue_outside", "{{continue}}"},
		{"non_executable_stage", "{{.S | 1}}"},
		{"dot_after_literal", "{{\"a\".X}}"},
		{"unclosed_comment", "{{/* abc"},
		{"comment_before_delim", "{{/* abc */ x}}"},
		{"illegal_number", "{{089}}"},
		{"integer_overflow", "{{99999999999999999999}}"},
		{"uint_overflows_int", "{{18446744073709551615}}"},
		{"too_many_decls", "{{$a, $b := 1}}"},
		{"range_init_only", "{{range $a, 1}}{{end}}"},
		{"bad_character", "{{.S@}}"},
		{"unrecognized_char", "{{\x01}}"},
		{"unexpected_rparen", "{{)}}"},
		{"unclosed_lparen", "{{(1}}"},
		{"expected_declare", "{{$x : 1}}"},
		{"malformed_char", "{{'ab'}}"},
		{"empty_pipe", "{{|}}"},
		{"else_extra_end", "{{if 1}}{{else}}{{else}}{{end}}"},
		{"define_bad_name", "{{define a}}{{end}}"},
		{"define_unclosed", "{{define \"a\"}}x"},
		{"template_bad_name", "{{template x}}"},
		{"unexpected_in_operand", "{{.S \"a\"b}}"},
		{"bad_escape", "{{\"\\q\"}}"},
		{"complex_rejected", "{{1+2i}}"},
		{"nested_action_error", "{{if .S}}\n{{.S\n}}{{end}}"},
		{"range_no_end", "{{range .L}}"},
		{"with_else_bad", "{{with .S}}{{else if}}{{end}}"},
		{"double_else", "{{with .S}}{{else}}{{else}}{{end}}"},
		{"bad_delim_space", "{{ -3}}"},
		{"unicode_ident", "{{.Nämé}}"},
	} {
		add(gtOne("parse/"+pe[0], pe[1], data))
	}
	return cases
}

func gtRun(c gtCase, html bool) map[string]any {
	rec := map[string]any{"name": c.Name, "sources": c.Sources, "exec": c.Exec, "data": gotemplateEncodeAny(c.Data), "option": c.Option}
	var runs []any
	if html {
		var root *htmltemplate.Template
		for _, s := range c.Sources {
			var t *htmltemplate.Template
			if root == nil {
				root = htmltemplate.New(s[0])
				if c.Option != "" {
					root.Option(c.Option)
				}
				t = root
			} else {
				t = root.New(s[0])
			}
			if _, err := t.Parse(s[1]); err != nil {
				rec["parse_err"] = err.Error()
				return rec
			}
		}
		for _, name := range c.Exec {
			var buf bytes.Buffer
			err := root.ExecuteTemplate(&buf, name, c.Data)
			runs = append(runs, map[string]any{"name": name, "out": buf.String(), "err": gtErrString(err)})
		}
	} else {
		var root *texttemplate.Template
		for _, s := range c.Sources {
			var t *texttemplate.Template
			if root == nil {
				root = texttemplate.New(s[0])
				if c.Option != "" {
					root.Option(c.Option)
				}
				t = root
			} else {
				t = root.New(s[0])
			}
			if _, err := t.Parse(s[1]); err != nil {
				rec["parse_err"] = err.Error()
				return rec
			}
		}
		for _, name := range c.Exec {
			var buf bytes.Buffer
			err := root.ExecuteTemplate(&buf, name, c.Data)
			runs = append(runs, map[string]any{"name": name, "out": buf.String(), "err": gtErrString(err)})
		}
	}
	rec["runs"] = runs
	return rec
}

func writeGotemplateBehaviourFixture(outDir, rustDir string) error {
	if err := writeGotemplateUnicodeTables(rustDir); err != nil {
		return err
	}
	if err := writeGotemplateEntityTable(rustDir); err != nil {
		return err
	}
	mm, err := gotemplateMattermostCorpus()
	if err != nil {
		return fmt.Errorf("mattermost corpus: %w", err)
	}
	var htmlCases, textCases []any
	for _, c := range gtHTMLCorpus() {
		htmlCases = append(htmlCases, gtRun(c, true))
	}
	for _, c := range gtTextCorpus() {
		textCases = append(textCases, gtRun(c, false))
	}
	// The same text corpus through html/template: the two differ on missing keys, nil pointers and
	// every escaper, which is the point of recording both.
	var textAsHTML []any
	for _, c := range gtTextCorpus() {
		textAsHTML = append(textAsHTML, gtRun(c, true))
	}
	out := map[string]any{
		"mattermost":   mm,
		"html":         htmlCases,
		"text":         textCases,
		"text_as_html": textAsHTML,
	}
	blob, err := json.MarshalIndent(out, "", " ")
	if err != nil {
		return err
	}
	path := filepath.Join(outDir, "behaviour_gotemplate.json")
	if err := os.WriteFile(path, append(blob, '\n'), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d html, %d text cases)\n", path, len(htmlCases), len(textCases))
	return nil
}
