package main

// Generator + behavioural oracle for model/emoji.go.
//
// This one does two jobs, because emoji.go is unusable without a table it does not contain.
//
//  1. **It emits `crates/mm-model/src/emoji_generated.rs`.** `model.SystemEmojis` lives in
//     emoji_data.go, 4,473 lines of generated map literal, and `IsValidEmojiName` rejects any
//     name in it. Hand-transcribing 4,464 entries is exactly the kind of work CLAUDE.md sends to
//     a generator (the same call as permission.go and the D-001 locale table), so the Rust table
//     is emitted from Go rather than typed. Re-running the generator re-emits it, so a Mattermost
//     bump updates the table instead of silently leaving it stale.
//
//  2. **It writes fixtures/behaviour_emoji.json**, pinning the functions around that table.
//
// The emitted table carries `#[rustfmt::skip]`: at one entry per line some rows exceed
// rustfmt's width and it would re-wrap them, so `cargo fmt` and this generator would rewrite
// each other on every run. With the attribute both are idempotent.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

// --- the generated Rust table -------------------------------------------------------

func writeEmojiTable(rustOutDir string) error {
	names := make([]string, 0, len(model.SystemEmojis))
	for name := range model.SystemEmojis {
		names = append(names, name)
	}
	// Sorted by byte value so the Rust side can binary-search, and so the emitted file is
	// deterministic rather than following Go's randomised map iteration.
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("//! @generated by `reference/dump` from `model.SystemEmojis` (emoji_data.go).\n")
	b.WriteString("//! DO NOT EDIT — re-run `cd reference/dump && go run .` instead.\n")
	b.WriteString("//!\n")
	b.WriteString("//! Maps a system emoji name to its unicode code-point sequence. `IsValidEmojiName`\n")
	b.WriteString("//! rejects every name in here, so a missing entry would let a user create a custom\n")
	b.WriteString("//! emoji the Go server refuses — and one the Go server would then shadow.\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "/// Sorted by name, so [`slice::binary_search_by_key`] applies.\n")
	// rustfmt wraps any entry whose line exceeds its width, which would make `cargo fmt` and
	// this generator rewrite each other on every run. Skipping the item keeps both idempotent.
	fmt.Fprintf(&b, "#[rustfmt::skip]\n")
	fmt.Fprintf(&b, "pub(crate) static SYSTEM_EMOJIS: [(&str, &str); %d] = [\n", len(names))
	for _, name := range names {
		fmt.Fprintf(&b, "    (%s, %s),\n", rustStringLit(name), rustStringLit(model.SystemEmojis[name]))
	}
	b.WriteString("];\n")

	path := filepath.Join(rustOutDir, "emoji_generated.rs")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// rustStringLit quotes for Rust. Every key and value in the table is ASCII
// [a-z0-9_+-] / hex-and-dashes today; the escaping is here so a future entry with a quote or a
// backslash cannot silently emit broken Rust.
func rustStringLit(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// --- the behavioural fixture ----------------------------------------------------------

func writeEmojiBehaviourFixture(outDir string) error {
	out := map[string]any{
		"constants":                   emojiConstants(),
		"system_emoji_count":          len(model.SystemEmojis),
		"system_emoji_sample":         emojiSample(),
		"is_system_emoji_name":        isSystemEmojiNameAll(),
		"get_emoji_name_from_unicode": emojiNameFromUnicodeAll(),
		"is_valid_emoji_name":         isValidEmojiNameAll(),
		"is_valid":                    emojiIsValidAll(),
		"pre_save":                    emojiPreSaveAll(),
		"emoji_pattern":               emojiPatternAll(),
	}

	blob, err := json.MarshalIndent(out, "", "    ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "behaviour_emoji.json"), append(blob, '\n'), 0o644)
}

func emojiConstants() map[string]any {
	return map[string]any{
		"name_max_length": model.EmojiNameMaxLength,
		"sort_by_name":    model.EmojiSortByName,
		"pattern":         model.EmojiPattern.String(),
	}
}

// emojiSample spot-checks the generated table end to end. The names are chosen to cover the
// shapes the table actually contains: plain, with digits, with underscores, with a `+`, with a
// `-`, and a multi-codepoint sequence.
func emojiSample() map[string]emojiLookup {
	names := []string{
		"grinning", "+1", "-1", "100", "1234", "e-mail", "u5272",
		"woman_judge", "flag-gb", "man_technologist_dark_skin_tone",
		"heart", "smile", "thumbsup",
		// Not every value is a code-point sequence: this one maps to its own name.
		"mattermost",
		// A deliberate miss. Go returns ("", false) — and a plain map index would give ""
		// either way, which is why GetSystemEmojiId returns the bool.
		"flag_gb",
	}
	res := make(map[string]emojiLookup, len(names))
	for _, n := range names {
		id, found := model.GetSystemEmojiId(n)
		res[n] = emojiLookup{ID: id, Found: found}
	}
	return res
}

type emojiLookup struct {
	ID    string `json:"id"`
	Found bool   `json:"found"`
}

func isSystemEmojiNameAll() map[string]bool {
	names := []string{
		"grinning", "+1", "100", "mattermost",
		"", "not_an_emoji", "GRINNING", "Grinning", "grinning ", " grinning",
		":grinning:", "1f600",
	}
	res := make(map[string]bool, len(names))
	for _, n := range names {
		res[n] = model.IsSystemEmojiName(n)
	}
	return res
}

type unicodeCase struct {
	Unicode string `json:"unicode"`
	Name    string `json:"name"`
	Count   int    `json:"count"`
}

// emojiNameFromUnicodeAll deliberately includes a code point with several names, since the
// function returns the alphabetically *first* of them plus how many there are. The multi-name
// probes are discovered rather than hard-coded, so the corpus survives an upstream table change.
func emojiNameFromUnicodeAll() []unicodeCase {
	reverse := map[string][]string{}
	for name, code := range model.SystemEmojis {
		reverse[code] = append(reverse[code], name)
	}

	var multi []string
	for code, names := range reverse {
		if len(names) >= 3 {
			multi = append(multi, code)
		}
	}
	sort.Strings(multi)
	if len(multi) > 4 {
		multi = multi[:4]
	}

	probes := append([]string{"1f600", "not-a-codepoint", "", "1F600"}, multi...)
	res := make([]unicodeCase, 0, len(probes))
	for _, p := range probes {
		name, count := model.GetEmojiNameFromUnicode(p)
		res = append(res, unicodeCase{Unicode: p, Name: name, Count: count})
	}
	return res
}

// --- IsValidEmojiName / IsValid / PreSave ---------------------------------------------

func isValidEmojiNameAll() map[string]string {
	names := []string{
		"", "a", "custom_emoji", "custom-emoji", "custom+emoji", "CustomEmoji", "123",
		repeat("a", 64), repeat("a", 65),
		// The pattern is ^[a-zA-Z0-9+_-]+$ — anything else fails.
		"has space", "has.dot", "has:colon", "has/slash", "héllo", "\U0001F600",
		// The byte limit vs the rune count: 32 two-byte characters is 64 bytes.
		repeat("é", 32), repeat("é", 33),
		// System names are rejected *after* the pattern check, with a different error id.
		"grinning", "+1", "100", "mattermost",
	}
	res := make(map[string]string, len(names))
	for _, n := range names {
		if appErr := model.IsValidEmojiName(n); appErr != nil {
			res[n] = appErr.Id
		} else {
			res[n] = ""
		}
	}
	return res
}

type emojiValidCase struct {
	Name     string          `json:"name"`
	Emoji    json.RawMessage `json:"emoji"`
	ErrorID  string          `json:"error_id"`
	Detailed string          `json:"detailed"`
}

func emojiIsValidAll() []emojiValidCase {
	type mut struct {
		name string
		fn   func(e *model.Emoji)
	}
	muts := []mut{
		{"valid", func(e *model.Emoji) {}},
		{"id_empty", func(e *model.Emoji) { e.Id = "" }},
		{"id_short", func(e *model.Emoji) { e.Id = repeat("a", 25) }},
		{"create_at_zero", func(e *model.Emoji) { e.CreateAt = 0 }},
		{"update_at_zero", func(e *model.Emoji) { e.UpdateAt = 0 }},
		{"delete_at_set", func(e *model.Emoji) { e.DeleteAt = 1700000000000 }},
		// CreatorId is only length-checked, and only in bytes — never validated as an id.
		{"creator_id_empty", func(e *model.Emoji) { e.CreatorId = "" }},
		{"creator_id_nonsense", func(e *model.Emoji) { e.CreatorId = "nope" }},
		{"creator_id_26", func(e *model.Emoji) { e.CreatorId = repeat("a", 26) }},
		{"creator_id_27", func(e *model.Emoji) { e.CreatorId = repeat("a", 27) }},
		{"creator_id_multibyte_26_bytes", func(e *model.Emoji) { e.CreatorId = repeat("é", 13) }},
		{"creator_id_multibyte_28_bytes", func(e *model.Emoji) { e.CreatorId = repeat("é", 14) }},
		{"name_empty", func(e *model.Emoji) { e.Name = "" }},
		{"name_system", func(e *model.Emoji) { e.Name = "grinning" }},
		{"name_bad_pattern", func(e *model.Emoji) { e.Name = "has space" }},
		{"name_65", func(e *model.Emoji) { e.Name = repeat("a", 65) }},
	}

	var res []emojiValidCase
	for _, m := range muts {
		e := &model.Emoji{
			Id:        idA,
			CreateAt:  1700000000000,
			UpdateAt:  1700000000000,
			CreatorId: idB,
			Name:      "custom_emoji",
		}
		m.fn(e)

		blob, err := json.Marshal(e)
		if err != nil {
			panic(err)
		}
		c := emojiValidCase{Name: m.name, Emoji: blob}
		if appErr := e.IsValid(); appErr != nil {
			c.ErrorID = appErr.Id
			c.Detailed = appErr.DetailedError
		}
		res = append(res, c)
	}
	return res
}

type emojiPreSaveCase struct {
	Name   string `json:"name"`
	InID   string `json:"in_id"`
	InName string `json:"in_name"`
	// CreateAt/UpdateAt come from GetMillis() and cannot be pinned; these record the invariants
	// that hold regardless of the clock.
	OutName        string `json:"out_name"`
	IDPreserved    bool   `json:"id_preserved"`
	IDGenerated    bool   `json:"id_generated"`
	TimesAreEqual  bool   `json:"times_are_equal"`
	CreateOverride bool   `json:"create_at_overwritten"`
}

func emojiPreSaveAll() []emojiPreSaveCase {
	cases := []struct {
		name, id, emojiName string
	}{
		{"empty_id_is_generated", "", "Custom_Emoji"},
		{"existing_id_kept", idA, "MiXeD"},
		{"name_lowercased", idA, "ALLCAPS"},
		{"name_already_lower", idA, "already_lower"},
		{"name_with_plus", idA, "A+B"},
		{"name_non_ascii", idA, "ÉCLAIR"},
	}

	var res []emojiPreSaveCase
	for _, c := range cases {
		e := &model.Emoji{Id: c.id, Name: c.emojiName, CreateAt: 12345, UpdateAt: 67890}
		e.PreSave()
		res = append(res, emojiPreSaveCase{
			Name:           c.name,
			InID:           c.id,
			InName:         c.emojiName,
			OutName:        e.Name,
			IDPreserved:    c.id != "" && e.Id == c.id,
			IDGenerated:    c.id == "" && len(e.Id) == 26,
			TimesAreEqual:  e.CreateAt == e.UpdateAt,
			CreateOverride: e.CreateAt != 12345,
		})
	}
	return res
}

// --- EmojiPattern -----------------------------------------------------------------------

type patternCase struct {
	In      string   `json:"in"`
	Matches []string `json:"matches"`
}

// EmojiPattern is unanchored and is used to find emoji references inside message text, so what
// matters is which substrings it picks out — including the overlapping cases, where Go's
// leftmost-first scan consumes the shared colon.
func emojiPatternAll() []patternCase {
	inputs := []string{
		"", ":grinning:", "hello :smile: world", ":a::b:", ":a:b:c:",
		"::", ":::", ":no_spaces here:", ":+1: :-1:", ":UPPER:",
		"text:notanemoji", ":has space:", ":a-b_c+d:", ":é:", "::::",
		"a :one: b :two: c",
	}
	res := make([]patternCase, 0, len(inputs))
	for _, in := range inputs {
		matches := model.EmojiPattern.FindAllString(in, -1)
		if matches == nil {
			matches = []string{}
		}
		res = append(res, patternCase{In: in, Matches: matches})
	}
	return res
}
