package main

// Generator for crates/mm-model/src/go_unicode_generated.rs and the behavioural oracle for
// `strconv.Quote`, written to fixtures/behaviour_quote.json.
//
// Go's `%q` is `strconv.Quote`, and it is **not** Rust's `{:?}`. The two agree on ASCII graphics,
// on `\"`, `\\` and the seven single-letter escapes, and on printable non-ASCII — and disagree on
// everything else: Go writes `\x7f` where Rust writes `\u{7f}`, and Go writes `​` where Rust
// writes the raw character. `role.go` puts `%q` into two error messages that quote a role name
// straight off the wire, so the difference is reachable with a role named `a\x7fb`.
//
// The rule Go applies is `unicode.IsPrint`, which is a Unicode property table, so it is emitted
// here rather than approximated — the same decision as `unicode_generated.rs` ([D-070]), and for
// the same reason: a crate's idea of "printable" tracks its own Unicode version, not the Go
// toolchain's.
//
// The corpus probes every ASCII byte and **both sides of every one of the 711 IsPrint range
// boundaries**, which is what makes the emitted table verifiable rather than merely present: a
// table with a run boundary off by one fails at exactly the code point that moved.
//
// Determinism: `unicode.IsPrint` is a compile-time table in the Go toolchain. It moves only when
// the toolchain's Unicode version does — the same caveat [D-070] records for the CJK ranges.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func writeQuoteGenerated(outDir, rustOutDir string) error {
	ranges := scanRuneRanges(unicode.IsPrint)
	letterRanges := scanRuneRanges(unicode.IsLetter)
	numberRanges := scanRuneRanges(unicode.IsNumber)
	if len(ranges) == 0 || len(letterRanges) == 0 || len(numberRanges) == 0 {
		return fmt.Errorf("a category scan came back empty")
	}

	var b strings.Builder
	header := []string{
		"//! @generated by `reference/dump/quote_gen.go` from Go's `unicode` package.",
		"//! DO NOT EDIT — re-run `cd reference/dump && go run .` instead.",
		"//!",
		"//! `unicode.IsPrint` as a range table — the predicate `strconv.Quote` uses to decide whether",
		"//! a character survives quoting or becomes an escape. Rust's `char::escape_debug` answers a",
		"//! similar question with a different table and a different syntax (`\\u{7f}` where Go writes",
		"//! `\\x7f`), so [`crate::utils::go_quote`] uses this instead of the standard library.",
		"//!",
		"//! Unicode version: the **Go toolchain's**, not the pinned tree's and not the Rust",
		"//! toolchain's — the same caveat [D-070] records for the CJK script ranges.",
		"//!",
		"//! Sorted and non-overlapping, so [`slice::binary_search_by`] applies.",
		"",
	}
	b.WriteString(strings.Join(header, "\n"))
	emitRanges(&b, "IS_PRINT_RANGES", "unicode.IsPrint", ranges)
	emitRanges(&b, "IS_LETTER_RANGES", "unicode.IsLetter (general category `L`)", letterRanges)
	emitRanges(&b, "IS_NUMBER_RANGES", "unicode.IsNumber (general category `N`)", numberRanges)

	rustPath := filepath.Join(rustOutDir, "go_unicode_generated.rs")
	if err := os.WriteFile(rustPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d print, %d letter, %d number ranges)\n", rustPath, len(ranges), len(letterRanges), len(numberRanges))

	// The corpus: every ASCII byte, both sides of every range boundary, and a handful of strings
	// that exercise quoting of more than one character at a time.
	seen := map[rune]bool{}
	var probes []rune
	addRune := func(r rune) {
		if r < 0 || r > unicode.MaxRune || seen[r] {
			return
		}
		// Surrogates cannot appear in a Rust `char`, so a probe there would test nothing the port
		// can reach. Go would quote them as � via the !ValidRune branch.
		if r >= 0xD800 && r <= 0xDFFF {
			return
		}
		seen[r] = true
		probes = append(probes, r)
	}
	for r := rune(0); r < utf8.RuneSelf; r++ {
		addRune(r)
	}
	for _, table := range [][]runeRange{ranges, letterRanges, numberRanges} {
		for _, rg := range table {
			addRune(rg.lo - 1)
			addRune(rg.lo)
			addRune(rg.hi)
			addRune(rg.hi + 1)
		}
	}

	runeCases := make([]map[string]any, 0, len(probes))
	for _, r := range probes {
		runeCases = append(runeCases, map[string]any{
			"code_point": int(r),
			"is_print":   unicode.IsPrint(r),
			"is_letter":  unicode.IsLetter(r),
			"is_number":  unicode.IsNumber(r),
			"quoted":     strconv.Quote(string(r)),
		})
	}

	stringProbes := []string{
		"", "a", "role", `bad"name`, `back\slash`, "tab\there", "line\nbreak",
		"bell\a", "vertical\vtab", "form\ffeed", "carriage\rreturn", "null\x00byte",
		"del\x7fete", "nel\u0085", "nbsp\u00a0space", "zwsp\u200bhere",
		"linesep\u2028", "parasep\u2029", "bom\ufeff", "r\u00f4le", "role\U0001F600",
		"privateuse\ue000", "unassigned\u0378", "mixed\x01\u00e9\U0001F600\x7f",
	}
	stringCases := make([]map[string]any, 0, len(stringProbes))
	for _, s := range stringProbes {
		stringCases = append(stringCases, map[string]any{
			"in":     s,
			"quoted": strconv.Quote(s),
		})
	}

	out := map[string]any{
		"range_count":        len(ranges),
		"letter_range_count": len(letterRanges),
		"number_range_count": len(numberRanges),
		"runes":              runeCases,
		"strings":            stringCases,
	}
	blob, err := json.MarshalIndent(out, "", "    ")
	if err != nil {
		return err
	}
	path := filepath.Join(outDir, "behaviour_quote.json")
	if err := os.WriteFile(path, append(blob, '\n'), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d rune probes, %d strings)\n", path, len(runeCases), len(stringCases))
	return nil
}

type runeRange struct{ lo, hi rune }

// scanRuneRanges turns a predicate over the whole code-point space into inclusive runs. Emitting
// runs rather than a bitmap keeps the three tables to a few hundred lines each and lets the Rust
// side answer with a binary search.
func scanRuneRanges(pred func(rune) bool) []runeRange {
	var out []runeRange
	var start rune = -1
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if pred(r) {
			if start < 0 {
				start = r
			}
			continue
		}
		if start >= 0 {
			out = append(out, runeRange{start, r - 1})
			start = -1
		}
	}
	if start >= 0 {
		out = append(out, runeRange{start, unicode.MaxRune})
	}
	return out
}

func emitRanges(b *strings.Builder, rustName, goName string, ranges []runeRange) {
	fmt.Fprintf(b, "\n/// The %d inclusive ranges over which `%s` is true.\n", len(ranges), goName)
	fmt.Fprintf(b, "#[rustfmt::skip]\npub static %s: &[(u32, u32)] = &[\n", rustName)
	for i := 0; i < len(ranges); i += 4 {
		end := min(i+4, len(ranges))
		b.WriteString("   ")
		for _, r := range ranges[i:end] {
			fmt.Fprintf(b, " (0x%X, 0x%X),", r.lo, r.hi)
		}
		b.WriteString("\n")
	}
	b.WriteString("];\n")
}
