package main

// Generator for crates/mm-model/src/role_generated.rs — the data half of model/role.go.
//
// role.go is 1,311 lines, and roughly 740 of them are data: `init()` builds
// `SysconsoleAncillaryPermissions` plus five default-permission lists and two role-id lists
// (lines 25-375), and `MakeDefaultRoles` builds thirty roles out of permission ids (lines
// 919-1292). Both are pure functions of the permission table, so both are emitted from the linked
// package rather than transcribed, for the same reason permission.go is: a role that is missing one
// permission id is a role that silently denies, and nothing downstream reports it.
//
// # What is checked here rather than asserted downstream
//
//  1. `MakeDefaultRoles` is called twice and the two results compared. It builds
//     `allPermissionIDs` with `append`, and an `append` onto a shared backing array is exactly how
//     a "constant" table stops being constant between calls. If the two ever disagree, this fails
//     rather than emitting whichever one ran first.
//  2. Every permission id a role names must exist in the permission table. A default role carrying
//     an unknown permission would fail `Role.IsValid` — which is worth knowing about Go, not
//     reproducing blindly.
//  3. No default role may have a nil `Permissions`. Go's field has no `omitempty`, so nil marshals
//     to `null` and an empty slice to `[]`; the Rust side models the table as a slice and would
//     turn a nil into `[]`. Today every default role has a non-nil list, and the generator fails
//     if that changes rather than letting the wire format drift.
//
// Determinism: `MakeDefaultRoles` returns a map, which Go iterates in random order, so the emitted
// table is sorted by key. Nothing reads it in order — the Rust side rebuilds a map from it.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

func writeRoleGenerated(outDir, rustOutDir string) error {
	// Reuse permission_gen's AST read: it is the only source of the Rust static name for a
	// permission id, and SysconsoleAncillaryPermissions is a map of *Permission.
	literals, _, _, err := parsePermissionSource(permissionGoPath)
	if err != nil {
		return err
	}
	rustNameByID := make(map[string]string, len(literals))
	for _, p := range literals {
		rustNameByID[p.ID] = p.RustName
	}
	knownPermission := func(id string) bool {
		_, ok := rustNameByID[id]
		return ok
	}

	first := model.MakeDefaultRoles()
	second := model.MakeDefaultRoles()
	if !reflect.DeepEqual(first, second) {
		return fmt.Errorf("MakeDefaultRoles is not stable across calls; the table cannot be emitted")
	}

	keys := make([]string, 0, len(first))
	for k := range first {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nilPermissions []string
	for _, key := range keys {
		role := first[key]
		if role.Permissions == nil {
			nilPermissions = append(nilPermissions, key)
		}
		for _, id := range role.Permissions {
			if !knownPermission(id) {
				return fmt.Errorf("default role %q names unknown permission %q", key, id)
			}
		}
	}
	if len(nilPermissions) > 0 {
		return fmt.Errorf("default roles with a nil Permissions slice, which marshals to null rather than []: %v", nilPermissions)
	}

	ancillaryKeys := make([]string, 0, len(model.SysconsoleAncillaryPermissions))
	for k := range model.SysconsoleAncillaryPermissions {
		ancillaryKeys = append(ancillaryKeys, k)
	}
	sort.Strings(ancillaryKeys)

	// The permission statics the ancillary table references, so the generated file can import
	// exactly those rather than glob-importing 311 names.
	usedNames := map[string]bool{}
	for _, key := range ancillaryKeys {
		for _, p := range model.SysconsoleAncillaryPermissions[key] {
			name, ok := rustNameByID[p.Id]
			if !ok {
				return fmt.Errorf("SysconsoleAncillaryPermissions[%q] names unknown permission %q", key, p.Id)
			}
			usedNames[name] = true
		}
	}
	imports := make([]string, 0, len(usedNames)+1)
	for name := range usedNames {
		imports = append(imports, name)
	}
	sort.Strings(imports)

	var b strings.Builder
	// Backticks are literal here, so the header is built from interpreted strings rather than a raw
	// one — a raw string would end at the first backtick of a doc-comment code span.
	header := []string{
		"//! @generated by `reference/dump/role_gen.go` from `model/role.go`.",
		"//! DO NOT EDIT — re-run `cd reference/dump && go run .` instead.",
		"//!",
		fmt.Sprintf("//! The data half of role.go: the %d roles `MakeDefaultRoles` builds, the seven lists", len(keys)),
		"//! `init()` fills, and the sysconsole ancillary-permission map. All of it is a pure function of",
		"//! the permission table, so all of it is emitted rather than transcribed — a role missing one",
		"//! permission id denies silently.",
		"//!",
		"//! `MakeDefaultRoles` returns a map, so Go has no order to reproduce; this table is sorted by",
		"//! key and [`crate::role::make_default_roles`] rebuilds the map from it. The seven lists **are**",
		"//! ordered and keep Go's order.",
		"//!",
		"//! Every table carries `#[rustfmt::skip]` so `cargo fmt` and the generator stay idempotent.",
		"",
		"#[rustfmt::skip]",
		"use crate::permission::{",
		"    Permission,",
	}
	for _, name := range imports {
		header = append(header, "    "+name+",")
	}
	header = append(header, "};", "use crate::role::DefaultRole;", "", "")
	b.WriteString(strings.Join(header, "\n"))

	fmt.Fprintf(&b, "/// The output of `model.MakeDefaultRoles` (role.go:919), sorted by map key.\n")
	b.WriteString("#[rustfmt::skip]\npub static DEFAULT_ROLES: &[DefaultRole] = &[\n")
	for _, key := range keys {
		role := first[key]
		fmt.Fprintf(&b, "    DefaultRole {\n")
		fmt.Fprintf(&b, "        key: %s,\n", strconv.Quote(key))
		fmt.Fprintf(&b, "        name: %s,\n", strconv.Quote(role.Name))
		fmt.Fprintf(&b, "        display_name: %s,\n", strconv.Quote(role.DisplayName))
		fmt.Fprintf(&b, "        description: %s,\n", strconv.Quote(role.Description))
		fmt.Fprintf(&b, "        scheme_managed: %t,\n", role.SchemeManaged)
		fmt.Fprintf(&b, "        built_in: %t,\n", role.BuiltIn)
		if len(role.Permissions) == 0 {
			b.WriteString("        permissions: &[],\n")
		} else {
			b.WriteString("        permissions: &[\n")
			for _, id := range role.Permissions {
				fmt.Fprintf(&b, "            %s,\n", strconv.Quote(id))
			}
			b.WriteString("        ],\n")
		}
		b.WriteString("    },\n")
	}
	b.WriteString("];\n\n")

	lists := []struct {
		rustName, goName, doc string
		values                []string
	}{
		{"BUILT_IN_SCHEME_MANAGED_ROLE_IDS", "BuiltInSchemeManagedRoleIDs",
			"the canonical list of built-in role ids. Despite the name, **not all of them are\n/// scheme-managed** — Go's own comment at role.go:886 says so, and roughly half carry\n/// `scheme_managed: false`. It is the source of truth for [`crate::role::is_built_in_role`].",
			model.BuiltInSchemeManagedRoleIDs},
		{"NEW_SYSTEM_ROLE_IDS", "NewSystemRoleIDs",
			"the system-console roles added after the original three.", model.NewSystemRoleIDs},
		{"SYSTEM_MANAGER_DEFAULT_PERMISSIONS", "SystemManagerDefaultPermissions",
			"the permission ids `system_manager` starts with.", model.SystemManagerDefaultPermissions},
		{"SYSTEM_USER_MANAGER_DEFAULT_PERMISSIONS", "SystemUserManagerDefaultPermissions",
			"the permission ids `system_user_manager` starts with.", model.SystemUserManagerDefaultPermissions},
		{"SYSTEM_READ_ONLY_ADMIN_DEFAULT_PERMISSIONS", "SystemReadOnlyAdminDefaultPermissions",
			"the permission ids `system_read_only_admin` starts with.", model.SystemReadOnlyAdminDefaultPermissions},
		{"SYSTEM_CUSTOM_GROUP_ADMIN_DEFAULT_PERMISSIONS", "SystemCustomGroupAdminDefaultPermissions",
			"the permission ids `system_custom_group_admin` starts with.", model.SystemCustomGroupAdminDefaultPermissions},
		{"SHARED_CHANNEL_MANAGER_DEFAULT_PERMISSIONS", "SharedChannelManagerDefaultPermissions",
			"the permission ids `system_shared_channel_manager` starts with.", model.SharedChannelManagerDefaultPermissions},
	}
	for _, list := range lists {
		fmt.Fprintf(&b, "/// `model.%s` — %s\n", list.goName, list.doc)
		fmt.Fprintf(&b, "#[rustfmt::skip]\npub static %s: &[&str] = &[\n", list.rustName)
		for _, v := range list.values {
			fmt.Fprintf(&b, "    %s,\n", strconv.Quote(v))
		}
		b.WriteString("];\n\n")
	}

	b.WriteString("/// `model.SysconsoleAncillaryPermissions` (role.go:13) — the non-sysconsole permissions\n" +
		"/// each sysconsole view needs in order to work. Sorted by key so\n" +
		"/// [`slice::binary_search_by_key`] applies; Go's map has no order and\n" +
		"/// `AddAncillaryPermissions` only ever looks a key up.\n")
	b.WriteString("#[rustfmt::skip]\npub static SYSCONSOLE_ANCILLARY_PERMISSIONS: &[(&str, &[&Permission])] = &[\n")
	for _, key := range ancillaryKeys {
		perms := model.SysconsoleAncillaryPermissions[key]
		names := make([]string, 0, len(perms))
		for _, p := range perms {
			name, ok := rustNameByID[p.Id]
			if !ok {
				return fmt.Errorf("SysconsoleAncillaryPermissions[%q] names unknown permission %q", key, p.Id)
			}
			names = append(names, "&"+name)
		}
		fmt.Fprintf(&b, "    (%s, &[%s]),\n", strconv.Quote(key), strings.Join(names, ", "))
	}
	b.WriteString("];\n")

	rustPath := filepath.Join(rustOutDir, "role_generated.rs")
	if err := os.WriteFile(rustPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d default roles, %d ancillary keys)\n", rustPath, len(keys), len(ancillaryKeys))

	return writeRoleTablesFixture(outDir, first, keys, ancillaryKeys)
}

// writeRoleTablesFixture records the same tables as data, so the Rust tests assert against Go
// rather than against the file Go wrote for them. The distinction matters: a bug in the emitter
// above would otherwise be invisible, since the Rust side would be checking the emitter's output
// against itself.
func writeRoleTablesFixture(outDir string, roles map[string]*model.Role, keys, ancillaryKeys []string) error {
	roleRows := make([]map[string]any, 0, len(keys))
	for _, key := range keys {
		r := roles[key]
		roleRows = append(roleRows, map[string]any{
			"key":            key,
			"name":           r.Name,
			"display_name":   r.DisplayName,
			"description":    r.Description,
			"permissions":    r.Permissions,
			"scheme_managed": r.SchemeManaged,
			"built_in":       r.BuiltIn,
			"id":             r.Id,
			"create_at":      r.CreateAt,
			"update_at":      r.UpdateAt,
			"delete_at":      r.DeleteAt,
			"scheme_id_nil":  r.SchemeId == nil,
		})
	}

	ancillary := map[string][]string{}
	for _, key := range ancillaryKeys {
		ids := []string{}
		for _, p := range model.SysconsoleAncillaryPermissions[key] {
			ids = append(ids, p.Id)
		}
		ancillary[key] = ids
	}

	// Which built-in role ids are *not* scheme-managed, and which are not in the default-role
	// table at all. Both are counting results rather than beliefs — see the note in the emitted
	// Rust doc comment.
	var builtInNotSchemeManaged, builtInWithNoDefaultRole []string
	for _, id := range model.BuiltInSchemeManagedRoleIDs {
		role, ok := roles[id]
		if !ok {
			builtInWithNoDefaultRole = append(builtInWithNoDefaultRole, id)
			continue
		}
		if !role.SchemeManaged {
			builtInNotSchemeManaged = append(builtInNotSchemeManaged, id)
		}
	}

	var defaultRolesNotBuiltIn []string
	builtInSet := map[string]bool{}
	for _, id := range model.BuiltInSchemeManagedRoleIDs {
		builtInSet[id] = true
	}
	for _, key := range keys {
		if !builtInSet[key] {
			defaultRolesNotBuiltIn = append(defaultRolesNotBuiltIn, key)
		}
	}

	out := map[string]any{
		"default_roles":                                 roleRows,
		"built_in_scheme_managed_role_ids":              model.BuiltInSchemeManagedRoleIDs,
		"new_system_role_ids":                           model.NewSystemRoleIDs,
		"system_manager_default_permissions":            model.SystemManagerDefaultPermissions,
		"system_user_manager_default_permissions":       model.SystemUserManagerDefaultPermissions,
		"system_read_only_admin_default_permissions":    model.SystemReadOnlyAdminDefaultPermissions,
		"system_custom_group_admin_default_permissions": model.SystemCustomGroupAdminDefaultPermissions,
		"shared_channel_manager_default_permissions":    model.SharedChannelManagerDefaultPermissions,
		"sysconsole_ancillary_permissions":              ancillary,
		"built_in_not_scheme_managed":                   orEmpty(builtInNotSchemeManaged),
		"built_in_with_no_default_role":                 orEmpty(builtInWithNoDefaultRole),
		"default_roles_not_built_in":                    orEmpty(defaultRolesNotBuiltIn),
		"counts": map[string]int{
			"default_roles":      len(keys),
			"built_in_role_ids":  len(model.BuiltInSchemeManagedRoleIDs),
			"new_system_roles":   len(model.NewSystemRoleIDs),
			"ancillary_keys":     len(ancillaryKeys),
			"system_admin_perms": len(roles[model.SystemAdminRoleId].Permissions),
		},
	}

	blob, err := json.MarshalIndent(out, "", "    ")
	if err != nil {
		return err
	}
	path := filepath.Join(outDir, "behaviour_role_tables.json")
	if err := os.WriteFile(path, append(blob, '\n'), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}
