package main

// Generator for crates/mm-model/src/timezones_generated.rs, and the behavioural oracle for
// server/public/shared/timezones, written to fixtures/behaviour_timezones.json.
//
// The package is 29 lines of code and 592 lines of data. The code half is trivial:
//
//	func DefaultUserTimezone() map[string]string {
//		defaultTimezone := make(map[string]string)
//		defaultTimezone["useAutomaticTimezone"] = "true"
//		defaultTimezone["automaticTimezone"] = ""
//		defaultTimezone["manualTimezone"] = ""
//		return defaultTimezone
//	}
//
// Two things about it are load-bearing and neither is obvious from reading it.
//
// # "true" is a STRING
//
// `User.Timezone` is a `map[string]string`, so the automatic-timezone flag is the four-byte text
// `"true"`, not a JSON boolean. A port that reaches for a bool changes the wire format of every
// user object and the stored `Users.Timezone` column with it.
//
// # It returns a fresh map each call, and `PreSave` only fills a NIL one
//
// `if u.Timezone == nil { u.Timezone = timezones.DefaultUserTimezone() }`. An empty-but-present
// map is left empty — the same nil-vs-empty distinction `IsValid`'s props check turns on. So the
// fixture records the marshalled default alongside what `PreSave` does to each of the three
// starting states, rather than only the former.
//
// # And the map's marshalled key order is not its insertion order
//
// Go sorts map keys when marshalling, so the JSON is automaticTimezone, manualTimezone,
// useAutomaticTimezone — the reverse of the order the function writes them in. `StringMap` is a
// `BTreeMap` on our side ([D-027]), so this agrees, but only because that conversion happened.
//
// The 592-entry supported list is EMITTED rather than transcribed, for the same reason the emoji
// and locale tables are: a hand-copied list of 592 IANA names is a guarantee that one is wrong,
// and nothing downstream would notice.
//
// Determinism: the package holds no clock, no randomness and no host lookup — `DefaultSupportedTimezones`
// is a compile-time literal, NOT a scan of the host's tzdata. That is why this can be a table at
// all, and it is the difference from [D-065], where `time.LoadLocation` reads the filesystem.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/public/shared/timezones"
)

func writeTimezonesGenerated(outDir, rustOutDir string) error {
	supported := timezones.New().GetSupported()

	var b strings.Builder
	b.WriteString(`//! Generated by reference/dump/timezones_gen.go — DO NOT EDIT.
//!
//! ` + "`timezones.DefaultSupportedTimezones`" + ` (shared/timezones/default.go) — the IANA zone names
//! Mattermost offers a user in the timezone picker.
//!
//! This is a **compile-time literal in Go**, not a scan of the host's tzdata, which is what makes
//! it portable as a table at all. Contrast [D-065], where ` + "`time.LoadLocation`" + ` reads the
//! filesystem and therefore has no single answer to match.
//!
//! Never hand-edit; re-run the generator. The table carries ` + "`#[rustfmt::skip]`" + ` so ` + "`cargo fmt`" + `
//! and the generator stay idempotent against each other, the same as ` + "`emoji_generated.rs`" + `.

`)
	fmt.Fprintf(&b,
		"/// The zone names `timezones.New().GetSupported()` returns, in Go's order (%d).\n"+
			"///\n"+
			"/// The order is the source literal's, which is byte-sorted and strictly increasing —\n"+
			"/// so `US/*` and the single-word aliases trail the `Area/Location` names for the\n"+
			"/// ordinary reason. The behaviour fixture records that, and `timezones.rs` asserts it,\n"+
			"/// rather than either side taking it on trust.\n"+
			"#[rustfmt::skip]\npub static DEFAULT_SUPPORTED_TIMEZONES: &[&str] = &[\n",
		len(supported))
	for i := 0; i < len(supported); i += 4 {
		end := min(i+4, len(supported))
		b.WriteString("    ")
		for _, v := range supported[i:end] {
			fmt.Fprintf(&b, "%q, ", v)
		}
		b.WriteString("\n")
	}
	b.WriteString("];\n")

	rustPath := filepath.Join(rustOutDir, "timezones_generated.rs")
	if err := os.WriteFile(rustPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d entries)\n", rustPath, len(supported))

	return writeTimezonesBehaviourFixture(outDir, supported)
}

func writeTimezonesBehaviourFixture(outDir string, supported []string) error {
	def := timezones.DefaultUserTimezone()

	// The default map, recorded three ways: as a value, as Go's marshalled bytes (which is the
	// form `User.IsValid` measures its 256-rune cap against), and as the marshalled key ORDER,
	// which is sorted rather than insertion-ordered.
	marshalled, err := json.Marshal(def)
	if err != nil {
		return err
	}

	// Two calls, to establish that the returned map is fresh rather than shared: mutating one
	// must not be visible in the other. A port returning a `&'static` would pass every other
	// assertion here and fail this one.
	a := timezones.DefaultUserTimezone()
	b := timezones.DefaultUserTimezone()
	a["manualTimezone"] = "Europe/Berlin"

	// What PreSave does to each of the three starting states of `User.Timezone`. `nil` is filled;
	// an empty-but-present map is NOT, because the guard is `== nil` rather than `len() == 0`.
	preSaveCases := []map[string]any{}
	for _, c := range []struct {
		name string
		in   map[string]string
	}{
		{"nil", nil},
		{"empty_but_present", map[string]string{}},
		{"already_set", map[string]string{"useAutomaticTimezone": "false", "manualTimezone": "Asia/Kolkata"}},
	} {
		u := model.User{Timezone: c.in}
		if u.Timezone == nil {
			u.Timezone = timezones.DefaultUserTimezone()
		}
		preSaveCases = append(preSaveCases, map[string]any{
			"name":     c.name,
			"in_nil":   c.in == nil,
			"in_len":   len(c.in),
			"out":      u.Timezone,
			"out_len":  len(u.Timezone),
			"replaced": len(u.Timezone) != len(c.in),
		})
	}

	out := map[string]any{
		"default_user_timezone": map[string]any{
			"value": def,
			// The key order Go's marshaller emits — sorted, not the order the function writes.
			"marshalled":     string(marshalled),
			"insertion_note": "useAutomaticTimezone, automaticTimezone, manualTimezone",
			// `true` here is the four-byte STRING, and this records the Go type to prove it.
			"use_automatic_timezone_go_type": fmt.Sprintf("%T", def["useAutomaticTimezone"]),
			"len":                            len(def),
			"rune_count_of_marshalled":       len([]rune(string(marshalled))),
			"user_timezone_max_runes":        model.UserTimezoneMaxRunes,
		},
		"freshness": map[string]any{
			"mutating_one_call_leaks_into_another": a["manualTimezone"] == b["manualTimezone"],
			"second_call_manual_timezone":          b["manualTimezone"],
		},
		"pre_save": preSaveCases,
		"supported": map[string]any{
			"len":   len(supported),
			"first": supported[0],
			"last":  supported[len(supported)-1],
			// The list is NOT sorted; recording that stops a port from "tidying" it.
			"is_sorted": isSortedStrings(supported),
			// A hash so the Rust table can be checked in one assertion rather than 592.
			"fnv1a64": fnv1a64Strings(supported),
		},
	}

	blob, err := json.MarshalIndent(out, "", "    ")
	if err != nil {
		return err
	}
	path := filepath.Join(outDir, "behaviour_timezones.json")
	if err := os.WriteFile(path, append(blob, '\n'), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	return nil
}

func isSortedStrings(v []string) bool {
	for i := 1; i < len(v); i++ {
		if v[i-1] > v[i] {
			return false
		}
	}
	return true
}

// fnv1a64Strings folds a string slice into one 64-bit digest, order-sensitively.
//
// FNV-1a, not FNV-1 — this is our own checksum rather than a reproduction of Go's
// `GenerateLinkMetadataHash`, which is FNV-**1** and where the distinction is load-bearing.
// Each element is followed by a NUL so that ["ab","c"] and ["a","bc"] differ.
func fnv1a64Strings(v []string) uint64 {
	const (
		offset = 14695981039346656037
		prime  = 1099511628211
	)
	h := uint64(offset)
	for _, s := range v {
		for i := 0; i < len(s); i++ {
			h ^= uint64(s[i])
			h *= prime
		}
		h ^= 0
		h *= prime
	}
	return h
}
