#!/usr/bin/env python3
"""Transcribe two Go tables into crates/mm-model/src/go_html_tables.rs:

1. `golang.org/x/net/html`'s `entity` and `entity2` maps (entity.go) — the named character
   references the tokenizer's `unescape` and the standard library's `html.UnescapeString`
   resolve. The script refuses to write unless the standard library's copy
   (`$GOROOT/src/html/entity.go`) holds the same single-code-point table and a subset of the
   two-code-point one; the standard library comments out `nLt;` and `nGt;`, which the generated
   `ENTITY2_NOT_IN_STD` records.
2. `golang.org/x/text/encoding/htmlindex`'s `nameMap` and `canonical` (tables.go) — the encoding
   labels `charset.Lookup` accepts, and the canonical name each resolves to.

Run from the repository root:

    PATH=$PATH:/usr/local/go/bin scripts/gen-go-html-tables.py

The module versions are the ones reference/dump/go.mod pins.
"""
import os
import re
import subprocess
import sys

NET = 'golang.org/x/net@v0.56.0'
TEXT = 'golang.org/x/text@v0.40.0'
OUT = 'crates/mm-model/src/go_html_tables.rs'


def go_env(name):
    return subprocess.check_output(['go', 'env', name], text=True).strip()


modcache = go_env('GOMODCACHE')
goroot = go_env('GOROOT')

RUNE = r"'\\U([0-9A-Fa-f]{8})'|'\\u([0-9A-Fa-f]{4})'"


def rune(m1, m2):
    return int(m1 or m2, 16)


def parse_entities(src):
    one = {}
    two = {}
    for m in re.finditer(r'^\s*"([^"]+)":\s*(?:' + RUNE + r'),\s*$', src, re.M):
        one[m.group(1)] = rune(m.group(2), m.group(3))
    for m in re.finditer(r'^\s*"([^"]+)":\s*\{(?:' + RUNE + r'),\s*(?:' + RUNE + r')\},\s*$', src, re.M):
        two[m.group(1)] = (rune(m.group(2), m.group(3)), rune(m.group(4), m.group(5)))
    return one, two


net_src = open(os.path.join(modcache, NET, 'html', 'entity.go'), encoding='utf-8').read()
std_src = open(os.path.join(goroot, 'src', 'html', 'entity.go'), encoding='utf-8').read()
one, two = parse_entities(net_src)
std_one, std_two = parse_entities(std_src)
if one != std_one or not set(std_two.items()) <= set(two.items()):
    sys.exit('x/net/html and the standard library disagree on the entity table')
# The standard library comments out two of x/net's pairs ("nLt;" and "nGt;"), so
# `html.UnescapeString` leaves them alone while the tokenizer resolves them.
std_missing = sorted(set(two) - set(std_two), key=lambda s: s.encode())
if len(one) < 2000 or len(two) < 50:
    sys.exit(f'suspiciously small entity table: {len(one)} / {len(two)}')

tables = open(os.path.join(modcache, TEXT, 'encoding', 'htmlindex', 'tables.go'), encoding='utf-8').read()
consts = re.search(r'const \(\n\tutf8 htmlEncoding = iota\n(.*?)\n\)', tables, re.S)
const_names = ['utf8'] + [c.strip() for c in consts.group(1).split('\n') if c.strip()]
const_names = [c for c in const_names if c != 'numEncodings']
canon_block = re.search(r'var canonical = \[numEncodings\]string\{\n(.*?)\n\}', tables, re.S).group(1)
canonical = re.findall(r'"([^"]+)"', canon_block)
if len(canonical) != len(const_names):
    sys.exit('canonical and the constants disagree in length')
by_const = dict(zip(const_names, canonical))
name_block = re.search(r'var nameMap = map\[string\]htmlEncoding\{\n(.*?)\n\}', tables, re.S).group(1)
labels = re.findall(r'"([^"]+)":\s*(\w+),', name_block)
if len(labels) < 200:
    sys.exit(f'suspiciously few labels: {len(labels)}')


def rs_char(cp):
    return f"'\\u{{{cp:X}}}'"


out = []
out.append('//! Generated by `scripts/gen-go-html-tables.py` — do not edit.')
out.append('//!')
out.append(f'//! * [`ENTITY`] and [`ENTITY2`]: `{NET}/html/entity.go`, identical to the standard')
out.append('//!   library\'s `html/entity.go` except [`ENTITY2_NOT_IN_STD`] (the script checks). Sorted by name in byte')
out.append('//!   order for `binary_search_by_key`; the semicolon is part of the name, as in Go.')
out.append(f'//! * [`ENCODING_LABELS`]: `{TEXT}/encoding/htmlindex/tables.go` `nameMap`, each label paired')
out.append('//!   with the canonical name of its encoding. Sorted by label.')
out.append('')
out.append('/// `entity` (entity.go): name → code point.')
out.append('#[rustfmt::skip]')
out.append('pub static ENTITY: &[(&str, char)] = &[')
for name in sorted(one, key=lambda s: s.encode()):
    out.append(f'    ("{name}", {rs_char(one[name])}),')
out.append('];')
out.append('')
out.append('/// `entity2` (entity.go): the entities that are two code points.')
out.append('#[rustfmt::skip]')
out.append('pub static ENTITY2: &[(&str, char, char)] = &[')
for name in sorted(two, key=lambda s: s.encode()):
    a, b = two[name]
    out.append(f'    ("{name}", {rs_char(a)}, {rs_char(b)}),')
out.append('];')
out.append('')
out.append('/// The [`ENTITY2`] names the standard library\'s copy of the table comments out, so that')
out.append('/// `html.UnescapeString` does not resolve them though the x/net tokenizer does.')
out.append('pub static ENTITY2_NOT_IN_STD: &[&str] = &[' + ', '.join(f'"{n}"' for n in std_missing) + '];')
out.append('')
out.append('/// `nameMap` (htmlindex/tables.go): label → canonical encoding name.')
out.append('#[rustfmt::skip]')
out.append('pub static ENCODING_LABELS: &[(&str, &str)] = &[')
for label, const in sorted(labels, key=lambda p: p[0].encode()):
    out.append(f'    ("{label}", "{by_const[const]}"),')
out.append('];')
out.append('')
open(OUT, 'w', encoding='utf-8').write('\n'.join(out))
print(f'wrote {OUT}: {len(one)} entities, {len(two)} pairs, {len(labels)} labels')
