#!/usr/bin/env python3
"""Generate mm-plugin's gob wire types from the Go plugin IDL.

The IDL, `fixtures/plugin/idl.json`, is written by `reference/dump/plugingen` from reflection over
the pinned Go tree (docs/PLUGIN_PLAN.md, D5). This script turns it into committed Rust:

  crates/mm-plugin/src/wire/<package>.rs   one module per Go package: every struct, named type
                                           and wire struct (`Z_*Args`/`Z_*Returns`) the plugin RPC
                                           can send, as `#[derive(Gob)]` types
  crates/mm-plugin/src/wire/mod.rs         the modules, the names `init()` registers, and
                                           `for_each_wire_struct!` and `for_each_registered!`
  crates/mm-plugin/src/rpc/hooks.rs        hook ids, the `Hooks` trait, its server registration,
                                           and `HooksClient`'s methods, for every generated hook
  crates/mm-plugin/src/rpc/api.rs          the `PluginApi` trait, its server registration, and
                                           `ApiClient`'s methods, for every generated API method

The methods in `excludedPluginHooks` have hand-written wire shapes and are not generated here.

The Rust types are the **gob** form of the Go types, not `mm-model`'s JSON form: every field gob
sends is here (including the `json:"-"` ones), named exactly as Go names it, typed by its Go kind.
Converting them to and from `mm-model` is the host's business, where a lossy mapping is visible.

Go → Rust:
  int, int64 … uint8      i64, i64 … u8 (int and uint are 64-bit on every Mattermost build)
  string, bool, float64   String, bool, f64
  []byte (any uint8 elem) Vec<u8>
  []T, map[K]V            Vec<T>, HashMap<K, V>   (a pointer element is flattened: gob cannot
                                                  send a nil element, and decodes to non-nil)
  *T                      Option<Box<T>> for a struct, Option<T> otherwise
  interface (any, error)  Option<gobwire::Interface>
  time.Time               gobwire::GoTime
  GobEncoder / Binary…    gobwire::GobBytes / gobwire::BinaryBytes
  named non-struct type   `pub type Name = <underlying>;`

Usage:
    scripts/plugingen.py           regenerate
    scripts/plugingen.py --check   fail if the committed output differs from a fresh generation
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IDL = ROOT / "fixtures/plugin/idl.json"
OUT = ROOT / "crates/mm-plugin/src/wire"
RPC = ROOT / "crates/mm-plugin/src/rpc"
HEADER = "// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit."

# Go package → Rust module. Every package the IDL reaches must be listed: an unlisted one is a new
# dependency of the plugin API and deserves a deliberate name.
MODULES = {
    "github.com/mattermost/mattermost/server/public/model": "model",
    "github.com/mattermost/mattermost/server/public/plugin": "plugin",
    "github.com/mattermost/gosaml2": "saml2",
    "github.com/mattermost/gosaml2/types": "saml2_types",
    "github.com/mattermost/logr/v2": "logr",
    "github.com/lib/pq": "pq",
    "github.com/lib/pq/pqerror": "pqerror",
    "crypto/tls": "tls",
    "crypto/x509": "x509",
    "crypto/x509/pkix": "pkix",
    "encoding/asn1": "asn1",
    "encoding/json": "json",
    "encoding/xml": "xml",
    "math/big": "big",
    "mime/multipart": "multipart",
    "net": "net",
    "net/http": "http",
    "net/textproto": "textproto",
    "net/url": "url",
    "time": "time",
    "io": "io",
}

BASIC = {
    "bool": "bool",
    "int": "i64",
    "int8": "i8",
    "int16": "i16",
    "int32": "i32",
    "int64": "i64",
    "uint": "u64",
    "uint8": "u8",
    "uint16": "u16",
    "uint32": "u32",
    "uint64": "u64",
    "uintptr": "u64",
    "float32": "f32",
    "float64": "f64",
    "complex64": "::gobwire::Complex",
    "complex128": "::gobwire::Complex",
    "string": "::std::string::String",
}

RUST_KEYWORDS = {
    "as", "async", "await", "break", "const", "continue", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "static", "struct", "trait", "true", "type", "unsafe", "use", "where",
    "while", "abstract", "become", "box", "do", "final", "macro", "override", "priv", "try",
    "typeof", "unsized", "virtual", "yield", "gen",
}
NOT_RAW = {"self", "Self", "super", "crate"}


# Methods whose RPC server is hand-written in crates/mm-plugin/src/rpc/: `OnActivate` dials the
# brokered connections, `Implemented` has no wire structs, and `LoadPluginConfiguration` answers
# `null` rather than a not-implemented error. Their trait methods are still generated, except for
# the two that have no plain wire structs.
REGISTER_BY_HAND = {"OnActivate", "Implemented", "LoadPluginConfiguration"}


class GenError(Exception):
    pass


def snake(name: str) -> str:
    """Go identifier → snake_case: `CreateAt` → `create_at`, `IPAddress` → `ip_address`."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    s = s.lower()
    if s in NOT_RAW:
        return s + "_"
    if s in RUST_KEYWORDS:
        return "r#" + s
    return s


def screaming(name: str) -> str:
    return snake(name).removeprefix("r#").rstrip("_").upper()


class Generator:
    def __init__(self, idl):
        self.idl = idl
        self.types = idl["types"]
        self.rust_names = {}  # type id → Rust item name, for named types
        self.modules = {}  # module → list of type ids
        self.assign_names()

    def module_of(self, tid):
        pkg = self.types[tid].get("package", "")
        if pkg not in MODULES:
            raise GenError(f"{tid}: Go package {pkg!r} has no Rust module in MODULES")
        return MODULES[pkg]

    def assign_names(self):
        taken = {}
        for tid in sorted(self.types):
            t = self.types[tid]
            if not t.get("name") or not t.get("package"):
                continue
            if t["kind"] == "interface" or tid == "time.Time":
                continue
            go = t["name"]
            base, _, args = go.partition("[")
            rust = base[0].upper() + base[1:]
            if args:
                # Name a generic instantiation after its type arguments' own names.
                for arg in re.findall(r"[\w/.-]+\.(\w+)", args):
                    rust += arg[0].upper() + arg[1:]
            module = self.module_of(tid)
            key = (module, rust)
            if key in taken:
                raise GenError(f"{tid} and {taken[key]} both map to {module}::{rust}")
            taken[key] = tid
            self.rust_names[tid] = rust
            self.modules.setdefault(module, []).append(tid)

    def path(self, tid, here):
        """The Rust path of a named type, relative to module `here`."""
        module = self.module_of(tid)
        name = self.rust_names[tid]
        return name if module == here else f"super::{module}::{name}"

    def rust_type(self, tid, here, flatten_pointer=False):
        t = self.types[tid]
        kind = t["kind"]
        if tid == "time.Time":
            return "::gobwire::GoTime"
        if kind == "interface":
            return "::std::option::Option<::gobwire::Interface>"
        if tid in self.rust_names:
            return self.path(tid, here)
        if kind in BASIC:
            return BASIC[kind]
        if kind == "pointer":
            elem = self.types[t["elem"]]
            inner = self.rust_type(t["elem"], here)
            if flatten_pointer:
                return inner
            if elem["kind"] == "interface":
                raise GenError(f"{tid}: a pointer to an interface cannot be sent by gob")
            if elem["kind"] == "pointer":
                raise GenError(f"{tid}: a pointer to a pointer has no mapping")
            if elem["kind"] == "struct":
                return f"::std::option::Option<::std::boxed::Box<{inner}>>"
            return f"::std::option::Option<{inner}>"
        if kind == "slice":
            elem = self.types[t["elem"]]
            if elem["kind"] == "uint8":
                return "::std::vec::Vec<u8>"
            return f"::std::vec::Vec<{self.rust_type(t['elem'], here, flatten_pointer=True)}>"
        if kind == "array":
            return f"[{self.rust_type(t['elem'], here, flatten_pointer=True)}; {t['len']}]"
        if kind == "map":
            key = self.rust_type(t["key"], here)
            val = self.rust_type(t["elem"], here, flatten_pointer=True)
            return f"::std::collections::HashMap<{key}, {val}>"
        if kind == "gob":
            return "::gobwire::GobBytes"
        if kind == "binary":
            return "::gobwire::BinaryBytes"
        raise GenError(f"{tid}: unmapped kind {kind}")

    def underlying(self, tid, here):
        """The Rust type a named non-struct type aliases."""
        t = dict(self.types[tid])
        kind = t["kind"]
        if kind in BASIC:
            return BASIC[kind]
        if kind == "gob":
            return "::gobwire::GobBytes"
        if kind == "binary":
            return "::gobwire::BinaryBytes"
        # A named slice, map or pointer: the same mapping as the unnamed form.
        saved = self.rust_names.pop(tid)
        try:
            return self.rust_type(tid, here)
        finally:
            self.rust_names[tid] = saved

    def item(self, tid, module):
        t = self.types[tid]
        name = self.rust_names[tid]
        go = f"{t['package']}.{t['name']}"
        if t["kind"] != "struct":
            return (
                f"/// Go `{go}` ({t['kind']}).\n"
                f"pub type {name} = {self.underlying(tid, module)};\n"
            )
        lines = [f"/// Go `{go}`, as gob sends it."]
        if name.startswith("Z_"):
            lines.append("#[allow(non_camel_case_types)]")
        lines.append("#[derive(::gobwire::Gob, Debug, Clone, Default, PartialEq)]")
        lines.append(f'#[gob(name = "{t["name"]}")]')
        lines.append(f"pub struct {name} {{")
        seen = set()
        for f in t.get("fields", []):
            field = snake(f["name"])
            if field in seen:
                raise GenError(f"{tid}: two fields map to {field}")
            seen.add(field)
            rust = self.rust_type(f["type"], module)
            if f.get("embedded"):
                lines.append("    /// Embedded: gob sends it as one field named after its type.")
            lines.append(f'    #[gob(name = "{f["name"]}")]')
            lines.append(f"    pub {field}: {rust},")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def module_file(self, module):
        pkgs = sorted(p for p, m in MODULES.items() if m == module)
        out = [
            "// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.",
            "",
            f"//! Gob wire types of Go package `{pkgs[0]}`.",
            "",
            "#![allow(clippy::doc_markdown)]",
            "",
        ]
        items = sorted(self.modules[module], key=lambda tid: self.rust_names[tid])
        for tid in items:
            out.append(self.item(tid, module))
        return "\n".join(out)

    def mod_file(self):
        out = [
            "// @generated by scripts/plugingen.py from fixtures/plugin/idl.json. Do not edit.",
            "",
            "//! The gob form of every value Mattermost's plugin RPC sends, generated from the Go",
            "//! tree (docs/PLUGIN_PLAN.md, D5).",
            "//!",
            f"//! Generated from Go {self.idl['go_version']}: {len(self.idl['wire'])} wire structs, "
            f"{sum(len(v) for v in self.modules.values())} named types.",
            "",
        ]
        for module in sorted(self.modules):
            out.append(f"pub mod {module};")
        out.append("")
        out.append("mod gob_safe;")
        out.append("pub use gob_safe::{interface_to_json, value_to_json};")
        out.append("")
        out.append("/// The names client_rpc.go's `init()` registers with gob, for interface values.")
        out.append("pub mod registered {")
        consts = []
        for r in self.idl["registered"]:
            const = self.registered_const(r)
            consts.append(const)
            out.append(f"    /// Go `{r['type']}`.")
            out.append(f'    pub const {const}: &str = "{r["name"]}";')
        out.append("    /// Every name above.")
        out.append(f"    pub const ALL: &[&str] = &[{', '.join(consts)}];")
        out.append("}")
        out.append("")
        out.append("/// Invoke `$m!` with every registered interface type as `(registered::NAME, Type),`: the")
        out.append("/// type a value sent under that name decodes into.")
        out.append("#[doc(hidden)]")
        out.append("#[macro_export]")
        out.append("macro_rules! for_each_registered {")
        out.append("    ($m:ident) => {")
        out.append("        $m! {")
        for r in self.idl["registered"]:
            tid = r["type"]
            if self.types[tid]["kind"] == "pointer":
                tid = self.types[tid]["elem"]  # gob flattens the pointer
            rust = self.rust_type(tid, "").replace("super::", "$crate::wire::")
            out.append(f"            ($crate::wire::registered::{self.registered_const(r)}, {rust}),")
        out.append("        }")
        out.append("    };")
        out.append("}")
        out.append("")
        out.append("/// Invoke `$m!` with every wire struct as `(\"Z_Name\", path::Z_Name),`.")
        out.append("#[doc(hidden)]")
        out.append("#[macro_export]")
        out.append("macro_rules! for_each_wire_struct {")
        out.append("    ($m:ident) => {")
        out.append("        $m! {")
        for tid in self.idl["wire"]:
            name = self.rust_names[tid]
            out.append(f'            ("{name}", $crate::wire::plugin::{name}),')
        out.append("        }")
        out.append("    };")
        out.append("}")
        return "\n".join(out) + "\n"

    def registered_const(self, r):
        t = r["type"]
        tt = self.types[t]
        if tt["kind"] == "pointer":
            name = self.rust_names[tt["elem"]]
            if name == "Error":
                # `pq.Error`: name the package, not just "ERROR".
                return f"{self.module_of(tt['elem']).upper()}_ERROR"
            return screaming(name)
        if t in self.rust_names:
            return screaming(self.rust_names[t])
        if tt["kind"] == "slice":
            elem = self.types[tt["elem"]]
            if elem["kind"] == "pointer":
                return screaming(self.rust_names[elem["elem"]]) + "_PTR_SLICE"
            if tt["elem"] in self.rust_names:
                return screaming(self.rust_names[tt["elem"]]) + "_SLICE"
            return "ANY_SLICE"
        if tt["kind"] == "map":
            return "STRING_ANY_MAP"
        raise GenError(f"no constant name for registered {t}")

    # ─── Go's json.Marshal, for the audit records a plugin logs ───────────────────────────

    def registered_closure(self):
        """Every type reachable from a registered one: what an interface value can hold."""
        seen, stack = set(), [r["type"] for r in self.idl["registered"]]
        while stack:
            tid = stack.pop()
            if tid in seen:
                continue
            seen.add(tid)
            t = self.types[tid]
            stack += [t[k] for k in ("elem", "key") if t.get(k)]
            stack += [f["type"] for f in t.get("fields", [])]
        return seen

    def flattened(self, tid):
        """The type a slice or map element has in Rust: a pointer to it is flattened away."""
        t = self.types[tid]
        return t["elem"] if t["kind"] == "pointer" else tid

    def json_fn(self, tid):
        return "json_" + snake(self.rust_names[tid]).removeprefix("r#")

    def json_expr(self, tid, expr):
        """A Rust expression turning `expr` into the `serde_json::Value` Go's json.Marshal makes."""
        t = self.types[tid]
        kind = t["kind"]
        # `&v.field` needs brackets before a method call, a plain binding does not.
        call = expr if expr.isidentifier() else f"({expr})"
        if tid == "encoding/json.RawMessage":
            # A RawMessage marshals verbatim, and fails the whole marshal if it is not JSON.
            return f"serde_json::from_slice({expr}).ok()?"
        if kind == "interface":
            return f"match {expr} {{ Some(i) => interface_to_json(i)?, None => Json::Null }}"
        if kind == "pointer":
            # `rust_type` boxes a pointer to a struct and only that.
            deref = "&**v" if self.types[t["elem"]]["kind"] == "struct" else "v"
            inner = self.json_expr(t["elem"], "v")
            return f"match {expr} {{ Some(v) => {{ let v = {deref}; {inner} }}, None => Json::Null }}"
        if kind == "slice":
            if self.types[t["elem"]]["kind"] == "uint8":
                # Go marshals a byte slice as base64, and a nil one as null.
                return f"if {call}.is_empty() {{ Json::Null }} else {{ Json::String(B64.encode({expr})) }}"
            # A slice or map of pointers is a Vec/HashMap of values: gob cannot send a nil
            # element, so `rust_type` flattens the pointer and so must this.
            elem = self.json_expr(self.flattened(t["elem"]), "v")
            return (
                f"if {call}.is_empty() {{ Json::Null }} else {{ Json::Array({call}.iter()"
                f".map(|v| -> Option<Json> {{ Some({elem}) }}).collect::<Option<Vec<_>>>()?) }}"
            )
        if kind == "map":
            elem = self.json_expr(self.flattened(t["elem"]), "v")
            return (
                f"if {call}.is_empty() {{ Json::Null }} else {{ Json::Object({call}.iter()"
                f".map(|(k, v)| -> Option<(String, Json)> {{ Some((k.clone(), {elem})) }})"
                ".collect::<Option<Map<String, Json>>>()?) }"
            )
        if kind == "struct":
            return f"{self.json_fn(tid)}({expr})?"
        if kind == "string":
            return f"Json::String(ToOwned::to_owned({expr}))"
        if kind == "bool":
            return f"Json::Bool(*{expr})"
        if kind in ("int", "int8", "int16", "int32", "int64"):
            return f"Json::from(*{expr} as i64)"
        if kind in ("uint", "uint8", "uint16", "uint32", "uint64", "uintptr"):
            return f"Json::from(u64::from(*{expr}))"
        if kind in ("float32", "float64"):
            return f"Json::from(f64::from(*{expr}))"
        raise GenError(f"{tid}: no JSON mapping for kind {kind}")

    def json_is_empty(self, tid, expr):
        """Go's `isEmptyValue`, for a field tagged omitempty."""
        kind = self.types[tid]["kind"]
        call = expr if expr.isidentifier() else f"({expr})"
        if kind in ("string", "slice", "map"):
            return f"{call}.is_empty()"
        if kind == "bool":
            return f"!*{expr}"
        if kind in ("pointer", "interface"):
            return f"{call}.is_none()"
        if kind == "struct":
            return "false"  # Go never omits a struct: it has no zero test for one.
        if kind in ("float32", "float64"):
            return f"*{expr} == 0.0"
        return f"*{expr} == 0"

    def gob_safe_file(self):
        closure = self.registered_closure()
        structs = sorted(
            (t for t in closure if self.types[t]["kind"] == "struct"),
            key=lambda t: self.rust_names[t],
        )
        out = [
            HEADER,
            "",
            "//! Go's `json.Marshal` for every type an interface value can hold, which is what",
            "//! `makeAuditRecordGobSafe` puts an audit record through (audit.go).",
            "//!",
            "//! The gob wire types carry Go field names; JSON carries the `json:` tags, so this is",
            "//! generated from the same IDL. `None` means the value cannot be marshalled, which is",
            "//! Go's error return.",
            "",
            "#![allow(clippy::wildcard_imports, clippy::too_many_lines, clippy::match_same_arms)]",
            "",
            "use base64::Engine as _;",
            "use base64::engine::general_purpose::STANDARD as B64;",
            "use gobwire::{Interface, Value};",
            "use serde_json::{Map, Value as Json};",
            "",
            "use super::registered;",
            "#[allow(unused_imports)]",
            "use super::{model, pq, plugin, json as json_pkg};",
            "",
        ]
        # The interface dispatch: a registered name says which type the value has.
        out.append("/// One interface value as JSON, by the name its type was registered under.")
        out.append("pub fn interface_to_json(i: &Interface) -> Option<Json> {")
        out.append("    Some(match i.name.as_str() {")
        for r in self.idl["registered"]:
            tid = r["type"]
            t = self.types[tid]
            const = f"registered::{self.registered_const(r)}"
            if t["kind"] == "pointer":
                inner = self.types[t["elem"]]
                if inner["kind"] != "struct":
                    raise GenError(f"{tid}: a registered pointer to a non-struct")
                fn = self.json_fn(t["elem"])
                ty = self.rust_type(t["elem"], "")
                out.append(f"        {const} => {fn}(&i.downcast::<{ty}>().ok()?)?,")
            elif t["kind"] == "struct":
                out.append(
                    f"        {const} => {self.json_fn(tid)}(&i.downcast::<{self.rust_type(tid, '')}>().ok()?)?,"
                )
            else:
                ty = self.rust_type(tid, "")
                expr = self.json_expr(tid, "&value")
                out.append(f"        {const} => {{ let value = i.downcast::<{ty}>().ok()?; {expr} }}")
        out.append("        // Everything else is one of gob's basic types, which carry no names.")
        out.append("        _ => value_to_json(&i.value)?,")
        out.append("    })")
        out.append("}")
        out.append("")
        out.append("/// A dynamic value of a basic type as JSON: what Go's `any` holds when it is not a")
        out.append("/// registered type. Numbers become JSON numbers, bytes base64, as `json.Marshal` does.")
        out.append("pub fn value_to_json(v: &Value) -> Option<Json> {")
        out.append("    Some(match v {")
        out.append("        Value::Bool(b) => Json::Bool(*b),")
        out.append("        Value::Int(i) => Json::from(*i),")
        out.append("        Value::Uint(u) => Json::from(*u),")
        out.append("        Value::Float(f) => Json::from(*f),")
        out.append("        Value::String(s) => Json::String(s.clone()),")
        out.append("        Value::Bytes(b) => Json::String(B64.encode(b)),")
        out.append("        Value::Interface(None) => Json::Null,")
        out.append("        Value::Interface(Some(i)) => interface_to_json(i)?,")
        out.append("        Value::Slice(items) | Value::Array(items) => Json::Array(")
        out.append("            items.iter().map(value_to_json).collect::<Option<Vec<_>>>()?,")
        out.append("        ),")
        out.append("        Value::Map(pairs) => Json::Object(")
        out.append("            pairs")
        out.append("                .iter()")
        out.append("                .map(|(k, v)| match k {")
        out.append("                    Value::String(k) => Some((k.clone(), value_to_json(v)?)),")
        out.append("                    _ => None,")
        out.append("                })")
        out.append("                .collect::<Option<Map<String, Json>>>()?,")
        out.append("        ),")
        out.append("        // A struct only reaches this through a registered name, and a marshaler's")
        out.append("        // bytes have no JSON form without its Go type.")
        out.append("        Value::Struct(_) | Value::Marshaled(_) | Value::Complex(..) => return None,")
        out.append("    })")
        out.append("}")
        out.append("")
        for tid in structs:
            t = self.types[tid]
            out.append(f"/// Go `{t['package']}.{t['name']}`, as `json.Marshal` writes it.")
            out.append(f"fn {self.json_fn(tid)}(v: &{self.rust_type(tid, '')}) -> Option<Json> {{")
            out.append("    let mut m = Map::new();")
            for f in t.get("fields", []):
                tag = f.get("json", "")
                name, _, opts = tag.partition(",")
                if name == "-" and not opts:
                    out.append(f"    // {f['name']}: `json:\"-\"`, never marshalled.")
                    continue
                key = name or f["name"]
                field = f"v.{snake(f['name'])}"
                value = self.json_expr(f["type"], f"&{field}")
                if "omitempty" in opts.split(","):
                    out.append(f"    if !({self.json_is_empty(f['type'], f'&{field}')}) {{")
                    out.append(f'        m.insert("{key}".into(), {value});')
                    out.append("    }")
                else:
                    out.append(f'    m.insert("{key}".into(), {value});')
            out.append("    Some(Json::Object(m))")
            out.append("}")
            out.append("")
        return "\n".join(out)

    def files(self):
        out = {OUT / "mod.rs": self.mod_file()}
        for module in self.modules:
            out[OUT / f"{module}.rs"] = self.module_file(module)
        out[OUT / "gob_safe.rs"] = self.gob_safe_file()
        out[RPC / "hooks.rs"] = self.hooks_file()
        out[RPC / "api.rs"] = self.api_file()
        return out

    # ─── the RPC layer ────────────────────────────────────────────────────────────────────

    def go_type(self, tid):
        """A Go type as source would spell it: package names, not import paths."""
        return re.sub(r"[\w.-]+(?:/[\w.-]+)*/(\w+)\.", r"\1.", tid).replace("interface{}", "any")

    def go_signature(self, m):
        params = ", ".join(
            (f"{p['name']} " if p["name"] else "") + self.go_type(p["type"]) for p in m["params"]
        )
        results = [self.go_type(r["type"]) for r in m["results"]]
        if len(results) == 1 and not m["results"][0]["name"]:
            ret = " " + results[0]
        elif results:
            ret = " (" + ", ".join(
                (f"{r['name']} " if r["name"] else "") + self.go_type(r["type"]) for r in m["results"]
            ) + ")"
        else:
            ret = ""
        return f"{m['name']}({params}){ret}"

    def doc(self, m, indent):
        lines = [f"{indent}/// Go: `{self.go_signature(m)}`"]
        if m.get("doc"):
            lines.append(f"{indent}///")
            lines.append(f"{indent}/// ```text")
            for line in m["doc"].splitlines():
                lines.append(f"{indent}/// {line}".rstrip())
            lines.append(f"{indent}/// ```")
        return lines

    def generated(self, methods):
        """The methods whose trait method and server registration are generated: everything whose
        wire structs are the plain A, B, C layout, hand-written ones included."""
        out = [m for m in methods if not m.get("custom")]
        seen = {}
        for m in out:
            rust = snake(m["name"])
            if rust in seen:
                raise GenError(f"{m['name']} and {seen[rust]} both map to {rust}")
            seen[rust] = m["name"]
        return out

    def rpc_trait(self, out, trait, methods, what):
        for m in methods:
            name, rust = m["name"], snake(m["name"])
            out.extend(self.doc(m, "    "))
            out.append("    ///")
            if m.get("excluded"):
                out.append(f"    /// Hand-written in Go (client_rpc.go), so its wire structs are `{m['args']}`")
                out.append(f"    /// and `{m['returns']}`.")
            out.append(f'    /// The default answers as Go does for a {what} the implementation lacks.')
            out.append(
                f"    fn {rust}(&self, args: {m['args']}) -> impl Future<Output = Result<{m['returns']}, NotImplemented>> + Send {{"
            )
            out.append("        let _ = args;")
            out.append("        async { Err(NotImplemented) }")
            out.append("    }")
            out.append("")

    def rpc_register(self, out, fn, trait, methods):
        out.append(f"/// Register every generated method of `{trait}` on `server` as `Plugin.<Method>`.")
        out.append("///")
        out.append(f"/// Not registered here: {', '.join(sorted(REGISTER_BY_HAND))}, whose servers are hand-written.")
        out.append(f"pub fn {fn}<T: {trait}>(server: &mut Server, implementation: &Arc<T>) {{")
        for m in methods:
            if m["name"] in REGISTER_BY_HAND:
                continue
            name, rust = m["name"], snake(m["name"])
            message = m["not_implemented"]
            if '"' in message:
                raise GenError(f"{name}: the not-implemented message is not a plain string")
            out.append("    let this = Arc::clone(implementation);")
            out.append(f'    server.register("Plugin.{name}", move |args: {m["args"]}| {{')
            out.append("        let this = Arc::clone(&this);")
            out.append(
                f'        async move {{ this.{rust}(args).await.map_err(|NotImplemented| ServiceError("{message}".into())) }}'
            )
            out.append("    });")
        out.append("}")
        out.append("")

    def rpc_macro(self, out, macro, methods, what):
        out.append(
            f'/// Invoke `$m!` with every {what} as'
        )
        out.append('/// `(method, "GoName", "Z_Args", Args, "Z_Returns", Returns),`.')
        out.append("#[doc(hidden)]")
        out.append("#[macro_export]")
        out.append(f"macro_rules! {macro} {{")
        out.append("    ($m:ident) => {")
        out.append("        $m! {")
        for m in methods:
            out.append(
                f'            ({snake(m["name"])}, "{m["name"]}",'
                f' "{m["args"]}", $crate::wire::plugin::{m["args"]},'
                f' "{m["returns"]}", $crate::wire::plugin::{m["returns"]}),'
            )
        out.append("        }")
        out.append("    };")
        out.append("}")

    def rpc_prelude(self, what):
        return [
            HEADER,
            "",
            f"//! {what}",
            "",
            "#![allow(clippy::too_many_lines)]",
            "",
            "use std::future::Future;",
            "use std::sync::Arc;",
            "",
            "use go_netrpc::{Server, ServiceError};",
            "",
            "#[allow(clippy::wildcard_imports)]",
            "use crate::wire::plugin::*;",
            "",
        ]

    def hooks_file(self):
        hooks = self.generated(self.idl["hooks"])
        out = self.rpc_prelude(
            "Every generated hook: its id, the `Hooks` trait a plugin implements, the server that "
            "exposes it, and the host's `HooksClient` methods (client_rpc_generated.go)."
        )
        out.append("use super::{HooksClient, NotImplemented};")
        out.append("")
        ids = self.idl["hook_ids"]
        out.append("/// The hook ids of hooks.go: part of the wire protocol, indexing the implemented-hooks table.")
        out.append("pub mod hook_id {")
        for h in ids:
            out.append(f"    /// Go `{h['name']}ID`.")
            out.append(f"    pub const {screaming(h['name'])}: usize = {h['id']};")
        out.append("}")
        out.append("")
        total = ids[-1]["id"]
        out.append("/// The Go name of every hook id below `TOTAL_HOOKS`.")
        out.append(f"pub const HOOK_NAMES: [&str; hook_id::TOTAL_HOOKS] = [")
        for h in ids[:-1]:
            out.append(f'    "{h["name"]}",')
        out.append("];")
        out.append("")
        out.append("/// The hooks a plugin implements. A plugin overrides the ones it handles and lists them in")
        out.append("/// [`Hooks::implemented`]; the host calls no other.")
        out.append("pub trait Hooks: Send + Sync + 'static {")
        out.append("    /// The Go names of the hooks this plugin implements. Go finds them by reflection over the")
        out.append("    /// plugin's method set (client_rpc.go, `Implemented`); Rust cannot, so the plugin says.")
        out.append("    fn implemented(&self) -> Vec<String>;")
        out.append("")
        self.rpc_trait(out, "Hooks", hooks, "hook")
        out.append("}")
        out.append("")
        self.rpc_register(out, "register_hooks", "Hooks", hooks)
        out.append("impl HooksClient {")
        for m in (m for m in hooks if not m.get("excluded")):
            name, rust = m["name"], snake(m["name"])
            out.extend(self.doc(m, "    "))
            out.append("    ///")
            out.append("    /// Skipped, answering zero values, when the plugin does not implement it. A transport")
            out.append("    /// failure is logged and also answers zero values.")
            out.append(f"    pub async fn {rust}(&self, args: Z_{name}Args) -> Z_{name}Returns {{")
            out.append(f'        self.call(hook_id::{screaming(name)}, "{name}", &args).await')
            out.append("    }")
            out.append("")
            out.append(f"    /// [`HooksClient::{rust}`], also returning the transport error.")
            out.append(
                f"    pub async fn {rust}_with_rpc_err(&self, args: Z_{name}Args) -> (Z_{name}Returns, Option<go_netrpc::Error>) {{"
            )
            out.append(f'        self.call_with_rpc_err(hook_id::{screaming(name)}, "{name}", &args).await')
            out.append("    }")
            out.append("")
        out.append("}")
        out.append("")
        self.rpc_macro(out, "for_each_hook", hooks, "hook a plugin serves")
        out.append("")
        self.rpc_macro(
            out, "for_each_hook_call", [m for m in hooks if not m.get("excluded")],
            "hook whose `HooksClient` method is generated",
        )
        return "\n".join(out) + "\n"

    def api_file(self):
        api = self.generated(self.idl["api"])
        out = self.rpc_prelude(
            "Every generated API method: the `PluginApi` trait the host implements, the server that "
            "exposes it, and the plugin's `ApiClient` methods (client_rpc_generated.go)."
        )
        out.append("use super::{ApiClient, NotImplemented};")
        out.append("")
        out.append("/// The server API a plugin calls. The host implements it; a method it does not override")
        out.append("/// answers the plugin with Go's not-implemented error.")
        out.append("pub trait PluginApi: Send + Sync + 'static {")
        self.rpc_trait(out, "PluginApi", api, "method")
        out.append("}")
        out.append("")
        self.rpc_register(out, "register_api", "PluginApi", api)
        out.append("impl ApiClient {")
        for m in (m for m in api if not m.get("excluded")):
            name, rust = m["name"], snake(m["name"])
            out.extend(self.doc(m, "    "))
            out.append("    ///")
            out.append("    /// A transport failure is logged and answers zero values, as Go's client does.")
            out.append(f"    pub async fn {rust}(&self, args: Z_{name}Args) -> Z_{name}Returns {{")
            out.append(f'        self.call("{name}", &args).await')
            out.append("    }")
            out.append("")
        out.append("}")
        out.append("")
        self.rpc_macro(out, "for_each_api_method", api, "API method a host serves")
        out.append("")
        self.rpc_macro(
            out, "for_each_api_call", [m for m in api if not m.get("excluded")],
            "API method whose `ApiClient` method is generated",
        )
        return "\n".join(out) + "\n"


def rustfmt(src: str) -> str:
    r = subprocess.run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input=src,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        raise GenError("rustfmt failed:\n" + r.stderr[:4000])
    return r.stdout


def main():
    check = "--check" in sys.argv[1:]
    gen = Generator(json.loads(IDL.read_text()))
    files = {path: rustfmt(src) for path, src in gen.files().items()}
    if check:
        stale = [p for p, src in files.items() if not p.exists() or p.read_text() != src]
        extra = [p for p in OUT.glob("*.rs") if p not in files]
        # rpc/ mixes generated and hand-written files: only a generated one can be stray.
        extra += [
            p for p in RPC.glob("*.rs") if p not in files and p.read_text().startswith(HEADER)
        ]
        for p in stale + extra:
            print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
        sys.exit(1 if stale or extra else 0)
    OUT.mkdir(parents=True, exist_ok=True)
    RPC.mkdir(parents=True, exist_ok=True)
    for p in OUT.glob("*.rs"):
        if p not in files:
            p.unlink()
    for path, src in files.items():
        path.write_text(src)
    print(f"wrote {len(files)} files")


if __name__ == "__main__":
    try:
        main()
    except GenError as e:
        print(f"plugingen: {e}", file=sys.stderr)
        sys.exit(1)
