//! Byte-exact port of [goldmark](https://github.com/yuin/goldmark) **v1.8.2** — the CommonMark
//! parser, its default HTML renderer and the GFM extension — as Mattermost uses it.
//!
//! Mattermost converts markdown with goldmark in two places: the text of every push
//! notification (`utils.StripMarkdown`, goldmark + Strikethrough under a custom node renderer)
//! and the HTML of every notification e-mail (`utils.MarkdownToHTML`, goldmark + GFM). Both are
//! ported on top of this crate in `mm-app`. This crate holds no Mattermost code and must never
//! depend on an `mm-*` crate.
//!
//! What is ported: `text`, the parts of `util` the parser and renderer call, `ast`, the default
//! block and inline parsers with delimiter processing, link reference definitions and the
//! paragraph transformer, `renderer`, `renderer/html` with its **default options**, and the
//! `Strikethrough`, `Table`, `Linkify` and `TaskList` extensions (`GFM` is the four). Not
//! ported: the renderer options (`WithUnsafe`, `WithXHTML`, `WithHardWraps`, East Asian line
//! breaks), the parser options (`WithAttribute`, `WithAutoHeadingID`, escaped spaces), the other
//! extensions (footnotes, definition lists, typographer, CJK) and custom linkify regexps.
//!
//! Parity is asserted against `fixtures/behaviour_goldmark.json`, generated by the Go program
//! `reference/dump/behaviour_goldmark.go` from goldmark itself.

pub mod ast;
pub mod html;
pub mod parser;
pub mod renderer;
mod tables_generated;
pub mod text;
pub mod util;

use std::io::Write;
use std::rc::Rc;

pub use ast::{Ast, NodeData, NodeId, NodeKind, WalkStatus};
pub use parser::Parser;
pub use renderer::{
    NodeRenderer, NodeRendererFunc, NodeRendererFuncRegisterer, RenderError, Renderer,
};

/// The goldmark extensions this port carries (`extension.Strikethrough`, …, `extension.GFM`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Extension {
    /// `extension.Strikethrough`: `~~text~~` (and `~text~`).
    Strikethrough,
    /// `extension.Table`: GFM pipe tables.
    Table,
    /// `extension.Linkify`: bare `http(s)://`, `ftp://`, `www.` and e-mail autolinks.
    Linkify,
    /// `extension.TaskList`: `[ ]` / `[x]` at the start of a list item.
    TaskList,
    /// `extension.GFM`: Linkify, Table, Strikethrough and TaskList, in that order.
    Gfm,
}

impl Extension {
    fn expand(self) -> &'static [Extension] {
        match self {
            Extension::Gfm => &[
                Extension::Linkify,
                Extension::Table,
                Extension::Strikethrough,
                Extension::TaskList,
            ],
            Extension::Strikethrough => &[Extension::Strikethrough],
            Extension::Table => &[Extension::Table],
            Extension::Linkify => &[Extension::Linkify],
            Extension::TaskList => &[Extension::TaskList],
        }
    }
}

/// `goldmark.DefaultRenderer()`: the HTML renderer at priority 1000.
pub fn default_renderer() -> Renderer {
    Renderer::new().with_node_renderer(Rc::new(html::HtmlRenderer), 1000)
}

/// Port of `goldmark.Markdown` (markdown.go:36): a parser and a renderer.
#[derive(Clone, Debug)]
pub struct Markdown {
    parser: Parser,
    renderer: Renderer,
}

impl Markdown {
    /// `goldmark.New(goldmark.WithExtensions(extensions...))`.
    pub fn new(extensions: &[Extension]) -> Self {
        Markdown::with_renderer(extensions, default_renderer())
    }

    /// `goldmark.New(goldmark.WithExtensions(extensions...), goldmark.WithRenderer(renderer))`.
    /// As in Go, the options apply first and the extensions' `Extend` second, so each
    /// extension's HTML node renderer is added to `renderer` at priority 500.
    pub fn with_renderer(extensions: &[Extension], mut renderer: Renderer) -> Self {
        for &e in extensions {
            for &x in e.expand() {
                match x {
                    Extension::Table => {
                        renderer.add_node_renderer(Rc::new(html::TableHtmlRenderer), 500)
                    }
                    Extension::Strikethrough => {
                        renderer.add_node_renderer(Rc::new(html::StrikethroughHtmlRenderer), 500)
                    }
                    Extension::TaskList => {
                        renderer.add_node_renderer(Rc::new(html::TaskCheckBoxHtmlRenderer), 500)
                    }
                    Extension::Linkify | Extension::Gfm => {}
                }
            }
        }
        Markdown {
            parser: Parser::new(extensions),
            renderer,
        }
    }

    /// Port of `Markdown.Parser`.
    pub fn parser(&self) -> &Parser {
        &self.parser
    }

    /// Port of `Markdown.Renderer`.
    pub fn renderer(&self) -> &Renderer {
        &self.renderer
    }

    /// Port of `Markdown.Convert`: parse `source` and render it into `w`. goldmark's only
    /// failures are the writer's and a node renderer's.
    pub fn convert(&self, source: &[u8], w: &mut dyn Write) -> Result<(), RenderError> {
        let mut ast = self.parser.parse(source);
        let root = ast.root();
        self.renderer.render(w, source, &mut ast, root)
    }
}

/// goldmark with `extensions` and the default HTML renderer, over a string. goldmark's output
/// for UTF-8 input is UTF-8 on every path this port knows of; were it ever not, the invalid
/// bytes would be replaced (`from_utf8_lossy`) — the same thing Go's `encoding/json` does to the
/// string downstream.
pub fn convert(markdown: &str, extensions: &[Extension]) -> String {
    let mut out = Vec::new();
    // Writing into a Vec cannot fail and the default renderers return no errors.
    let _ = Markdown::new(extensions).convert(markdown.as_bytes(), &mut out);
    String::from_utf8_lossy(&out).into_owned()
}
