//! Go's `path` package — the two functions the ported tree needs.
//!
//! **Not `std::path`**, which is filesystem-flavoured and platform-dependent: on Windows it would
//! join with a backslash, and it does not collapse `a/b/../c` lexically the way Go's `path.Clean`
//! does. A URL path is neither of those things, so the algorithm is reproduced rather than
//! delegated.
//!
//! Lived inside `command_autocomplete.rs` until a second caller appeared —
//! `GetSubpathFromConfig`, which cleans the path out of `SiteURL`. It sits beside [`crate::go_url`]
//! for the same reason that module exists: a Go stdlib port with its own oracle, used by whatever
//! needs it.

/// Port of `path.Join` — concatenate the non-empty elements with `/`, then `Clean`.
pub fn join(elems: &[&str]) -> String {
    let joined = elems
        .iter()
        .filter(|e| !e.is_empty())
        .copied()
        .collect::<Vec<&str>>()
        .join("/");
    if joined.is_empty() {
        return String::new();
    }
    clean(&joined)
}

/// Port of `path.Clean` — the lexical shortest equivalent path.
///
/// Byte-oriented, like Go's: a `/` inside a multi-byte character is impossible in UTF-8, so
/// working on bytes is safe and matches Go's indexing exactly.
pub fn clean(path: &str) -> String {
    if path.is_empty() {
        return ".".to_string();
    }

    let bytes = path.as_bytes();
    let rooted = bytes[0] == b'/';
    let n = bytes.len();

    let mut out: Vec<u8> = Vec::with_capacity(n);
    let mut r = 0usize;
    let mut dotdot = 0usize;

    if rooted {
        out.push(b'/');
        r = 1;
        dotdot = 1;
    }

    while r < n {
        if bytes[r] == b'/' {
            // Empty path element.
            r += 1;
        } else if bytes[r] == b'.' && (r + 1 == n || bytes[r + 1] == b'/') {
            // `.` element.
            r += 1;
        } else if bytes[r] == b'.'
            && r + 1 < n
            && bytes[r + 1] == b'.'
            && (r + 2 == n || bytes[r + 2] == b'/')
        {
            // `..` element: remove the previous one.
            r += 2;
            if out.len() > dotdot {
                // Go decrements the write cursor and then tests `out.index(out.w)` — the byte
                // **just past** the new end, i.e. the byte it has only now excluded. So the
                // separator that ends the loop is itself dropped. Testing `out.last()` here
                // instead leaves it in place, which turns `a/b/..` into `a/` rather than `a`;
                // the oracle caught exactly that.
                let mut popped = out.pop();
                while out.len() > dotdot && popped != Some(b'/') {
                    popped = out.pop();
                }
            } else if !rooted {
                // Cannot backtrack, and the path is relative: keep the `..`.
                if !out.is_empty() {
                    out.push(b'/');
                }
                out.push(b'.');
                out.push(b'.');
                dotdot = out.len();
            }
        } else {
            // A real path element. Add a separator if needed, then copy it.
            if (rooted && out.len() != 1) || (!rooted && !out.is_empty()) {
                out.push(b'/');
            }
            while r < n && bytes[r] != b'/' {
                out.push(bytes[r]);
                r += 1;
            }
        }
    }

    if out.is_empty() {
        return ".".to_string();
    }

    // Every byte came from `path`, which is `&str`, and the only bytes inserted are ASCII.
    String::from_utf8(out).unwrap_or_default()
}

#[cfg(test)]
mod go_parity {
    use super::{clean, join};

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!("../../../fixtures/behaviour_go_stdlib.json"))
            .expect("behaviour_go_stdlib.json is generated by reference/dump")
    }

    /// `path.Clean` is reimplemented here because `std::path` is filesystem-flavoured and
    /// platform-dependent; this asserts the reimplementation against Go's own answers.
    #[test]
    fn path_clean_matches_go() {
        let oracle = oracle();
        let cases = oracle["path_clean"].as_array().unwrap();
        assert!(cases.len() >= 25, "corpus should cover Clean's branches");
        for case in cases {
            let input = case["in"].as_str().unwrap();
            assert_eq!(
                clean(input),
                case["out"].as_str().unwrap(),
                "path.Clean({input:?})"
            );
        }
    }

    /// `path.Join` drops empty elements **before** cleaning, so `Join("", "x")` is `x`, not `/x`.
    #[test]
    fn path_join_matches_go() {
        let oracle = oracle();
        let cases = oracle["path_join"].as_array().unwrap();
        assert!(!cases.is_empty());
        for case in cases {
            let a = case["a"].as_str().unwrap();
            let b = case["b"].as_str().unwrap();
            assert_eq!(
                join(&[a, b]),
                case["out"].as_str().unwrap(),
                "path.Join({a:?}, {b:?})"
            );
        }
    }
}
