//! Port of `model/group_member.go` — membership of a user in a custom or LDAP-synced group.

use serde::{Deserialize, Serialize};

use crate::user::User;
use crate::utils::{AppError, AppResult, is_valid_id};

/// Port of `model.GroupMember` (group_member.go:5).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct GroupMember {
    #[serde(rename = "group_id")]
    pub group_id: String,

    #[serde(rename = "user_id")]
    pub user_id: String,

    /// Epoch milliseconds.
    #[serde(rename = "create_at")]
    pub create_at: i64,

    /// Epoch milliseconds; membership is soft-deleted.
    #[serde(rename = "delete_at")]
    pub delete_at: i64,
}

impl GroupMember {
    /// Port of `(*GroupMember).IsValid` (group_member.go:12).
    ///
    /// The error ids are `model.group_member.<field>.app_error` — **no `is_valid` segment**.
    /// Neither timestamp is checked.
    pub fn is_valid(&self) -> AppResult {
        if !is_valid_id(&self.group_id) {
            return Err(err("group_id"));
        }
        if !is_valid_id(&self.user_id) {
            return Err(err("user_id"));
        }
        Ok(())
    }
}

fn err(field: &str) -> Box<AppError> {
    Box::new(AppError::new(
        "GroupMember.IsValid",
        format!("model.group_member.{field}.app_error"),
        None,
        "",
        400,
    ))
}

/// Port of `model.GroupMemberList` (group_member.go:22).
///
/// The count is tagged **`total_member_count`** while the field is `Count` — it is the total
/// across all pages, not `members.len()`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct GroupMemberList {
    #[serde(rename = "members")]
    pub members: Option<Vec<User>>,

    #[serde(rename = "total_member_count")]
    pub count: i64,
}

#[cfg(test)]
mod wire_parity {
    use super::*;

    /// Round-trips the Go-generated fixture: decode into the port's type, re-encode, and compare
    /// the value graphs. The fixture is produced by `reference/dump`, whose reflective filler
    /// gives **every** field a distinctive non-zero value — so a dropped key, a renamed tag or a
    /// mis-typed field cannot pass. This is the parity oracle, not a smoke test.
    macro_rules! assert_fixture_round_trips {
        ($ty:ty, $fixture:literal) => {{
            let raw = include_str!(concat!("../../../fixtures/", $fixture, ".json"));
            let decoded: $ty =
                serde_json::from_str(raw).unwrap_or_else(|e| panic!("decoding {}: {e}", $fixture));
            let expected: serde_json::Value = serde_json::from_str(raw).unwrap();
            assert_eq!(
                serde_json::to_value(&decoded).unwrap(),
                expected,
                "re-encoding {} does not match Go",
                $fixture
            );
        }};
    }

    #[test]
    fn group_member_round_trips_the_fixture() {
        assert_fixture_round_trips!(GroupMember, "group_member");
    }
    #[test]
    fn group_member_list_round_trips_the_fixture() {
        assert_fixture_round_trips!(GroupMemberList, "group_member_list");
    }
}

#[cfg(test)]
mod go_parity {
    //! Asserts against the `member_is_valid` section of `fixtures/behaviour_group.json`,
    //! generated by `reference/dump/behaviour_group.go`.
    //!
    //! Two id checks, group before user, and **neither timestamp is checked** — a membership with
    //! a zero `create_at` is valid, which is what lets the store mint it on insert.

    use super::*;
    use serde::Deserialize;

    const CORPUS: &str = include_str!("../../../fixtures/behaviour_group.json");

    #[derive(Deserialize)]
    struct Corpus {
        member_is_valid: Vec<Row>,
    }

    #[derive(Deserialize)]
    struct Row {
        name: String,
        #[serde(rename = "in")]
        input: String,
        ok: bool,
        id: Option<String>,
        status_code: Option<i32>,
        #[serde(rename = "where")]
        where_: Option<String>,
        detailed_error: Option<String>,
    }

    #[test]
    fn is_valid_matches_go_on_every_branch() {
        let corpus: Corpus = serde_json::from_str(CORPUS).expect("the behaviour corpus decodes");
        assert!(corpus.member_is_valid.len() >= 8, "the corpus shrank");
        for row in corpus.member_is_valid {
            let member: GroupMember =
                serde_json::from_str(&row.input).unwrap_or_else(|e| panic!("{}: {e}", row.name));
            match (member.is_valid(), row.ok) {
                (Ok(()), true) => {}
                (Err(err), false) => {
                    // `both_empty` is the row that pins the order: Go reports `group_id`.
                    assert_eq!(row.id.as_deref(), Some(err.id.as_str()), "{}", row.name);
                    assert_eq!(row.status_code, Some(err.status_code), "{}", row.name);
                    assert_eq!(
                        row.where_.as_deref(),
                        Some(err.where_.as_str()),
                        "{}",
                        row.name
                    );
                    assert_eq!(
                        row.detailed_error.as_deref(),
                        Some(err.detailed_error.as_str()),
                        "{}",
                        row.name
                    );
                }
                (Ok(()), false) => panic!("{}: Go refused and we accepted", row.name),
                (Err(err), true) => {
                    panic!("{}: Go accepted and we refused with {}", row.name, err.id)
                }
            }
        }
    }
}
