//! Wire types ported from `server/public/model/`.
//!
//! This crate has **no internal dependencies**. It holds the serde types whose JSON
//! representation must match the Go server byte-for-byte.

pub mod access;
pub mod access_control_masking;
pub mod access_policy;
pub mod access_request;
pub mod agents;
pub mod ai_recap_limits;
pub mod ai_recap_settings;
pub mod analytics_row;
pub mod audit;
pub mod audit_events;
pub mod audit_record;
pub mod auditconv;
pub mod authorize;
pub mod autotranslation;
pub mod bot;
pub mod builtin;
pub mod bulk_export;
pub mod bundle_info;
pub mod cel;
pub mod channel;
pub mod channel_bookmark;
pub mod channel_data;
pub mod channel_join_request;
pub mod channel_list;
pub mod channel_member;
pub mod channel_member_history;
pub mod channel_member_history_result;
pub mod channel_mentions;
pub mod channel_search;
pub mod channel_stats;
pub mod channel_view;
pub mod cloud;
pub mod cluster_discovery;
pub mod cluster_info;
pub mod cluster_message;
pub mod command;
pub mod command_args;
pub mod command_autocomplete;
pub mod command_request;
pub mod command_response;
pub mod command_webhook;
pub mod compliance;
pub mod compliance_post;
pub mod config;
pub mod content_flagging;
pub mod content_flagging_report;
pub mod content_flagging_setting_request;
pub mod content_flagging_settings;
pub mod custom_profile_attributes;
pub mod custom_status;
pub mod data_retention_policy;
pub mod draft;
pub mod email_notification;
pub mod emoji;
/// The system-emoji table, emitted from Go by `reference/dump`. Private: `emoji` wraps it.
mod emoji_generated;
pub mod feature_flags;
pub mod file;
pub mod file_info;
pub mod file_info_list;
pub mod file_info_search_results;
pub mod fips;
pub mod github_release;
pub mod gitlab;
pub mod go_bytes;
/// Go's `unicode.IsPrint`, `IsLetter` and `IsNumber` as range tables, emitted from the Go
/// toolchain. Private: `utils` wraps them, and they are Go's `unicode` package rather than a
/// Mattermost source file. Not to be confused with `unicode_generated`, which is the four CJK
/// script tables `model.ContainsCJK` needs.
mod go_unicode_generated;
pub mod go_url;
pub mod group;
pub mod group_member;
pub mod group_syncable;
pub mod guest_invite;
pub mod incoming_webhook;
pub mod initial_load;
pub mod integration_action;
pub mod integrity;
pub mod ip_filtering;
pub mod job;
pub mod ldap;
pub mod license;
pub mod limits;
pub mod link_metadata;
pub mod locale_generated;
pub mod manifest;
pub mod marketplace_plugin;
pub mod member_invite;
pub mod mention_map;
pub mod message_attachment;
pub mod message_export;
pub mod metrics;
pub mod mfa_secret;
pub mod migration;
pub mod mm_blocks_actions;
pub mod native_attributes;
pub mod notification;
pub mod notify_admin;
pub mod oauth;
pub mod oauth_dcr;
pub mod oauth_metadata;
pub mod onboarding;
pub mod outgoing_oauth_connection;
pub mod outgoing_webhook;
pub mod packet_metadata;
pub mod permalink;
pub mod permission;
/// The 311 permissions and the seven tables grouping them, emitted from Go by `reference/dump`.
/// Private: `permission` re-exports it, so a caller never has to know which half a name came from.
mod permission_generated;
pub mod plugin_cluster_event;
pub mod plugin_constants;
pub mod plugin_event_data;
pub mod plugin_key_value;
pub mod plugin_kvset_options;
pub mod plugin_on_install_event;
pub mod plugin_reattach;
pub mod plugin_status;
pub mod plugin_toast;
pub mod post;
pub mod post_acknowledgement;
pub mod post_attributes;
pub mod post_deletion_report;
pub mod post_embed;
pub mod post_info;
/// The mm_blocks / Block Kit / Adaptive Card tree walkers behind two `Post` methods. Private:
/// every function in the Go file is unexported, and `post` is the surface.
mod post_interactive_blocks;
pub mod post_list;
pub mod post_metadata;
pub mod post_search_results;
pub mod preference;
pub mod product_notices;
pub mod property_access;
pub mod property_access_control;
pub mod property_field;
pub mod property_field_attrs_validation;
pub mod property_group;
pub mod property_value;
pub mod push_notification;
pub mod push_response;
pub mod reaction;
pub mod read_receipt;
pub mod recap;
pub mod remote_cluster;
pub mod report;
pub mod role;
/// The 24 default roles and the seven permission/id lists role.go builds in `init()`, emitted
/// from Go by `reference/dump`. Private: `role` re-exports it.
mod role_generated;
pub mod saml;
pub mod scheduled_post;
pub mod scheduled_post_recurrence;
pub mod scheduled_recap;
pub mod scheduled_task;
pub mod scheme;
pub mod search_params;
pub mod search_requests;
pub mod security_bulletin;
pub mod serde_helpers;
pub mod service_environment;
pub mod session;
pub mod session_attributes;
pub mod shared_channel;
/// `channel_sidebar.go`, for the read side of `BaseRoutes.ChannelCategories`.
pub mod sidebar_category;
pub mod slack_compatibility;
pub mod stats;
pub mod status;
pub mod suggest_command;
pub mod support_packet;
pub mod switch_request;
pub mod system;
pub mod team;
pub mod team_member;
pub mod team_search;
pub mod temporary_post;
pub mod terms_of_service;
pub mod thread;
pub mod timeutils;
pub mod timezones;
/// The supported-zone table, emitted from Go by `reference/dump`. Private: `timezones` re-exports it.
mod timezones_generated;
pub mod token;
pub mod typing_request;
pub mod unicode;
/// The four CJK script range tables, emitted from Go by `reference/dump`. Private: `unicode`
/// wraps them, and they are Go's `unicode` package rather than a Mattermost source file.
mod unicode_generated;
pub mod upload_session;
pub mod usage;
pub mod user;
pub mod user_access_token;
pub mod user_autocomplete;
pub mod user_count;
pub mod user_get;
pub mod user_search;
pub mod user_terms_of_service;
pub mod utils;
pub mod version;
pub mod view;
pub mod websocket_message;
pub mod websocket_request;
pub mod wrangler;
pub mod xml_helpers;
