//! Port of `model/scheduled_task.go` — the descriptor half of Go's in-process task scheduler.
//!
//! # The scheduler itself is not ported
//!
//! `createTask` spawns a goroutine around a `time.Ticker` and cancels it by closing a channel.
//! That is runtime plumbing, and its Rust equivalent is a `tokio` task with a `JoinHandle` and a
//! cancellation token — which belongs in `mm-app`, not in a crate that must have no runtime
//! dependency. What lives here is the **description** of a task, which is what crosses the wire
//! and appears in the admin console.
//!
//! One behaviour worth carrying over when that scheduler is written:
//! `CreateRecurringTaskFromNextIntervalTime` aligns the first tick to the next multiple of the
//! interval on the wall clock (`time.Now().Truncate(interval)`), rather than to "now plus
//! interval" — so an hourly task fires on the hour, not at an arbitrary offset.

use serde::{Deserialize, Serialize};

/// Port of `model.ScheduledTask` (scheduled_task.go:12).
///
/// `Interval` is a `time.Duration`, which `encoding/json` marshals as an **integer count of
/// nanoseconds** — not a string, and not milliseconds like every timestamp in this crate. The
/// four unexported fields (the function, the two channels and the alignment flag) are not part of
/// the wire form.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct ScheduledTask {
    #[serde(rename = "name")]
    pub name: String,

    /// **Nanoseconds** — see the type docs.
    #[serde(rename = "interval")]
    pub interval_nanos: i64,

    #[serde(rename = "recurring")]
    pub recurring: bool,
}

impl std::fmt::Display for ScheduledTask {
    /// Port of `(*ScheduledTask).String` (scheduled_task.go:94).
    ///
    /// Three lines, each newline-terminated — including the last, so the output ends with a blank
    /// line. `Interval.String()` is Go's duration formatting (`1h0m0s`, `1.5s`, `0s`), reproduced
    /// by [`format_go_duration`].
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}\nInterval: {}\nRecurring: {}\n",
            self.name,
            format_go_duration(self.interval_nanos),
            self.recurring
        )
    }
}

/// Go's `time.Duration.String()` for the subset of values a scheduled task uses.
///
/// Go's algorithm: zero is `"0s"`; durations under a second use the largest unit that keeps the
/// value ≥ 1 (`ns`, `µs`, `ms`) with a trailing fractional part; a second or more is
/// `[Xh][Ym]Z[.fff]s`, omitting leading zero units but **never** omitting the seconds.
pub fn format_go_duration(nanos: i64) -> String {
    if nanos == 0 {
        return "0s".to_string();
    }

    let negative = nanos < 0;
    let n = nanos.unsigned_abs();

    let mut out = String::new();
    if n < 1_000_000_000 {
        // Sub-second: pick the unit, then trim trailing zeros from the fraction.
        let (unit, scale) = if n < 1_000 {
            ("ns", 1u64)
        } else if n < 1_000_000 {
            ("µs", 1_000)
        } else {
            ("ms", 1_000_000)
        };
        let whole = n / scale;
        let frac = n % scale;
        out.push_str(&whole.to_string());
        if frac > 0 {
            let mut digits = format!("{frac:0width$}", width = scale.to_string().len() - 1);
            while digits.ends_with('0') {
                digits.pop();
            }
            if !digits.is_empty() {
                out.push('.');
                out.push_str(&digits);
            }
        }
        out.push_str(unit);
    } else {
        let total_secs = n / 1_000_000_000;
        let frac = n % 1_000_000_000;
        let hours = total_secs / 3600;
        let minutes = (total_secs % 3600) / 60;
        let seconds = total_secs % 60;

        if hours > 0 {
            out.push_str(&format!("{hours}h"));
        }
        if hours > 0 || minutes > 0 {
            out.push_str(&format!("{minutes}m"));
        }
        out.push_str(&seconds.to_string());
        if frac > 0 {
            let mut digits = format!("{frac:09}");
            while digits.ends_with('0') {
                digits.pop();
            }
            out.push('.');
            out.push_str(&digits);
        }
        out.push('s');
    }

    if negative { format!("-{out}") } else { out }
}

#[cfg(test)]
mod go_parity {
    use super::format_go_duration;

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!("../../../fixtures/behaviour_go_stdlib.json"))
            .expect("behaviour_go_stdlib.json is generated by reference/dump")
    }

    /// `time.Duration.String` picks a unit, trims trailing zeros from the fraction, and omits the
    /// decimal point entirely when there is none. Every one of those is a place to be off by a
    /// character, which is why this asserts against Go rather than against a reading of it.
    #[test]
    fn duration_string_matches_go() {
        let oracle = oracle();
        let cases = oracle["duration_string"].as_array().unwrap();
        assert!(cases.len() >= 20, "corpus should cover every unit");
        for case in cases {
            let nanos = case["nanos"].as_i64().unwrap();
            assert_eq!(
                format_go_duration(nanos),
                case["out"].as_str().unwrap(),
                "time.Duration({nanos}).String()"
            );
        }
    }
}

#[cfg(test)]
mod wire_parity {
    use super::*;

    /// Round-trips the Go-generated fixture: decode into the port's type, re-encode, and compare
    /// the value graphs. The fixture is produced by `reference/dump`, whose reflective filler
    /// gives **every** field a distinctive non-zero value — so a dropped key, a renamed tag or a
    /// mis-typed field cannot pass. This is the parity oracle, not a smoke test.
    macro_rules! assert_fixture_round_trips {
        ($ty:ty, $fixture:literal) => {{
            let raw = include_str!(concat!("../../../fixtures/", $fixture, ".json"));
            let decoded: $ty =
                serde_json::from_str(raw).unwrap_or_else(|e| panic!("decoding {}: {e}", $fixture));
            let expected: serde_json::Value = serde_json::from_str(raw).unwrap();
            assert_eq!(
                serde_json::to_value(&decoded).unwrap(),
                expected,
                "re-encoding {} does not match Go",
                $fixture
            );
        }};
    }

    #[test]
    fn scheduled_task_round_trips_the_fixture() {
        assert_fixture_round_trips!(ScheduledTask, "scheduled_task");
    }
}
