//! Port of `model/terms_of_service.go` — the custom terms a server can require.

use serde::{Deserialize, Serialize};

use crate::post::POST_MESSAGE_MAX_RUNES_V2;
use crate::utils::{AppError, AppResult, get_millis, is_valid_id, new_id};

/// Port of `model.TermsOfService` (terms_of_service.go:9).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct TermsOfService {
    #[serde(rename = "id")]
    pub id: String,

    /// Epoch milliseconds.
    #[serde(rename = "create_at")]
    pub create_at: i64,

    /// The admin who published this revision.
    #[serde(rename = "user_id")]
    pub user_id: String,

    /// Capped at [`POST_MESSAGE_MAX_RUNES_V2`] — the terms are bounded by the *post* limit,
    /// because they are rendered as a post body.
    #[serde(rename = "text")]
    pub text: String,
}

impl TermsOfService {
    /// Port of `(*TermsOfService).IsValid` (terms_of_service.go:16).
    pub fn is_valid(&self) -> AppResult {
        if !is_valid_id(&self.id) {
            // Note: the id branch passes an **empty** terms id, so its error carries no details.
            return Err(invalid_terms_of_service_error("id", ""));
        }

        if self.create_at == 0 {
            return Err(invalid_terms_of_service_error("create_at", &self.id));
        }

        if !is_valid_id(&self.user_id) {
            return Err(invalid_terms_of_service_error("user_id", &self.id));
        }

        if self.text.chars().count() > POST_MESSAGE_MAX_RUNES_V2 {
            return Err(invalid_terms_of_service_error("text", &self.id));
        }

        Ok(())
    }

    /// Port of `(*TermsOfService).PreSave` (terms_of_service.go:45).
    ///
    /// **`create_at` is set unconditionally**, unlike almost every other `PreSave` in the
    /// package, which only fills a zero timestamp. Re-saving a row rewrites its creation time.
    pub fn pre_save(&mut self) {
        if self.id.is_empty() {
            self.id = new_id();
        }

        self.create_at = get_millis();
    }
}

/// Port of `model.InvalidTermsOfServiceError` (terms_of_service.go:34).
///
/// Every branch carries `MaxLength` in its i18n params — including the ones that have nothing to
/// do with length — because Go builds the params unconditionally.
pub fn invalid_terms_of_service_error(
    field_name: &str,
    terms_of_service_id: &str,
) -> Box<AppError> {
    let details = if terms_of_service_id.is_empty() {
        String::new()
    } else {
        format!("terms_of_service_id={terms_of_service_id}")
    };

    let mut params = std::collections::HashMap::new();
    params.insert(
        "MaxLength".to_string(),
        serde_json::Value::from(POST_MESSAGE_MAX_RUNES_V2 as i64),
    );

    Box::new(AppError::new(
        "TermsOfService.IsValid",
        format!("model.terms_of_service.is_valid.{field_name}.app_error"),
        Some(params),
        details,
        400,
    ))
}

#[cfg(test)]
mod wire_parity {
    use super::*;

    /// Round-trips the Go-generated fixture: decode into the port's type, re-encode, and compare
    /// the value graphs. The fixture is produced by `reference/dump`, whose reflective filler
    /// gives **every** field a distinctive non-zero value — so a dropped key, a renamed tag or a
    /// mis-typed field cannot pass. This is the parity oracle, not a smoke test.
    macro_rules! assert_fixture_round_trips {
        ($ty:ty, $fixture:literal) => {{
            let raw = include_str!(concat!("../../../fixtures/", $fixture, ".json"));
            let decoded: $ty =
                serde_json::from_str(raw).unwrap_or_else(|e| panic!("decoding {}: {e}", $fixture));
            let expected: serde_json::Value = serde_json::from_str(raw).unwrap();
            assert_eq!(
                serde_json::to_value(&decoded).unwrap(),
                expected,
                "re-encoding {} does not match Go",
                $fixture
            );
        }};
    }

    #[test]
    fn terms_of_service_round_trips_the_fixture() {
        assert_fixture_round_trips!(TermsOfService, "terms_of_service");
    }
}

#[cfg(test)]
mod go_parity {
    use super::*;

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!(
            "../../../fixtures/behaviour_terms_of_service.json"
        ))
        .expect("behaviour_terms_of_service.json is generated by reference/dump")
    }

    /// Rebuild the case's subject, restoring the `text` the fixture elides.
    fn subject(case: &serde_json::Value) -> TermsOfService {
        let mut terms: TermsOfService =
            serde_json::from_value(case["subject"].clone()).expect("the subject decodes");
        let count = case["text_repeat_count"].as_u64().unwrap_or(0) as usize;
        if count > 0 {
            let rune = case["text_repeat_rune"].as_str().expect("a rune");
            terms.text = rune.repeat(count);
        }
        terms
    }

    /// `(*TermsOfService).IsValid`, branch by branch, against Go's own answers.
    ///
    /// The two rows a reader would get wrong are pinned here rather than described: the **id**
    /// branch passes an empty terms id and so carries **no detail**, where the other three carry
    /// `terms_of_service_id=…`; and the text limit is counted in **runes**, so 16,383 `é` pass and
    /// 16,384 do not, while a byte count would have refused the first.
    #[test]
    fn is_valid_matches_go() {
        let oracle = oracle();
        let cases = oracle["terms_of_service_is_valid"]
            .as_array()
            .expect("an array");
        assert!(cases.len() >= 12, "every branch plus the orderings");

        let mut refused = 0;
        for case in cases {
            let name = case["name"].as_str().expect("a name");
            let result = subject(case).is_valid();
            let expected = case["error_id"].as_str().expect("an id");

            match result {
                Ok(()) => assert!(expected.is_empty(), "{name}: Go refused this"),
                Err(err) => {
                    assert_eq!(err.id, expected, "{name}");
                    assert_eq!(
                        err.detailed_error,
                        case["detailed"].as_str().expect("a detail"),
                        "{name}"
                    );
                    assert_eq!(
                        i64::from(err.status_code),
                        case["status_code"].as_i64().expect("a status"),
                        "{name}"
                    );
                    assert_eq!(
                        err.where_,
                        case["where"].as_str().expect("a where"),
                        "{name}"
                    );
                    // Every branch carries `MaxLength`, including the three about ids and times.
                    // `AppError.params` is unexported in Go, so this half is transcribed from
                    // terms_of_service.go:43 rather than measured — see the oracle's header.
                    let params = err.params.as_ref().expect("params on every branch");
                    assert_eq!(
                        params.get("MaxLength"),
                        Some(&serde_json::Value::from(POST_MESSAGE_MAX_RUNES_V2 as i64)),
                        "{name}"
                    );
                    refused += 1;
                }
            }
        }
        assert!(
            refused >= 8,
            "only {refused} rows exercised a failure branch"
        );
    }

    /// `(*TermsOfService).PreSave`: the id is minted only when absent, and `create_at` moves
    /// **every time** — a re-save rewrites the publication date.
    #[test]
    fn pre_save_matches_go() {
        let oracle = oracle();
        for case in oracle["terms_of_service_pre_save"]
            .as_array()
            .expect("an array")
        {
            let name = case["name"].as_str().expect("a name");
            let mut terms = TermsOfService {
                id: case["in_id"].as_str().expect("an id").to_owned(),
                create_at: 12345,
                user_id: "6bdz674pgq767e4jx75w4pf57a".to_owned(),
                text: "x".to_owned(),
            };
            let before = terms.id.clone();
            terms.pre_save();

            assert_eq!(
                !before.is_empty() && terms.id == before,
                case["id_preserved"].as_bool().expect("a bool"),
                "{name}"
            );
            assert_eq!(
                before.is_empty() && terms.id.len() == 26,
                case["id_generated"].as_bool().expect("a bool"),
                "{name}"
            );
            assert_eq!(
                terms.create_at != 12345,
                case["create_at_overwritten"].as_bool().expect("a bool"),
                "{name}"
            );
        }
    }
}
