//! @generated by `reference/dump` from Go's `unicode` package.
//! DO NOT EDIT — re-run `cd reference/dump && go run .` instead.
//!
//! The four script `RangeTable`s `model.ContainsCJK` (unicode.go:8) tests. Rust's std has
//! no script API, and `unicode-general-category` answers a different question, so these
//! are emitted from Go rather than taken from a crate whose Unicode version may differ
//! from the toolchain's.
//!
//! Unicode version: 15.0.0. See [D-070] — this is the Go toolchain's, not the pinned tree's.
//!
//! Each entry is `(lo, hi, stride)`, sorted ascending and non-overlapping, with Go's
//! `R16` and `R32` concatenated — every `R16` bound is below every `R32` bound, so one
//! search over the whole slice is equivalent to Go's two-step `Is`. A stride above 1
//! means the range is not solid: membership is `lo <= r <= hi && (r - lo) % stride == 0`.

/// Go's `unicode.Han`, 20 ranges.
#[rustfmt::skip]
pub(crate) static HAN: [(u32, u32, u32); 20] = [
    (0x2E80, 0x2E99, 1),
    (0x2E9B, 0x2EF3, 1),
    (0x2F00, 0x2FD5, 1),
    (0x3005, 0x3007, 2),
    (0x3021, 0x3029, 1),
    (0x3038, 0x303B, 1),
    (0x3400, 0x4DBF, 1),
    (0x4E00, 0x9FFF, 1),
    (0xF900, 0xFA6D, 1),
    (0xFA70, 0xFAD9, 1),
    (0x16FE2, 0x16FE3, 1),
    (0x16FF0, 0x16FF1, 1),
    (0x20000, 0x2A6DF, 1),
    (0x2A700, 0x2B739, 1),
    (0x2B740, 0x2B81D, 1),
    (0x2B820, 0x2CEA1, 1),
    (0x2CEB0, 0x2EBE0, 1),
    (0x2F800, 0x2FA1D, 1),
    (0x30000, 0x3134A, 1),
    (0x31350, 0x323AF, 1),
];

/// Go's `unicode.Hiragana`, 6 ranges.
#[rustfmt::skip]
pub(crate) static HIRAGANA: [(u32, u32, u32); 6] = [
    (0x3041, 0x3096, 1),
    (0x309D, 0x309F, 1),
    (0x1B001, 0x1B11F, 1),
    (0x1B132, 0x1B150, 30),
    (0x1B151, 0x1B152, 1),
    (0x1F200, 0x1F200, 1),
];

/// Go's `unicode.Katakana`, 14 ranges.
#[rustfmt::skip]
pub(crate) static KATAKANA: [(u32, u32, u32); 14] = [
    (0x30A1, 0x30FA, 1),
    (0x30FD, 0x30FF, 1),
    (0x31F0, 0x31FF, 1),
    (0x32D0, 0x32FE, 1),
    (0x3300, 0x3357, 1),
    (0xFF66, 0xFF6F, 1),
    (0xFF71, 0xFF9D, 1),
    (0x1AFF0, 0x1AFF3, 1),
    (0x1AFF5, 0x1AFFB, 1),
    (0x1AFFD, 0x1AFFE, 1),
    (0x1B000, 0x1B120, 288),
    (0x1B121, 0x1B122, 1),
    (0x1B155, 0x1B164, 15),
    (0x1B165, 0x1B167, 1),
];

/// Go's `unicode.Hangul`, 14 ranges.
#[rustfmt::skip]
pub(crate) static HANGUL: [(u32, u32, u32); 14] = [
    (0x1100, 0x11FF, 1),
    (0x302E, 0x302F, 1),
    (0x3131, 0x318E, 1),
    (0x3200, 0x321E, 1),
    (0x3260, 0x327E, 1),
    (0xA960, 0xA97C, 1),
    (0xAC00, 0xD7A3, 1),
    (0xD7B0, 0xD7C6, 1),
    (0xD7CB, 0xD7FB, 1),
    (0xFFA0, 0xFFBE, 1),
    (0xFFC2, 0xFFC7, 1),
    (0xFFCA, 0xFFCF, 1),
    (0xFFD2, 0xFFD7, 1),
    (0xFFDA, 0xFFDC, 1),
];

/// The Unicode version Go's tables carried when this file was emitted.
pub(crate) const UNICODE_VERSION: &str = "15.0.0";
