//! Port of `model/user_terms_of_service.go`.
//!
//! Two routes read it: `getUser` copies `terms_of_service_id` / `create_at` onto the `User` body
//! for a self-or-admin viewer, and `saveUserTermsOfService` writes it through
//! [`UserTermsOfService::pre_save`] and [`UserTermsOfService::is_valid`].

use serde::{Deserialize, Serialize};

use crate::utils::{AppError, AppResult, get_millis, is_valid_id, new_id};

/// Port of `model.UserTermsOfService` (user_terms_of_service.go:11).
///
/// No `omitempty` anywhere: the zero value serialises all three keys.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct UserTermsOfService {
    #[serde(rename = "user_id")]
    pub user_id: String,

    #[serde(rename = "terms_of_service_id")]
    pub terms_of_service_id: String,

    #[serde(rename = "create_at")]
    pub create_at: i64,
}

impl UserTermsOfService {
    /// Port of `(*UserTermsOfService).IsValid` (user_terms_of_service.go:17).
    ///
    /// # Every branch reports `user_id` as the detail, including the one about the *terms* id
    ///
    /// Go writes `InvalidUserTermsOfServiceError("terms_of_service_id", ut.UserId)` — the second
    /// argument is the **user** id in all three branches, so a bad `terms_of_service_id` produces
    /// `detailed_error: "user_terms_of_service_user_id=<the user>"` and never names the value it
    /// rejected. Reproduced; a port that "fixed" it would change a string on the wire.
    pub fn is_valid(&self) -> AppResult {
        if !is_valid_id(&self.user_id) {
            return Err(invalid_user_terms_of_service_error(
                "user_id",
                &self.user_id,
            ));
        }

        if !is_valid_id(&self.terms_of_service_id) {
            return Err(invalid_user_terms_of_service_error(
                "terms_of_service_id",
                &self.user_id,
            ));
        }

        if self.create_at == 0 {
            return Err(invalid_user_terms_of_service_error(
                "create_at",
                &self.user_id,
            ));
        }

        Ok(())
    }

    /// Port of `(*UserTermsOfService).PreSave` (user_terms_of_service.go:33).
    ///
    /// **It mints a `user_id` when one is missing**, which is nonsense for a row keyed on a real
    /// user and is exactly what Go does — the generated id then fails nothing, because
    /// [`Self::is_valid`] only checks the *shape*. `create_at` is overwritten unconditionally,
    /// like `TermsOfService` and unlike `User`. `terms_of_service_id` is never filled, so an
    /// empty one reaches `is_valid` and is the 400 there.
    pub fn pre_save(&mut self) {
        if self.user_id.is_empty() {
            self.user_id = new_id();
        }

        self.create_at = get_millis();
    }
}

/// Port of `model.InvalidUserTermsOfServiceError` (user_terms_of_service.go:41).
///
/// No `params` at all — unlike `InvalidTermsOfServiceError` beside it, which attaches `MaxLength`
/// to every branch — and the detail is omitted entirely when the id is empty.
pub fn invalid_user_terms_of_service_error(
    field_name: &str,
    user_terms_of_service_id: &str,
) -> Box<AppError> {
    let details = if user_terms_of_service_id.is_empty() {
        String::new()
    } else {
        format!("user_terms_of_service_user_id={user_terms_of_service_id}")
    };

    Box::new(AppError::new(
        "UserTermsOfService.IsValid",
        format!("model.user_terms_of_service.is_valid.{field_name}.app_error"),
        None,
        details,
        400,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Round trip through the generated fixture: decode, re-encode, compare value graphs.
    #[test]
    fn serialization_parity_with_the_fixture() {
        let raw = include_str!("../../../fixtures/user_terms_of_service.json");
        let parsed: UserTermsOfService = serde_json::from_str(raw).unwrap();
        let expected: serde_json::Value = serde_json::from_str(raw).unwrap();
        assert_eq!(serde_json::to_value(&parsed).unwrap(), expected);
        // The fixture is only evidence if nothing in it is a zero value.
        assert!(!parsed.user_id.is_empty());
        assert!(!parsed.terms_of_service_id.is_empty());
        assert_ne!(parsed.create_at, 0);
    }

    /// No `omitempty`: the zero value is three keys, in Go's declaration order.
    #[test]
    fn the_zero_value_keeps_all_three_keys() {
        assert_eq!(
            serde_json::to_string(&UserTermsOfService::default()).unwrap(),
            r#"{"user_id":"","terms_of_service_id":"","create_at":0}"#
        );
    }
}

#[cfg(test)]
mod go_parity {
    use super::*;

    fn oracle() -> serde_json::Value {
        serde_json::from_str(include_str!(
            "../../../fixtures/behaviour_terms_of_service.json"
        ))
        .expect("behaviour_terms_of_service.json is generated by reference/dump")
    }

    /// `(*UserTermsOfService).IsValid`, branch by branch.
    ///
    /// The row that earns the oracle is `terms_id_empty`: its detail is
    /// `user_terms_of_service_user_id=<the **user** id>`, because Go passes `ut.UserId` as the
    /// second argument on all three branches. A port that passed the field it was rejecting would
    /// write a different string on the wire and no reading of the code would catch it.
    ///
    /// No branch carries `params` — unlike `TermsOfService.IsValid` beside it, which attaches
    /// `MaxLength` to every one.
    #[test]
    fn is_valid_matches_go() {
        let oracle = oracle();
        let cases = oracle["user_terms_of_service_is_valid"]
            .as_array()
            .expect("an array");
        assert!(cases.len() >= 8, "every branch plus the ordering");

        let mut refused = 0;
        for case in cases {
            let name = case["name"].as_str().expect("a name");
            let subject: UserTermsOfService =
                serde_json::from_value(case["subject"].clone()).expect("the subject decodes");
            let expected = case["error_id"].as_str().expect("an id");

            match subject.is_valid() {
                Ok(()) => assert!(expected.is_empty(), "{name}: Go refused this"),
                Err(err) => {
                    assert_eq!(err.id, expected, "{name}");
                    assert_eq!(
                        err.detailed_error,
                        case["detailed"].as_str().expect("a detail"),
                        "{name}"
                    );
                    assert_eq!(
                        i64::from(err.status_code),
                        case["status_code"].as_i64().expect("a status"),
                        "{name}"
                    );
                    assert_eq!(
                        err.where_,
                        case["where"].as_str().expect("a where"),
                        "{name}"
                    );
                    assert!(err.params.is_none(), "{name}: no params on any branch");
                    refused += 1;
                }
            }
        }
        assert!(
            refused >= 6,
            "only {refused} rows exercised a failure branch"
        );
    }

    /// `(*UserTermsOfService).PreSave`: it **mints a user id** when one is missing — nonsense for a
    /// row keyed on a real user, and exactly what Go does — and overwrites `create_at` every time.
    /// `terms_of_service_id` is never filled, which is why an empty one survives to `IsValid`.
    #[test]
    fn pre_save_matches_go() {
        let oracle = oracle();
        for case in oracle["user_terms_of_service_pre_save"]
            .as_array()
            .expect("an array")
        {
            let name = case["name"].as_str().expect("a name");
            let mut row = UserTermsOfService {
                user_id: case["in_id"].as_str().expect("an id").to_owned(),
                terms_of_service_id: "6bdz674pgq767e4jx75w4pf57a".to_owned(),
                create_at: 12345,
            };
            let before = row.user_id.clone();
            row.pre_save();

            assert_eq!(
                !before.is_empty() && row.user_id == before,
                case["id_preserved"].as_bool().expect("a bool"),
                "{name}"
            );
            assert_eq!(
                before.is_empty() && row.user_id.len() == 26,
                case["id_generated"].as_bool().expect("a bool"),
                "{name}"
            );
            assert_eq!(
                row.create_at != 12345,
                case["create_at_overwritten"].as_bool().expect("a bool"),
                "{name}"
            );
            assert_eq!(
                row.terms_of_service_id, "6bdz674pgq767e4jx75w4pf57a",
                "{name}: PreSave never touches the terms id"
            );
        }
    }
}
